elastic/elasticsearch-specification

- specification/specs/analysis/StopWords.ts
- specification/specs/common.ts
- specification/specs/common_abstractions/infer/field/Field.ts
- specification/specs/common_abstractions/infer/id/Id.ts
- specification/specs/common_abstractions/infer/id/Ids.ts
- specification/specs/common_abstractions/infer/index_name/IndexName.ts
- specification/specs/common_abstractions/infer/indices/Indices.ts
- specification/specs/common_abstractions/infer/join_field_routing/Routing.ts
- specification/specs/common_abstractions/infer/long_id/LongId.ts
- specification/specs/common_abstractions/infer/metrics/IndexMetrics.ts
- specification/specs/common_abstractions/infer/metrics/Metrics.ts
- specification/specs/common_abstractions/infer/name/Name.ts
- specification/specs/common_abstractions/infer/name/Names.ts
- specification/specs/common_abstractions/infer/node_id/NodeIds.ts
- specification/specs/common_abstractions/infer/property_name/PropertyName.ts
- specification/specs/common_abstractions/infer/relation_name/RelationName.ts
- specification/specs/common_abstractions/infer/task_id/TaskId.ts
- specification/specs/common_abstractions/infer/timestamp/Timestamp.ts
- specification/specs/common_options/minimum_should_match/MinimumShouldMatch.ts
- specification/specs/query_dsl/specialized/more_like_this/like/Like.ts
- specification/specs/search/multi_search/MultiSearchResponse.ts
- specification/specs/search/suggesters/context_suggester/Context.ts
- specification/src/domain.ts
- specification/src/main.ts
- specification/src/specification/type-reader.ts
`TypeDeclaration` now has two more implementations
this allows us to reuse unions more purposefully in the
spec.
```ts
type X = Y | Z
```
This allows us to reuse a union in multiple places as well as name the
union explicitly and provide it with its own documentation. See e.g
`MinimumShouldMatch` which is on its own a union of `int` and `string`
which on its own is very nondescript.
In many cases rather then documenting something is just a `string` we
can do better. e.g we know the string is functionally a `NodeId` or
`Field` reference.
```ts
type Field = string
```
Now suffices to strongly type strings. Added benefits to documentation
apply as well.
------
Type aliases ONLY work for string or unions the following is not valid:
```ts
type X = number
type Z = { A : B }
```
generators will …
> Introduce UnionAlias and StringAlias

- specification/specs/common.ts
- specification/specs/search/search/SearchRequest.ts
- specification/specs/search/search/source_filtering/SourceFilter.ts
Simplification of `sort`: the `string` variant does not exist in the request body, but only as a query parameter
Simplification of `source`:
- rather than considering that there only exists a 2-variant `Union` (aka `Either`), we should let code generators handle unions of arbitrary length (we can have `Union2`, `Union3`, `Union4`, etc in languages missing proper tagged unions).
- Usage of `Fields` instead of `Field | Field[]` may help generators understand that these two variants are related and provide more ergonomic builder methods (although this could also be inferred from the `TypeA | TypeA[]` pattern).
Additional questions:
- `sort` and `_source` are also defined as query parameters in `search.json` (the Rest API spec) but only exist as a body parameters in `SearchRequest.ts`. Is …
> Simplify SearchRequest's sort and _source field

- output/typescript/types.ts
- specification/specs/common.ts
- specification/specs/search/search/SearchResponse.ts
- specification/specs/search/search/hits/Hit.ts
- specification/specs/search/search/hits/HitsMetadata.ts
- specification/specs/search/search/hits/InnerHitsMetadata.ts
This updates the spec to address Search response type validations
Still 148 failures remaining but they are all localized to Aggregate.
- add pit_id to search response
- add _index and _id to Hit
- add _source to Hit
- update sort on Hit
- Allow for long as total on HitsMetadata
- update innerhits total to allow for long too
- update specification search response failures
> Updates spec to address search response failures

- specification/specs/document/single/update/UpdateRequest.ts
Part of https://github.com/elastic/clients-team/issues/326
> Add missing 'require_alias' query param on 'update' API

- output/schema/schema.json
- output/typescript/types.ts
- package.json
- run-validations.sh
- specification/src/metamodel_reader.ts
- Also ensure we include `ErrorResponse` to the canonical spec
> Make sure run-validation gens the canonical spec

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/aggregations/Aggregate.ts
- specification/specs/common/ShardFailure.ts
- specification/specs/search/search/SearchResponse.ts
- specification/specs/search/search/hits/Hit.ts
- specification/specs/search/search/hits/HitsMetadata.ts
- specification/specs/search/search/hits/InnerHitsMetadata.ts
- specification/specs/search/search/hits/NestedIdentity.ts
- specification/specs/search/search/profile/AggregationProfile.ts
- specification/specs/search/search/profile/Collector.ts
- specification/specs/search/search/profile/QueryProfile.ts
Reduces failures down to 15 locally.
The remainder are aggregations N level deep for which we need to
formulate a battle plan.
> Update search response with optionalibility

- README.md
- package.json
- specification/package.json
This fix removes the requirement of a first `npm install` in the top-level folder and some docs nits.
> Fixed docs and scripts

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/index_modules/index_settings/IndexState.ts
Fix `IndexState` with nullable properties so that Indices.Get_Settings response tests pass.
> Indices Get Settings

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/aggregations/Aggregate.ts
- specification/specs/analysis/char_filters/CharFilterBase.ts
- specification/specs/analysis/char_filters/ICharFilter.ts
- specification/specs/analysis/token_filters/ITokenFilter.ts
- specification/specs/analysis/token_filters/TokenFilterBase.ts
- specification/specs/analysis/tokenizers/ITokenizer.ts
- specification/specs/analysis/tokenizers/TokenizerBase.ts
- specification/specs/behaviors.ts
- specification/specs/common.ts
- specification/specs/common/Dictionary.ts
- specification/specs/indices/analyze/AnalyzeRequest.ts
- specification/specs/indices/mapping_management/put_mapping/PutMappingRequest.ts
- specification/specs/mapping/TypeMapping.ts
- specification/specs/mapping/dynamic_template/DynamicTemplate.ts
- specification/specs/mapping/types/CorePropertyBase.ts
- specification/specs/mapping/types/IProperty.ts
- specification/specs/mapping/types/PropertyBase.ts
- specification/specs/mapping/types/complex/object/ObjectProperty.ts
- specification/specs/search/search/SearchResponse.ts
- specification/specs/x_pack/machine_learning/machine_learning_info/CategorizationAnalyzer.ts
- specification/src/api-specification.ts
- specification/src/domain.ts
- specification/src/main.ts
- specification/src/metamodel.ts
- specification/src/metamodel_reader.ts
- specification/src/specification/type-reader.ts
This PR splits extends and implements to two seperately exposed
components. Previously they were all exposed under `.inherits`.
Interfaces are barely used in the input specification. Where they were
used there was always also a common base class implementation.
I removed all the used interfaces and reintroduced `IDictionary<TKey,
TValue>`
This allows types to declare they implement this dictionary and we can
the presence of this to either generate an appropiate type or know that
we might need to handle serialization explicitly.
```json
{
"doc_count: 0
"mykey" { .. }
"myother_key" : { ... }
}
```
Can therefor now be typed as:
```ts
class ThingWithDocCount implements IDictionary<string, Aggregate> {}
```
In the typescript output we can inspect `interface.implements` to see if
it extends …
> Seperate extends and implements

- .github/workflows/linter.yml
- specification/package-lock.json
- specification/package.json
- specification/src/api-specification.ts
- specification/src/domain.ts
- specification/src/format.ts
- specification/src/main.ts
- specification/src/metamodel.ts
- specification/src/metamodel_generate.ts
- specification/src/metamodel_reader.ts
- specification/src/specification/rest-spec-mapping.ts
- specification/src/specification/type-reader.ts
- specification/src/specification/validator.ts
- specification/tsconfig.json
- typescript-generator/package.json
This pr adds a linter, [standard](https://github.com/standard/standard) to the typescript generator and [ts-standard](https://github.com/standard/ts-standard) to the compiler, in an effort to improving the code quality and resilience.
Standard is a well known linter in the js community and other than fixing the code style, it also contains a series of gotchas to avoid falling in "brittle code" situations.
The linter will be executed as CI step as well.
This pr is the first step towards refactoring of the compiler.
> Add linter

- Makefile
* `check-license` target that locally verifies the presence of license headers
* `contrib` target that runs all pre contribution tasks: `check-license`, `format-code` and `generate-spec`
> Make targets for contrib & check-license

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/document/multiple/multi_get/request/MultiGetRequest.ts
- specification/specs/document/multiple/multi_get/response/MultiGetResponse.ts
Wasn't sure about `MultiGetSourceFilter` but `mget` seems to use slightly different attributes for it's source filtering unfortunately?
> Add types to the 'mget' API

- output/schema/schema.json
- package.json
- specification/compiler/model/build-model.ts
Currently, we are optimistically assuming that given a. request class, we also have the response, that is not always the case, this pr adds a check to verify this assumption.
>  Check Response class existence

- output/dangling-types/dangling.csv
- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/common.ts
- specification/specs/x_pack/watcher/Watch.ts
- specification/specs/x_pack/watcher/acknowledge_watch/ActionStatus.ts
- specification/specs/x_pack/watcher/acknowledge_watch/ActivationState.ts
- specification/specs/x_pack/watcher/acknowledge_watch/WatchStatus.ts
- specification/specs/x_pack/watcher/action/Action.ts
- specification/specs/x_pack/watcher/action/slack/SlackAttachment.ts
- specification/specs/x_pack/watcher/action/slack/SlackMessage.ts
- specification/specs/x_pack/watcher/activate_watch/ActivationStatus.ts
- specification/specs/x_pack/watcher/condition/ConditionContainer.ts
- specification/specs/x_pack/watcher/condition/ScriptCondition.ts
- specification/specs/x_pack/watcher/execute_watch/ExecuteWatchResponse.ts
- specification/specs/x_pack/watcher/execute_watch/ExecutionResultAction.ts
- specification/specs/x_pack/watcher/execute_watch/WatchRecord.ts
- specification/specs/x_pack/watcher/execution/email/EmailActionResult.ts
- specification/specs/x_pack/watcher/execution/email/EmailResult.ts
- specification/specs/x_pack/watcher/execution/index/IndexActionResult.ts
- specification/specs/x_pack/watcher/execution/index/IndexActionResultIndexResponse.ts
- specification/specs/x_pack/watcher/execution/slack/SlackActionMessageResult.ts
- specification/specs/x_pack/watcher/execution/slack/SlackActionResult.ts
- specification/specs/x_pack/watcher/execution/webhook/WebhookActionResult.ts
- specification/specs/x_pack/watcher/get_watch/GetWatchResponse.ts
- specification/specs/x_pack/watcher/input/InputContainer.ts
- specification/specs/x_pack/watcher/schedule/ScheduleContainer.ts
- specification/specs/x_pack/watcher/schedule/ScheduleTriggerEvent.ts
endpoints added:
* response for `watcher.ack_watch` 
* response for `watcher.activate_watch` 
* response for `watcher.deactivate_watch` 
* response for `watcher.get_watch` 
Improved validation for `watcher.execute_watch`, close but not cigar!
> Validate several Watcher endpoints

- .github/workflows/output-check.yml
- output/schema/schema.json
- specification/specs/search/search/source_filtering/SourceFilter.ts
Switch to using `--porcelain` and now emits `git diff` if it fails so we can debug why the generation is not fresh
> update git clean check and print the diff if its not

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/common.ts
Finally, the `Id` type is now correct thanks to https://github.com/elastic/clients-flight-recorder/pull/655 🎉
> Id should be a string

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/compiler/compiler.ts
- specification/compiler/index.ts
- specification/compiler/steps/validate-model.ts
- specification/compiler/steps/validate-rest-spec.ts
- specification/compiler/validation-errors.ts
This PR collects errors of the different compilation/validation pipeline steps and outputs them as JSON in `output/schema/validation-errors.json` (and also in the console, sorted by endpoint name).
The file is structured by endpoint/request & response with also a section for general errors (e.g. on builtin types) which aren't associated to an endpoint.
This file should be used to show model validation errors in [`clients-flight-recorder/recordings/types-validation/types-validation.md`](https://github.com/elastic/clients-flight-recorder/blob/dev/recordings/types-validation/types-validation.md) to provide a complete picture of input specifications "readiness". I'll prepare a PR in that repo once this one is merged.
> Write validation errors to a json file

- typescript-generator/client.js
Since https://github.com/elastic/elastic-client-generator/pull/221 many APIs have a request/response definition, but it contain dummy properties.
The js clients use a `TODO` type if the definition does not exist, this change makes sure that stubbed request/responses are still represented as TODO types.
> Create a TODO type if the request or response contains stubs

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/x_pack/eql/search/EqlSearchRequest.ts
`filter_path` is specified in the `CommonQueryParameters` behaviour already.
> Remove filter_path from EQL Search

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/common.ts
Any reason not to use aliases on these? Today .NET has a custom formatter to handle the oddities of the naming here. I think the approach I've applied on Cat*Records for alias generation should avoid that custom handling.
> Switch to aliases

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/cluster/cluster_delete_component_template/ClusterDeleteComponentTemplateRequest.ts
- specification/specs/cluster/cluster_delete_component_template/ClusterDeleteComponentTemplateResponse.ts
> Validate cluster.delete_component_template Endpoint

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/x_pack/watcher/watcher_stats/WatcherNodeStats.ts
as titled.
@delvedor, I wanted to validated the request as well but ran into a type casting issue:
```
expectAssignable<T.WatcherStatsRequest>({
"metric": "all",
"emit_stacktraces": "true"
})
```
and `emit_stacktraces` is of type `boolean` in `WatcherStatsRequest.ts` 🤷
> Validated watcher.stats Response

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/x_pack/eql/EqlHits.ts
- specification/specs/x_pack/eql/EqlSearchResponseBase.ts
as titled.
Needed `EmptyObject` union to `hits` property to resolve the no hits found case.
> Validate eql.search Response

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/specs/x_pack/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheRequest.ts
- specification/specs/x_pack/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheResponse.ts
- specification/specs/x_pack/searchable_snapshots/mount/SearchableSnapshotsMountRequest.ts
- specification/specs/x_pack/searchable_snapshots/mount/SearchableSnapshotsMountResponse.ts
- specification/specs/x_pack/searchable_snapshots/repository_stats/SearchableSnapshotsRepositoryStatsRequest.ts
- specification/specs/x_pack/searchable_snapshots/repository_stats/SearchableSnapshotsRepositoryStatsResponse.ts
- specification/specs/x_pack/searchable_snapshots/stats/SearchableSnapshotsStatsRequest.ts
- specification/specs/x_pack/searchable_snapshots/stats/SearchableSnapshotsStatsResponse.ts
added request & response for:
* searchable_snapshots.clear_cache
* searchable_snapshots.mount
* searchable_snapshots.repository_stats
* searchable_snapshots.stats
the endpoints don't validate (yet) just the classes added ..
> Add missing searchable snapshot Endpoints

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/mapping/types/complex/flattened/FlattenedProperty.ts
- specification/specs/mapping/types/core/keyword/KeywordProperty.ts
- specification/specs/mapping/types/core/range/RangeProperty.ts
- specification/specs/mapping/types/specialized/generic/GenericProperty.ts
- specification/specs/x_pack/watcher/watcher_stats/WatchRecordStats.ts
The following were flagged in compiler warnings in the .NET generated code because the types included properties which duplicates properties from types they extend.
> Remove duplicate properties which appear on base types

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/specs/common.ts
- specification/specs/x_pack/data_streams/create_data_stream/IndicesCreateDataStreamRequest.ts
- specification/specs/x_pack/data_streams/create_data_stream/IndicesCreateDataStreamResponse.ts
- specification/specs/x_pack/data_streams/data_streams_stats/IndicesDataStreamsStatsRequest.ts
- specification/specs/x_pack/data_streams/data_streams_stats/IndicesDataStreamsStatsResponse.ts
- specification/specs/x_pack/data_streams/delete_data_stream/IndicesDeleteDataStreamRequest.ts
- specification/specs/x_pack/data_streams/delete_data_stream/IndicesDeleteDataStreamResponse.ts
- specification/specs/x_pack/data_streams/get_data_stream/IndicesGetDataStreamRequest.ts
- specification/specs/x_pack/data_streams/get_data_stream/IndicesGetDataStreamResponse.ts
- specification/specs/x_pack/data_streams/migrate_to_data_stream/IndicesMigrateToDataStreamRequest.ts
- specification/specs/x_pack/data_streams/migrate_to_data_stream/IndicesMigrateToDataStreamResponse.ts
- specification/specs/x_pack/data_streams/promote_data_stream/IndicesPromoteDataStreamRequest.ts
- specification/specs/x_pack/data_streams/promote_data_stream/IndicesPromoteDataStreamResponse.ts
request & responses for:
* indices.create_data_stream
* indices.data_streams_stats
* indices.delete_data_stream
* indices.promoted_data_stream
* indices.get_data_stream
* indices.migrate_to_data_stream
`indices.delete_data_stream` is validated, the others are stubbed
> Add Indices.data streams Endpoints

- output/schema/schema.json
- specification/compiler/model/build-model.ts
- specification/compiler/model/metamodel.ts
- specification/compiler/model/utils.ts
- specification/compiler/steps/validate-model.ts
- specification/specs/common_options/minimum_should_match/MinimumShouldMatch.ts
- specification/specs/query_dsl/specialized/more_like_this/like/Like.ts
- specification/specs/search/suggesters/context_suggester/Context.ts
- typescript-generator/index.js
This PR updates the metamodel with a few cleanups and consistency improvements:
- Remove the `internal.Array` type: `Array<SomeType>` now compiles to a `array_of` value.
- Rename `BaseType.url` to `BaseType.docUrl` to be consistent with `Endpoint.docUrl` and add `Property.docUrl`. Endpoints, types and properties now all have `description`, `docUrl` and `deprecation`.
- Remove `Implements` and use `Inherits` everywhere.
- Change open generic parameters from `string[]` to `TypeName[]`. The namespace is arbitrary (the fact that it's the enclosing type's namespace is an implementation detail). This fully qualified type name is the one used to reference that open generic in property types. No more guess-based-on-convention to resolve type names.
> Update the metamodel with cleanups and consistency improvements

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/specs/modules/scripting/get_script_context/GetScriptContextRequest.ts
- specification/specs/modules/scripting/get_script_context/GetScriptContextResponse.ts
- specification/specs/modules/scripting/get_script_languages/GetScriptLanguagesRequest.ts
- specification/specs/modules/scripting/get_script_languages/GetScriptLanguagesResponse.ts
added the request & response stubs for the endpoints:
* `get_script_context`
* `get_script_languages`
> Stubbed Req & Resp for get_script_* APIs

- output/schema/schema.json
- output/typescript/types.ts
- specification/specs/x_pack/machine_learning/datafeed/Datafeed.ts
- specification/specs/x_pack/machine_learning/get_datafeeds/GetDatafeedsRequest.ts
- specification/specs/x_pack/machine_learning/get_job_stats/GetJobStatsRequest.ts
- specification/specs/x_pack/machine_learning/job/config/JobForecastStatistics.ts
- specification/specs/x_pack/machine_learning/job/config/JobStats.ts
- specification/specs/x_pack/machine_learning/job/config/TimingStats.ts
- specification/specs/x_pack/machine_learning/job/process/DataCounts.ts
- specification/specs/x_pack/machine_learning/job/process/ModelSizeStats.ts
addressed feedback from https://github.com/elastic/elastic-client-generator/issues/252
Added missing properties and validated endpoints:
* `ml.get_datafeeds`
* `ml.get_job_stats`
> Validate ML DataCounts and Datafeed type

- output/schema/schema.json
- specification/specs/x_pack/watcher/watcher_stats/WatcherStatsRequest.ts
The request is failing to validate based on the casting of `true` a string `"true"`. The [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/watcher-api-stats.html) state that `emit_stacktraces` is of type `boolean` but the compiler presents a string:
```
expectAssignable<T.WatcherStatsRequest>({
"metric": "all",
"emit_stacktraces": "true"
})
```
> watcher.stats Request

- specification/compiler/model/build-model.ts
- specification/compiler/model/utils.ts
With this pr assertions will no longer show which part of the compiler throws the error, but which file and line(s) of the input spec caused such error.
Furthermore, some error messages have been improved.
> Improve error UX

- docs/modeling-guide.md
- output/schema/schema.json
- specification/compiler/model/metamodel.ts
- specification/compiler/model/utils.ts
- specification/specs/search/search_template/SearchTemplateRequest.ts
> Introduce since, description and default tags

- compiler/model/metamodel.ts
- compiler/model/utils.ts
- compiler/package.json
- compiler/steps/validate-model.ts
- compiler/validation-errors.ts
- docs/modeling-guide.md
- output/schema/schema.json
- output/typescript/types.ts
- specification/__common/aggregations/AggregationContainer.ts
- specification/__common/query_dsl/abstractions/container/QueryContainer.ts
- specification/__common/query_dsl/full_text/intervals/IntervalsContainer.ts
- specification/__common/watcher/conditions/ConditionContainer.ts
- specification/__common/watcher/input/InputContainer.ts
- specification/__common/watcher/schedule/ScheduleContainer.ts
- specification/__common/watcher/transform/TransformContainer.ts
- specification/__common/watcher/trigger/TriggerContainer.ts
- specification/__common/watcher/trigger/TriggerEventContainer.ts
- specification/__global/mget/MultiGetRequest.ts
- specification/__global/search/suggesters/SuggestContainer.ts
- specification/__global/search/suggesters/phrase_suggester/smoothing_model/SmoothingModelContainer.ts
- specification/ingest/ProcessorContainer.ts
- specification/transform/TransformSyncContainer.ts
Backport of #333 with additional validations and fewer spec changes.
This adds `variants` tags to polymorphic types (container classes and variant unions) and additional related model validations.
The `Aggregate` container class has been left out for now as it requires extensive refactoring, which will be done in a separate PR.
A new annotation is introduced for properties, `@variant container_property` to identify properties that belong to the container and aren't part of the variants. This is the case of `aggs` and `meta` on aggregations.
This PR also includes a "json ambiguity check" in the model validation, that verifies that the json structure of the model can be analyzed unambiguously with a streaming JSON parser, which is what strongly typed languages generally use to avoid …
> Add annotations and validations for polymorphic types

- compiler/compiler.ts
- compiler/model/utils.ts
- compiler/steps/validate-model.ts
- compiler/steps/validate-rest-spec.ts
- compiler/validation-errors.ts
- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/__common/common.ts
- specification/__global/bulk/BulkRequest.ts
- specification/__global/delete_by_query/DeleteByQueryRequest.ts
- specification/__global/explain/ExplainRequest.ts
- specification/__global/get/GetRequest.ts
- specification/__global/mget/MultiGetRequest.ts
- specification/__global/msearch_template/MultiSearchTemplateRequest.ts
- specification/__global/search/SearchRequest.ts
- specification/__global/update/UpdateRequest.ts
- specification/async_search/get/AsyncSearchGetRequest.ts
- specification/indices/upgrade/IndicesUpgradeRequest.ts
- specification/ingest/geo_ip_stats/IngestGeoIpStatsRequest.ts
- specification/ingest/processors/DateIndexNameProcessor.ts
- specification/ingest/processors/DateRounding.ts
- specification/task/cancel_tasks/CancelTasksRequest.ts
- specification/watcher/stats/WatcherMetric.ts
- specification/watcher/stats/WatcherStatsRequest.ts
The input specification has a lot of endpoints that are still a work in progress. They have either `@stability TODO` or do not have associated requests and responses. Validating these endpoints creates a lot of validation errors (we had 600+), making the validation report practically useless.
This PR makes sure we only output one single validation error for these work-in-progress endpoints, so that work to be done is tracked, but we're not flooded with non-actionable errors.
Note that model validation still happens, which allows these endpoints and their transitive dependent types to be output in `schema.json`, even if incomplete/incorrect.
After this fitlering phase, some non-TODO endpoints showed some validation errors that this PR also fixes.
> Only output one validation message for "todo" endpoints, fix non-todo endpoints

- compiler/model/build-model.ts
- compiler/model/metamodel.ts
- compiler/steps/validate-model.ts
- output/schema/schema.json
- typescript-generator/index.ts
This updates the metamodel to have a single optional inherits clause instead of an array.
This has no impact on the spec as TypeScript doesn't allow extending more than one class, and we had a model validation ensuring that `inherits` had zero or one parent class.
> Use a single value for inherits in metamodel

- compiler/model/metamodel.ts
- compiler/model/utils.ts
- compiler/steps/validate-model.ts
- output/schema/schema.json
- output/typescript/types.ts
- specification/_spec_utils/Dictionary.ts
- specification/_types/query_dsl/abstractions/container/QueryContainer.ts
- typescript-generator/index.ts
Semantic typing of strings is important to precisely capture the nature of fields, which is useful for very strongly typed languages and tools like editors where types can drive autocompletion and validation.
The `SingleKeyDictionary` behavior assumes that its keys are `strings` and doesn't allow expressing the real nature of these keys.
This PR changes `SingleKeyDictionary` to have a `Key` generic parameter, just like `Dictionary`, and updates the specification accordingly (using `Field` in `QueryContainer`, for example).
With `SingleKeyDictionary` also having a `key`, there's no real point for it to be a dedicated abstration in the metamodel. It is now represented as a `isSingleKey` boolean value on the `Dictionary` model class. This simplifies the model, and also code generators for …
> Add a key parameter to SingleKeyDictionary

- compiler/model/build-model.ts
- compiler/model/utils.ts
This pr improves the inherit resolving, now we can also import an alias, and the generated schema will use the original declaration with the correct namespace.
> Update inherits resolver

- compiler/model/utils.ts
This change will allow us to fully (🤞) support import aliases.
For example:
```ts
// ns/foo.ts
export type Hello = string
// ns/bar.ts
import { Hello as Greeting } from './foo'
export class Bar {
greeting: Greeting
}
``` 
In the schema, the `greeting` property of `Bar` will be:
```json
{
"name": "Hello",
"namespace": "ns"
}
```
> Support import alias

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts
- specification/indices/simulate_index_template/IndicesSimulateIndexTemplateResponse.ts
> Add indices.simulate_index_template Request

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/indices/delete_index_template/IndicesDeleteIndexTemplateRequest.ts
- specification/indices/delete_index_template/IndicesDeleteIndexTemplateResponse.ts
> Validate indices.delete_index_template API

- output/schema/schema.json
- output/typescript/types.ts
- specification/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheRequest.ts
as titled, but has no upstream tests.
added `human` and `pretty` based on https://github.com/elastic/support-diagnostics/pull/482/files
> Validate searchable_snapshots.clear_cache fix

- output/schema/schema.json
- output/typescript/types.ts
- specification/_global/scroll/ScrollResponse.ts
- specification/_types/Errors.ts
> Fix scroll Response

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
- specification/indices/put_index_template/IndicesPutIndexTemplateResponse.ts
The request is validated but 2 more tests are failing because of flattening. E.g. in xpack-Verify_data_stream_resolvability_in_ILM_remove_policy_API_1_request.json.test-d.ts:
```
"settings": {
"index.lifecycle.name": "my_moveable_timeseries_lifecycle"
}
```
Response is validated.
> Validate indices.put_index_template

- output/schema/schema.json
- output/typescript/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/sort/NestedSort.ts
- specification/_types/query_dsl/abstractions/container/QueryContainer.ts
- specification/_types/query_dsl/abstractions/query/Query.ts
- specification/_types/query_dsl/geo/distance/GeoDistanceQuery.ts
@delvedor - the compiler is unable to resolve lat & lon from `GeoLocation` with the failing test
```
"location": {
"lat": 0,
"lon": 0
}
```
```
export type GeoLocation = string | double[] | TwoDimensionalPoint
```
> Fix search Request

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/BucketInfluencer.ts
- specification/ml/_types/CategoryDefinition.ts
- specification/ml/_types/Page.ts
- specification/ml/get_calendars/Calendar.ts
- specification/ml/get_calendars/MlGetCalendarsRequest.ts
- specification/ml/get_categories/MlGetCategoriesRequest.ts
- specification/ml/get_influencers/MlGetInfluencersRequest.ts
- specification/ml/get_influencers/MlGetInfluencersResponse.ts
* `ml.get_calendars`
* `ml.get_categories`
* `ml.get_influencers`
> Validate ml.get_* API

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/ModelSnapshot.ts
- specification/ml/get_model_snapshots/MlGetModelSnapshotsRequest.ts
- typescript-generator/index.ts
as titled.
Also contains a fix for https://github.com/elastic/elastic-client-generator/pull/391
> Fix ml.get_model_snapshots API

- output/schema/schema.json
- output/typescript/types.ts
- specification/security/disable_user/SecurityDisableUserResponse.ts
- specification/security/enable_user/SecurityEnableUserResponse.ts
removing the stub that was in place for status code only responses because https://github.com/elastic/elastic-client-generator/pull/391 allows to build upon.
> Remove stubbing of security.*_user response

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/common.ts
- specification/_types/mapping/types/Property.ts
- specification/security/_types/XPackRole.ts
- specification/security/_types/XPackRoleMapping.ts
- specification/security/_types/XPackUser.ts
- specification/security/authenticate/SecurityAuthenticateResponse.ts
- specification/security/create_api_key/SecurityCreateApiKeyRequest.ts
- specification/security/get_api_key/ApiKeys.ts
- specification/security/put_privileges/PrivilegesActions.ts
- specification/security/put_role/SecurityPutRoleRequest.ts
- specification/security/put_role_mapping/SecurityPutRoleMappingRequest.ts
- specification/security/put_user/SecurityPutUserRequest.ts
- specification/snapshot/_types/SnapshotInfo.ts
- specification/snapshot/create/SnapshotCreateRequest.ts
- specification/watcher/_types/Watch.ts
- specification/watcher/execute_watch/WatchRecord.ts
- specification/watcher/put_watch/WatcherPutWatchRequest.ts
validated `security.create_api_key` Request and introduced alongside the type `Metadata` for (surprise 😄 ) metadata.
> Fix security.create_api_key Request + Metadata

- compiler/model/build-model.ts
- compiler/model/metamodel.ts
- compiler/model/utils.ts
- compiler/steps/validate-model.ts
- compiler/validation-errors.ts
- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/info/RootNodeInfoRequest.ts
- specification/_global/info/RootNodeInfoResponse.ts
- typescript-generator/client.ts
- typescript-generator/index.ts
Follow-up to https://github.com/elastic/elastic-client-generator/pull/391#discussion_r626069633
This PR changes the way we represent no-body responses (and requests) in `schema.json`:
- the `body` property is now required
- it can now be a `NoBody` in addition to the existing `PropertyBody | ValueBody`
- the `void_value` value kind has been removed (it doesn't make sense for a property to be of type void)
We also formalize the the close relation between body type and inheritance: when a request or response extends a class, the parent class defines body properties inherited by the child class. The child class therefore has to have a `PropertyBody`.
The body is required in the schema but is still optional in the spec (ultimately we should enforce it), and a simple heuristic is used to find …
> Changes "void_value" into "no_body" for req/responses with no body

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/mapping/complex.ts
- specification/_types/query_dsl/compound.ts
During .NET code gen I identified a few types which duplicate properties defined on types they derive from. This causes compilation errors in the C# code. This PR removes the duplicated properties.
> Remove duplicated properties

- compiler/model/metamodel.ts
- compiler/model/utils.ts
- compiler/steps/validate-model.ts
- output/schema/schema.json
`container_property` in the metamodel should be `containerProperty` to be consistent with the camelCase convention used in that file.
> Fix "container_property" naming discrepancy

- output/schema/schema.json
- output/typescript/types.ts
- specification/nodes/_types/NodesResponseBase.ts
- specification/security/clear_api_key_cache/SecurityClearApiKeyCacheResponse.ts
- specification/security/clear_cached_privileges/SecurityClearCachedPrivilegesResponse.ts
- specification/security/clear_cached_realms/SecurityClearCachedRealmsResponse.ts
- specification/security/clear_cached_roles/ClearCachedRolesResponse.ts
- specification/security/clear_cached_service_tokens/ClearCachedServiceTokensResponse.ts
- specification/watcher/stats/WatcherStatsResponse.ts
Some properties in the ES API have a leading underscore, e.g. `_id`, `_source`, `_nodes`, etc.
In languages where JSON properties can be renamed, it's nicer from a DX perspective to remove these leading underscores from the generated property identifiers. Leading underscores also have special meanings in some languages like private in Python or unused in Rust.
Removing leading underscores from property names however is causing issues in classes that have a `_nodes: NodeStatistics` property that also contain a `nodes` property.
This PR adds `@identifier node_stats` to all `_nodes: NodeStatistics` properties.
> Add @identifier annotation to _nodes properties

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/Base.ts
Remove the error from `WriteResponseBase` which may conflict with error handling defined in individual clients (as it did with .NET).
> Remove error from WriteResponseBase

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/_types/Datafeed.ts
- specification/ml/_types/Job.ts
- specification/ml/preview_datafeed/MlPreviewDatafeedRequest.ts
- specification/ml/put_job/MlPutJobRequest.ts
- specification/ml/put_job/MlPutJobResponse.ts
Related to https://github.com/elastic/elasticsearch/pull/74265
This PR adds the datafeed_config object to the put_job specifications, as well as a missing renormalization_window_days property. It also sorts the properties alphabetically so it'll be easier to compare to the docs in https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-put-job.html
> [ML] Add datafeed_config to create anomaly detection job request and response

- output/schema/schema.json
- output/typescript/types.ts
- specification/indices/data_streams_stats/IndicesDataStreamsStatsRequest.ts
Remove human property which comes from CommonQueryParameters. I discovered this conflict when generating the .NET class for this type.
> Fix IndicesDataStreamsStatsRequest duplicate property

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/_types/Analysis.ts
- specification/ml/_types/Datafeed.ts
- specification/ml/_types/Detector.ts
- specification/ml/_types/Filter.ts
- specification/ml/_types/Job.ts
- specification/ml/_types/ModelPlot.ts
- specification/ml/_types/Rule.ts
- specification/ml/put_job/MlPutJobRequest.ts
This PR adds default values and descriptions from the documentation for the [create anomaly detection job API](
https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-put-job.html) to the appropriate specifications.
> [ML] Adds descriptions for the put_jobs specification

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/Errors.ts
`MainError` includes a `root_cause` property which is a duplicate of the property from `ErrorCause` which it extends.
> Fix MainError duplicated property

- output/schema/schema.json
- specification/_global/reindex/types.ts
In .NET properties of a type cannot be named the same as the enclosing class. The `source` type includes an `_source`  property which currently conflicts. This could be handled in the .NET generator but perhaps this property can be more clearly named.
> Add identifier for `_source` property in `source` type.

- README.md
- docs/validation-example.md
- run-validations.sh
As titled. This will tell the flight recorder which branch to use.
Related: #499
> Require the use of STACK_VERSION when running validations

- .github/workflows/update-model-info.yml
- compiler/model/metamodel.ts
- compiler/steps/add-info.ts
- output/schema/schema.json
This pr introduces a new github action that is executed every time some code is pushed in `main` or `7.*` branches.
It also updates the info step of the compiler to update the `version` and `hash` fields to use the current git values if the compiler is being run from a base branch, leave those fields as is otherwise.
NOTE: It will require a test run in the main branch to be sure that everything works as expected.
Related: #499
> Generate version and hash fields in schema output

- .github/workflows/update-rest-api-json.yml
- compiler/steps/add-info.ts
As titled.
The issue was that the `update-rest-api-json.yml` action runs itself on main, and then creates a branch if there are changes, which triggers a version field change.
Fixes https://github.com/elastic/elasticsearch-specification/pull/526
> Skip version update when updating the rest-api-spec

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/_types/Detector.ts
- specification/ml/_types/Settings.ts
- specification/ml/update_job/MlUpdateJobRequest.ts
- specification/ml/update_job/MlUpdateJobResponse.ts
- Ran into the `MlCustomSettings` issue I've seen before, not sure how to handle arbitrary fields plus a few known fields.
- Hit a validation error where a value wasn't fitting into the `MlAppliesTo` enum but that value wasn't printed and when I checked out the `workbench` directory it was consistently empty, not sure what to do here?
> Validate 'ml.update_job'

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/_types/Datafeed.ts
- specification/ml/preview_datafeed/MlPreviewDatafeedRequest.ts
- specification/ml/preview_datafeed/MlPreviewDatafeedResponse.ts
Got an error for having an array of `TDocument` as a response body:
```
> elasticsearch-client-specification@0.0.1 generate-schema /home/sethmlarson/elasticsearch-specification/compiler
> ts-node index.ts
Error: Children should be PropertySignature or PropertyDeclaration but is TypeReference instead
At: /home/sethmlarson/elasticsearch-specification/specification/ml/preview_datafeed/MlPreviewDatafeedResponse.ts:21:8
19  
20  export class Response<TDocument> {
21    body: TDocument[]
22  }
23  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elasticsearch-client-specification@0.0.1 generate-schema: `ts-node index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elasticsearch-client-specification@0.0.1 generate-schema script.
npm ERR! This is probably not a problem with npm. …
```
> Validate 'ml.preview_datafeed' API

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/Job.ts
- specification/ml/reset_job/MlResetJobRequest.ts
- specification/ml/reset_job/MlResetJobResponse.ts
Closes https://github.com/elastic/elasticsearch-specification/issues/494
@jgowdyelastic can you take a look and verify this matches what you expect?
There don't seem to be any YAML tests for the `blocked` attribute (can we get one or more of these?)
> Add 'ml.reset_job' API and 'MlJob.blocked'

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/_types/Job.ts
- specification/ml/put_job/MlPutJobRequest.ts
- specification/ml/put_job/MlPutJobResponse.ts
- specification/ml/update_job/MlUpdateJobRequest.ts
This is a reversion of #522.
We decided not to add a new setting after all, but to
use results_retention_days for both results and system
annotations (on the basis that system annotations are
a type of result).
This setting has been added and removed within the 7.15
development cycle so there are no implications for
anyone using released product.
Relates to elastic/elasticsearch#76096
> Remove ML system_annotations_retention_days setting

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/_types/Analysis.ts
Related to https://github.com/elastic/elasticsearch/pull/75741
> [ML] Add 'model_prune_window' field to AD job config

- output/schema/schema.json
- output/typescript/types.ts
- specification/_global/search/SearchRequest.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
It's common to do `search_after = hits[-1].sort` so type-wise we should ensure this works out.
> Make search_after type the same as Hit.sort

- .github/CODEOWNERS
As titled, for now, I've configured only the `ml` subfolder, in the future, we should identify more teams.
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners
> Add CODEOWNERS configuration

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/Scripting.ts
As titled, see https://github.com/elastic/elasticsearch-js/issues/1518.
I'm not sure defining the type like this makes sense. It might be worth just define `lang` as `string`.
> Script lang can be a custom string

- output/schema/schema.json
- specification/ml/delete_data_frame_analytics/MlDeleteDataFrameAnalyticsRequest.ts
This PR adds descriptions to the properties of the DELETE data frame analytics API.
> [ML] Adds description to the DELETE DFA API spec

- output/schema/schema.json
- specification/ml/_types/Analysis.ts
This PR changes the `model_prune_window` parameter description to be in line with the published ML API docs in the ES guide.
> [ML] Changes model_prune_window description

- output/schema/schema.json
- specification/_global/search/SearchRequest.ts
Wanted to fill in a bunch of descriptions for the `search` API.
Also `@server_default` doesn't work great for `union_of` types which is unfortunate because there are a couple cases where we can't use `@server_default` with these parameters like `_source`.
> [DOCS] Document parameters for the 'search' API

- output/schema/schema.json
- specification/security/_types/IndicesPrivileges.ts
Applies changes from #551, which were merged into a GitHub void and utterly consumed by its crushing power.
> [DOCS] Update security indices

- output/schema/schema.json
- specification/ml/_types/Analysis.ts
This PR removes references of two model memory limit-related settings from  `model_prune_window` description as they seem equal to the soft and hard limits, but it is not the case.
> [ML] Fixes model_prune_window description

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/render_search_template/RenderSearchTemplateRequest.ts
- specification/ilm/delete_lifecycle/DeleteLifecycleRequest.ts
- specification/ilm/put_lifecycle/PutLifecycleRequest.ts
- specification/indices/put_mapping/IndicesPutMappingRequest.ts
- specification/ml/post_calendar_events/MlPostCalendarEventsRequest.ts
- specification/security/clear_api_key_cache/SecurityClearApiKeyCacheRequest.ts
This pr fixes a bunch of `path_parts` that should be required.
This change will break the validation for [`security.clear_api_key_cache`](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-clear-api-key-cache.html), our test are sending requests without `ids`, but in both docs and rest-api-spec `ids` is required.
> Fix required properties

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/update/UpdateRequest.ts
Two test cases use strings for the `routing` parameter, will have to fix that in rest-api-spec.
> Validate the 'update' API

- compiler/steps/add-description.ts
- output/schema/schema.json
This pr updates the `addDescription` step of the compiler which wasn't updated with the last iteration of the spec.
Now, if a path or query parameter does not contain a description in the input specification, the description will be pulled from the rest-api-spec.
> Fix addDescription step

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/rollup/rollup/RollupRequest.ts
- specification/rollup/rollup/RollupResponse.ts
As this API is not documented, quite complex, and experimental, we have agreed to treat the request and response body as `UserDefinedValue` for now. I'm awaiting some feedback from the Elasticsearch engineers to understand if this API is valid still.
> Fix stubbed rollup API

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/common.ts
- specification/shutdown/get_node/ShutdownGetNodeRequest.ts
- Updates NodeIds to be a union of `string` and `string[]` to align with other types.
- Updates Shutdown Get Node to use NodeIds rather than `NodeId[]` for the path part.
> Fix shutdown get node API

- .github/workflows/update-rest-api-json.yml
As titled. This should fix the current issue once merged with https://github.com/elastic/elasticsearch-specification/pull/654. Furthermore, if it fails it will now open an issue.
> Update rest-api-spec action

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/slm/_types/SnapshotLifecycle.ts
- specification/slm/put_lifecycle/PutSnapshotLifecycleRequest.ts
- specification/watcher/_types/Schedule.ts
as titled.
Problem was that `CronExpression` was a class extending `ScheduleBase` which is an empty object, hence the correct type string could not be casted.
Commented out obsolete classes.
Will also fix, `slm.get_lifecycle` response
> Fix slm.put_lifecycle Request

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/search_mvt/SearchMvtRequest.ts
- specification/_global/search_mvt/SearchMvtResponse.ts
- specification/_global/search_mvt/_types/GridType.ts
This API is different than others because it's response body is a binary format. Wasn't sure how else to represent this except for `any`? Currently there aren't any test cases for this API but I plan on adding some.
cc @iverase
> Add 'search_mvt' API

- output/schema/schema.json
- output/typescript/types.ts
- specification/_global/mtermvectors/MultiTermVectorsRequest.ts
- specification/_global/mtermvectors/types.ts
as titled and **do not** backport as this PR removes `_type` which is only deployed on `master`.
> Fix mtermvectors

- .gitattributes
- output/schema/schema.json
This file [**should** instruct github](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/customizing-how-changed-files-appear-on-github) not to show the diff for every file inside `output/**` by default.
This should help reviewers who are not used or do not know the repo structure, hinting them directly at which files they should review.
> Add .gitattributes

- compiler/model/utils.ts
- output/schema/schema.json
Follow up to PR https://github.com/elastic/elasticsearch-specification/pull/550#discussion_r690437940 and PR #553 that removed newlines from descriptions in `schema.json`.
This PR removes the replacement of newlines by spaces. This is loosing some important information, even more now that we have settled on using Markdown for rich descriptions (Java generator [now has support for it](https://github.com/elastic/elastic-client-generator-java/commit/5f36e67f9b11c70fb90bbd108075552c2fc9f60e)).
> Do not filter out newlines in descriptions

- output/schema/schema.json
- output/typescript/types.ts
- specification/_global/search_mvt/SearchMvtRequest.ts
- specification/_global/search_mvt/_types/Coordinate.ts
- specification/_global/search_mvt/_types/ZoomLevel.ts
As discussed on today's sync, I've updated the path parts for the SearchMvtRequest to use type aliases which are more descriptive. I've opted not to reuse `GeoTilePrecision` for `zoom` for the time being. It's not clear if these are exactly the same thing, despite being constrained to the same range of values. Once #477 is concluded, we may change these to constrain their inputs.
> Update path parts for SearchMvtRequest

- output/schema/schema.json
- output/typescript/types.ts
- specification/ccr/get_auto_follow_pattern/types.ts
- specification/ccr/put_auto_follow_pattern/PutAutoFollowPatternRequest.ts
> Fix ccr.get_auto_follow_pattern response

- compiler/model/utils.ts
- docs/modeling-guide.md
- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/Binary.ts
- typescript-generator/index.ts
> Add Binary data type

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/indices/disk_usage/IndicesDiskUsageRequest.ts
- specification/indices/disk_usage/IndicesDiskUsageResponse.ts
added the request but I need some help from @delvedor & @swallez how to model the reponse.
> Add indices.disk_usage Enpoint

- docs/doc-comments-guide.md
- docs/modeling-guide.md
Adds a doc explaining how to write and structure JSDoc documentation in the specification.
@goodroot I added you as a reviewer, feel free to add more people from the docs team to raise awareness and provide feedback.
> Add documentation on spec documentation

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/count/CountRequest.ts
- specification/_global/explain/ExplainRequest.ts
- specification/_global/scroll/ScrollRequest.ts
- specification/_global/search_template/SearchTemplateRequest.ts
- specification/_global/update_by_query/UpdateByQueryRequest.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
- specification/indices/validate_query/IndicesValidateQueryRequest.ts
Noticed these options on multiple APIs which looks like an artifact from the past? Removed as it didn't seem to be used/documented on the Elasticsearch side.
> Remove unused NEST options from APIs

- compiler/model/utils.ts
- compiler/steps/add-description.ts
- output/schema/schema.json
For some reason, we are not outputting the endpoint descriptions in the json, this pr fixes that.
If an endpoint definition is not present in the input spec, the rest-api-spec will be used, in the same way we are doing for the path/query parameters.
> Add support for endpoint description

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/analysis/analyzers.ts
- specification/_types/analysis/char_filters.ts
- specification/_types/analysis/icu-plugin.ts
- specification/_types/analysis/kuromoji-plugin.ts
- specification/_types/analysis/normalizers.ts
- specification/_types/analysis/phonetic-plugin.ts
- specification/_types/analysis/token_filters.ts
- specification/_types/analysis/tokenizers.ts
- specification/indices/_types/IndexSettings.ts
- specification/indices/_types/IndexState.ts
Most of this is adding `@variant` to analyzers, tokenizers, token filters and char filters.
Added `IndexState.data_stream?` to close https://github.com/elastic/elasticsearch-specification/issues/532
> Add variants to analysis classes, Add IndexState.data_stream

- compiler/model/metamodel.ts
- compiler/model/utils.ts
- docs/modeling-guide.md
> Add support for doc_id

- output/schema/schema.json
- output/typescript/types.ts
- specification/nodes/info/types.ts
Backport to `7.x` of https://github.com/elastic/elasticsearch-specification/pull/744
> [Backport 7.x] Fix nodes.info settings

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/Geo.ts
- specification/_types/Result.ts
- specification/_types/Time.ts
- specification/_types/aggregations/pipeline.ts
- specification/_types/common.ts
- specification/indices/_types/DataStreamStatus.ts
This fixes a few enumerations (e.g. `GREEN / green` or `z-score`) and adds some meaningful `snake_case` identifiers that translate well using the various casing conventions used in generated code (e.g. `UpperCamelCase` in Java).
> Fix enumerations and add more meaningful identifiers

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/query_dsl/fulltext.ts
- specification/_types/query_dsl/span.ts
As titled. The existing definition was most certainly a "Nest-ism".
> Fix span_gap query definition

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/put_datafeed/MlPutDatafeedRequest.ts
Follow-up to PR #518 - removes the `indexes` property from `ml.put_datafeed` and replace it with an alias on `indices`. Both values are accepted server-side but end up in the same property, and only `indices` is used in serialization.
/cc @sethmlarson and @stevejgordon for information
> Use a single property for indexes/indices

- output/schema/schema.json
- specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts
Related to https://github.com/elastic/elasticsearch-specification/issues/713 and https://github.com/elastic/elasticsearch-specification/pull/717#issuecomment-918844192
This PR tests the addition of security prerequisites to the API spec, in particular for a PR that has different index privileges related to source and destination indices per https://www.elastic.co/guide/en/elasticsearch/reference/master/put-dfanalytics.html#ml-put-dfanalytics-prereq
> Add security prerequisites for ML create data frame analytics API

- output/schema/schema.json
- specification/ml/update_job/MlUpdateJobRequest.ts
Related to https://github.com/elastic/elasticsearch-specification/pull/732
This PR tests the new [@doc_id ](https://github.com/elastic/elasticsearch-specification/blob/main/docs/modeling-guide.md#doc_id) functionality. The ml.customUrls keyword in this case should resolve to the same type of URL as exists in https://github.com/elastic/kibana/blob/master/src/core/public/doc_links/doc_links_service.ts
I also removed some links to out-dated URLs that are no longer valid or necessary.
> Add doc_id; remove out-dated links

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/close_job/MlCloseJobRequest.ts
Related to https://github.com/elastic/elasticsearch/pull/60601
This PR updates the spec for the close anomaly detection jobs API as follows:
- Adds API description/overview 
- Adds security prerequisites
- Adds missing allow_no_match query parameter
- Deprecates allow_no_jobs 
- Updates timeout default value from 30s to 30m (per [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-close-job.html) and https://github.com/elastic/elasticsearch/blob/6fbc1b88d8a39bba6ab3c113b9410d0cfbff655a/client/rest-high-level/src/main/java/org/elasticsearch/client/ml/CloseJobRequest.java#L99)
> Updates the spec for ML close anomaly detection jobs API

- output/schema/schema.json
- output/typescript/types.ts
- specification/security/_types/Privileges.ts
In the response at least, some `IndicesPrivileges` properties are returned as arrays, potentially containing a single item. Since this type is used for requests also where single items can be sent, I've made these a union.
> Fix Security.Get_User_Privileges

- docs/doc-comments-guide.md
- output/schema/schema.json
- specification/_global/rank_eval/RankEvalRequest.ts
Since the [doc comments guide](https://github.com/elastic/elasticsearch-specification/blob/main/docs/doc-comments-guide.md) references the rank evaluation API, this PR adds some missing info to that specification then refreshes the example in the guide. It also adds a link to the [modeling guide](https://github.com/elastic/elasticsearch-specification/blob/main/docs/modeling-guide.md#additional-information), where the tags are explained in greater detail.
> Refresh rank_eval and doc comments guide

- compiler/model/metamodel.ts
- compiler/model/utils.ts
- docs/modeling-guide.md
- typescript-generator/index.ts
For some enumerations, the ES server accepts aliases for enum members. A typical example is [`GeoOrientation`](https://github.com/elastic/elasticsearch-specification/blob/7783d94c66913fe408715065075f2533f26c43b0/specification/_types/mapping/geo.ts#L30) where [ES interprets](https://github.com/elastic/elasticsearch/blob/7047e202eae7d40beda2ed14a573ee9f0c935538/server/src/main/java/org/elasticsearch/common/geo/Orientation.java#L38) `counterclockwise` and `ccw` as `right`, and `clockwise` and `cw` as `left`.
This PR adds `@aliases` on enumerations to support these use cases.
> Add @aliases support to enum members

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/analysis/normalizers.ts
- specification/indices/_types/IndexSettings.ts
This fixes the normalizers definition for index settings. There's one builtin `lowercase` normalizer, and the `custom` normalizer defined as a filter pipeline.
> Fix normalizer definition in index settings

- output/typescript/types.ts
- typescript-generator/index.ts
Generates `Partial<Record<TKey, TValue>>` for single key dictionaries (needed for #890).
Although `Record<TKey, TValue>` works fine for string keys as this is an open-ended type, using an enum causes errors as `Record` expects *all* enum values to exist as properties, and not only one. Using `Partial` makes all keys optional, which allow just one to exist.
Capturing in the type that exactly one of the enum members must exist as a property can probably be achieved by expanding a union with all enum members, but that would substantially complexify the code generator and its output.
> Fix SingleKeyDictionary TypeScript generation

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/Errors.ts
- specification/_types/mapping/meta-fields.ts
- specification/nodes/_types/Stats.ts
Fixes a few tiny issues on some unrelated types:
- `Error.root_cause` should be optional
- `FieldMapping.mapping` maps fields
- `ExtendedMemoryStats` has some duplicate fields with the parent `ExtendedMemory`, but with different tyles (long vs int)
> Fine tuning and minor fixes

- output/schema/schema.json
- output/typescript/types.ts
- specification/cluster/pending_tasks/types.ts
Per the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-pending.html#cluster-pending-api-response-body), the pending task should include a `boolean` property named `executing`. This PR adds that missing property.
> Add missing executing property on PendingTask

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/get_source/SourceRequest.ts
The 7.x APIs still have type parameters and it was missing from the `get_source` request definition.
> Add missing (deprecated) `type` query parameter

- compiler/model/utils.ts
- output/typescript/types.ts
- typescript-generator/index.ts
Adds support for `@aliases` to request and response properties (it was only implemented on classes/interfaces)
Also improves error message for the expected `@variant` syntax
> Add property alias support in requests and responses & improve error message

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/async_search/_types/AsyncSearch.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
- specification/license/post_start_trial/StartTrialLicenseResponse.ts
- specification/ml/_types/Datafeed.ts
- specification/rollup/rollup_search/RollupSearchRequest.ts
Depends on PR #970
Uses `@aliases` to deduplicate `aggs` and `aggregations` properties in search requests and a few other places. `aggregations` is chosen as the canonical name and `aggs` as an alias as ES uses `aggregations` when serializing objects (and it's also more meaningful).
`SearchMvtRequest` is the only exception, since it only accepts `aggs` with no alias.
> Dedup aggregrations/aggs fields

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
- specification/cat/ml_jobs/CatJobsRequest.ts
Adds descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-datafeeds.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-anomaly-detectors.html
Related to https://github.com/elastic/elasticsearch/issues/60732
... also replaces the allow_no_datafeeds and allow_no_jobs with allow_no_match
> Adds descriptions for cat anomaly detectors and cat datafeeds APIs

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/close_job/MlCloseJobRequest.ts
- specification/ml/get_job_stats/MlGetJobStatsRequest.ts
- specification/ml/get_jobs/MlGetJobsRequest.ts
- specification/ml/get_overall_buckets/MlGetOverallBucketsRequest.ts
Relates to https://github.com/elastic/elasticsearch/issues/60732
This PR removes the allow_no_jobs and allow_no_datafeeds properties, which have been replaced by allow_no_match in 8.0.  It also sorts the properties in the get overall buckets API.
> Remove allow_no_jobs and allow_no_datafeeds

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
- specification/cat/ml_jobs/CatJobsRequest.ts
- specification/ml/get_datafeed_stats/MlGetDatafeedStatsRequest.ts
- specification/ml/get_datafeeds/MlGetDatafeedsRequest.ts
- specification/ml/get_job_stats/MlGetJobStatsRequest.ts
- specification/ml/get_jobs/MlGetJobsRequest.ts
- specification/ml/stop_datafeed/MlStopDatafeedRequest.ts
Relates to https://github.com/elastic/elasticsearch/issues/60642
This PR adds the @deprecated attribute for the allow_no_datafeeds and allow_no_jobs properties in the appropriate machine learning APIs.
> Deprecates allow_no_jobs and allow_no_datafeeds 

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/analysis/analyzers.ts
- specification/_types/analysis/icu-plugin.ts
- specification/_types/analysis/kuromoji-plugin.ts
- specification/_types/analysis/phonetic-plugin.ts
- specification/_types/analysis/token_filters.ts
- specification/_types/analysis/tokenizers.ts
- specification/_types/mapping/DenseVectorIndexOptions.ts
- specification/_types/mapping/TimeSeriesMetricType.ts
- specification/_types/mapping/complex.ts
- specification/_types/mapping/core.ts
- specification/indices/_types/IndexSegmentSort.ts
- specification/indices/_types/IndexSettings.ts
- specification/indices/create/IndicesCreateRequest.ts
This PR updates the create index request type so that it uses just a mapping instance rather than a union, and uses the `IndexSettings` type for settings. This required many tokenizers, char filters, token filters and analyzers to be fixed up due to failing tests.
The remaining failures are due to the flattened, vs object style settings and we will deal with those separately as discussed with @delvedor.
This will require a manual cherry-pick backport once merged since some changes fix additions for the new time series properties which won't be needed for 7.x.
> Fix create index request

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/query_dsl/term.ts
A wildcard query must have either a `value` or a `wildcard` property. This PR adds the missing property and marks both as optional since either may be set.
> Add missing wildcard property

- output/schema/schema.json
- specification/ml/preview_data_frame_analytics/MlPreviewDataFrameAnalyticsRequest.ts
- specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts
- specification/ml/put_trained_model/MlPutTrainedModelRequest.ts
- specification/ml/put_trained_model_alias/MlPutTrainedModelAliasRequest.ts
- specification/ml/reset_job/MlResetJobRequest.ts
- specification/ml/revert_model_snapshot/MlRevertModelSnapshotRequest.ts
This PR adds descriptions to the properties of the following APIs:
* preview DFA 
* PUT DFA
* PUT trained models
* PUT trained model aliases
* reset AD job
* revert model snapshot.
> [ML] Updates preview, create DFA, create trained model/aliases, reset job, and revert model snapshot APIs

- output/schema/schema.json
- output/typescript/types.ts
- specification/watcher/stats/types.ts
reduces the error from 4 to 3.
By casting  `"emit_stacktraces": "true"` to boolean in the upstream test `rest-spec-tests/platinum/watcher/stats/10_basic.yml`, we'll eliminate another error case.
> Improve watcher.stats request

- output/schema/schema.json
- output/typescript/types.ts
- specification/_spec_utils/behaviors.ts
Documented all the parameters defined in `CommonQueryParameters` and `CommonCatQueryParameters`.
I also found `source_query_string` which isn't an Elasticsearch parameter but is instead likely inherited from NEST and would've been translated into `?source=...` as a means of smuggling small request bodies for GET into the query string. I've removed this parameter in this PR.
> Document CommonQueryParameters

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/get_calendar_events/MlGetCalendarEventsRequest.ts
- specification/ml/get_calendars/MlGetCalendarsRequest.ts
- specification/ml/get_calendars/types.ts
This PR updates [get_calendar_events](https://github.com/elastic/elasticsearch-specification/tree/main/specification/ml/get_calendar_events) and [get_calendars](https://github.com/elastic/elasticsearch-specification/tree/main/specification/ml/get_calendars) with info from the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-get-calendar-event.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-get-calendar.html).
NOTE: The request body is omitted from the get calendar events API, per https://github.com/elastic/elasticsearch/issues/79271
> Adds missing doc details for ML get calendar APIs

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/start_datafeed/MlStartDatafeedRequest.ts
- specification/ml/start_datafeed/MlStartDatafeedResponse.ts
- specification/ml/stop_datafeed/MlStopDatafeedRequest.ts
Relates to https://github.com/elastic/stack-docs/issues/1845
Uses descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-start-datafeed.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-stop-datafeed.html
> Adds descriptions and missing parameters for start and stop datafeed APIs

- output/schema/schema.json
- output/typescript/types.ts
- specification/_global/open_point_in_time/OpenPointInTimeRequest.ts
The `keep_alive` parameter isn't documented as required/options in the docs, however trying to use the API without it [always produces an error](https://github.com/elastic/elasticsearch/blob/26c86871fc091900952e88e252c36fbfedf8d5fa/server/src/main/java/org/elasticsearch/action/search/OpenPointInTimeRequest.java#L104). I'm not sure if there are other query parameters that are required, if not this may be the first of it's kind!
Corresponding PR to the other API spec: https://github.com/elastic/elasticsearch/pull/80449
> Mark 'keep_alive' for 'open_point_in_time' API as required

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/forecast/MlForecastJobRequest.ts
This PR updates the specification for the machine learning "forecast" API, since the parameters listed in the body of the API are also applicable as query parameters.
> Adds missing query parameters for ML forecast API

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/flush_job/MlFlushJobRequest.ts
- specification/ml/flush_job/MlFlushJobResponse.ts
This PR updates the specification for the machine learning "flush jobs" API, since the parameters listed in the body of the API are also applicable as query parameters.
> Adds missing query parameters in ML flush jobs API

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/Bucket.ts
- specification/ml/_types/Influencer.ts
- specification/ml/get_buckets/MlGetBucketsRequest.ts
- specification/ml/get_influencers/MlGetInfluencersResponse.ts
This PR fixes the get buckets API as follows:
- the list of query parameters and request body parameters should be identical
- the list of properties for the `bucket_influencers` in the API response was inaccurate. I've therefore split off a new Influencer.ts for use by the get influencers API and fixed the existing details in Bucket.ts
- the partition_scores response is no longer valid and has been removed
> Updates ML get buckets API specification

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/Bucket.ts
- specification/ml/_types/Influencer.ts
- specification/ml/get_buckets/MlGetBucketsRequest.ts
- specification/ml/get_influencers/MlGetInfluencersResponse.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/1020, which didn't backport automatically.
> Updates ML get buckets API specification (#1020)

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/update_datafeed/MlUpdateDatafeedRequest.ts
- specification/ml/update_datafeed/MlUpdateDatafeedResponse.ts
[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-update-datafeed.html) and a [rest-api-spec](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/ml.update_datafeed.json) exist for the "update datafeed" API, but it was missing from these specifications.
> Adds spec for update datafeed API

- output/schema/schema.json
- output/typescript/types.ts
- specification/ml/_types/Model.ts
- specification/ml/get_model_snapshots/MlGetModelSnapshotsRequest.ts
These descriptions are based on the [get model snapshots API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-get-snapshot.html)
> Adds missing model snapshot parameters and descriptions

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/close_job/MlCloseJobRequest.ts
- specification/ml/get_calendar_events/MlGetCalendarEventsRequest.ts
- specification/ml/get_overall_buckets/MlGetOverallBucketsRequest.ts
- specification/ml/get_records/MlGetAnomalyRecordsRequest.ts
- specification/ml/open_job/MlOpenJobRequest.ts
This PR adds missing details for the ML get calendar events, get overall buckets, and get records API.
> Add missing request body detail for ML get APIs

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/put_datafeed/MlPutDatafeedRequest.ts
- specification/ml/revert_model_snapshot/MlRevertModelSnapshotRequest.ts
This PR adds missing query parameters for the ML revert model snapshot API and missing descriptions for the create datafeeds API.
> Add query parameters for revert model API

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/bulk/BulkRequest.ts
- specification/_global/delete_by_query/DeleteByQueryRequest.ts
- specification/_global/exists/DocumentExistsRequest.ts
- specification/_global/exists_source/SourceExistsRequest.ts
- specification/_global/explain/ExplainRequest.ts
- specification/_global/get/GetRequest.ts
- specification/_global/get/GetResponse.ts
- specification/_global/get/types.ts
- specification/_global/get_source/SourceRequest.ts
- specification/_global/mget/MultiGetRequest.ts
- specification/_global/mget/MultiGetResponse.ts
- specification/_global/mget/types.ts
- specification/_global/msearch/MultiSearchRequest.ts
- specification/_global/msearch/MultiSearchResponse.ts
- specification/_global/msearch/types.ts
- specification/_global/msearch_template/MultiSearchTemplateRequest.ts
- specification/_global/msearch_template/MultiSearchTemplateResponse.ts
- specification/_global/msearch_template/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
- specification/_global/update/UpdateRequest.ts
- specification/_global/update_by_query/UpdateByQueryRequest.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
Refactor and fix the `Multi{Search|Get|TemplateSearch}` APIs:
* fix some definitions that were not correct
* introduce unions to distiguish the header and body parts of ndjson requests
* reuse types between APIs when possible.
> Refactor and fix multi* APIs

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/fleet/_types/Checkpoints.ts
- specification/fleet/global_checkpoints/GlobalCheckpointsRequest.ts
- specification/fleet/global_checkpoints/GlobalCheckpointsResponse.ts
Adds the `fleet.global_checkpoints` API which unfortunately doesn't have any recorded tests?
Request was built from the documentation, an example response for this API looks like:
```json
{"timed_out":false,"global_checkpoints":[2]}
```
> Add 'fleet.global_checkpoints' API

- output/schema/schema.json
- output/typescript/types.ts
- specification/_types/mapping/TermVectorOption.ts
Adds `with_positions_payloads` to `TermVectorOption`.
Reported by @sothawo in https://github.com/elastic/elasticsearch-java/issues/48
> Add missing TermVectorOption enum member

- output/schema/schema.json
- output/typescript/types.ts
- specification/indices/_types/IndexRouting.ts
- specification/indices/_types/IndexSegmentSort.ts
Follow-up to #1054 - testing with `include_defaults=true` revealed some further issues in the index settings definition.
> Fix some index setting fields

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/put_trained_model_definition_part/MlPutTrainedModelDefinitionPartRequest.ts
- specification/ml/put_trained_model_definition_part/MlPutTrainedModelDefinitionPartResponse.ts
Relates to https://github.com/elastic/elasticsearch/pull/76987
This PR adds a specification for the ML [create trained model definition part API](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-trained-model-definition-part.html) per https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/ml.put_trained_model_definition_part.json
> Adds ML put model definition part API

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/put_trained_model_vocabulary/MlPutTrainedModelVocabularyRequest.ts
- specification/ml/put_trained_model_vocabulary/MlPutTrainedModelVocabularyResponse.ts
Relates to [elastic/elasticsearch#76987](https://github.com/elastic/elasticsearch/pull/77387)
This PR adds a specification for the ML [create trained model vocabulary API](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-trained-model-vocabulary.html) per https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/ml.put_trained_model_vocabulary.json
> Adds ML put trained model vocabulary API

- output/schema/schema.json
- output/typescript/types.ts
- specification/transform/delete_transform/DeleteTransformRequest.ts
This PR adds descriptions to the delete transform specification from the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/delete-transform.html)
> Adds descriptions to delete transform API

- output/schema/schema.json
- specification/_json_spec/ml.validate.json
- specification/_json_spec/ml.validate_detector.json
- specification/ml/validate/MlValidateJobRequest.ts
- specification/ml/validate_detector/MlValidateDetectorRequest.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/1010
> Adds visibility tag to ML validate APIs

- output/schema/schema.json
- output/typescript/types.ts
- specification/_global/search/SearchResponse.ts
Remove a property which is a carry over from a NEST shortcut to the hits. This is not on the response.
> Remove NESTism documents property

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
- specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentRequest.ts
- specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentResponse.ts
- specification/ml/stop_trained_model_deployment/MlStopTrainedModelDeploymentRequest.ts
- specification/ml/stop_trained_model_deployment/MlStopTrainedModelDeploymentResponse.ts
Relates to https://github.com/elastic/elasticsearch/pull/73660
Adds specifications for the [start trained model deployment API](https://www.elastic.co/guide/en/elasticsearch/reference/master/start-trained-model-deployment.html) and [stop trained model deployment APII](https://www.elastic.co/guide/en/elasticsearch/reference/master/stop-trained-model-deployment.html) based on the documentation and specs ([ml.stop_trained_model_deployment.json](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/ml.stop_trained_model_deployment.json), [ml.start_trained_model_deployment](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/ml.start_trained_model_deployment.json))
> Adds ML start and stop trained model deployment specifications

- output/schema/schema.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
- specification/ml/infer_trained_model_deployment/MlInferTrainedModelDeploymentRequest.ts
- specification/ml/infer_trained_model_deployment/MlInferTrainedModelDeploymentResponse.ts
Relates to https://github.com/elastic/elasticsearch/pull/73660
This PR adds a specification for the ML [infer trained model deployment API](https://www.elastic.co/guide/en/elasticsearch/reference/master/infer-trained-model-deployment.html) per https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/ml.infer_trained_model_deployment.json
NOTE: I have omitted the security details for now, since they're missing from the documentation but we'll want to fix that in both places.
> Adds ML infer trained model deployment API

- compiler/model/build-model.ts
- compiler/model/metamodel.ts
- compiler/model/utils.ts
- compiler/steps/validate-model.ts
Adds spec source location to type definitions in `schema.json`, containing path and line number. The path is relative to the `specification` directory, e.g.
```json
"specLocation": {
"path": "_types/query_dsl/compound.ts",
"startLine": 131,
"endLine": 137
}
```
> Add spec source location to type definitions

- output/typescript/types.ts
- specification/ml/delete_data_frame_analytics/MlDeleteDataFrameAnalyticsRequest.ts
- specification/ml/delete_job/MlDeleteJobRequest.ts
- specification/ml/get_categories/MlGetCategoriesRequest.ts
- specification/ml/put_trained_model/MlPutTrainedModelRequest.ts
- specification/ml/reset_job/MlResetJobRequest.ts
- specification/ml/stop_trained_model_deployment/MlStopTrainedModelDeploymentRequest.ts
This PR adds two missing ML API descriptions and does some minor edits to a few other intros so that our first draft of all the machine learning API specs is complete.
> Adds missing ML API intros

- output/schema/schema.json
- output/typescript/types.ts
- specification/transform/_types/Transform.ts
- specification/transform/put_transform/PutTransformRequest.ts
Relates to https://github.com/elastic/elasticsearch/pull/79003, https://github.com/elastic/elasticsearch/pull/56007, and https://github.com/elastic/elasticsearch/pull/76609 
This PR:
* Adds `align_checkpoints` and  `_meta` to the create transform API specification.
* Removes the discontinued max_page_search_size from the pivot configuration.
* Adds more descriptions based on the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-transform.html)
> Adds missing details in the create transform API

- output/typescript/types.ts
- specification/ml/delete_data_frame_analytics/MlDeleteDataFrameAnalyticsRequest.ts
- specification/ml/delete_job/MlDeleteJobRequest.ts
- specification/ml/get_categories/MlGetCategoriesRequest.ts
- specification/ml/put_trained_model/MlPutTrainedModelRequest.ts
- specification/ml/reset_job/MlResetJobRequest.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/1084
> [7.16] Adds missing ML API intros 

- output/typescript/types.ts
- specification/transform/start_transform/StartTransformRequest.ts
- specification/transform/stop_transform/StopTransformRequest.ts
Adds descriptions for the [start transform](https://www.elastic.co/guide/en/elasticsearch/reference/master/start-transform.html) and [stop transform](https://www.elastic.co/guide/en/elasticsearch/reference/master/stop-transform.html) APIs.
> Adds descriptions for start and stop transform APIs

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/delete_by_query/DeleteByQueryRequest.ts
- specification/_global/update_by_query/UpdateByQueryRequest.ts
Follows from https://github.com/elastic/elasticsearch/pull/81131, these parameters were always no-ops as both `update_by_query` and `delete_by_query` don't return source information.
> Remove source parameters from update_by_query/delete_by_query

- output/typescript/types.ts
- specification/ml/put_trained_model_definition_part/MlPutTrainedModelDefinitionPartRequest.ts
`number` converts to `float` in Python which isn't correct, should be an integer/long.
> Switch to using concrete types for ml.put_trained_model_definition_part

- output/typescript/types.ts
- specification/_json_spec/transform.delete_transform.json
- specification/_json_spec/transform.preview_transform.json
- specification/_json_spec/transform.put_transform.json
- specification/_json_spec/transform.reset_transform.json
- specification/_json_spec/transform.update_transform.json
- specification/_json_spec/transform.upgrade_transforms.json
- specification/transform/delete_transform/DeleteTransformRequest.ts
- specification/transform/preview_transform/PreviewTransformRequest.ts
- specification/transform/put_transform/PutTransformRequest.ts
- specification/transform/update_transform/UpdateTransformRequest.ts
This PR must be merged after https://github.com/elastic/elasticsearch/pull/81129
It adds the missing timeout query parameters to the transform API specifications.
> Adds missing timeout parameter to transform APIs

- output/typescript/types.ts
- specification/_json_spec/transform.delete_transform.json
- specification/_json_spec/transform.preview_transform.json
- specification/_json_spec/transform.put_transform.json
- specification/_json_spec/transform.update_transform.json
- specification/_json_spec/transform.upgrade_transforms.json
- specification/transform/delete_transform/DeleteTransformRequest.ts
- specification/transform/preview_transform/PreviewTransformRequest.ts
- specification/transform/put_transform/PutTransformRequest.ts
- specification/transform/update_transform/UpdateTransformRequest.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/1094
> [Backport 7.16] Adds missing timeout parameter to transform APIs

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/transform/upgrade_transforms/UpgradeTransformsRequest.ts
- specification/transform/upgrade_transforms/UpgradeTransformsResponse.ts
Adds a specification for the [upgrade transforms API](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/upgrade-transforms.html)
> Adds upgrade transform specification

- output/typescript/types.ts
- specification/_global/search/_types/hits.ts
`HitsMetadata.total` should be optional. Reported in https://github.com/elastic/elasticsearch-java/issues/56
> HitsMetadata.total is not present if track_total_hits == false

- output/typescript/types.ts
- specification/_global/search/_types/hits.ts
> [8.0] HitsMetadata.total is not present if track_total_hits == false

- output/typescript/types.ts
- specification/_global/search/_types/hits.ts
> [7.16] HitsMetadata.total is not present if track_total_hits == false

- output/typescript/types.ts
- specification/security/create_api_key/SecurityCreateApiKeyResponse.ts
There are NEST tests that don't have this property and thus fail, but those will require an update.
> Add 'encoded' property to SecurityCreateApiKeyResponse

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/query_dsl/abstractions.ts
The "wrapper" query type is missing in `QueryContainer`.
Reported in https://github.com/elastic/elasticsearch-java/issues/67
> Add missing "wrapper" query type

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/query_dsl/abstractions.ts
> query.wrapper should be optional

- output/typescript/types.ts
- typescript-generator/index.ts
This PR updates the TypeScript generator to produce `type Id = string | number`. Although document ids are strings, a lot of yaml tests use numbers as test document identifiers, which yaml returns as... well... numbers, and cause a number of API validations to fail.
With this change numbers are accepted for document id, which allows many more validation tests to pass.
> Generate Id as string|number in TypeScript

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ilm/delete_lifecycle/DeleteLifecycleRequest.ts
added more descriptions and fixed upstream tests in https://github.com/elastic/clients-flight-recorder/pull/839
> Validate ilm.delete_lifecycle

- .github/download-artifacts/index.js
- .github/workflows/update-rest-api-json.yml
Closes: https://github.com/elastic/elasticsearch-specification/issues/1081
> GA: Automatically use latest major version in main

- Makefile
- README.md
- compiler/check-node.js
- compiler/src/index.ts
With this change, the compiler will ensure that you are running it with the nodejs version configured in `.nvmrc`.
The `make setup` target will perform the same check as well.
Closes: #1011
> Check nodejs version before running the compiler

- specification/ml/_types/Analysis.ts
Relates to https://github.com/elastic/elasticsearch/pull/81377, which sets a default value for the model_prune_window setting in 8.1 and later releases.
> Model prune default

- compiler/package-lock.json
- compiler/package.json
- compiler/run-validations.js
- compiler/src/model/utils.ts
As titled.
Example:
```sh
▶ make validate stack-version=8.1.0-SNAPSHOT type=response api=indices.get_mappings
✖ The api 'indices.get_mappings' does not exists, did you mean 'indices.get_mapping'?
```
This check will be performed by both the compiler and validator.
> Suggest the correct API name if the input is wrong

- README.md
- compiler/run-validations.js
If you want to validate both requests and response types at the same time, omit the `type` argument in the make command, for example:
```sh
make validate stack-version=8.1.0-SNAPSHOT api=indices.create type=request
make validate stack-version=8.1.0-SNAPSHOT api=indices.create type=response
make validate stack-version=8.1.0-SNAPSHOT api=indices.create
```
> Validate both request and response at the same time

- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
Only applies to 8.1.0 I believe? The [PR adding it](https://github.com/elastic/elasticsearch/pull/78291) is marked as 8.0.0 but the YAML tests say 8.1.0.
> Add IndexSettings.time_series field

- output/typescript/types.ts
- specification/_types/aggregations/Aggregate.ts
Fixes https://github.com/elastic/elasticsearch-specification/issues/1221
`SingleBucketAggregateBase` accepts nested aggregations.
This PR also fixes `parent` and `children` aggregate that are single bucket aggregates and adds the missing `unmapped_sampler` aggregate.
Validation shows no new error related to the change:
```
% make validate api=search type=response stack-version=8.0.0-SNAPSHOT
- Validating endpoints
⚠ It looks like search response has some errors, take a look at the workbench.
/Users/sylvain/dev/elastic/src/clients/clients-flight-recorder/scripts/types-validator/workbench
scripts/types-validator/workbench/4fc631504dd7228aa9688c037933c48c.test-d.ts:16:6
Property '_id' is missing in type '{ _index: string; _score: number; }' but required in type 'SearchHit<unknown>'.
✖ 1560 …
```
> Single bucket aggregates have nested aggregates

- output/typescript/types.ts
- specification/_types/Stats.ts
- specification/indices/data_streams_stats/IndicesDataStreamsStatsResponse.ts
- specification/ml/_types/Model.ts
- specification/ml/post_data/MlPostJobDataResponse.ts
Integers are not large enough to hold timestamps. This caused a failure in the Java client (see https://github.com/elastic/elasticsearch-java/issues/88).
This PR fixes fields declared as `*_timestamp: integer` (which includes the one that caused the original issue).
> Change timestamps defined as integer to long

- output/typescript/types.ts
- specification/_types/aggregations/Aggregate.ts
As discussed with @swallez last week. It appears that a mistake slipped into a prior PR which changed the `distribution` field in `StringStatsAggregate` to a `string` from a `Dictionary<string, double>`. This PR reverts this as .NET client tests are failing due to the currently generated type using a string for the property.
@swallez Not sure if we want this backported back to 7.x branches?
> Fix regression in aggregation changes

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/msearch/MultiSearchRequest.ts
- specification/_global/msearch_template/MultiSearchTemplateRequest.ts
- specification/indices/_types/IndexSettings.ts
- specification/ml/_types/Datafeed.ts
- specification/ml/_types/Job.ts
- specification/nodes/hot_threads/NodesHotThreadsRequest.ts
- specification/transform/get_transform/GetTransformResponse.ts
- specification/transform/get_transform/types.ts
Backport #1235 to 7.17.
These changes, even if they introduce breaking changes, have to be backported as they're fixing errors in the spec that will cause strongly types clients (like Java) to fail.
> Address some of the Top 20 APIs

- output/typescript/types.ts
- specification/eql/search/EqlSearchRequest.ts
fixed 13 tests, still two failing though.
```
make validate stack-version=8.0.0-SNAPSHOT api=eql.search
- Validating endpoints
⚠ It looks like eql.search request has some errors, take a look at the workbench.
/Users/pkrauss/github.com/clients-flight-recorder/scripts/types-validator/workbench
scripts/types-validator/workbench/0407f84ece889d72be16d0133bbad50a.test-d.ts:15:6
Property 'type' is missing in type '{ script: string; }' but required in type 'MappingRuntimeField'.
scripts/types-validator/workbench/09192327dc9f866660e042f1f72f1742.test-d.ts:15:6
Property 'type' is missing in type '{ script: string; type: string; }[]' but required in type 'MappingRuntimeField'.
✖ 24 out of 26 test request cases are passing.
✔ 26 out of 26 test response cases are passing.
```
> Improve eql.search

- output/typescript/types.ts
- specification/_global/search/_types/profile.ts
- specification/_types/Node.ts
- specification/_types/aggregations/bucket.ts
Fixes some union types that had a missing `@codegen_names`, and also a property that only had a `null` type.
`AggregationProfileDebug` and `AggregationProfileDelegateDebug` have been merged into a single type. On the server side it's a `Map<String, Object>` and there's no strong indication that these are really two different types. Avoiding the union also simplifies the type definition.
> Fix some unlabelled unions

- output/typescript/types.ts
- specification/transform/_types/Transform.ts
Adds new deduce_mappings setting to the types in Transform.ts
Relates to https://github.com/elastic/elasticsearch/pull/82256
> Adds deduce_mappings transform setting

- output/typescript/types.ts
- specification/_types/aggregations/Aggregate.ts
The `key` field is missing on `RangeBucket`. Found in https://github.com/elastic/elasticsearch-java/issues/107
> Add an optional key field to RangeBucket

- output/typescript/types.ts
- specification/_types/Transform.ts
Follow-up to #1272
Chained transform is not a union but a simple array.
Backporting also to 7.17 even if #1272 was not as this field definition needs to be fixed.
> Fix chained transform definition

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/search/_types/suggester.ts
This PR fixes the defintion of suggest results. They are a typed-keys union type (i.e. externally tagged), used in `SearchResponse` as follows:
```ts
suggest?: Dictionary<SuggestionName, Suggest<TDocument>[]>
```
To correctly capture the typed-key nature of this type, `Suggest` has to be the union type, even if the difference only happens in the nested `options` field.
This was found in https://github.com/elastic/elasticsearch-java/issues/57 that is fixed by this change.
Unfortunately this PR adds 2 validation errors: `expectAssignable` doesn't seem to be able to correctly resolve the union member when the discriminating field is in the nested `options` field.
```
scripts/types-validator/workbench/702f290e18c3cd5fbc1ce1a3b0304f29.test-d.ts:32:12
Type '{ freq: number; score: number; text: …
```
> Fix suggest results that are a typed-key union type

- output/typescript/types.ts
- specification/_types/Time.ts
- specification/indices/_types/IndexSettings.ts
Refactor times series settings to add `@codegen_name` needed by the Java code generator.
Follow-up to #1229 that is 8.1 only
> Add `codegen_names` to time series settings time fields

- output/typescript/types.ts
- specification/_global/bulk/BulkRequest.ts
- specification/_global/bulk/types.ts
- specification/monitoring/bulk/BulkMonitoringRequest.ts
Adds a formal definition for the "document" part of the `update` bulk operation, similar to a regular document update request.
This also removes the generic parameter of the top-level `BulkRequest` (they're kept in invididual operations), considering that operations of a bulk request can have widely different unrelated types. The generic parameters are kept though in individual operation definitions.
Reported in https://github.com/elastic/elasticsearch-java/issues/81
> Add UpdateAction for bulk requests

- output/typescript/types.ts
- specification/indices/create/IndicesCreateRequest.ts
Follow-up to #1276 - reverts `indices.create:alias` to be a simple dictionary as it doesn't accept an array value.
> Changes back indices.create:alias to a simple dictionary

- output/typescript/types.ts
- specification/_global/msearch/types.ts
The `MultiSearchItem.status` property is always returned in multisearch responses but is missing from multisearch-template responses.
This should be considered as an inconsistency/bug in the ES API, and this PR fixes it by making `status` optional rather than creating a separate type for multisearch-template responses.
Reported in https://github.com/elastic/elasticsearch-java/issues/110
> Make MultiSearchItem.status optional

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/cat/_types/CatBase.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
Adds missing fields for the [cat datafeeds API](https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-datafeeds.html).
> Update cat datafeeds specification

- output/typescript/types.ts
- specification/_types/aggregations/Aggregate.ts
The top hits aggregation returns a simple result, with no buckets
Reported in https://github.com/elastic/elasticsearch-java/issues/123 ([see also doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-aggregations-metrics-top-metrics.html))
> Fixes TopHitsAggregate which are a simple aggregate (no buckets)

- output/typescript/types.ts
- specification/snapshot/create/SnapshotCreateResponse.ts
Snapshot info is only present if `wait_for_completion` was set to `true`.
Found in https://github.com/elastic/elasticsearch-java/issues/132
> Make snapshot info in CreateSnapshotResponse optional

- output/typescript/types.ts
- specification/_global/search/SearchResponse.ts
- specification/_global/search_template/SearchTemplateResponse.ts
Add missing fields to `SearchTemplateResponse` so that it has the same fields as `SearchResponse`.
Reported in https://github.com/elastic/elasticsearch-java/issues/89 and [the docs says](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#run-templated-search) _"The response uses the same properties as the search API's response"_.
> Add missing fields to SearchTemplateResponse

- specification/cat/ml_data_frame_analytics/CatDataFrameAnalyticsRequest.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
- specification/cat/ml_jobs/CatJobsRequest.ts
- specification/cat/ml_trained_models/CatTrainedModelsRequest.ts
- specification/cat/transforms/CatTransformsRequest.ts
This PR adds the admonition from https://www.elastic.co/guide/en/elasticsearch/reference/master/cat.html to all of the ML-related cat API specifications.
> Add admonition to cat ML specifications

- specification/cat/ml_data_frame_analytics/CatDataFrameAnalyticsRequest.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
- specification/cat/ml_jobs/CatJobsRequest.ts
- specification/cat/ml_trained_models/CatTrainedModelsRequest.ts
- specification/cat/transforms/CatTransformsRequest.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/1337
> [Backport 7.17] Add admonition to cat ML specifications

- .github/workflows/output-check.yml
- compiler/package.json
- compiler/run-validations.js
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/cat/_types/CatBase.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
- specification/cat/ml_jobs/CatJobsRequest.ts
It can happen that the specification does not catch an invalid `extends` or `implements`, especially if we are using behaviors.
This additional check will add an additional safeguard for those cases.
> Verify that the TS view is valid

- output/typescript/types.ts
- specification/security/_types/Privileges.ts
- specification/security/delete_privileges/SecurityDeletePrivilegesRequest.ts
As titled.
The APIs that are still failing should be fixed once https://github.com/elastic/clients-flight-recorder/pull/941 is merged.
> Fix security apis

- .github/workflows/validate-pr.yml
As titled. Otherwise the action will fail due to permissions.
> Run validate-pr action only if the pr is not from a fork

- specification/indices/exists_type/IndicesExistsTypeRequest.ts
This PR adds the @deprecated property to the
[type exists API](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-types-exists.html). The API is removed in 8.0 per https://www.elastic.co/guide/en/elasticsearch/reference/8.0/indices-types-exists.html
> Add @deprecated to indices.exists_type

- Makefile
- output/viewer.py
This adds a quick and dirty command line tool for browsing through the endpoints in a schema.
Arrow keys allow selection of an endpoint, [Q] to exit.
Usage:
```
$ python3 output/viewer.py output/schema/schema.json
```
Screenshot:
> Simple command line tool for browsing schema endpoints

- output/typescript/types.ts
- specification/ml/_types/Datafeed.ts
> Fix ml.get_datafeed_stats add missing optional search_interval property

- output/typescript/types.ts
- specification/async_search/status/AsyncSearchStatusResponse.ts
As titled, this removes the generic type on the status response for async search which is not used in the body. 
Also, `completion_status` should be optional as it's only returned for non-running searches.
@swallez Should we backport to 7.17?
> Remove generic on async search status response

- compiler/src/model/utils.ts
- compiler/src/steps/read-definition-validation.ts
- compiler/src/steps/validate-model.ts
- output/schema/validation-errors.json
- typescript-generator/src/client.ts
- typescript-generator/src/index.ts
In light of the new Elasticsearch’s `internal` namespace, we must rename our `internal` namespace.
Given that our namespace was holding primitive values, I propose to rename it to `_primitive`.
Related: https://github.com/elastic/elasticsearch-specification/pull/1417
> Rename internal namespace

- output/typescript/types.ts
- specification/indices/field_usage_stats/IndicesFieldUsageStatsRequest.ts
The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/field-usage-stats.html) says it's optional, but the [rest-api-spec](https://github.com/elastic/elasticsearch/blob/e851efbaa1d0048909a96bdb942d6a2ebb462504/rest-api-spec/src/main/resources/rest-api-spec/api/indices.field_usage_stats.json#L15-L29) allows only url templates with the index defined.
> Fix indices.field_usage_stats

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/indices/delete_index_template/IndicesDeleteIndexTemplateRequest.ts
Name can be a list (csv) of indices, change the type to `Names` which includes the type `Name` but also `Name[]` making this change not breaking but additive.
> Fix indices.delete_index_template Request

- output/typescript/types.ts
- specification/nodes/clear_repositories_metering_archive/ClearRepositoriesMeteringArchiveResponse.ts
- specification/nodes/get_repositories_metering_info/GetRepositoriesMeteringInfoResponse.ts
`_node: NodeStatistics` is defined in the parent class `NodesResponseBase` and causes a conflict.
> Remove _nodes property that exists in parent class

- output/typescript/types.ts
- specification/ml/_types/Filter.ts
- specification/ml/get_filters/MlGetFiltersRequest.ts
The API accepts an one or a list of unique identifiers, the PR changes the type from `Id` to `Ids` to address this.
> Fix ml.get_filters Request

- output/typescript/types.ts
- specification/ml/get_trained_models_stats/MlGetTrainedModelStatsRequest.ts
changed `Id` to `Ids` to unblock to list of identifiers use case.
> Fix ml.get_trained_models_stats Request

- output/typescript/types.ts
- specification/ml/delete_calendar_job/MlDeleteCalendarJobRequest.ts
Changed `Id` to `Ids` which is a superset of `Id`. The API accepts a string or a list of strings which is reflected in `Ids`.
> Fix ml.delete_calendar_job Request

- output/typescript/types.ts
- specification/indices/_types/IndexTemplate.ts
- specification/indices/get_index_template/IndicesGetIndexTemplateRequest.ts
- specification/indices/get_index_template/IndicesGetIndexTemplateResponse.ts
- specification/indices/simulate_template/IndicesSimulateTemplateRequest.ts
- specification/indices/simulate_template/IndicesSimulateTemplateResponse.ts
* removed three instances of `UserDefinedValue` in favour of once the correct [data_stream def](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-simulate-template.html#simulate-template-api-request-body) and twice for `IndexSettings`.
* moved shared type `IndexTemplate` into `indices._types`
> Fix indices.simulate_template

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/scroll/ScrollResponse.ts
- specification/_global/search/SearchResponse.ts
Backport 7.17 of #1476 
Remove nestsism of `documents` in `SearchResponse`
> Backport 1476 to 7.17

- specification/_doc_ids/table.csv
- specification/security/_types/Privileges.ts
- specification/security/create_api_key/SecurityCreateApiKeyRequest.ts
- specification/security/get_role/SecurityGetRoleRequest.ts
- specification/security/put_role/SecurityPutRoleRequest.ts
- specification/security/query_api_keys/QueryApiKeysRequest.ts
- specification/snapshot/_types/SnapshotShardsStatsStage.ts
- specification/sql/query/QuerySqlRequest.ts
- specification/watcher/_types/Action.ts
- specification/watcher/execute_watch/WatcherExecuteWatchRequest.ts
This PR updates a dead link in the table of documentation URLs. It also replaces a handful of @doc_url values with appropriate @doc_id values. In some cases where the @doc_url wasn't necessary, it's been removed.
> Replace or remove more doc URLs

- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
As titled.
Related: https://github.com/elastic/elasticsearch-specification/pull/1501
> Add doc_id support to all types

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/field_caps/FieldCapabilitiesRequest.ts
as titled. This properties are introduced in `main` -- do not backport.
> Fix field_caps API

- compiler/src/model/utils.ts
In 7.17 we are not tracking the doc_id values.
Fixes: https://github.com/elastic/elasticsearch-specification/issues/1513
> Fix doc_id handling in 7.17

- output/typescript/types.ts
- specification/_global/field_caps/FieldCapabilitiesRequest.ts
The `fields` property in `FieldCapabilitiesRequest` is required (see [API doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html#search-field-caps-api-query-params)).
Having it optional leads to all properties to be optional, causing the generation of a shortcut method in the Java client that always fails (reported in https://github.com/elastic/elasticsearch-java/issues/145).
> Fields in FieldCapabilities is required

- specification/_doc_ids/table.csv
- specification/_global/search/_types/suggester.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
- specification/ccr/put_auto_follow_pattern/PutAutoFollowPatternRequest.ts
- specification/cluster/put_component_template/ClusterPutComponentTemplateRequest.ts
- specification/cluster/stats/ClusterStatsResponse.ts
- specification/eql/_types/EqlSearchResponseBase.ts
- specification/eql/search/EqlSearchRequest.ts
- specification/fleet/msearch/MultiSearchRequest.ts
- specification/fleet/search/SearchRequest.ts
- specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
- specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/1523
> [8.0] Replace more hard-coded doc URLs with @doc_id #1523

- output/typescript/types.ts
- specification/_global/reindex/ReindexRequest.ts
The `source` and `dest` properties in `ReindexRequest` are required.
Having them optional leads to all properties to be optional, causing the generation of a shortcut method in the Java client that always fails (reported in https://github.com/elastic/elasticsearch-java/issues/145).
> Reindex source and dest fields are required

- specification/_doc_ids/table.csv
- specification/_global/rank_eval/types.ts
- specification/_types/Scripting.ts
- specification/_types/Time.ts
- specification/_types/aggregations/AggregationContainer.ts
- specification/_types/analysis/normalizers.ts
- specification/_types/common.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/TypeMapping.ts
- specification/_types/mapping/geo.ts
- specification/_types/query_dsl/abstractions.ts
- specification/_types/query_dsl/fulltext.ts
- specification/_types/query_dsl/specialized.ts
- specification/_types/sort.ts
- specification/cluster/_types/ComponentTemplate.ts
- specification/cluster/allocation_explain/types.ts
- specification/cluster/reroute/types.ts
- specification/cluster/stats/types.ts
- specification/eql/_types/EqlHits.ts
- specification/indices/_types/DataStream.ts
- specification/indices/_types/IndexSettings.ts
- specification/indices/_types/IndexTemplate.ts
- specification/nodes/_types/NodesResponseBase.ts
- specification/nodes/info/types.ts
- specification/security/_types/Privileges.ts
- specification/watcher/_types/Schedule.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/1530
> [8.1] Replace hard-coded doc URLs with @doc_id #1530

- specification/_doc_ids/table.csv
- specification/_global/rank_eval/types.ts
- specification/_types/Scripting.ts
- specification/_types/Time.ts
- specification/_types/aggregations/AggregationContainer.ts
- specification/_types/analysis/normalizers.ts
- specification/_types/common.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/TypeMapping.ts
- specification/_types/mapping/geo.ts
- specification/_types/query_dsl/abstractions.ts
- specification/_types/query_dsl/fulltext.ts
- specification/_types/query_dsl/specialized.ts
- specification/_types/sort.ts
- specification/cluster/_types/ComponentTemplate.ts
- specification/cluster/allocation_explain/types.ts
- specification/cluster/reroute/types.ts
- specification/cluster/stats/types.ts
- specification/eql/_types/EqlHits.ts
- specification/indices/_types/IndexSettings.ts
- specification/nodes/_types/NodesResponseBase.ts
- specification/nodes/info/types.ts
- specification/security/_types/Privileges.ts
- specification/watcher/_types/Schedule.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/1530
> [8.0] Replace hard-coded doc URLs with @doc_id (#1530)

- output/typescript/types.ts
- specification/ml/put_trained_model_vocabulary/MlPutTrainedModelVocabularyRequest.ts
With https://github.com/elastic/elasticsearch/pull/84777, the put trained model vocab can now accept an optional `merges` field that is a string array. This field is required for `roberta` tokenizers, but not for `mpnet` or `bert`.
> [ML] update put trained model vocab spec to allow merges

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/open_point_in_time/OpenPointInTimeRequest.ts
> Add missing `ignore_unavailable` query param for open PIT request

- compiler/src/model/build-model.ts
- compiler/src/model/metamodel.ts
- docs/add-new-api.md
- docs/specification-structure.md
- specification/_global/clear_scroll/ClearScrollResponse.ts
- specification/_global/close_point_in_time/ClosePointInTimeResponse.ts
- specification/_global/delete/DeleteResponse.ts
- specification/indices/get_alias/IndicesGetAliasResponse.ts
- typescript-generator/src/metamodel.ts
Continuation of #1536.
Fixes: https://github.com/elastic/elasticsearch-specification/issues/928
> Add failures to spec

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/indices/get/IndicesGetRequest.ts
closes https://github.com/elastic/elasticsearch-specification/issues/1382
> Add features property to indices.get

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
`jlh` appears to be an empty object for both the `significant_terms` and `significant_text` aggs.
> Add 'jlh' property to SignificantTerms aggs

- output/typescript/types.ts
- specification/_types/aggregations/AggregationContainer.ts
- specification/_types/aggregations/bucket.ts
Adds the `geohex_grid` aggregation which was added in 8.1.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohexgrid-aggregation.html
> Add the 'geohex_tile' aggregation

- compiler/src/model/utils.ts
Allows quoted strings in `@aliases` and other comma-separated jstags.
This is needed for `StorageType` where the empty string is an alias for the `fs` enum member (a follow-up PR will add it).
Asking for index defaults with `include_default=true` will return `""` for the storage type. When parsing this setting, Elasticsearch interprets the empty string as `fs`.
> Allow quoted strings in comma-separated jstags

- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
- specification/_types/analysis/analyzers.ts
- specification/_types/mapping/Property.ts
Adds an optional `default` configuration to internally tagged union definitions, e.g. `@variants internal tag='type' default='object'`
This is needed for:
* property mappings where `object` is the default (reported in [elasticsearch-java#45](https://github.com/elastic/elasticsearch-java/issues/45#issuecomment-978033425))
* analyzers where `custom` is the default (reported in [elasticsearch-java#216](https://github.com/elastic/elasticsearch-java/issues/216))
> Add default value for internal tags

- output/typescript/types.ts
- specification/_types/mapping/core.ts
- specification/_types/mapping/specialized.ts
The `GenericProperty` is not a true property type in ES, and was ported from NEST in error originally. This PR removes it from the spec.
> Remove generic property

- .github/workflows/update-rest-api-json.yml
Closes #1617 The 8.0 branch isn't available in the Elastic Artifacts API any more.
> Remove 8.0 branch from update-rest-api-json GHA

- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
Closes https://github.com/elastic/elasticsearch-specification/issues/1566
> Add 'ignore_malformed' to MappingLimitSettings

- compiler/src/model/metamodel.ts
- compiler/src/steps/add-content-type.ts
- typescript-generator/src/metamodel.ts
Renames `accept` to `responseMediaType` and `content_type` into `requestMediaType`.
> Rename media fields

- README.md
- docs/schema-structure.md
As titled.
The goal of the document is not to explain every component of the schema, but rather to explain the core concepts and provide a link to the living definition of the schema.
> Add schema structure docs

- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
- docs/modeling-guide.md
- specification/_global/search/_types/highlighting.ts
- specification/_global/search/_types/suggester.ts
- specification/_types/Scripting.ts
- specification/_types/aggregations/Aggregate.ts
- specification/_types/aggregations/AggregationContainer.ts
- specification/_types/analysis/analyzers.ts
- specification/_types/analysis/char_filters.ts
- specification/_types/analysis/token_filters.ts
- specification/_types/analysis/tokenizers.ts
- specification/_types/mapping/Property.ts
- specification/_types/query_dsl/abstractions.ts
- specification/ingest/_types/Processors.ts
Elasticsearch plugins can add new implementations for a significant number of components, such as for example queries, aggregations and property types.
This PR adds an additional `@non_exhaustive` annotation (term borrowed from [Rust's equivalent feature](https://doc.rust-lang.org/reference/attributes/type_system.html)) that can be added to `@variants` types and enums (see below) to capture the fact that variants or enum members not present in the spec can exist, and clients should allow that.
This PR also adds the new `@non_exhaustive` annotation to the relevant types, found from the [plugin interface definitions](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/plugins/) in the ES code base.
Example: 
```ts
/**
* @variants container
* …
```
> Add support for non exhaustive variants

- output/typescript/types.ts
- specification/_types/query_dsl/compound.ts
The `field` and `filter` parameters of function score queries are defined in the enclosing `FunctionScoreQuery` object, and not in the function definition itself. `ScoreFunctionQueryBase` is therefore unnecessary.
Also removes `WeightScoreFunction` that is still there but not referenced.
Verified in ES source code, `make validate api=search type=request` doesn't show new errors after this change.
> Remove unnecessary ScoreFunctionBase

- .gitignore
- output/typescript/types.ts
- specification/enrich/_types/Policy.ts
- specification/enrich/put_policy/PutEnrichPolicyRequest.ts
This PR adds support for range policies, [as specified in the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/put-enrich-policy-api.html).
It also adds `.*.swp`, nano lockfiles, to gitignore.
> Add range policy support to enrich

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleResponse.ts
- specification/snapshot/restore/SnapshotRestoreRequest.ts
The functionality remains the same, this were leftovers.
> Fix bad imports

- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
- docs/known-issues.md
- docs/modeling-guide.md
- output/typescript/types.ts
- specification/_types/common.ts
- specification/_types/mapping/dynamic-template.ts
- specification/_types/query_dsl/compound.ts
- specification/indices/_types/IndexSettings.ts
Adds a new `@es_quirk` jsdoc tag to capture weird snowflakes in the specification. This tag's value is a description of the quirk.
It is exported in `schema.json` as an `esQuirk?: string` property on type definition and properties. This allows code generators to track the quirks they have effectively implemented and fail if a new quirk appears in the schema that needs to be handled in the code generator.
> Add the "es_quirk" annotation to capture snowflakes in ES behavior

- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
- docs/modeling-guide.md
- output/typescript/types.ts
- specification/_types/common.ts
- specification/_types/mapping/dynamic-template.ts
- specification/_types/query_dsl/compound.ts
- specification/indices/_types/IndexSettings.ts
> [7.17] Add the "es_quirk" annotation to capture snowflakes in ES behavior (#1674)

- output/typescript/types.ts
- specification/ml/_types/inference.ts
adds new question_answering configuration elements to inference config and inference config updates
related: https://github.com/elastic/elasticsearch/pull/85958
> [ML] add question_answering config elements

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
- specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentRequest.ts
Renames start trained model deployment API parameters:
`model_threads` => `number_of_allocations`
`inference_threads` => `threads_per_allocation`
> [ML] Rename start deployment api threading params

- output/typescript/types.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/core.ts
Backport 80618757a29d8017316d4d40c21f77eee6c0d6e6 from #1710
> [Backport 7.17] Remove `Name` from `PropertyBase`

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/shutdown/_types/types.ts
- specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts
- specification/shutdown/put_node/ShutdownPutNodeRequest.ts
As titled.
Related: https://github.com/elastic/elasticsearch-js/issues/1695
> Add missing params to shutdown APIs

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ingest/put_pipeline/PutPipelineRequest.ts
This parameter makes safe concurrent updates to ingest pipelines possible. Added in https://github.com/elastic/elasticsearch/pull/78551
> Add 'if_version' parameter to 'ingest.put_pipeline' API

- .github/workflows/metamodel-sync.yml
Message within `echo` should be wrapped in quotes, otherwise will never pass this step.
See: https://github.com/elastic/elasticsearch-specification/runs/6675231493?check_suite_focus=true
```
Run if [ -n "$(git status --porcelain)" ]; then echo Error: compiler's metamodel and ts generator metamodel are not in sync; git diff; git status; exit 1; fi
if [ -n "$(git status --porcelain)" ]; then echo Error: compiler's metamodel and ts generator metamodel are not in sync; git diff; git status; exit 1; fi
shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/22d832cd-5cf4-4529-80be-b6de19ff6225.sh: line 1: unexpected EOF while looking for matching `''
Error: Process completed with exit code 2.
```
> Wrap error message in quotes

- .github/workflows/update-rest-api-json.yml
> Add 8.3 and remove 8.1 from rest-api-spec sync

- output/typescript/types.ts
- specification/security/_types/UserProfile.ts
- specification/security/update_user_profile_data/Request.ts
Now that we have test cases for UserProfile test cases we can fix these APIs. This model is defined [here](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/profile/Profile.java) in elastic/elasticsearch.
```
+ make validate api=security.activate_user_profile stack-version=8.4.0-SNAPSHOT
- Validating endpoints
✔ security.activate_user_profile request has been successfully validated!
✔ 4 out of 4 test request cases are passing.
✔ 4 out of 4 test response cases are passing.
+ make validate api=security.get_user_profile stack-version=8.4.0-SNAPSHOT
- Validating endpoints
✔ security.get_user_profile request has been successfully validated!
✔ 7 out of 7 test request cases are passing.
✔ 7 out of 7 test response …
```
> Fix property and field names for User Profile APIs

- .ci/Dockerfile
- .ci/bump.sh
- .ci/make.sh
- .github/workflows/validate-pr.yml
- Makefile
This commit adds a `bump` task to the Makefile, as well as the make.sh script and Dockerfile to automate the bump task.
I tried to keep it as simple as possible, not bringing in all the code (particularly in make.sh) from the clients.
> Adds make.sh, Dockerfile, bump task

- .gitignore
- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
- specification/_types/analysis/token_filters.ts
- specification/indices/_types/IndexSettings.ts
- specification/indices/get_field_mapping/types.ts
- specification/indices/recovery/types.ts
- specification/sql/translate/TranslateSqlResponse.ts
Fixes some spec issues found in the Java client:
* Missing fields in MultiTermsAggregation.  
Found in https://github.com/elastic/elasticsearch-java/issues/319
* TypeFieldMappings is a multi-key dictionary.  
Found in https://github.com/elastic/elasticsearch-java/issues/166
* Missing/wrong fields in ExplainSqlRequest.  
Found in https://github.com/elastic/elasticsearch-java/issues/167
* Misc fixes on token filters.  
Found in https://github.com/elastic/elasticsearch-java/issues/199
* Fix typo in IndexSettings.mapping and allow extended settings.  
Found in https://github.com/elastic/elasticsearch-java/issues/295
* ShardRecovery.stop_time_in_millis is optional.  
Found in https://github.com/elastic/elasticsearch-java/issues/202
> Misc java fixes 220617

- specification/_types/aggregations/bucket.ts
Follow-up to #1773: add a note about the very lazy parsing of `AggregateOrder`.
> Add note about AggregateOrder parsing lazyness

- specification/_types/aggregations/bucket.ts
> [7.17] Add note about AggregateOrder parsing lazyness (#1777)

- output/typescript/types.ts
- specification/_global/search/_types/suggester.ts
- specification/_types/analysis/char_filters.ts
Fixes issues found in the Java client:
* `MappingCharFilter.mapping` is optional. See https://github.com/elastic/elasticsearch-java/issues/318
* Suggester options are arrays (with their usual leniency rules). See https://github.com/elastic/elasticsearch-java/issues/214
> Fix suggestion options and mapping char filter

- output/typescript/types.ts
- specification/_types/aggregations/metric.ts
This adds a specification for the new Cardinality aggregation execution hint parameter, which is optional and accepts an enum value from a list.  This parameter will be available from 8.4 forward.  Generally speaking, we do not expect users to set this value, but we are providing it as a option for tuning performance in extreme cases.
> add new execution hint for cardinality

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/snapshot/_types/SnapshotInfo.ts
- specification/snapshot/get/SnapshotGetRequest.ts
- Adds the missing `index_names` parameter which is a part of the JSON spec
- Only remaining validation errors will be fixed by https://github.com/elastic/elasticsearch/issues/88620
> Fix snapshot.get validation errors

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_types/Knn.ts
- specification/_types/query_dsl/abstractions.ts
- specification/_types/query_dsl/term.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
Adds changes from these PRs:
- https://github.com/elastic/elasticsearch/pull/88002
- https://github.com/elastic/elasticsearch/pull/88217
Which add the `knn` property to the Search request body.
Questions for @jtibshirani:
- Is there a `knn` property for Async Search as well?
- Should we remove the `knn` query filter? I didn't see it documented on elastic.co and wasn't sure if it was supposed to be there.
Closes #1779
> Add 'knn' property to Search request body

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
- specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentRequest.ts
- specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentResponse.ts
While adding the `cache_size` parameter to `ml.start_trained_model_deployment` API for 8.4 I noticed a renaming of "allocation" to "assignment" had [happened during 8.3](https://github.com/elastic/elasticsearch/pull/85503) that we missed unfortunately. Made all the fixes for that renaming in this PR as well.
> Adds cache_size, fixes for TrainedModelDeployment models

- output/typescript/types.ts
- specification/ml/get_model_snapshot_upgrade_stats/MlGetModelSnapshotUpgradeStatsRequest.ts
This API endpoint only has one path `/_ml/anomaly_detectors/{job_id}/model_snapshots/{snapshot_id}/_upgrade/_stats` Which means that the `snapshot_id` parameter should be required.
> Fix snapshot_id to be required for ml.get_model_snapshot_upgrade_stats

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_types/Errors.ts
- specification/_types/aggregations/Aggregate.ts
- specification/_types/analysis/icu-plugin.ts
- specification/_types/mapping/RuntimeFields.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
- specification/cluster/_types/ComponentTemplate.ts
- specification/fleet/search/SearchRequest.ts
- specification/indices/_types/IndexSettings.ts
- specification/security/get_token/GetUserAccessTokenResponse.ts
This PR fixes a number of fields that should be optional and also adds `SearchRequest.ext` that is undocumented but is present in HLRC and used by some plugins to add new sections to search requests.
These are bug fixes that should be backported down to 7.17.
- `IndexVersioning.created` is optional (not present on default index settings)  
Found in https://github.com/elastic/elasticsearch-java/issues/286
- `GeoBoundsAggregate.bounds` should be optional.  
Found in https://github.com/elastic/elasticsearch-java/issues/383
- `RuntimeFields` is a dictionary of single values, not an array  
Found in https://github.com/elastic/elasticsearch-java/issues/298
- Search requests have an `ext` field for plugin extensions  
Found in https://github.com/elastic/elasticsearch-java/issues/264
- All fields …
> Fix optional/missing fields reported via Java client issues

- output/typescript/types.ts
- specification/_global/get_source/SourceRequest.ts
`get_source` request is missing the `RequestBase` superclass. It is needed as it accepts common requests parameters (and also IIRC all requests must inherit either `RequestBase` or `CatRequestBase`.
> Add missing superclass to get_source request

- output/typescript/types.ts
- specification/indices/analyze/types.ts
As reported in the Java Client repo, elastic/elasticsearch-java#391, `positionLength` is not being de-serialised by the Java API client, as the specification appears to mistakenly have `position_length` as the name of the property.
The change renames `position_length` to `positionLength` in the Specification, so the issue will be fixed in the Java API client when the client's entity classes are next generated.
> Rename position_length to positionLength

- output/typescript/types.ts
- specification/_types/analysis/icu-plugin.ts
The documents describe that `icu_transform` token filter doesn't require `dir` option.
7.17 Document
https://www.elastic.co/guide/en/elasticsearch/plugins/7.17/analysis-icu-transform.html
8.4 Document
https://www.elastic.co/guide/en/elasticsearch/plugins/8.4/analysis-icu-transform.html
Actually, Elasticsearch Server (7.17.x) accepts the following request successfully.
```
{"settings": {"index": {"analysis": {"filter": {"myLatinTransform": {"type": "icu_transform", "id": "Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC"}}}}}}
```
However, `elasticsearch-specification` defines the `dir` option is required.
Because of this, elasticsearch-java-client cannot send the request.
```
new co.elastic.clients.elasticsearch.indices.CreateIndexRequest.Builder().withJson(new …
```
> Fix IcuTransformTokenFilter definition

- output/typescript/types.ts
- specification/_types/analysis/icu-plugin.ts
Co-authored-by: Seth Michael Larson <seth.larson@elastic.co>
> Make 'dir' optional on IcuTransformTokenFilter

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/complex.ts
- specification/_types/mapping/core.ts
- specification/_types/mapping/specialized.ts
This PR adds the missing `IPProperty`, revamps the `NumberPropertyBase` to include missing possible properties and adds `time_series_metric` to `AggregateMetricDoubleProperty`.
Relates to #1881
> Add IPProperty and missing properties in mappings

- output/typescript/types.ts
- specification/_types/mapping/meta-fields.ts
This allows to set the `_source` storage to `synthetic`. ([doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#synthetic-source))
Relates to https://github.com/elastic/elasticsearch-specification/issues/1881
> Add Mode to Mappings for _source

- output/typescript/types.ts
- specification/indices/_types/Downsample.ts
Now that `indices.downsample` will become a non-feature flag API in 8.5 we should start modeling the config object. Right now there is only one option, `fixed_interval`.
> Add model for DownsampleConfig

- output/typescript/types.ts
- specification/_global/search/_types/suggester.ts
Backport https://github.com/elastic/elasticsearch-specification/commit/d14be06b80b9211f367362b2382d542961b6c23f from https://github.com/elastic/elasticsearch-specification/pull/1906
> Add collate_match and highlighted to SuggestionOptions

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/core.ts
This removes some property overrides that were introduced by the refactoring in #1920
Note to self: this should be caught by the model validation rules.
> Remove overriden properties

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/mapping/core.ts
- specification/indices/_types/IndexSettings.ts
- specification/indices/forcemerge/IndicesForceMergeResponse.ts
- specification/indices/forcemerge/_types/response.ts
- specification/indices/rollover/types.ts
> Fix issues in indices API - java-client+recordings

- output/typescript/types.ts
- specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts
When using the delete by query API asynchronously, it returns a `TaskId` for the ongoing task. The DeleteByQueryRethrottleRequest accepts a `task_id` as a required path parameter, but it's currently typed as `Id`. For the .NET client, at least, it presents some usability hurdles as you can't just pass the value of the `Task` property from the `DeleteByQueryResponse` into subsequent API calls. Ideally, I believe we should align the typing here with the usage scenario.
My only concern is this being a breaking change for other clients that probably function today using the parameter typed as `Id`.
> Use TaskId for DeleteByQueryRethrottleRequest path parameter

- output/typescript/types.ts
- specification/enrich/_types/Policy.ts
- specification/ingest/simulate/types.ts
- specification/license/post/PostLicenseRequest.ts
- specification/ml/_types/Job.ts
- specification/ssl/certificates/types.ts
- specification/transform/_types/Transform.ts
- specification/xpack/usage/types.ts
> Fix misc issues found with java-client+recordings

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/clear_trained_model_deployment_cache/MlClearTrainedModelDeploymentCacheRequest.ts
- specification/ml/clear_trained_model_deployment_cache/MlClearTrainedModelDeploymentCacheResponse.ts
Relates to https://github.com/elastic/elasticsearch/pull/89074
This PR adds definitions for https://www.elastic.co/guide/en/elasticsearch/reference/master/clear-trained-model-deployment-cache.html (https://github.com/elastic/elasticsearch-specification/blob/main/specification/_json_spec/ml.clear_trained_model_deployment_cache.json)
> Add ml.clear_trained_model_deployment_cache

- output/typescript/types.ts
- specification/_global/field_caps/FieldCapabilitiesRequest.ts
- specification/_global/search/_types/highlighting.ts
- specification/_global/search/_types/hits.ts
- specification/_global/search/_types/profile.ts
- specification/_types/Errors.ts
- specification/_types/Node.ts
- specification/_types/SlicedScroll.ts
- specification/_types/aggregations/Aggregate.ts
- specification/_types/sort.ts
Part of https://github.com/elastic/elasticsearch-specification/issues/1878
> Start of fixes for core/search

- output/typescript/types.ts
- specification/_global/field_caps/FieldCapabilitiesRequest.ts
- specification/_global/search/_types/highlighting.ts
- specification/_global/search/_types/hits.ts
- specification/_global/search/_types/profile.ts
- specification/_types/Node.ts
- specification/_types/SlicedScroll.ts
- specification/_types/aggregations/Aggregate.ts
- specification/_types/sort.ts
> [7.17] Start of fixes for core/search (#1947)

- output/typescript/types.ts
- specification/security/_types/FieldSecurity.ts
- specification/security/_types/Privileges.ts
- specification/security/get_user_privileges/SecurityGetUserPrivilegesResponse.ts
Follow-up to PR #1963
`IndicesPrivileges` can contain multiple queries _only_ in the context of `GetUserPrivilegeResponses`, and not in the context of `RoleDescriptor`. We therefore have to introduce a new `UserIndicesPrivileges` type that has multiple queries.
Additionally, this PR adds missing  `@codegen_names` on `RoleTemplateInlineScript.source`, requiring to move it to a separate type to hold this annotation.
Finally, `FieldSecurity.grant` is actually optional.
> Fix user privileges

- output/typescript/types.ts
- specification/ingest/_types/Processors.ts
Fixes the optionality of ingest processor fields (most of them are optional) and add a few missing ones.
Checked with [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/processors.html).
> Fix optional Processor fields and add missing fields

- output/typescript/types.ts
- specification/_types/Geo.ts
- specification/_types/aggregations/Aggregate.ts
Found in https://github.com/elastic/elasticsearch-java/issues/397
Adds the `geohex_grid` aggregate. The aggregation (request part) already exists in the spec.
> Add missing geohex_grid aggregate

- compiler/src/steps/validate-rest-spec.ts
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/rank_eval/RankEvalRequest.ts
- specification/fleet/msearch/MultiSearchRequest.ts
- specification/ml/clear_trained_model_deployment_cache/MlClearTrainedModelDeploymentCacheRequest.ts
Path parameters aren't checked whether they're required or optional compared to the paths provided in the JSON specs. Found this through the newly added API `ml.clear_model_deployment_cache` which mistakenly was added with an optional path parameter `model_id` but the parameter should be marked as required in the spec.
> Enforce path parameter required/optional with JSON specs

- output/typescript/types.ts
- specification/_types/mapping/Property.ts
`local-metadata` is a NEST client concept and not part of the server model. NEST added it to support consumers who wanted to tag properties with extra data. It is not serialized on requests and I can find no reference for it in Elasticsearch. This PR removes it and I propose we backport it to all versions.
> Remove local-metadata from PropertyBase

- output/typescript/types.ts
- specification/_types/mapping/Property.ts
Backport 0f1a36891730a8a3c68bf88947d590107637fdd8 from #1979
> [Backport 7.17] Remove local-metadata from PropertyBase

- output/typescript/types.ts
- specification/ml/_types/Anomaly.ts
Relates to https://github.com/elastic/elasticsearch/pull/47050
It uses descriptions from https://github.com/elastic/elasticsearch/pull/91237
> Add geo_results.actual_point and typical_point

- compiler/src/dump/extract-routes.ts
Follow up to https://github.com/elastic/elasticsearch-specification/pull/1992
This changes:
* Uses string for version in serialization.
* Unexports the field of the Go structures in serialization.
* Add the generated code disclaimer.
> Improve route serialization

- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
The `StorageType` enumeration is non exhaustive: some plugins may add additional storage types, and snapshot/frozen repositories, although they cannot be created directly, are identified with a storage type `snapshot`.
Reported in https://github.com/elastic/elasticsearch-java/issues/458
> Change StorageType to an open enumeration

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Adds a missing property for `MultiTermLookup` to support providing a missing value per [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.5/search-aggregations-bucket-multi-terms-aggregation.html#_missing_value_3).
Raised in https://github.com/elastic/elasticsearch-net/issues/7119
> Add missing property for MultiTerms aggregation

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Backport 9cc32aeefffbcf62c5d7b1e94110c759caac5bb8 from #2000
> [Backport 7.17] Add missing property for MultiTerms aggregation

- .github/download-artifacts/index.js
- .github/workflows/update-rest-api-json.yml
Currently if a JSON spec is deleted upstream (like was done to `semantic_search.json` for 8.6) then the `download-artifacts.js` script doesn't detect and delete the file. This amends that missing behavior.
> Remove non-existent JSON specs when updating from artifacts API

- specification/ml/_types/Anomaly.ts
This PR adds descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-get-record.html to the Anomaly.ts file.
> Anomaly explanation

- specification/sql/query/QuerySqlRequest.ts
The `columnar` parameter is missing docstring. I've just copied it from the documentation [page](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest-columnar.html) and pasted it there.
> Add SQL Request `columnar` Docstring

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/knn_search/KnnSearchRequest.ts
- specification/_global/knn_search/_types/Knn.ts
- specification/_types/Knn.ts
This adds the `query_vector_builder` field to the KnnQuery for semantic search.
https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#semantic-search
> [KNN] Add query vector builder

- compiler/src/steps/validate-rest-spec.ts
- output/schema/validation-errors.json
Noticed that tons of APIs had an identical `Request: should not have a body` validation warning which made no sense, I believe this problem was introduced when we switched from `null` meaning "No Body" to an actual definition of `NoBody` but didn't go back and check.
> Remove erroneous request body validation warnings

- output/typescript/types.ts
- specification/_types/mapping/TypeMapping.ts
Creating an index with a mapping that includes `dynamic_templates` fails when sending the dictionary without wrapping it in an array: 
e.g.
```
PUT my-index
{
"mappings": {
"dynamic_templates": {
"testTemplateName": {
"mapping": {
"type": "keyword"
},
"path_match": "testPathMatch"
}
}
}
}
```
Error:
```
{
"error": {
"root_cause": [
{
"type": "mapper_parsing_exception",
"reason": "Dynamic template syntax error. An array of named objects is expected."
}
],
"type": "mapper_parsing_exception",
"reason": "Failed to parse mapping: Dynamic template syntax error. An array of named objects is expected.",
"caused_by": {
"type": "mapper_parsing_exception",
"reason": "Dynamic template syntax error. An array of named objects is expected."
}
},
"status": 400
}
```
I've made a check to the spec but …
> Remove union for dynamic_templates

- output/typescript/types.ts
- specification/_types/mapping/TypeMapping.ts
Backport d5e725afc0420d706e05319620a3e8b21e08cbbd from #2033
> [Backport 7.17] Remove union for dynamic_templates

- .github/workflows/gh-pages-report.yml
- .github/workflows/output-check.yml
- .gitignore
- Makefile
- compiler/src/compiler.ts
- compiler/src/index.ts
- compiler/src/model/build-model.ts
- compiler/test/body-codegen-name/test.ts
- compiler/test/duplicate-body-codegen-name/test.ts
- compiler/test/no-body/test.ts
- compiler/test/request-fields/test.ts
- compiler/test/response-exceptions-fields/test.ts
- compiler/test/response-fields/test.ts
- compiler/test/types/test.ts
- compiler/test/writes-to-output/specification/_global/index/request.ts
- compiler/test/writes-to-output/specification/tsconfig.json
- compiler/test/writes-to-output/test.ts
- compiler/test/wrong-namespace/test.ts
Currently the compiler is hardcoded for paths in this repository, we'd like to be able to compile specs that are elsewhere so I've added `--spec` and `--output` parameters to the compiler CLI.
Tested by running within a Dockerfile of the `compiler` directory. There are still some external dependencies like the rest-api-spec stubs, `nvmrc` file, and `tsconfig.json`.
> Add parameters to compiler for specifying input and output

- output/typescript/types.ts
- specification/_types/Stats.ts
As titled.
Relates to [this issue](https://github.com/elastic/elasticsearch-net/issues/7445) on the .NET client repo.
> Replace integers with longs on indices stats types

- output/typescript/types.ts
- specification/_global/search/_types/suggester.ts
Fixes issues raised in https://github.com/elastic/elasticsearch-net/issues/7454.
The completion suggester doesn't support a field named "prefix" which is a FieldSuggester container property.
After reviewing the server code, I noticed that `regex` is not a string but an instance of `RegexOptions` used to control the regex provided via the container property.
> Fix completion suggester

- compiler/run-validations.js
Follow up from https://github.com/elastic/elasticsearch-specification/pull/2032 that was missed due to not finding the compiler invocation.
> Add explicit paths to run-validations.js script

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/transform/start_transform/StartTransformRequest.ts
This PR adds the `from` parameter for `transform.start_transform` API. Fixes #2064
> Add from parameter for transform.start_transform

- output/typescript/types.ts
- specification/security/_types/Privileges.ts
This field doesn't accept an array of `FieldSecurity` instances, only a single instance. This causes an issue in strongly-typed languages that collapse `X | X[]` type into `X[]` because users can't set a single object on a request.
> Fix IndexPrivileges.field_security

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
In 8.6 the `knn` search field only accepted a single value. In 8.7 it has been updated to allow a single value and an array of values.
> Add support for multiple knn queries

- specification/_json_spec/search_application.delete.json
- specification/_json_spec/search_application.delete_behavioral_analytics.json
- specification/_json_spec/search_application.get.json
- specification/_json_spec/search_application.get_behavioral_analytics.json
- specification/_json_spec/search_application.list.json
- specification/_json_spec/search_application.put.json
- specification/_json_spec/search_application.put_behavioral_analytics.json
- specification/_json_spec/search_application.search.json
- specification/search_application/delete/SearchApplicationsDeleteRequest.ts
- specification/search_application/get/SearchApplicationsGetRequest.ts
- specification/search_application/list/SearchApplicationsListRequest.ts
- specification/search_application/put/SearchApplicationsPutRequest.ts
- specification/search_application/search/SearchApplicationsSearchRequest.ts
Follow up to https://github.com/elastic/elasticsearch-specification/pull/2082, merged the change in APIs stability done in Elasticsearch (https://github.com/elastic/elasticsearch/pull/95379) here and updated stability.
> Changed Search Applications stability from beta to experimental

- output/typescript/types.ts
- specification/cluster/health/ClusterHealthResponse.ts
`cluster_health` could return a valid payload with a `408` status code if one of the nodes from the cluster failed to respond before the timeout.
> Add 408 as exception status code for normal behaviour on cluster_health

- output/typescript/types.ts
- specification/ml/_types/Include.ts
- specification/ml/_types/TrainedModel.ts
Updates TrainedModelConfig for the new fully_defined field add in https://github.com/elastic/elasticsearch/pull/95271
Duplicate of #2081. Testing if opening against the repo instead of a fork fixes the CI failures
> ML Add trained model definition status to TrainedModelConfig

- output/typescript/types.ts
- specification/security/_types/Privileges.ts
Our current set of index privileges is an enum, but misses out on many of the fine-grained privileges like `indices:admin/aliases`. We have application privileges as a `string`, so this PR converts the enum into a non-exhaustive enum in order to accept arbitrary values like a `string`.
> Convert IndexPrivilege and ClusterPrivilege to non-exhaustive enums

- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
- specification/ml/_types/inference.ts
Updates the ML NLP APIs for new features added in 8.8. Namely the `text_expansion` config  and adding the new `deployment_id` field to stats results.
> Add text expansion config for the NLP APIs

- output/typescript/types.ts
- specification/snapshot/_types/SnapshotShardFailure.ts
If a shard isn't allocated, the `node_id` will be omitted in the shard failure object.
> Make node_id optional on SnapshotShardFailure

- .github/workflows/validate-pr.yml
- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
Raised in https://github.com/elastic/elasticsearch-net/issues/7714, it appears that the possible block values should all be stringified as they are each produced as an `APIBlock` ([see server code](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java#L264)).
This PR updates each possible block option to support the stringified value when getting index settings.
> Make index settings blocks stringified

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_json_spec/indices.explain_data_lifecycle.json
- specification/cluster/_types/ComponentTemplate.ts
- specification/cluster/get_component_template/ClusterGetComponentTemplateRequest.ts
- specification/indices/_types/DataLifecycle.ts
- specification/indices/_types/DataStream.ts
- specification/indices/_types/IndexState.ts
- specification/indices/_types/IndexTemplate.ts
- specification/indices/delete_data_lifecycle/IndicesDeleteDataLifecycleRequest.ts
- specification/indices/delete_data_lifecycle/IndicesDeleteDataLifecycleResponse.ts
- specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleRequest.ts
- specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleResponse.ts
- specification/indices/get_data_lifecycle/IndicesGetDataLifecycleRequest.ts
- specification/indices/get_data_lifecycle/IndicesGetDataLifecycleResponse.ts
- specification/indices/get_data_stream/IndicesGetDataStreamRequest.ts
- specification/indices/get_index_template/IndicesGetIndexTemplateRequest.ts
- specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
- specification/indices/put_data_lifecycle/IndicesPutDataLifecycleResponse.ts
- specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
- specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts
- specification/indices/simulate_template/IndicesSimulateTemplateRequest.ts
In this PR we update existing endpoints and we implement new ones to match the changes that the Data Lifecycle Management project is introducing (see https://github.com/elastic/elasticsearch/issues/93596).
We added the query param include_defaults where appropriate and introduced the lifecycle or lifecycle with rollover when necessary. This change affected the following:
Data streams
Component templates
Index templates (composable)
Template simulation
Furthermore, we implement the following endpoints:
CRUD data lifecycle for a specific data stream
Explain data lifecycle for a backing index of a data stream
I believe there are no backwards compatibility concerns because everything was added at the end. But please, correct me if I am wrong.
> Update rest endpoint specs to facilitate Data Lifecycle Management

- output/typescript/types.ts
- specification/_types/query_dsl/TextExpansionQuery.ts
- specification/_types/query_dsl/abstractions.ts
Documents the new `text_expansion` query created in https://github.com/elastic/elasticsearch/pull/93694
The query is first available in Elasticsearch version 8.8
> Add the text_expansion query

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/search_application/_types/AnalyticsEvent.ts
- specification/search_application/_types/BehavioralAnalytics.ts
- specification/search_application/delete_behavioral_analytics/BehavioralAnalyticsDeleteRequest.ts
- specification/search_application/delete_behavioral_analytics/BehavioralAnalyticsDeleteResponse.ts
- specification/search_application/get_behavioral_analytics/BehavioralAnalyticsGetRequest.ts
- specification/search_application/get_behavioral_analytics/BehavioralAnalyticsGetResponse.ts
- specification/search_application/put_behavioral_analytics/BehavioralAnalyticsPutRequest.ts
- specification/search_application/put_behavioral_analytics/BehavioralAnalyticsPutResponse.ts
Add Behavioral Analytics APIs.
POST is missing - I understood from @afoucret and @joemcelroy that this API should not yet be available for clients. It can be contributed as a separate PR however.
> Added Behavioral Analytics APIs

- specification/_types/Stats.ts
- specification/async_search/_types/AsyncSearch.ts
- specification/async_search/_types/AsyncSearchResponseBase.ts
- specification/async_search/delete/AsyncSearchDeleteRequest.ts
- specification/async_search/get/AsyncSearchGetRequest.ts
- specification/async_search/status/AsyncSearchStatusRequest.ts
- specification/async_search/status/AsyncSearchStatusResponse.ts
- specification/async_search/submit/AsyncSearchSubmitRequest.ts
This PR augments the specification with descriptions and defaults from https://www.elastic.co/guide/en/elasticsearch/reference/master/async-search.html
> Add descriptions for async search

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_types/Rank.ts
This PR adds the `rank` parameter for [Reciprocal Rank Fusion](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/rrf.html) (RRF) to the search API. This parameter has been introduced in 8.8.0.
> Added RRF rank parameter to search

- docs/modeling-guide.md
Relates to https://github.com/elastic/elasticsearch-specification/issues/2107
I received an error in https://github.com/elastic/elasticsearch-specification/pull/2139 until I realized that `@stability` is now a property of `@availability`, so I've updated the readme.
> [DOCS] Update modeling-guide.md

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_doc_ids/table.csv
- specification/_types/common.ts
- specification/cluster/info/ClusterInfoRequest.ts
- specification/cluster/info/ClusterInfoResponse.ts
Closes elastic/elasticsearch#96477
> Add types for new cluster info api (`_info/<target>`)

- output/typescript/types.ts
- specification/_types/mapping/TimeSeriesMetricType.ts
https://github.com/elastic/elasticsearch/pull/93946 added `position` time series metric. This PR updates `TimeSeriesMetricType` to include `position`.
> add posotion to TimeSeriesMetricType

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/cat/ml_data_frame_analytics/types.ts
- specification/cat/ml_datafeeds/types.ts
- specification/cat/ml_jobs/types.ts
- specification/cat/ml_trained_models/CatTrainedModelsRequest.ts
- specification/cat/ml_trained_models/types.ts
- specification/cat/nodes/types.ts
- specification/cat/segments/CatSegmentsRequest.ts
- specification/cat/segments/types.ts
- specification/cat/shards/CatShardsRequest.ts
- specification/cat/shards/types.ts
- specification/cat/snapshots/CatSnapshotsRequest.ts
- specification/cat/snapshots/types.ts
- specification/cat/tasks/CatTasksRequest.ts
- specification/cat/tasks/types.ts
- specification/cat/templates/CatTemplatesRequest.ts
- specification/cat/templates/types.ts
- specification/cat/thread_pool/CatThreadPoolRequest.ts
- specification/cat/thread_pool/types.ts
- specification/cat/transforms/CatTransformsRequest.ts
- specification/cat/transforms/types.ts
- specification/ml/_types/Job.ts
This PR pulls descriptions from these docs:
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-segments.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-shards.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-snapshots.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-tasks.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-templates.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-thread-pool.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-trained-model.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-transforms.html
NOTE: I changed `parent_task?: long` to `parent_task_id?: string` in cat tasks due …
> Add descriptions for final cat APIs

- specification/cluster/pending_tasks/ClusterPendingTasksRequest.ts
- specification/cluster/pending_tasks/types.ts
Adds descriptions derived from https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-pending.html
> Add descriptions to pending cluster tasks API

- output/typescript/types.ts
- specification/_global/health_report/types.ts
Adds new [`shards_capacity`](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/health-api.html#health-api-response-details-shards-capacity) to the health API.
My first time making a spec change so let me know if I missed anything important here. :pray:
Done per @rudolf's needs mentioned in https://github.com/elastic/kibana/pull/159587#discussion_r1230997505.
> Add shards_capacity to health_report

- specification/security/authenticate/SecurityAuthenticateRequest.ts
Adds descriptions derived from https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-authenticate.html
It's a trivial one, so it's a good one to do first :)
> Add description to Authenticate API

- specification/_global/get/GetResponse.ts
This adds an exception to the `core.get` response to handle `index_not_found_exception` and document not found.
> Add exception to core.get to handle index_not_found & document not found

- output/typescript/types.ts
- specification/indices/_types/DataLifecycle.ts
- specification/indices/_types/DataStream.ts
- specification/indices/create_data_stream/IndicesCreateDataStreamRequest.ts
- specification/indices/delete_data_stream/IndicesDeleteDataStreamRequest.ts
- specification/indices/get_data_stream/IndicesGetDataStreamRequest.ts
This PR adds descriptions from:
- https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-get-data-stream.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-delete-data-stream.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-create-data-stream.html
NOTE: In addition to adding descriptions in `specification/indices/_types/DataStream.ts`, I've sorted the properties alphabetically so they show up nicely in our output.
> Add data stream descriptions

- output/typescript/types.ts
- specification/ml/put_trained_model/MlPutTrainedModelRequest.ts
Built in models like ELSER do not require an inference_config be
specified. #2098 adjusted the spec to reflect this in one place,
but not in the put trained model API spec. This PR completes the
change.
> Fix put trained model spec

- compiler/src/model/utils.ts
- specification/security/_types/ApiKey.ts
- specification/security/_types/GrantType.ts
- specification/security/_types/RoleDescriptor.ts
- specification/security/clear_api_key_cache/SecurityClearApiKeyCacheRequest.ts
- specification/security/create_api_key/SecurityCreateApiKeyRequest.ts
- specification/security/get_api_key/SecurityGetApiKeyRequest.ts
- specification/security/grant_api_key/SecurityGrantApiKeyRequest.ts
- specification/security/grant_api_key/types.ts
- specification/security/invalidate_api_key/SecurityInvalidateApiKeyRequest.ts
- specification/security/query_api_keys/QueryApiKeysRequest.ts
- specification/security/query_api_keys/QueryApiKeysResponse.ts
- specification/security/update_api_key/Request.ts
- specification/security/update_api_key/Response.ts
Adds descriptions for these API key APIs:
- Create API key
- Grant API key
- Update API key
- Get API key information
- Invalidate API key
- Query API key information
- Clear API key cache
Source for the descriptions: https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api.html#security-api-keys
I also had to add the `read_security` cluster privilege. It was missing from `utils.ts`, but it is mentioned in several docs. I don't know if that was the right thing to do?
> Add descriptions for API key API

- output/typescript/types.ts
- specification/_types/query_dsl/geo.ts
geo_distance.distance parameter is required. If not provided, elasticsearch _search API returns a 400
Example of working query
```
GET kibana_sample_data_logs/_search
{
"size": 10,
"query": {
"bool": {
"must": [],
"filter": [
{
"bool": {
"must": [
{
"exists": {
"field": "geo.coordinates"
}
},
{
"geo_distance": {
"distance": "100km",
"geo.coordinates": [
-107.31,
40.66
]
}
}
]
}
}
],
"should": [],
"must_not": []
}
}
}
```
Example of 400 query with `distance` not provided
```
GET kibana_sample_data_logs/_search
{
"size": 10,
"query": {
"bool": {
"must": [],
"filter": [
{
"bool": {
"must": [
{
"exists": {
"field": "geo.coordinates"
}
},
{
"geo_distance": {
"geo.coordinates": [
-107.31,
40.66
]
}
}
]
}
}
],
"should": [],
"must_not": []
}
}
}
```
Error response
```
{
"error": {
"root_cause": [ …
```
> mark GeoDistanceQuery distance property as required

- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/FieldCollapse.ts
- specification/_global/search/_types/highlighting.ts
- specification/_global/search/_types/rescoring.ts
- specification/_types/mapping/RuntimeFields.ts
Adds descriptions for the Search API. Source for the descriptions: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-search.html (and pages linked from it)
**Does not include aggs and suggesters.**
> Add descriptions for Search API

- specification/indices/get_settings/IndicesGetSettingsRequest.ts
- specification/indices/put_settings/IndicesPutSettingsRequest.ts
Adds descriptions for the following APIs:
- Get index settings API
- Put index settings API
This PR **doesn't** update index setting descriptions. I have an [open request regarding setting type annotations](https://github.com/elastic/elasticsearch-specification/issues/2172) I'd like to resolve first.
Source for the descriptions:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-settings.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html
> Add descriptions for index settings APIs

- output/typescript/types.ts
- specification/ml/_types/inference.ts
Adds the specification for the new mask token field added in https://github.com/elastic/elasticsearch/pull/97453.
> [NLP] Support the different mask tokens used by NLP models for Fill Mask

- output/typescript/types.ts
- specification/indices/data_streams_stats/IndicesDataStreamsStatsRequest.ts
- specification/indices/data_streams_stats/IndicesDataStreamsStatsResponse.ts
- specification/indices/migrate_to_data_stream/IndicesMigrateToDataStreamRequest.ts
- specification/indices/modify_data_stream/IndicesModifyDataStreamRequest.ts
- specification/indices/modify_data_stream/types.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/964
This PR adds descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/master/data-stream-stats-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-migrate-to-data-stream.html, and https://www.elastic.co/guide/en/elasticsearch/reference/master/modify-data-streams-api.html
> Add descriptions for migrate, modify, and data stream stats

- compiler/package.json
- compiler/src/transform/filter-by-availability.ts
This PR adds a subscript to the transform list to filter the specification and types based on the `@availability` tags.
The script defaults to the standard `schema.json` and output a `schema-filtered.json` in the same directory based on the provided flags. (e.g. `--stack` or `--serverless`)
Input and output path the different source and target can be provided.
> [Transform] Filter availability

- .github/workflows/generate.yml
Makes sure to only commit files in the `./output` directory.
> Minor generation workflow bugfix

- specification/_doc_ids/table.csv
- specification/_types/Geo.ts
- specification/_types/common.ts
- specification/_types/query_dsl/abstractions.ts
- specification/_types/query_dsl/compound.ts
- specification/_types/query_dsl/geo.ts
- specification/_types/query_dsl/specialized.ts
- specification/_types/query_dsl/term.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/964
Adds Query DSL descriptions for queries A through G. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html and subpages.
> [DOCS] Add descriptions for queries A-G

- specification/ml/infer_trained_model/MlInferTrainedModelRequest.ts
- specification/ml/post_data/MlPostJobDataRequest.ts
Two ML APIs had the wrong serverless visibility:
1. Post data should not be visible at all in serverless
2. Infer trained model should be visible publicly
(With the infer endpoint there was confusion about the deprecated infer trained model _deployment_ API, which we want to pretend does not exist.)
> Correcting visibility of ML APIs in serverless

- specification/_json_spec/search_application.delete.json
- specification/_json_spec/search_application.get.json
- specification/_json_spec/search_application.list.json
- specification/_json_spec/search_application.put.json
- specification/_json_spec/search_application.render_query.json
- specification/_json_spec/search_application.search.json
- specification/search_application/delete/SearchApplicationsDeleteRequest.ts
- specification/search_application/get/SearchApplicationsGetRequest.ts
- specification/search_application/list/SearchApplicationsListRequest.ts
- specification/search_application/put/SearchApplicationsPutRequest.ts
- specification/search_application/search/SearchApplicationsSearchRequest.ts
Updates search applications APIs to beta.
> Update search application APIs from experimental to beta

- specification/_types/query_dsl/TextExpansionQuery.ts
- specification/_types/query_dsl/abstractions.ts
Changed the definition of `text_expansion` according to the documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-text-expansion-query.html
> Fix query `text_expansion` definition

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_json_spec/synonym_rule.delete.json
- specification/_json_spec/synonym_rule.get.json
- specification/_json_spec/synonym_rule.put.json
- specification/_json_spec/synonyms.delete.json
- specification/_json_spec/synonyms.get.json
- specification/_json_spec/synonyms.put.json
- specification/_json_spec/synonyms_sets.get.json
- specification/synonym_rule/delete/SynonymRuleDeleteRequest.ts
- specification/synonym_rule/delete/SynonymRuleDeleteResponse.ts
- specification/synonym_rule/get/SynonymRuleGetRequest.ts
- specification/synonym_rule/get/SynonymRuleGetResponse.ts
- specification/synonym_rule/put/SynonymRulePutRequest.ts
- specification/synonym_rule/put/SynonymRulePutResponse.ts
- specification/synonyms/_types/SynonymRule.ts
- specification/synonyms/_types/SynonymsSet.ts
- specification/synonyms/_types/SynonymsUpdateResult.ts
- specification/synonyms/delete/SynonymsDeleteRequest.ts
- specification/synonyms/delete/SynonymsDeleteResponse.ts
- specification/synonyms/get/SynonymsGetRequest.ts
- specification/synonyms/get/SynonymsGetResponse.ts
- specification/synonyms/put/SynonymsPutRequest.ts
- specification/synonyms/put/SynonymsPutResponse.ts
- specification/synonyms_sets/get/SynonymsSetsGetRequest.ts
- specification/synonyms_sets/get/SynonymsSetsGetResponse.ts
Adds Synonyms API spec and types
> Add Synonyms API spec

- specification/enrich/delete_policy/DeleteEnrichPolicyRequest.ts
- specification/enrich/execute_policy/ExecuteEnrichPolicyRequest.ts
- specification/enrich/get_policy/GetEnrichPolicyRequest.ts
- specification/enrich/put_policy/PutEnrichPolicyRequest.ts
- specification/enrich/stats/EnrichStatsRequest.ts
- specification/enrich/stats/EnrichStatsResponse.ts
Adds descriptions to Enrich API properties. Source of info: https://www.elastic.co/guide/en/elasticsearch/reference/master/enrich-apis.html
> [DOCS] Adds descriptions for Enrich APIs

- specification/indices/_types/IndexSettings.ts
Based on the documentation, these settings should be separate ones:
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-slowlog.html
Related to: https://github.com/elastic/elasticsearch-net/issues/7865
> Separate `IndexingSlowlogSettings` from regular search `SlowlogSettings`

- specification/_doc_ids/table.csv
- specification/graph/_types/ExploreControls.ts
- specification/graph/_types/Hop.ts
- specification/graph/_types/Vertex.ts
- specification/graph/explore/GraphExploreRequest.ts
Adds descriptions to Graph Explore API properties. Source of info: 
https://www.elastic.co/guide/en/elasticsearch/reference/master/graph-explore-api.html#graph-explore-api
> [DOCS] Adds descriptions for the Graph API

- specification/_doc_ids/table.csv
CI found a broken doc link on my latest [build of the JS client](https://github.com/elastic/elasticsearch-js/pull/1946). Looks like a slash was missed in https://github.com/elastic/elasticsearch-specification/pull/2226.
> Fix broken doc url for indices-close

- specification/_spec_utils/FlagsEnum.ts
- specification/_spec_utils/PipeSeparatedFlags.ts
- specification/_types/query_dsl/fulltext.ts
This PR introduces the `FlagsEnum<T>` marker class similar to the `Stringified<T>` concept.
Flags enums are defined as enums with a special case serialization. Values of this enum are represented as `string` (like for regular enums as well). In addition, individual enum member values can be combined using the pipe separator char (`|`) like e.g. described here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#supported-flags
At the moment, this specific construct is defined in 2 parts:
1. The enum itself (`TEnum`) as a regular enum type
2. A type alias defined as `FlagsEnum = TEnum | string`
Using just a generic union makes it hard to generate correct (de-)serialization code and "hard" for the users to use properties of this type, as …
> Introduce `PipeSeparatedFlags<T>` marker class

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Updates the descriptions of `field` for `geohash_grid`, `geohex_grid`, and `geotile_grid`, so they all mention support for `geo_shape` and array values.
> [DOCS] Update field descriptions for geogrid aggs

- output/typescript/types.ts
- specification/ingest/_types/Processors.ts
This PR fixes a typo that was introduced by [this PR](https://github.com/elastic/elasticsearch-specification/pull/2236).
> [DOCS] Fixes a typo in the processor descriptions

- .github/validate-pr/index.js
- specification/_types/query_dsl/fulltext.ts
- specification/query_ruleset/delete/QueryRulesetDeleteRequest.ts
- specification/query_ruleset/get/QueryRulesetGetRequest.ts
- specification/query_ruleset/list/QueryRulesetListRequest.ts
- specification/query_ruleset/put/QueryRulesetPutRequest.ts
- specification/search_application/delete/SearchApplicationsDeleteRequest.ts
- specification/search_application/delete_behavioral_analytics/BehavioralAnalyticsDeleteRequest.ts
- specification/search_application/get/SearchApplicationsGetRequest.ts
- specification/search_application/get_behavioral_analytics/BehavioralAnalyticsGetRequest.ts
- specification/search_application/list/SearchApplicationsListRequest.ts
- specification/search_application/put/SearchApplicationsPutRequest.ts
- specification/search_application/put_behavioral_analytics/BehavioralAnalyticsPutRequest.ts
- specification/search_application/search/SearchApplicationsSearchRequest.ts
- specification/synonyms/delete_synonym/SynonymsDeleteRequest.ts
- specification/synonyms/delete_synonym_rule/SynonymRuleDeleteRequest.ts
- specification/synonyms/get_synonym/SynonymsGetRequest.ts
- specification/synonyms/get_synonym_rule/SynonymRuleGetRequest.ts
- specification/synonyms/get_synonyms_sets/SynonymsSetsGetRequest.ts
- specification/synonyms/put_synonym/SynonymsPutRequest.ts
- specification/synonyms/put_synonym_rule/SynonymRulePutRequest.ts
- specification/tsconfig.json
Several new APIs were not exporting their `Request` interfaces. Also found some files importing modules they weren't using or that didn't exist, and noticed a few paths missing from the tsconfig.
> TypeScript fixes

- specification/_global/search_mvt/SearchMvtRequest.ts
The search mvt API is a public API in serverless, therefore adding corresponding annotation.
> Add serverless annotation to search mvt

- output/typescript/types.ts
- specification/_json_spec/indices.delete_data_lifecycle.json
- specification/_json_spec/indices.explain_data_lifecycle.json
- specification/_json_spec/indices.get_data_lifecycle.json
- specification/_json_spec/indices.put_data_lifecycle.json
- specification/cluster/_types/ComponentTemplate.ts
- specification/cluster/get_component_template/ClusterGetComponentTemplateRequest.ts
- specification/indices/_types/DataStream.ts
- specification/indices/_types/DataStreamLifecycle.ts
- specification/indices/_types/IndexState.ts
- specification/indices/_types/IndexTemplate.ts
- specification/indices/delete_data_lifecycle/IndicesDeleteDataLifecycleRequest.ts
- specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleRequest.ts
- specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleResponse.ts
- specification/indices/get_data_lifecycle/IndicesGetDataLifecycleRequest.ts
- specification/indices/get_data_lifecycle/IndicesGetDataLifecycleResponse.ts
- specification/indices/get_data_stream/IndicesGetDataStreamRequest.ts
- specification/indices/get_index_template/IndicesGetIndexTemplateRequest.ts
- specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
- specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
- specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts
- specification/indices/simulate_template/IndicesSimulateTemplateRequest.ts
As part of https://github.com/elastic/elasticsearch/pull/98644, the data stream lifecycle API become stable. Furthermore we aligned class names to reflect the rebranding of DLM to data stream lifecycle.
> Update the data stream lifecycle API

- specification/_global/search/_types/suggester.ts
- specification/_types/common.ts
Adds descriptions for the suggesters. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html
> [DOCS] Add descriptions for suggesters

- specification/_doc_ids/table.csv
- specification/ml/_types/Analysis.ts
- specification/ml/_types/Datafeed.ts
- specification/ml/_types/DataframeAnalytics.ts
- specification/ml/_types/Detector.ts
- specification/ml/_types/Job.ts
- specification/ml/delete_calendar_event/MlDeleteCalendarEventRequest.ts
- specification/ml/evaluate_data_frame/types.ts
- specification/ml/get_categories/MlGetCategoriesRequest.ts
- specification/ml/get_influencers/MlGetInfluencersRequest.ts
Adds descriptions to ML API properties. Source of info: 
* https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-apis.html
* https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-ad-apis.html
* https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-df-analytics-apis.html
* https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-df-trained-models-apis.html
> [DOCS] Adds descriptions to ML APIs

- specification/_global/reindex/ReindexRequest.ts
- specification/_global/reindex/types.ts
- specification/_types/common.ts
Adds descriptions for the reindex API. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-reindex.html
> [DOCS] Add descriptions for the reindex API

- specification/nodes/_types/Stats.ts
- specification/nodes/info/NodesInfoRequest.ts
- specification/nodes/reload_secure_settings/ReloadSecureSettingsRequest.ts
- specification/nodes/stats/NodesStatsRequest.ts
- specification/nodes/usage/NodesUsageRequest.ts
Adds descriptions to Node API properties. Source of info: 
* https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster.html
> [DOCS] Adds description to Node APIs

- output/typescript/types.ts
- specification/_types/Stats.ts
- specification/_types/common.ts
- specification/async_search/_types/AsyncSearchResponseBase.ts
- specification/async_search/status/AsyncSearchStatusResponse.ts
Updates the spec for the response objects for `POST _async_search`, `GET _async_search/:id`, `GET _async_search/status/:id` and `GET _search`
Two high level changes have happened in 8.10:
1) `completion_time` and `completion_time_in_millis` (async_search only) https://github.com/elastic/elasticsearch/pull/97700
2) Adding `details` metadata to the `_clusters` section of both async and synchronous search responses https://github.com/elastic/elasticsearch/pull/97731
> Search Response has completion_time and _cluster/details

- specification/tasks/cancel/CancelTasksRequest.ts
- specification/tasks/get/GetTaskRequest.ts
Adds descriptions for retrieve and cancel tasks APIs. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html
> [DOCS] Descriptions for tasks APIs

- specification/sql/clear_cursor/ClearSqlCursorRequest.ts
- specification/sql/delete_async/SqlDeleteAsyncRequest.ts
- specification/sql/get_async/SqlGetAsyncRequest.ts
- specification/sql/get_async_status/SqlGetAsyncStatusRequest.ts
- specification/sql/query/QuerySqlRequest.ts
- specification/sql/translate/TranslateSqlRequest.ts
Adds descriptions for SQL APIs. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-apis.html
> [DOCS] Descriptions for SQL APIs

- specification/search_application/_types/BehavioralAnalytics.ts
- specification/search_application/_types/SearchApplication.ts
- specification/search_application/list/SearchApplicationsListRequest.ts
- specification/search_application/put/SearchApplicationsPutRequest.ts
- specification/search_application/put_behavioral_analytics/BehavioralAnalyticsPutRequest.ts
- specification/search_application/search/SearchApplicationsSearchRequest.ts
Adds descriptions to Search Application API properties. Source of info: 
* https://www.elastic.co/guide/en/elasticsearch/reference/current/search-application-apis.html
> [DOCS] Adds description to the Search Application APIs

- specification/_global/count/CountRequest.ts
Adds descriptions for the count API. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/master/search-count.html
> [DOCS] Descriptions for the count API

- specification/_global/mtermvectors/MultiTermVectorsRequest.ts
- specification/_global/mtermvectors/types.ts
- specification/_global/termvectors/TermVectorsRequest.ts
- specification/_global/termvectors/types.ts
Adds descriptions for the term vectors and multi term vectors APIs. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-termvectors.html
> [DOCS] Descriptions for the termvector/mtermvector APIs

- specification/_global/bulk/BulkRequest.ts
- specification/_global/bulk/types.ts
- specification/_global/clear_scroll/ClearScrollRequest.ts
- specification/_global/close_point_in_time/ClosePointInTimeRequest.ts
Adds descriptions for the bulk and close_point_in_time APIs. Source of info:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html#:~:text=Close%20point%20in%20time%20API,longer%20used%20in%20search%20requests.
> [DOCS] Adds description to global APIs

- output/typescript/types.ts
- specification/_types/Stats.ts
- specification/_types/common.ts
- specification/async_search/_types/AsyncSearchResponseBase.ts
- specification/async_search/status/AsyncSearchStatusResponse.ts
> [8.10] Search Response has completion_time and _cluster/details (#2260)

- specification/_global/create/CreateRequest.ts
- specification/_global/delete/DeleteRequest.ts
- specification/_global/delete_by_query/DeleteByQueryRequest.ts
- specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts
- specification/_global/delete_script/DeleteScriptRequest.ts
- specification/_global/get_script/GetScriptRequest.ts
- specification/_global/open_point_in_time/OpenPointInTimeRequest.ts
- specification/_global/put_script/PutScriptRequest.ts
- specification/_global/scripts_painless_execute/ExecutePainlessScriptRequest.ts
- specification/_global/scripts_painless_execute/types.ts
- specification/_global/update_by_query/UpdateByQueryRequest.ts
- specification/_global/update_by_query_rethrottle/UpdateByQueryRethrottleRequest.ts
Adds descriptions to the:
* create
* delete
* delete by query
* delete by query rethrottle
* delete script
* get script
* open PIT
* PUT script
* scripts painless execute
* update by query
* update by query rethrottle
APIs.
Source of info:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/docs.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/script-apis.html
* https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-execute-api.html
> [DOCS] Adds description to global APIs part 2

- specification/_global/exists/DocumentExistsRequest.ts
- specification/_global/exists_source/SourceExistsRequest.ts
- specification/_global/explain/ExplainRequest.ts
- specification/_global/get/GetRequest.ts
- specification/_global/index/IndexRequest.ts
- specification/_global/msearch_template/MultiSearchTemplateRequest.ts
- specification/_global/msearch_template/types.ts
- specification/_global/reindex_rethrottle/ReindexRethrottleRequest.ts
- specification/_global/reindex_rethrottle/types.ts
- specification/_global/render_search_template/RenderSearchTemplateRequest.ts
- specification/_global/search_shards/SearchShardsRequest.ts
- specification/_global/search_template/SearchTemplateRequest.ts
Adds descriptions to the:
* document exists
* source exists
* explain
* GET
* index
* msearch template
* reindex rethrottle
* render search template
* search shards
* search template
APIs.
Source of info:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/docs.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html
> [DOCS] Adds description to global APIs part 3

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Closes #2275 
I'm not sure where this should be backported exactly. This aggregation was introduced in Elasticsearch 6.0.
> Fix include type in Significant Text agg

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
When working on https://github.com/elastic/elasticsearch-specification/pull/2279, I noticed that the Frequent Items set aggregation [appears to reuse](https://github.com/elastic/elasticsearch/blob/92458fcbcca2d36a2a16f98e1f91d739bbebbb98/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/frequentitemsets/mr/ItemSetMapReduceValueSource.java#L24) the [standard include/exclude support](https://github.com/elastic/elasticsearch/blob/92458fcbcca2d36a2a16f98e1f91d739bbebbb98/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/IncludeExclude.java#L48), so I fixed it too.
I opened a different pull request because this aggregation is much more recent: it went GA for Elasticsearch 8.7. I would also appreciate guidance regarding the backports labels.
> Fix include/exclude type in Frequent Items agg

- output/typescript/types.ts
- specification/query_ruleset/put/QueryRulesetPutRequest.ts
Fix. See https://github.com/elastic/elasticsearch-py/pull/2299
> Update QueryRulesetPutRequest body to better align with REST API

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Backport https://github.com/elastic/elasticsearch-specification/commit/fa57bcdbb1823eb2b62ee983f64f131f4b2fc02e from https://github.com/elastic/elasticsearch-specification/pull/2280
> [Backport 8.8] Fix include/exclude type in Frequent Items agg (#2280)

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Backport https://github.com/elastic/elasticsearch-specification/commit/fa57bcdbb1823eb2b62ee983f64f131f4b2fc02e from https://github.com/elastic/elasticsearch-specification/pull/2280
> [Backport 8.9] Fix include/exclude type in Frequent Items agg (#2280)

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Backport ca591c5eda691a76bb5456d29637493b9a25b426 from #2279
> [Backport 8.9] Fix include type in Significant Text Agg (#2279)

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Backport ca591c5eda691a76bb5456d29637493b9a25b426 from #2279
> [Backport 8.8] Fix include type in Significant Text Agg (#2279)

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Backport ca591c5eda691a76bb5456d29637493b9a25b426 from #2279
> [Backport 7.17] Fix include type in Significant Text Agg (#2279)

- output/typescript/types.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/core.ts
- specification/_types/query_dsl/abstractions.ts
Add sparse_vector field support (added to Elasticsearch https://github.com/elastic/elasticsearch/pull/98996) to mappings, and include it as usable in the docs for `text_expansion` query.
> Add sparse_vector field type

- output/typescript/types.ts
- specification/_types/Stats.ts
Updates the spec for the response objects for `POST _async_search`, `GET _async_search/:id`, `GET _async_search/status/:id` and `GET _search`.
In `8.11` we are adding counters in the `_details` section of both async and synchronous search responses. The counters added are: `running`, `partial` and `failed`. https://github.com/elastic/elasticsearch/pull/99566
> Add additional counters in _clusters response

- compiler-rs/compiler-wasm-lib/src/lib.rs
This adds a simple compilation error in case someone tries to build the lib with a direct `cargo build`.
> [WASM lib] Add compiler error with instructions to build the webassembly

- output/typescript/types.ts
- specification/ml/put_trained_model_vocabulary/MlPutTrainedModelVocabularyRequest.ts
This adds the missing scores parameter that was introduced in v8.9.0.
[Docs](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/put-trained-model-vocabulary.html#ml-put-trained-model-vocabulary-request-body) say:
> (Optional, array) Vocabulary value scores used by sentence-piece tokenization. Must have the same length as vocabulary. Required for unigram sentence-piece tokenized models like XLMRoberta and T5.
> Add missing `scores` parameter in `MLPutTrainedModelVocabularyRequest`

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
This was initially reported in https://github.com/elastic/elasticsearch-py/pull/2347
The `_source` body field used to work but was broken in https://github.com/elastic/elasticsearch-specification/pull/1027/files#diff-4114e335296798822015a064d77c5c6d14c797a89c76a0d08b63dcf5d4028651.
Based on https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html, I fixed `_source`, `fields` and `docvalue_fields`.
> Allow single fields in fields and _source parameters

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
(cherry picked from commit 9f40be8b64f80a8602c362aae25ff27be71e1b9a)
> [8.11] Allow single fields in fields and _source parameters (#2317)

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
(cherry picked from commit 9f40be8b64f80a8602c362aae25ff27be71e1b9a)
> [8.10] Allow single fields in fields and _source parameters

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
(cherry picked from commit 9f40be8b64f80a8602c362aae25ff27be71e1b9a)
> [7.17] Allow single fields in fields and _source parameters

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
Reverts elastic/elasticsearch-specification#2331
> Revert "[8.10] Allow single fields in fields and _source parameters"

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
Reverts elastic/elasticsearch-specification#2332
> Revert "[7.17] Allow single fields in fields and _source parameters"

- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
Reverts elastic/elasticsearch-specification#2330
It's a breaking change for typed clients and too late for 8.11.
> Revert "[8.11] Allow single fields in fields and _source parameters (#2317)"

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_global/msearch/types.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/SourceFilter.ts
Reverts elastic/elasticsearch-specification#2317. The `FieldAndFormat` type has a `@shortcut_property` field which means that if it's a scalar value, it is equivalent to a `FieldAndFormat` with only field defined. The code generation strategy for Python should be to lift the shortcut property into a union, so that `FieldAndFormat` becomes `Field | FieldAndFormat`.
> Revert "Allow single fields in fields and _source parameters"

- .gitattributes
- output/typescript/types.ts
- specification/_types/mapping/Property.ts
* Add SparseVectorProperty to Property union
* Add output/openapi/elasticsearch-serverless-openapi.json to .gitattributes
(cherry picked from commit 45873c6fd4d1695892b81aba61f42418703905c3)
> Backport 2345 to 8.11

- specification/_types/analysis/tokenizers.ts
As per the docs for [Path hierarchy tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html#analysis-pathhierarchy-tokenizer) the replacement field should be optional.
> Change replacement for PathHierarchyTokenizer to be optional

- specification/_doc_ids/table.csv
The current links produce errors in the Python client documentation.
```
/.../elasticsearch-py/.nox/docs/lib/python3.11/site-packages/elasticsearch/client.py:docstring of elasticsearch.client.EqlClient.get:3: ERROR: Unknown t
arget name: "< https://www.elastic.co/guide/en/elasticsearch/reference/master/get-async-eql-search-api.html>".
/.../elasticsearch-py/.nox/docs/lib/python3.11/site-packages/elasticsearch/client.py:docstring of elasticsearch.client.EqlClient.get_status:4: ERROR: Un
known target name: "< https://www.elastic.co/guide/en/elasticsearch/reference/master/get-async-eql-status-api.html>".                    
```
> Fix whitespace in EQL links

- .github/workflows/generate.yml
This add the `transform-to-openapi` target to the `generate` Github Action.
> Add transform-to-openapi to auto regen Github action

- specification/_types/common.ts
- specification/indices/_types/DataStream.ts
Changes the definition of `ManagedBy` to an `enum` to make consumption more idiomatic.
@andreidan 
We noticed that the string values have different casing (e.g. lowercase "stream" "lifecycle", but uppercase "Lifecycle" "Management"). Are these the exact strings returned by the ES server?
> Fix definition of `ManagedBy`

- .github/workflows/validate-pr.yml
- specification/indices/_types/DataStream.ts
The `ManagedBy` enumeration has members containing spaces. This is uncommon, and much more verbose that the actual [values used in the server code](https://github.com/elastic/elasticsearch/blob/6fa7f600738494391b8ee2241ea8664db259cc95/server/src/main/java/org/elasticsearch/action/datastreams/GetDataStreamAction.java#L151).
This PR adds `@codegen_name` to this enum's members to have shorter 'space-less' identifiers.
> Add codegen_name annotations to ManagedBy

- output/typescript/types.ts
- specification/_types/query_dsl/TextExpansionQuery.ts
- specification/_types/query_dsl/TokenPruningConfig.ts
- specification/_types/query_dsl/WeightedTokensQuery.ts
- specification/_types/query_dsl/abstractions.ts
Adds the following specification after merging https://github.com/elastic/elasticsearch/pull/102862: 
- Optional `pruning_config` added to the `text_expansion` query 
- New `weighted_tokens` query
> Add token pruning to clients for text expansion query

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
The `prefix_strings` option was added to support the E5 model in https://github.com/elastic/elasticsearch/pull/102089
> Add prefix_string config option for ML models

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
The Java client has a `.shard()` method in the Index API  that returns `illegal_argument_exception` when called, with reason `unknown setting [index.shards]`.
For example:
```
esClient.indices().create(c -> c
.index("test")
.settings(st -> st
.shards(1)
```
Trying the same call in Kibana yields the same result:
```
PUT test/
{
"settings": {
"shards": 1
}
}
```
Given that `number_of_shards` exists, I suspect `shards` shouldn't be part of the IndexSettings type.
> Remove unknown setting index.shard

- specification/security/update_api_key/Request.ts
Backport of https://github.com/elastic/elasticsearch-specification/pull/2381
> [Backport 8.12] Update spec for `update_api_key` to include `expiration` (#2381)

- output/typescript/types.ts
- specification/security/_types/RoleMappingRule.ts
Closes #2344
This fixes three issues with `FieldRule`:
* `username` can also be a list,
* `realm.name` is the field name, using an intermediate `realm` object leads to a parsing exception,
* `metadata` is not an object: values are of the form `metadata.key = value`.
Sources:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role-mapping.html for the general documentation of `POST /_security/role_mapping/<name>`, including complete examples
* https://www.elastic.co/guide/en/elasticsearch/reference/current/jwt-auth-realm.html#jwt-authorization-role-mapping which has a an extensive list of possible rules
I only tested in Kibana, as the Python client only exposes `rules` and does not go deeper.
Regarding the backports, `realm.name` and `metadata` are unusable …
> Fix FieldRule

- output/typescript/types.ts
- specification/_doc_ids/table.csv
- specification/ingest/_types/Processors.ts
Adding the [reroute processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/reroute-processor.html) to the processor types
> Adding reroute processor to ProcessorContainer

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/ingest/_types/Processors.ts
Fixes [Issue 500](https://github.com/elastic/elasticsearch-java/issues/500)
ProcessorContainer class was referring to Script instead of ScriptProcessor
> Fix script definition in processorcontainer

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_types/analysis/tokenizers.ts
When attempting to configure the path hierarchy tokenizer from a .NET app, I noticed that many of the fields are serialized with their defaults when unset, and this is incorrect. They are all optional.
> Make `PathHierarchyTokenizer` properties optional

- output/typescript/types.ts
- specification/inference/_types/Results.ts
This PR is to reflect the proposed changes included in this PR: https://github.com/elastic/elasticsearch/pull/104559 which adds support for the Cohere 3rd party service. By adding Cohere we also would like to support signed bytes as a response format for dense vector.
I'll leave this in draft until the elasticsearch PR is merged.
> Adding signed byte support from cohere integration

- output/typescript/types.ts
- specification/synonyms/put_synonym_rule/SynonymRulePutRequest.ts
synonyms is not a list, but a string in Solr format.
(cherry picked from commit 90b09673b22aa4537a2339470dc123d03f167f3b)
> Fix synonyms/put_synonym_rule body (#2407)

- output/typescript/types.ts
- specification/inference/_types/Results.ts
This PR adds the text embedding byte representation. This is to resolve the problems with the original PR: https://github.com/elastic/elasticsearch-specification/pull/2398 which caused the client generates to fail because it was unable to deduce the response format.
These changes coincide with the server changes here: https://github.com/elastic/elasticsearch/pull/105290
> [ML] Adding text embedding byte representation

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_global/field_caps/FieldCapabilitiesRequest.ts
- specification/_json_spec/field_caps.json
Updates the spec for the request object for all `_field_caps` endpoints.
In `8.13` we are adding a new optional query parameter `include_empty_fields` that defaults to `true`. If `false` empty fields are not included in the response. This change will not alter the `_field_caps` response schema.
https://github.com/elastic/elasticsearch/pull/103651
> Add optional query param in _field_caps to return only fields with value in index

- output/openapi/elasticsearch-serverless-openapi.json
- specification/inference/delete_model/DeleteModelRequest.ts
- specification/inference/get_model/GetModelRequest.ts
- specification/inference/inference/InferenceRequest.ts
- specification/inference/put_model/PutModelRequest.ts
The _inference APIs were made public in https://github.com/elastic/elasticsearch/pull/105190 and are now available in serverless. This updates the serverless visibility to `public`.
> Make Inference APIs public in Serverless

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_json_spec/update_by_query.json
- specification/indices/_types/IndexSettings.ts
- specification/ingest/_types/Processors.ts
- specification/nodes/info/types.ts
Fixes provided in this PR:
- [727](https://github.com/elastic/elasticsearch-java/issues/727) added `remove_binary` to AttachmentProcessor
- [242](https://github.com/elastic/elasticsearch-java/issues/242) made NodeInfoPath and `seed_hosts` optional to make the method `.nodes().info()` work properly, also made `initial_master_nodes` a string array, since the documentation allows for both a single string and an array, also added additional properties for NodeInfoDiscover
- [315](https://github.com/elastic/elasticsearch-java/issues/315) fixed description for update by query
- [299](https://github.com/elastic/elasticsearch-java/issues/299) allowed custom options for IndexSettings Similarity (via custom plugin)
> Batch from java issues

- output/typescript/types.ts
- specification/_json_spec/update_by_query.json
- specification/ingest/_types/Processors.ts
- specification/nodes/info/types.ts
Fixes backported in this PR:
[727](https://github.com/elastic/elasticsearch-java/issues/727) added remove_binary to AttachmentProcessor
[242](https://github.com/elastic/elasticsearch-java/issues/242) made NodeInfoPath and seed_hosts optional to make the method .nodes().info() work properly, also made initial_master_nodes a string array, since the documentation allows for both a single string and an array, also added additional properties for NodeInfoDiscover
[315](https://github.com/elastic/elasticsearch-java/issues/315) fixed description for update by query
> Java client issues fixes backport

- output/typescript/types.ts
Change type of `QueryCacheStats.total_count` from `int` -> `long`. This was incorrectly typed just for this class. All other places are already using `long` for `total_count` properties.
Related to https://github.com/elastic/elasticsearch-net/issues/8015
> Change `total_count` from `int` -> `long`

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_doc_ids/table.csv
- specification/_types/Knn.ts
`KnnQuery` reuses the same `InnerHits` as `NestedQuery`. [source](https://github.com/elastic/elasticsearch/blob/b5828fbb671cae81a9f9818fe3370a00628a1a62/server/src/main/java/org/elasticsearch/search/vectors/KnnSearchBuilder.java#L119)
Fixes #2406
> Add inner_hits field to KnnQuery within search

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_types/mapping/TypeMapping.ts
- specification/_types/mapping/complex.ts
Closes #1714 
Per https://www.elastic.co/guide/en/elasticsearch/reference/current/subobjects.html, `subobjects` is allowed at the top level and in object properties.
> Add support for subobjects property

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
- specification/ml/put_trained_model/MlPutTrainedModelRequest.ts
The `prefix_string` option was added to the model configuration in #2363 but the PUT request does not use the same config and needs to be added explicitly. 
The model config as defined in `TrainedModels.ts` cannot be used in the PUT request because it contains many fields that are automatically generated by the server and those fields should not be optional in the config but would have to be optional if used in the PUT request.
Closes #2448
> Add prefix strings to PUT model request

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
Rewrites the index similarity definition: this is a dictionary and not a container, as users can define several similarities. The name is also user-defined, indicating a dictionary.
Also adds the boolean similarity that was missing and makes some of the configuration properties optional after inspection of [the ES code base](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/similarity/SimilarityService.java).
> Rewrite similarity definition

- specification/security/query_api_keys/APIKeyAggregationContainer.ts
- specification/security/query_api_keys/QueryApiKeysRequest.ts
- specification/security/query_api_keys/QueryApiKeysResponse.ts
- specification/security/query_api_keys/types.ts
In 8.13 ES's [Query API Key Information API](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/security-api-query-api-key.html#_response_2) added support for [aggregations](https://github.com/elastic/elasticsearch/issues/101691).
This should reflect that change in the request/response of the specification.
> Support for aggregations in Security's Query API Key Information API

- specification/security/query_api_keys/QueryApiKeysRequest.ts
- specification/security/query_api_keys/types.ts
Only a subset of query types are supported when [querying API keys](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/security-api-query-api-key.html).
> Restrict query type when querying API keys

- specification/_global/bulk/BulkRequest.ts
- specification/_global/create/CreateRequest.ts
- specification/_global/index/IndexRequest.ts
- specification/_global/msearch/MultiSearchRequest.ts
- specification/fleet/msearch/MultiSearchRequest.ts
- specification/indices/downsample/Request.ts
- specification/ml/validate_detector/MlValidateDetectorRequest.ts
- specification/monitoring/bulk/BulkMonitoringRequest.ts
- specification/security/put_privileges/SecurityPutPrivilegesRequest.ts
Removes incorrect nullability marker from certain bodies.
Related to #2463
> Fix body nullability

- compiler/src/model/build-model.ts
- compiler/src/steps/validate-rest-spec.ts
Propagate question mark from typescript spec
Overrides value taken from json spec file
Add an endpoint validation to detect discrenpancy
> Compiler: fix required body value

- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/security/query_api_keys/QueryApiKeysRequest.ts
- specification/security/query_api_keys/QueryApiKeysResponse.ts
- specification/security/query_api_keys/types.ts
Renames `APIKeyQueryContainer` and `APIKeyFiltersAggregation` to use the same casing convention as the existing `ApiKey`, `ApiKeyAuthorization`, etc.
> Use consistent naming for API when used in a word

- output/typescript/types.ts
- specification/inference/_types/Results.ts
This PR adds the new completion task type and the result to the specification.
Completion result example:
```
{ 
"completion": [ 
{ 
"result": "..." 
} 
] 
}
> Add Completion result and task type to the Inference API spec

- specification/security/_types/RoleMapping.ts
- specification/security/put_role_mapping/SecurityPutRoleMappingRequest.ts
The `roles` is optional the same way as `role_templates` is.
ES in both 7.17 [https://github.com/elastic/elasticsearch/blob/92f290e9537478f85ff3fe3ab39945c1a49a[…]k/core/security/authc/support/mapper/ExpressionRoleMapping.java](https://github.com/elastic/elasticsearch/blob/92f290e9537478f85ff3fe3ab39945c1a49a6c1a/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/support/mapper/ExpressionRoleMapping.java#L236) and master (8.13) [https://github.com/elastic/elasticsearch/blob/09df99393193b2c53d92899662a8b8b3c55b[…]k/core/security/authc/support/mapper/ExpressionRoleMapping.java](https://github.com/elastic/elasticsearch/blob/09df99393193b2c53d92899662a8b8b3c55b45cd/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/support/mapper/ExpressionRo …
> Get Role Mappings optional roles field

- README.md
- api-design-guidelines/README.md
- api-design-guidelines/data-modelling.md
- api-design-guidelines/naming.md
- api-design-guidelines/requests-responses.md
This PR introduces the API Design Guidelines into this repository, giving them greater visibility. The content of these has not been changed, beyond conversion from `.mdx` to `.md`, which allows them to be viewed inline within GitHub (which is useful given that GitHub is a major part of the workflow for users of these).
The top-level README has also been updated to include reference to this new subdirectory, and a table of repo structure has been included.
> Adding the API design guidelines.

- api-design-guidelines/data-modelling.md
- api-design-guidelines/naming.md
- api-design-guidelines/requests-responses.md
Updating JSON blocks to use `yaml` tag to allow for invalid syntax in comments, etc
> Changed json blocks to use yaml tag

- specification/_spec_utils/utils.ts
This PR adds a `NullValue` type that is an alias to `null`, meant to represent "meaningful" null values, i.e. nulls that are not equivalent to missing value.
It also introduces a `Settings` type that represent a setting. Elasticsearch handles settings in very specific ways:
* setting their value to `null` resets the setting to its default value
* because of how they're implementing on the server, setting values are always returned as strings.
This PR does not uses these new types and value in the API specification. They first need to be implemented in code generators where relevant (a separate issue will track this).
Fixes #2049 - from the proposals in this issue, we introduce a specific type for meaningful nulls, but keep the standard typescript `null` for "null as optional".
> Add null value and Setting type

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/inference/_types/Results.ts
Following on the review of this PR, I am renaming the rerank parameter `id` to `index`. https://github.com/elastic/elasticsearch-specification/pull/2479
> Rerank renamed id to index

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/get/GetRequest.ts
- specification/_global/mget/MultiGetRequest.ts
- specification/_global/search/SearchRequest.ts
I noticed that `force_synthetic_source` was missing from this report: https://github.com/elastic/elasticsearch-specification/blob/071b2f79d37b92150d8ce42e3bd77951aa917f4f/output/schema/validation-errors.json#L655. Do we typically add fields behind feature flags?
I checked the following things:
* this parameter is not accepted as body parameter, either in get, mget or search
* this parameter is not accepted in msearch at all
> Add force_synthethic_source parameter

- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/security/_types/ApiKey.ts
- specification/security/get_api_key/SecurityGetApiKeyRequest.ts
- specification/security/query_api_keys/QueryApiKeysRequest.ts
This PR changes the client spec to support the new
`with_profile_uid` request parameter, as well as the
corresponding `profile_uid` response field in the returned API key information,
for the Get and Query API key endpoints, from https://github.com/elastic/elasticsearch/pull/106531 .
Separately it adds support for the `typed_keys` request parameter to
the Query API key endpoint, from https://github.com/elastic/elasticsearch/pull/106873
It also exposes the `realm_type` field in the returned API key information,
from https://github.com/elastic/elasticsearch/pull/105629
> Query and Get API Key Information endpoints support for profile uid

- specification/_spec_utils/utils.ts
PR #2478 introduced `NullValue` and `Settings` but was not exporting these types, and this went unnoticed as they were not used by other modules as part of that PR.
> Make NullValue and Setting public

- specification/_spec_utils/utils.ts
This defines a generic `WithNullValue` type that allows for semantic null assignment. 
Connectors type declarations would use this type in several different places so I'm proposing to make it a global utils type.
> Define global WithNullValue<T> type

- specification/ilm/put_lifecycle/PutLifecycleRequest.ts
- specification/indices/_types/IndexSettings.ts
JavaScript codegen [started failing](https://github.com/elastic/clients-team/actions/runs/8611069657/job/23597614947#step:3:205) for me after [this PR](https://github.com/elastic/elasticsearch-specification/pull/2485) merged the other day, specifically breaking on the "policy name in ILM should be optional" change. [The docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-put-lifecycle.html#ilm-put-lifecycle-path-params) say `policy_id` is a required parameter, since it is part of the URL path. 
I'm fairly certain the optional name that [the original issue](https://github.com/elastic/elasticsearch-java/issues/456) was referring to was for `IndexSettingsLifecycle` rather than `PutLifecycleRequest`.
> Index settings lifecycle name should be optional, not ILM policy name

- docs/add-new-api.md
Changing `__global` to `_global` in add new api docs
https://github.com/elastic/elasticsearch-specification/blob/main/specification/__global doesn't exist
> Fix 404 links in "add new api "docs

- output/typescript/types.ts
- specification/inference/inference/InferenceRequest.ts
Adding the `timeout` query parameter. This coincides with the elasticsearch PR: https://github.com/elastic/elasticsearch/pull/107242
> [ML] Adding timeout field

- specification/_types/query_dsl/span.ts
Span queries are a subset of queries, and as such can be extended through plugins.
Reported in https://github.com/elastic/elasticsearch-java/issues/780
> Make SpanQuery non exhaustive, as they can be extended with plugins

- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/Knn.ts
removing boost from knn query, querybase already has it
> Knn already inherits boost field

- specification/_types/Stats.ts
Server class: https://github.com/elastic/elasticsearch/blob/08a2f7991e214f2ac8e8b274ac51a540c30b6f3c/server/src/main/java/org/elasticsearch/index/cache/query/QueryCacheStats.java#L23
Related to: https://github.com/elastic/elasticsearch-net/issues/8015
> Change `QueryCacheStats` field types from `int` -> `long`

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_types/analysis/token_filters.ts
SynonymGraphTokenFilter and SynonymTokenFilter should have the `synonyms_set` field.
- SynonymGraphTokenFilter [server code](https://github.com/elastic/elasticsearch/blob/4cca544ccb0c12e9c35cd7f1ba49c65d84456ba0/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/SynonymGraphTokenFilterFactory.java#L28)
- SynonymTokenFilter [server code](https://github.com/elastic/elasticsearch/blob/4cca544ccb0c12e9c35cd7f1ba49c65d84456ba0/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/SynonymTokenFilterFactory.java#L169)
> Adding synonyms set to filters

- specification/connector/_types/Connector.ts
- specification/connector/last_sync/ConnectorUpdateLastSyncRequest.ts
- specification/connector/post/ConnectorPostRequest.ts
- specification/connector/put/ConnectorPutRequest.ts
- specification/connector/update_index_name/ConnectorUpdateIndexNameRequest.ts
Use alias types in connectors API where it makes sense
> Use alias types in connectors API where it makes sense

- output/typescript/types.ts
- specification/esql/_types/Version.ts
- specification/esql/query/QueryRequest.ts
Adds a `version` parameter to the ESQL `_query` request endpoint. We'll do some work to give this a default value in the generated clients soon, but for 8.14+ this'll be a required parameter.
> Add esql version

- README.md
It has been replaced by a JavaScript version that can be called with `make validate`. 
I have not found any mentions of recordings-dev and all the unzips happen in JavaScript now, which allowed to remove the section about missing the zip package.
> Remove outdated mentions of run-validations.sh

- specification/_types/aggregations/metric.ts
See https://github.com/elastic/elasticsearch-js/pull/2209.
> Add missing fields property on top_hits aggregation

- specification/_types/query_dsl/term.ts
Currently, we only support `DateRangeQuery` and `NumberRangeQuery`. According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#ranges-on-text-and-keyword), range queries can as well be used with `text` and `keyword` fields.
Related to: https://github.com/elastic/elasticsearch-net/issues/8004
> Add `TermsRangeQuery`

- compiler/src/steps/validate-model.ts
- output/typescript/types.ts
- specification/esql/_types/EsqlVersion.ts
- specification/esql/query/QueryRequest.ts
Adds constants for the base versions of ES|QL that should be used by default, for both Stateful and Serverless.
Also renames `Version` to a more specific `EsqlVersion`.
Changes to `validate-model.ts` ensure these new base version "pseudo-types" are output in `schema.json` since they're not part of the dependency graph that starts from API endpoints.
> Rename ESQL version, add constants for default versions

- compiler/src/steps/validate-model.ts
- output/typescript/types.ts
- specification/esql/_types/EsqlVersion.ts
- specification/esql/query/QueryRequest.ts
> [8.14] Rename ESQL version, add constants for default versions (#2534)

- specification/connector/_types/Connector.ts
- specification/connector/last_sync/ConnectorUpdateLastSyncRequest.ts
- specification/connector/post/ConnectorPostRequest.ts
- specification/connector/put/ConnectorPutRequest.ts
- specification/connector/update_index_name/ConnectorUpdateIndexNameRequest.ts
This will backport the following commits from `main` to `8.14`:
- [Use alias types in connectors API where it makes sense (#2507)](https://github.com/elastic/elasticsearch-specification/pull/2507)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [8.14] Use alias types in connectors API where it makes sense (#2507)

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_doc_ids/table.csv
- specification/_json_spec/connector.delete.json
- specification/_json_spec/connector.update_active_filtering.json
- specification/_json_spec/connector.update_filtering_validation.json
- specification/connector/_types/Connector.ts
- specification/connector/_types/SyncJob.ts
- specification/connector/delete/ConnectorDeleteRequest.ts
- specification/connector/update_active_filtering/ConnectorUpdateActiveFilteringRequest.ts
- specification/connector/update_active_filtering/ConnectorUpdateActiveFilteringResponse.ts
- specification/connector/update_filtering/ConnectorUpdateFilteringRequest.ts
- specification/connector/update_filtering_validation/ConnectorUpdateFilteringValidationRequest.ts
- specification/connector/update_filtering_validation/ConnectorUpdateFilteringValidationResponse.ts
This will backport the following commits from `main` to `8.14`:
- [[Connector API] Add missing 8.14 changes (#2527)](https://github.com/elastic/elasticsearch-specification/pull/2527)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [8.14] [Connector API] Add missing 8.14 changes (#2527)

- compiler/src/model/build-model.ts
- compiler/src/model/utils.ts
`ts-morph` provides us with a normalized path that always uses `/` as the path separator (even on Windows). In this PR I replace some occurences of `sep` with just `/` in that context.
Besides that, on Windows, multi-line strings are emitted with CRLF (`/r/n`) instead of just LF (`/n`). I use some ugly `replace` calls to fix this. A better solution would probably be the usage of `.gitattributes` to make sure `.ts` files are always committed and checked out in LF style. But I'm not sure if that would cause any side-effects.
TODO: Order of endpoints in the output json is not consistent between Windows and Linux. I did not dig into that for now as it does not change semantics...
> Fix spec compilation on Windows

- compiler/src/transform/expand-generics.ts
This parses the leftovers from the expansion which are tied to no `Request` nor `Response` and adds the missing behaviors without generics to the processed schema.
It allows the generic-less schema to know about:
* `CommonCatQueryParameters`
* `CommonQueryParameters`
* `BaseServerlessEsqlVersion`
* `BaseStatefulEsqlVersion`
> Add dangling types to the generic-less schema

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/inference/_types/Services.ts
- specification/inference/get/GetResponse.ts
- specification/inference/put/PutResponse.ts
The java generator was complaining about types `InferenceEndpointContainer` and `InferenceEndpoint`, changed the first one's name since it's not technically a container class.
> Changed inference name to avoid duplicate

- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_types/Base.ts
- specification/_types/aggregations/bucket.ts
- specification/_types/mapping/complex.ts
- specification/cluster/put_component_template/ClusterPutComponentTemplateRequest.ts
- specification/ingest/_types/Processors.ts
Fixes provided in this PR:
- commenting `cause` from PutComponentTemplateRequest, it's an internal parameter and should not be exposed 
- [472](https://github.com/elastic/elasticsearch-java/issues/472): `seq_no` should be optional too, like `primary_term`
- [610](https://github.com/elastic/elasticsearch-java/issues/610): RemoveProcessor is missing `keep` field. [docs]( https://www.elastic.co/guide/en/elasticsearch/reference/current/remove-processor.html#remove-processor) + [server code](https://github.com/elastic/elasticsearch/blob/b44ce50f64435d0738426551b42c950fbd59ed12/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RemoveProcessor.java#L32)
- [629](https://github.com/elastic/elasticsearch-java/issues/629): AdjacencyMatrixAggregation is missing the `separator` …
> Java issues batch 4

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_types/Retriever.ts
Relates to https://github.com/elastic/elasticsearch-specification/pull/2551
> Renaming window_size to rank_window_size for RRF in retrievers API

- specification/indices/_types/IndexSettings.ts
This remove what seems to be a leftover alias on the `StorageType` enum.
> Remove empty alias from StorageType

- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ml/update_trained_model_deployment/MlUpdateTrainedModelDeploymentRequest.ts
- specification/ml/update_trained_model_deployment/MlUpdateTrainedModelDeploymentResponse.ts
I'm not sure if it should be added or not, as this API is currently in beta.
> Add ml.update_trained_model_deployment API

- .gitignore
- Removed a duplicate `output/schema/schema/schema.json` file that was committed by mistake. 
- Added `output/schema/schema` to `.gitignore` to prevent this from happening again.
> Remove duplicate schema.json file

- .github/workflows/validate-pr.yml
This is a common problem, see #2555 and #2577 for recent examples. But not *that* common, and I tend to forget about it after a few months. Indeed, the current condition does not actually skip validation, and we don't want that anyway: we want to fail when we should have run validation but could not do it. And explain *why* we failed.
If the pull request was from an Elastic employee (95% of cases), then they can reopen it from a branch. If it was community-contributed, we need to do it for them (without closing the original pull request, thus preserving attribution when merging).
From a branch, the build was correctly triggered: https://github.com/elastic/elasticsearch-specification/actions/runs/9250931808/job/25445405796?pr=2580 (and failed as expected due to the extra file I have now …
> Fail explicitly with pull requests opened from forks

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
- specification/_types/analysis/normalizers.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/core.ts
- specification/_types/mapping/dynamic-template.ts
Fixes provided in this PR:
- [666](https://github.com/elastic/elasticsearch-java/issues/666): [AggregationRange](https://github.com/elastic/elasticsearch-specification/blob/02109140a64ce247fbb3fc0e6e4dd7b4b0d98da6/specification/_types/aggregations/bucket.ts#L674) accepting both double and string was probably established because at some point it was also used for RangeQuery, which accepts Objects for parameters `to` and `from`. But in the spec we just use it in [GeoDistanceAggregation](https://github.com/elastic/elasticsearch/blob/8864058f83bc485ce6c89a196e9d64b04e79b1cf/server/src/main/java/org/elasticsearch/search/aggregations/bucket/range/GeoDistanceAggregationBuilder.java#L98) and [RangeAggregation](https://github.com/elastic/elasticsearch/blob/8864058f83bc485ce6c89a196e9d64b04e79b1cf/s …
> Java issues batch 5

- output/typescript/types.ts
- specification/synonyms/put_synonym/SynonymsPutResponse.ts
The ReloadResult should be a member of the PutResponseSynonym, instead of the ReloadDetails, so that the PutResponseSynonym is properly serialized.
Current behavior is that it throws a [MissingRequiredPropertyException](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.13/missing-required-property.html)
Closes https://github.com/elastic/elasticsearch-java/issues/784
Closes #2578
> Fix deserialization for PutSynonymResponse

- specification/_types/analysis/phonetic-plugin.ts
The `languageset` array sometimes gets serialized as `string`, if it only contains a single element.
Related to: https://github.com/elastic/sdh-enterprise-search/issues/1360
> Fix `PhoneticTokenFilter`

- specification/indices/_types/IndexSettings.ts
The actual limits should accept `long` values instead of just `int`.
Server code:
https://github.com/elastic/elasticsearch/blob/e622101ac97496281f8bf87e537e1e0b4db30b9a/server/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L98-L147
Related to: https://github.com/elastic/elasticsearch-net/issues/8205
> Fix `IndicesMappingLimitSettings`

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_global/search/_types/hits.ts
as the comment just above the field says: 
> '_id' is not available when using 'stored_fields: `_none_`'
> Optional field id in hit class

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_global/mtermvectors/types.ts
- specification/_types/aggregations/Aggregate.ts
- specification/nodes/info/types.ts
- [558](https://github.com/elastic/elasticsearch-java/issues/558): box_plot should be boxplot. [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-boxplot-aggregation.html)
- [785](https://github.com/elastic/elasticsearch-java/issues/785): `doc_count_error` should be `doc_count_error_upper_bound`. [server code](https://github.com/elastic/elasticsearch/blob/ef12b99284785b5877bf62193bdb6f40a0bde66f/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java#L28) (it's the only match when searching)
- [716](https://github.com/elastic/elasticsearch-java/issues/716), [783](https://github.com/elastic/elasticsearch-java/issues/783): multi term vector can take both `_id` or `doc`, with `doc` being an artificial document …
> Java client issues batch 6

- specification/_types/mapping/specialized.ts
The `store` field is already defined in the base class.
> Remove duplicate `store` from `IcuCollationProperty

- specification/ml/_types/inference.ts
Some examples of singular predicted values are documented here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/infer-trained-model.html#infer-trained-model-example
Related to: https://github.com/elastic/elasticsearch-net/issues/8218
> `InferenceResponseResult.predicted_value` is single-or-many

- specification/_json_spec/inference.delete.json
- specification/inference/_types/Results.ts
- specification/inference/delete/DeleteRequest.ts
- specification/inference/delete/DeleteResponse.ts
Following on  https://github.com/elastic/elasticsearch/pull/109123 and https://github.com/elastic/elasticsearch/pull/109384, this change updates the elasticsearch specification to include the dry_run and force options for the Delete Inference Endpoint API.
> [ML] Update Delete Inference Endpoint for dry_run and force options

- .github/workflows/generate.yml
- Makefile
- compiler/src/dump/extract-routes.ts
This adds a target to generate a serverless schema and the relevant output to dump the serverless routes to the Go map.
> [route_name] Add serverless

- output/typescript/types.ts
- specification/_json_spec/ml.update_trained_model_deployment.json
- specification/ml/update_trained_model_deployment/MlUpdateTrainedModelDeploymentRequest.ts
Follow-up of https://github.com/elastic/elasticsearch-specification/pull/2564
Reflects the change made in https://github.com/elastic/elasticsearch/pull/108868. Per our [backporting guidelines](https://github.com/elastic/elasticsearch-specification/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1), this should not be backported into 8.14, as the API is usable in 8.14 and fix is on the request side.
> GA the update trained model action

- .github/validate-pr/index.js
- .github/workflows/validate-pr.yml
- typescript-generator/package.json
This also fixes generation to check generated types.
> Fail CI on generation errors

- .spectral.yaml
- Makefile
- specification/async_search/status/AsyncSearchStatusRequest.ts
- specification/ml/close_job/MlCloseJobRequest.ts
This PR adds the recommended set of Spectral linting rules and adds the linter to the makefile.
It also edits two operation summaries.
> Add Spectral linting rules for openAPI documents

- compiler/src/model/build-model.ts
- compiler/src/model/json-spec.ts
- compiler/src/model/utils.ts
- output/schema/validation-errors.json
Attach generic type parameters to the declaring type instead of the parent namespace.
This more precisely reflects the actual declaration hierarchy and allows type parameters to be uniquely identified by their FQNs.
The following definition:
```ts
export class A<T> { }
```
caused a type parameter with the FQN `some.namespace.T` to get emitted.
The same type parameter is now emitted as `some.namespace.A.T` instead.
> Attach generic type parameters to the declaring type

- output/typescript/types.ts
- specification/_types/mapping/Property.ts
- specification/_types/mapping/core.ts
- specification/_types/query_dsl/SemanticQuery.ts
- specification/_types/query_dsl/abstractions.ts
Add support for the upcoming [semantic_text](https://www.elastic.co/guide/en/elasticsearch/reference/master/semantic-text.html) and [semantic query](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-semantic-query.html).
> Add semantic_text and semantic query

- output/typescript/types.ts
- specification/ml/_types/Datafeed.ts
- specification/ml/get_trained_models/MlGetTrainedModelRequest.ts
- specification/ml/put_calendar_job/MlPutCalendarJobRequest.ts
Relates #2621 
When query parameters accept comma-separated strings, we should type them as `string | string[]` (which is what `Ids` and `Indices` are), so that clients can offer nicer list-based APIs. In fact, it's currently mandated for validation to pass, and I did not realize it when listing issues in #2621, so I am fixing those unlisted issues.
This fixes `ml.put_calendar_job`, fixes `ml.preview_datafeed` and improves `ml.get_trained_models` (fixed 5 examples, one example left).
> Fix errors around arrays in ML requests

- specification/ml/clear_trained_model_deployment_cache/examples/200_response/MlClearTrainedModelDeploymentCacheResponseExample1.json
- specification/ml/delete_expired_data/examples/200_response/MlDeleteExpiredDataResponseExample1.json
- specification/ml/delete_filter/examples/200_response/MlDeleteFilterResponseExample1.json
- specification/ml/delete_forecast/examples/200_response/MlDeleteForecastResponseExample1.json
- specification/ml/delete_model_snapshot/examples/200_responses/MlDeleteModelSnapshotResponseExample1.json
- specification/ml/delete_trained_model/examples/200_response/MlDeleteTrainedModelResponseExample1.json
- specification/ml/delete_trained_model_alias/examples/MlDeleteTrainedModelAliasResponseExample1.json
- specification/ml/estimate_model_memory/examples/200_response/MlEstimateModelMemoryResponseExample1.json
- specification/ml/estimate_model_memory/examples/request/MlEstimateModelMemoryRequestExample1.json
- specification/ml/evaluate_data_frame/examples/200_response/MlEvaluateDataFrameResponseClassificationExample1.json
- specification/ml/evaluate_data_frame/examples/200_response/MlEvaluateDataFrameResponseClassificationExample2.json
- specification/ml/evaluate_data_frame/examples/200_response/MlEvaluateDataFrameResponseOutlierExample.json
- specification/ml/evaluate_data_frame/examples/request/MlEvaluateDataFrameRequestClassificationExample1.json
- specification/ml/evaluate_data_frame/examples/request/MlEvaluateDataFrameRequestClassificationExample2.json
- specification/ml/evaluate_data_frame/examples/request/MlEvaluateDataFrameRequestOutlierExample.json
- specification/ml/evaluate_data_frame/examples/request/MlEvaluateDataFrameRequestRegressionExample1.json
- specification/ml/evaluate_data_frame/examples/request/MlEvaluateDataFrameRequestRegressionExample2.json
- specification/ml/explain_data_frame_analytics/examples/200_response/MlExplainDataFrameAnalyticsResponseExample1.json
- specification/ml/explain_data_frame_analytics/examples/request/MlExplainDataFrameAnalyticsRequestExample1.json
Part of https://github.com/elastic/elasticsearch-specification/issues/2482.
This PR adds example API calls to ML APIs (C-E), so we can generate API call examples for the documentation.
> [DOCS] Adds example requests and responses to ML APIs (C-E)

- compiler/src/steps/add-description.ts
- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
Changes the endpoint description lookup strategy to prioritize the description from request objects (i.e. in the TypeScript API) over the description from the rest-spec json file.
> Prioritize request descriptions over rest-spec for endpoint descriptions

- compiler/src/steps/add-description.ts
Follow-up to PR #2625 that incorrectly removed the fallback mechanism to rest-spec-json for request descriptions. This PR restores it.
> Restore request descriptions fallback to json-rest-spec

- output/typescript/types.ts
- specification/_types/aggregations/bucket.ts
Co-authored-by: Quentin Pradet <quentin.pradet@elastic.co>
(cherry picked from commit 2bb4d0cc61ca56099a1dd4e1dee4bdb1bf7e4362)
> [Backport 7.7] Add missing shard_min_doc_count to TermsAggregation

- compiler/src/index.ts
- compiler/src/steps/add-deprecation.ts
- specification/_types/query_dsl/abstractions.ts
Populates the `deprecation` field for endpoints from the value of the corresponding request definition.
Currently, the `deprecation` info is only available on the request type, but not on the corresponding endpoint.
> Populate endpoint deprecation from request definition

- compiler/src/model/build-model.ts
- compiler/src/model/utils.ts
Related to https://github.com/elastic/elasticsearch-specification/commit/5828dc9eb34856ceee270c5e6be638e7a9fc9f10 we wrap the propagated error such that the message become:
`failed to parse SparseVectorQuery, reason: cannot determine type of query, got: String`
> Wrap ts-morph errors to provide helpful error

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_json_spec/query_rule.delete.json
- specification/_json_spec/query_rule.get.json
- specification/_json_spec/query_rule.put.json
- specification/_json_spec/query_ruleset.delete.json
- specification/_json_spec/query_ruleset.get.json
- specification/_json_spec/query_ruleset.list.json
- specification/_json_spec/query_ruleset.put.json
- specification/_types/query_dsl/abstractions.ts
- specification/_types/query_dsl/specialized.ts
- specification/query_rule/delete/QueryRuleDeleteRequest.ts
- specification/query_rule/delete/QueryRuleDeleteResponse.ts
- specification/query_rule/get/QueryRuleGetRequest.ts
- specification/query_rule/get/QueryRuleGetResponse.ts
- specification/query_rule/put/QueryRulePutRequest.ts
- specification/query_rule/put/QueryRulePutResponse.ts
- specification/query_ruleset/_types/QueryRuleset.ts
- specification/query_ruleset/delete/QueryRulesetDeleteRequest.ts
- specification/query_ruleset/get/QueryRulesetGetRequest.ts
- specification/query_ruleset/list/QueryRulesetListRequest.ts
- specification/query_ruleset/list/types.ts
- specification/query_ruleset/put/QueryRulesetPutRequest.ts
The following changes are going live in 8.15 for query rules: 
- The feature is moving from Technical Preview to GA 
- The `rule_query` has been renamed to `rule` and support for multiple rulesets was added in https://github.com/elastic/elasticsearch/pull/108831
- A CRUD API for individual rule updates was added in https://github.com/elastic/elasticsearch/pull/109042 and https://github.com/elastic/elasticsearch/pull/109554
> [Query Rules] Update Query Rules API for 8.15

- compiler/src/steps/validate-model.ts
- output/schema/validation-errors.json
It has too many false positives to be useful in practice.
> Remove 'Non leaf-type cannot be used here' rule

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
The Index Settings API returns an additional optional field called `ignore_dynamic_beyond_limit`.
The Type definition for the same was missing in the specifications. Hence as part of this PR added.
`Request`
```
GET /logs-endpoint.alerts-default/_settings
```
`Response`
```
{
".ds-logs-endpoint.alerts-default-2024.06.24-000001": {
"settings": {
"index": {
"mapping": {
"nested_fields": {
"limit": "80"
},
"total_fields": {
"limit": "5000",
"ignore_dynamic_beyond_limit": "true"
},
"ignore_malformed": "true"
},
"hidden": "true",
"provided_name": ".ds-logs-endpoint.alerts-default-2024.06.24-000001",
"final_pipeline": ".fleet_final_pipeline-1",
"creation_date": "1719193327497",
"number_of_replicas": "1",
"uuid": "GnzWPltpSHKtwnyC3QdH2Q",
"version": {
"created": "8508000"
},
"lifecycle": { …
```
> Add missing type for ignore_dynamic_beyond_limit for the Indices Settings API

- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/indices/_types/IndexSettings.ts
(cherry picked from commit 084db754215a47db52b5c288629a21f1737c9081 from #2653)
> [Backport 8.14] Add missing index setting ignore_dynamic_beyond_limit

- .github/workflows/code-format.yml
- .github/workflows/compiler.test.yml
- .github/workflows/generate.yml
- .github/workflows/gh-pages-report.yml
- .github/workflows/linter.yml
- .github/workflows/update-rest-api-json.yml
- .github/workflows/validate-pr.yml
Older actions used older versions of Node.js themselves.
While `20.x` still works, 20 is the recommended way to setup the version now: https://github.com/actions/setup-node. Also, it's called Node.js 20, not Node.js 20.x.
> Switch to actions/setup-node@v4

- Makefile
- README.md
- docs/doc-comments-guide.md
- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- specification/indices/delete_index_template/IndicesDeleteIndexTemplateRequest.ts
- specification/indices/exists_template/IndicesExistsTemplateRequest.ts
- specification/indices/get_index_template/IndicesGetIndexTemplateRequest.ts
- specification/indices/get_template/IndicesGetTemplateRequest.ts
- specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
- specification/indices/put_template/IndicesPutTemplateRequest.ts
- specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts
- specification/indices/simulate_template/IndicesSimulateTemplateRequest.ts
This PR adds the sumarries for the index template APIs (using text from the appropriate pages under https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html).
It also updates the `make lint-docs` command to lint all the `*.json` files in the output folder and updates the readme to include the other new make commands.
> Add operation summaries for index template APIs

- .github/workflows/update-rest-api-json.yml
Otherwise, as soon as a job like 7.17 fails, everything else is canceled. But they are independent, and 1/ any success is welcome 2/ understanding fully all failures is welcome too.
> Set fail-fast: false on update-rest-api workflow

- compiler/src/model/build-model.ts
- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
- compiler/src/steps/validate-model.ts
- docs/behaviors.md
- specification/_global/search/_types/suggester.ts
- specification/_types/Errors.ts
- specification/_types/aggregations/Aggregate.ts
- specification/_types/common.ts
- specification/_types/query_dsl/compound.ts
- specification/_types/query_dsl/geo.ts
- specification/_types/query_dsl/specialized.ts
- specification/_types/query_dsl/term.ts
- specification/_types/sort.ts
- specification/indices/_types/IndexSettings.ts
- specification/indices/analyze/types.ts
- specification/indices/field_usage_stats/IndicesFieldUsageStatsResponse.ts
- specification/indices/shard_stores/types.ts
- specification/ingest/simulate/types.ts
- specification/nodes/info/types.ts
- specification/watcher/_types/Conditions.ts
- typescript-generator/src/metamodel.ts
Adds a new `behavior_meta` decorator that allows to specify supplementary meta-data per implemented behavior.
Closes #2637
> Maintain "behavior" meta-data in specification

- compiler-rs/clients_schema/src/lib.rs
- compiler-rs/clients_schema_to_openapi/src/main.rs
- compiler-rs/clients_schema_to_openapi/src/schemas.rs
- compiler-rs/openapi_to_clients_schema/src/types.rs
- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
- compiler/src/steps/validate-model.ts
- docs/modeling-guide.md
- output/openapi/elasticsearch-serverless-openapi.json
- output/typescript/types.ts
- specification/_types/query_dsl/compound.ts
- specification/_types/query_dsl/specialized.ts
- specification/_types/query_dsl/term.ts
- typescript-generator/src/index.ts
- typescript-generator/src/metamodel.ts
`RangeQuery` is currently declared as:
```ts
/** @codegen_names date, number, terms */
// Note: deserialization depends on value types
export type RangeQuery = DateRangeQuery | NumberRangeQuery | TermsRangeQuery
```
This declaration is highly problematic for statically typed clients as there is no way to correctly **de**serialize into the correct union variant, because for example the following variants share the same underlying JSON type:
```ts
export class TermsRangeQuery extends RangeQueryBase {
gt?: string
```
```ts
export class DateRangeQuery extends RangeQueryBase {
gt?: DateMath // string
```
There are more types for which the same issue applies, for example:
```ts
/** @codegen_names date, numeric, geo */
// Note: deserialization depends on value types
export type DecayFunction =
| …
```
> Improve declaration of untagged unions to allow for generator optimizations

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/_types/query_dsl/compound.ts
UserDefined in UntypedDecayFunction was too vague
> Decay placement in additional properties

- .gitattributes
We recently added new output files (e.g. schema-serverless.json) and their diff is displayed in PRs.
This PR updates `.gitattributes` to set the `linguist-generated` attribute [indicating generated files](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) to everything in `output/`.
> Collapse diffs in PRs for everything in output/

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/ingest/_types/Processors.ts
This is going to help with filling the blanks. I did not reorder the actual class declarations.
> Order ingest pipelines by name

- .github/workflows/update-rest-api-json.yml
Requesting a team review no longer works with the current PAT, which fails the action with:
```
Requesting team reviewers 'devtools-team'
Error: Unable to request reviewers. If requesting team reviewers a 'repo' scoped PAT is required.
```
Example: https://github.com/elastic/elasticsearch-specification/actions/runs/9774982444/job/26984431897
> Expand team in update rest-api-spec action

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- specification/ml/close_job/MlCloseJobRequest.ts
- specification/ml/delete_job/MlDeleteJobRequest.ts
- specification/ml/open_job/MlOpenJobRequest.ts
- specification/ml/put_job/MlPutJobRequest.ts
This PR fixes the operation summaries for a handful of machine learning anomaly detection APIs (ending period is necessary per https://github.com/elastic/elasticsearch-specification/blob/main/docs/doc-comments-guide.md), then runs the `make generate` and `make transform-to-openapi` commands to refresh the output.
> Add summaries for machine learning APIs

- output/schema/schema-serverless.json
- specification/connector/delete/ConnectorDeleteRequest.ts
- specification/connector/get/ConnectorGetRequest.ts
- specification/connector/list/ConnectorListRequest.ts
- specification/connector/post/ConnectorPostRequest.ts
- specification/connector/put/ConnectorPutRequest.ts
- specification/connector/sync_job_cancel/SyncJobCancelRequest.ts
- specification/connector/sync_job_delete/SyncJobDeleteRequest.ts
- specification/connector/sync_job_get/SyncJobGetRequest.ts
- specification/connector/sync_job_list/SyncJobListRequest.ts
- specification/connector/sync_job_post/SyncJobPostRequest.ts
- specification/connector/update_api_key_id/ConnectorUpdateAPIKeyIDRequest.ts
- specification/connector/update_configuration/ConnectorUpdateConfigurationRequest.ts
- specification/connector/update_filtering/ConnectorUpdateFilteringRequest.ts
- specification/connector/update_index_name/ConnectorUpdateIndexNameRequest.ts
- specification/connector/update_name/ConnectorUpdateNameRequest.ts
- specification/connector/update_native/ConnectorUpdateNativeRequest.ts
- specification/connector/update_pipeline/ConnectorUpdatePipelineRequest.ts
- specification/connector/update_scheduling/ConnectorUpdateSchedulingRequest.ts
- specification/connector/update_service_type/ConnectorUpdateServiceTypeRequest.ts
Connector management endpoints are marked as beta: https://www.elastic.co/guide/en/elasticsearch/reference/master/connector-apis.html
This PR updates `experimental` -> `beta` stability for connector management endpoints.
> [Connector API] Update endpoint stability

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/query_rules/_types/QueryRuleset.ts
- specification/query_rules/list_rulesets/types.ts
- specification/query_rules/put_rule/QueryRulePutRequest.ts
- specification/query_rules/put_ruleset/QueryRulesetPutRequest.ts
For reference, now that [we can use Query Rules YAML tests](https://github.com/elastic/elasticsearch/pull/110411), here is the current validation status:
| API | Status | Request | Response | Stability | Visibility |
| --- | --- | --- | --- | --- | --- |
| `delete_rule` | :green_circle: | 6/6 | 6/6 | stable | public |
| `delete_ruleset` | :green_circle: | 7/7 | 7/7 | stable | public |
| `get_rule` | :red_circle: | 5/5 | 3/5 | stable | public |
| `get_ruleset` | :red_circle: | 8/8 | 5/8 | stable | public |
| `list_rulesets` | :red_circle: | 7/7 | 1/7 | stable | public |
| `put_rule` | :red_circle: | 0/7 | 7/7 | stable | public |
| `put_ruleset` | :red_circle: | 4/10 | 10/10 | stable | public |
| **Summary** | :red_circle: | 74% | 78% | | |
With only looking at docs and validation errors …
> Fix Query Rules validation

- specification/_types/Stats.ts
It's a backport of following PR to 7.17
https://github.com/elastic/elasticsearch-specification/pull/2513
Which addresses following issues:
https://github.com/elastic/elasticsearch-net/issues/8015
https://github.com/elastic/elasticsearch-java/issues/685
> [Backport 7.17] Change `QueryCacheStats` field types from `int` -> `long` (#2513)

- .github/workflows/validate-pr.yml
- Makefile
- README.md
- compiler/run-validations.js
- docs/validation-example.md
Since #2536, validation in pull requests works based on branches, not versions. However, I had not updated `make validate` yet. It was even still suffering from the `slice(0, 3)` bug which was converting `8.15-SNAPSHOT` into `8.1`.
This should not be merged until we have `main` recordings, which should happen later today.
> make validate: Download recordings using branch, not version

- docs/validation-example.md
The README is up one folder, current link 404s.
> Fix README backlink in validation example docs

- compiler/src/model/build-model.ts
- compiler/src/model/metamodel.ts
- compiler/src/model/utils.ts
- compiler/src/steps/validate-model.ts
- compiler/src/transform/filter-by-availability.ts
- compiler/test/request-availability/test.ts
- typescript-generator/src/index.ts
- typescript-generator/src/metamodel.ts
Removes some deprecated fields which got replaced by `availability` a long time ago.
@elastic/devtools-team Please check, if your generator correctly uses the new `availability` field instead of the legacy ones.
> Remove deprecated code

- output/openapi/elasticsearch-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/security/bulk_delete_role/SecurityBulkDeleteRoleRequest.ts
- specification/security/bulk_delete_role/SecurityBulkDeleteRoleResponse.ts
This adds a new spec for the bulk delete roles API added in 8.15 in https://github.com/elastic/elasticsearch/pull/110383.
> Add specification for delete roles

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/security/_types/RoleDescriptor.ts
- specification/security/put_role/SecurityPutRoleRequest.ts
I included these changes for `SecurityPutRoleRequest` but they also need to be part of the role descriptor model since that is referenced by e.g. the API key APIs.
> Fix `RoleDescriptor` field annotations for Serverless

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/security/_types/RoleDescriptor.ts
- specification/security/put_role/SecurityPutRoleRequest.ts
(cherry picked from commit 2e232e572908af3abe551ab1700950912ee7b646)
> [Backport 8.15] Fix `RoleDescriptor` field annotations for Serverless

- docs/validation-example.md
The second one is not really a typo, it's the old name of the `main` branch.
> Fix two typos in validation example docs

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/scripts_painless_execute/ExecutePainlessScriptRequest.ts
- specification/_types/Scripting.ts
- specification/query_rules/_types/QueryRuleset.ts
- specification/search_application/_types/SearchApplication.ts
- specification/security/_types/Privileges.ts
`@shortcut_property` on `InlineScript` is unreachable from the union.
From the server code, `Script` could benefit from being a container instead.
> [Proposal] Transform script into a container

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- specification/indices/_types/DataStream.ts
- specification/indices/_types/DataStreamLifecycle.ts
- specification/indices/_types/IndexState.ts
- specification/indices/create_data_stream/IndicesCreateDataStreamRequest.ts
- specification/indices/data_streams_stats/IndicesDataStreamsStatsRequest.ts
- specification/indices/delete_data_lifecycle/IndicesDeleteDataLifecycleRequest.ts
- specification/indices/delete_data_stream/IndicesDeleteDataStreamRequest.ts
- specification/indices/get_data_lifecycle/IndicesGetDataLifecycleRequest.ts
- specification/indices/get_data_stream/IndicesGetDataStreamRequest.ts
- specification/indices/migrate_to_data_stream/IndicesMigrateToDataStreamRequest.ts
- specification/indices/modify_data_stream/IndicesModifyDataStreamRequest.ts
- specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
This PR adds operation summaries for the data stream and data stream lifecycle APIs, using text from the appropriate pages from the [elasticsearch API reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-stream-apis.html).
A couple of terminology fixes for data streams in the types area while I'm here as well
part of https://github.com/elastic/elasticsearch-specification/issues/2635
> [DOCS] Add operation summaries for data stream APIs

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/_global/search/_types/hits.ts
- specification/_types/Rank.ts
Originally reported on [discuss](https://discuss.elastic.co/t/hybrid-search-java-api-not-returning-rank/360700).
Hit is missing the optional `_rank` field -> [server code ](https://github.com/elastic/elasticsearch/blob/512bca8669faa69e0cf3be12416b000eafaf7f7c/server/src/main/java/org/elasticsearch/search/SearchHit.java#L842)
Also `window_size` in Rank was recently changed to `rank_window_size`  -> [commit](https://github.com/elastic/elasticsearch/commit/fdefe090418aed09243fb150548909e3e0c4ff0e)
> adding _rank to hit, fix property name

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/_types/mapping/DenseVectorIndexOptions.ts
From https://github.com/elastic/elasticsearch-java/issues/846
DenseVectorIndexOptions was missing a property + other fields except `type` are all optional because different types of algorithms support different options. 
[server code](https://github.com/elastic/elasticsearch/blob/199910c10b3bf63cfc1791f1e439cea85cee7fbc/server/src/main/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapper.java#L1169)
> Fixing properties in dense vector index options

- .spectral.yaml
- Makefile
- docs/overlays/elasticsearch-serverless-openapi-overlays.yaml
This PR:
- Adds an overlay file to add the missing OpenAPI `info.description`.
- Updates the linting rules to check for operation identifiers, since poor or inconsistent URLs might be created in their absence
- Adds an overlay command to the makefile for testing purposes
Per https://docs.bump.sh/guides/openapi/augmenting-generated-openapi/#deploy-overlay-changes-to-bumpsh overlays could ultimately be applied during a GitHub action so we don't need to store the modified version of the file.
> [OAS] Add OpenAPI overlays

- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/_global/rank_eval/types.ts
- specification/_types/query_dsl/compound.ts
Adding shortcuts to RankEvalQuery and FunctionScoreQuery
fixes #2713
> Adding missing shortcuts

- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
Fixes #2739. The required_native_memory_bytes represents a value in bytes, an integer is too small to fit the range, and other bytes parameters in the spec are already using the ByteSyze type.
> Change required_native_memory_bytes type to ByteSize

- output/typescript/types.ts
- specification/ml/_types/TrainedModel.ts
I opened this PR on behalf of @svalbuena so that CI can run on this change
Original change: https://github.com/elastic/elasticsearch-specification/pull/2740
Backport PR: https://github.com/elastic/elasticsearch-specification/pull/2742
> Change required_native_memory_bytes type to ByteSize (#2740)

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- specification/cat/aliases/CatAliasesRequest.ts
- specification/cat/component_templates/CatComponentTemplatesRequest.ts
- specification/cat/count/CatCountRequest.ts
- specification/cat/indices/CatIndicesRequest.ts
- specification/cat/ml_data_frame_analytics/CatDataFrameAnalyticsRequest.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
- specification/cat/ml_jobs/CatJobsRequest.ts
- specification/cat/ml_trained_models/CatTrainedModelsRequest.ts
- specification/cat/transforms/CatTransformsRequest.ts
Based on feedback, we realized that certain markdown was breaking other docs sets that rely on these specifications. Removing the problematic markdown while we decide on a strategy.
~holding this until I figure out whether additional markdown such as code markup and bulleted lists also break things~ <- will follow up on this in a later pr if needed
> Clean up markdown in spec

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- specification/ml/clear_trained_model_deployment_cache/MlClearTrainedModelDeploymentCacheRequest.ts
- specification/ml/delete_calendar/MlDeleteCalendarRequest.ts
- specification/ml/delete_calendar_event/MlDeleteCalendarEventRequest.ts
- specification/ml/delete_calendar_job/MlDeleteCalendarJobRequest.ts
- specification/ml/delete_data_frame_analytics/MlDeleteDataFrameAnalyticsRequest.ts
- specification/ml/delete_datafeed/MlDeleteDatafeedRequest.ts
- specification/ml/delete_expired_data/MlDeleteExpiredDataRequest.ts
- specification/ml/delete_filter/MlDeleteFilterRequest.ts
- specification/ml/delete_forecast/MlDeleteForecastRequest.ts
- specification/ml/delete_model_snapshot/MlDeleteModelSnapshotRequest.ts
- specification/ml/delete_trained_model/MlDeleteTrainedModelRequest.ts
- specification/ml/delete_trained_model_alias/MlDeleteTrainedModelAliasRequest.ts
- specification/ml/estimate_model_memory/MlEstimateModelMemoryRequest.ts
- specification/ml/evaluate_data_frame/MlEvaluateDataFrameRequest.ts
- specification/ml/explain_data_frame_analytics/MlExplainDataFrameAnalyticsRequest.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/2635 and https://github.com/elastic/search-docs-team/issues/136
This PR fixes the operation summaries for ML APIs (A-E) (ending period is necessary per https://github.com/elastic/elasticsearch-specification/blob/main/docs/doc-comments-guide.md), then runs the `make generate` and `make transform-to-openapi` commands to refresh the output.
> Reviews summaries of ML APIs (A-E)

- specification/connector/last_sync/ConnectorUpdateLastSyncRequest.ts
There is currently a bug when updating errors. When fixed (most likely for 8.16), this endpoint will be added back to the specification.
> Mark connector.last_sync as private for now

- output/openapi/elasticsearch-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/ilm/_types/Phase.ts
> Mapping ILM phases

- specification/cat/aliases/CatAliasesRequest.ts
- specification/cat/component_templates/CatComponentTemplatesRequest.ts
- specification/cat/count/CatCountRequest.ts
- specification/cat/indices/CatIndicesRequest.ts
- specification/cat/ml_data_frame_analytics/CatDataFrameAnalyticsRequest.ts
- specification/cat/ml_datafeeds/CatDatafeedsRequest.ts
- specification/cat/ml_jobs/CatJobsRequest.ts
- specification/cat/ml_trained_models/CatTrainedModelsRequest.ts
- specification/cat/transforms/CatTransformsRequest.ts
To avoid confusing people reading these docs in the client references, I'm removing explicit references to endpoints and endpoint names, and going back to general API names. We might revisit this [as we improve our link tech](https://github.com/elastic/elasticsearch-specification/issues/2758).
> Generalize references to APIs

- specification/cluster/health/ClusterHealthRequest.ts
Escaping the stars fixes a warning in the Python docs.
> Fix syntax in ClusterHealthRequest

- specification/cat/count/CatCountRequest.ts
Small fix on the documentation. I found this while adding markdown support to the Ruby client code generator.
> Update CatCountRequest.ts documentation

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/msearch/MultiSearchRequest.ts
- specification/_global/search/SearchRequest.ts
- specification/_global/search/_types/hits.ts
Added in [8.8](https://github.com/elastic/elasticsearch/pull/94564), `include_named_queries_score` adds the score to the result of named query. 
In practice, it changes the type of [matched_queries](https://github.com/elastic/elasticsearch-specification/blob/5615a46a870f15fa51edf6a3c4e8c2ed8cc3ebf7/specification/_global/search/_types/hits.ts#L52) in Hit from `string[]` to `string[] | Dictionary<string,double>`, because the server will return a different data structure depending on the value of `include_named_queries_score` in the request. 
After discussing this, we decided that for now strongly typed clients (java, go, .net) won't support it, but we're still adding this to the spec for completeness and for other clients that might be able to support it. 
@Anaethelion, @flobernd before …
> Added include_named_queries_score to search

- specification/_types/analysis/analyzers.ts
`CustomAnalyzer` is used in the `IndexSettings` structure for which the server flattens single-element-arrays to the element itself.
This PR fixes deserialization of `CustomAnalyzer` when e.g. requested by the `GetIndexSettings` API.
Note: There are more analyzer types with array fields that probably must be adjusted.
Closes: https://github.com/elastic/elasticsearch-net/issues/8291
> Fix `CustomAnalyzer`

- output/typescript/types.ts
- specification/synonyms/put_synonym/SynonymsPutRequest.ts
With the recent changes, `put_synonmys` can now support both `list` and `object`. Updating he specification to reflect the change.
> Updating put_synonyms api specification

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/_global/update_by_query/UpdateByQueryRequest.ts
(cherry picked from commit afc109553aeb809f05919836dc9da9f471e6e8eb)
> [Backport 8.15] Add q parameter to Update By Query API (#2792)

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/indices/_types/DataStream.ts
We used to score 3/11 on responses, it's now 11/11.
| API | Status | Request | Response |
| --- | --- | --- | --- |
| `indices.get_data_stream` | :green_circle: | 11/11 | 11/11 |
> Fix indices.get_data_stream response type

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/ml/_types/inference.ts
It can return list of lists of integers and floats.
> Fix infer_trained_model API

- output/typescript/types.ts
- specification/_global/get/types.ts
As documented in https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ignored-field.html. It also applies to get, as you can see in eg. https://github.com/elastic/elasticsearch/blob/84ddd6c7af4143861b2765bd5ff1f2a66bd41fae/rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/get/120_stored_fields_ignored.yml#L138-L142.
This fix the response validation for the Get API, while https://github.com/elastic/elasticsearch/pull/112059 will fix the request validation.
> Add _ignored to Get API response type

- output/openapi/elasticsearch-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/_global/health_report/types.ts
I noticed this error with `make validate`. I used the server source for [stagnating_backing_indices](https://github.com/elastic/elasticsearch/blob/158901577d27b426543cf1a30a7b9bd6cf93a0ba/modules/data-streams/src/main/java/org/elasticsearch/datastreams/lifecycle/health/DataStreamLifecycleHealthIndicatorService.java#L108-L127) which was missing from the example. Note that this indicator is not documented.
> Add data_stream_lifecycle to Health API response

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/query_rules/_types/QueryRuleset.ts
The `exclude` query rule type will go live with 8.16.0, this PR updates the specification accordingly.
> Add exclude query rule type to specification

- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/_global/scripts_painless_execute/types.ts
According to https://github.com/elastic/elasticsearch/blob/44758b3823a4982e9c62598f184cf90b67ab5d2a/modules/lang-painless/src/main/java/org/elasticsearch/painless/action/PainlessExecuteAction.java#L167-L223 all `context_setup` fields are optional, but [docs](https://www.elastic.co/guide/en/elasticsearch/painless/8.15/painless-execute-api.html) say that `index` and `document` are required, [all YAML tests](https://github.com/search?q=repo%3Aelastic%2Felasticsearch+scripts_painless_execute+language%3AYAML&type=code&l=YAML) include them and `context_setup` itself is already optional. As a result, I left them required.
> Fix Painless execute API

- compiler/package-lock.json
- compiler/package.json
- compiler/src/compiler.ts
This changes allows to speed up deserialization a lot (for statically typed languages) as the polymorhic variants can be determined by peeking a single JSON key-value pair instead of deserializing a complete object into an intermediate representation.
This as well allows to use built-in polymorphic JSON deserialization with several JSON frameworks (like e.g. `System.Text.Json` in .NET).
Note:
For other polymorhic objects like `Body`, `Value`, `Variant`, the discriminator is already emitted as the first key already.
Edit:
Needs further work to ensure rest of the properties stay sorted. In the best case, [safe-stable-stringify](https://github.com/BridgeAR/safe-stable-stringify/issues/48) would provide an option to customize the sort order.
> Make sure that the type discriminator is the first property

- compiler/package-lock.json
- output/openapi/elasticsearch-openapi.json
- output/openapi/elasticsearch-serverless-openapi.json
- output/schema/schema-serverless.json
- output/typescript/types.ts
- specification/_types/analysis/phonetic-plugin.ts
As the [documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-phonetic-token-filter.html#_beider_morse_settings) states, the parameters `rule_type`, `name_type` and `languageset` are only available for `beider_morse` encoder, so they should be optional.
> Making beider_morse only parameters optional

- output/openapi/elasticsearch-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ingest/delete_geoip_database/DeleteGeoipDatabaseRequest.ts
- specification/ingest/delete_geoip_database/DeleteGeoipDatabaseResponse.ts
Part of https://github.com/elastic/elasticsearch-specification/issues/2810, like https://github.com/elastic/elasticsearch-specification/pull/2815 and #2823. There's an output conflict with #2823 that I will fix when one of the two will have been merged.
> Add Delete geoip database configuration API

- docs/overlays/elasticsearch-serverless-openapi-overlays.yaml
This PR updates the OpenAPI document to use the https://creativecommons.org/licenses/by-nc-nd/4.0/ license.
> [DOCS] Overlay license in OpenAPI output

- output/openapi/elasticsearch-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ingest/_types/Database.ts
- specification/ingest/get_geoip_database/GetGeoipDatabaseResponse.ts
- specification/ingest/put_geoip_database/PutGeoipDatabaseRequest.ts
- specification/ingest/put_geoip_database/PutGeoipDatabaseResponse.ts
Part of #2810, like https://github.com/elastic/elasticsearch-specification/pull/2815.
> Add Create or update geoip database configuration API

- output/openapi/elasticsearch-openapi.json
- output/schema/validation-errors.json
- output/typescript/types.ts
- specification/ingest/delete_geoip_database/DeleteGeoipDatabaseRequest.ts
- specification/ingest/delete_geoip_database/DeleteGeoipDatabaseResponse.ts
(cherry picked from commit 21ef23261b8bcfd6fbb544ab5df8484b3e86e039)
> [Backport 8.15] Add Delete geoip database configuration API (#2824)

- docs/overlays/elasticsearch-serverless-openapi-overlays.yaml
This PR fixes the existing "create transform" example overlay, since the file path had changed. It also adds the "update transform" and "preview transform" examples.
NOTE: You need to run "make overlay-docs" to see the updated output, so I'm no longer checking in that file.
> [DOCS] Add more transform example overlays
