output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/ingest/simulate/SimulatePipelineRequest.ts, specification/ingest/simulate/SimulatePipelineResponse.ts, specification/ingest/simulate/types.ts
The errors on the request side are due to the missing `redact` processor.
=> Fix ingest.simulate API response

output/schema/validation-errors.json, output/typescript/types.ts, specification/ingest/delete_geoip_database/DeleteGeoipDatabaseRequest.ts
It was also a validation error here, but lost among the 400 other errors.
=> Mark delete_geoip_database id as mandatory

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/enrich/stats/types.ts
This was done in https://github.com/elastic/elasticsearch/pull/110578.
Unlike https://github.com/elastic/elasticsearch-specification/pull/2845, it will only appear in 8.16, so I won't backport it. But the two changes together will fix the enrich stats API response validation.
=> Add size_in_bytes to enrich stats API

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/enrich/stats/types.ts
This was done in https://github.com/elastic/elasticsearch/pull/107579.
Unlike https://github.com/elastic/elasticsearch-specification/pull/2846, this went into 8.15, so I'll backport it. The two changes together will fix the enrich stats API response validation.
=> Add hits_time_in_millis and misses_time_in_millis to enrich stats

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/cat/health/types.ts, specification/cluster/health/ClusterHealthResponse.ts, specification/cluster/health/types.ts
This was added in https://github.com/elastic/elasticsearch/pull/112024
Validation will fail because we're still using some old NEST client tests that don't have this field. I'll merge tomorrow when they will be gone.
=> Add unassigned primary shards to health reports

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_json_spec/indices.resolve_index.json, specification/indices/resolve_index/ResolveIndexRequest.ts
This PR adds the missing type definition for `ignore_unavailable` and `allow_no_indices` query param` which are [accepted by ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-resolve-index-api.html#resolve-index-api-query-params) but the definition is missing.
=> Update resolve index missing type definition

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_global/open_point_in_time/OpenPointInTimeResponse.ts
The remaining failures will be fixed when the point in time NEST tests will be removed.
=> Fix Open Point in time API

specification/_global/open_point_in_time/OpenPointInTimeRequest.ts
#2829 was merged after #2853, and introduced an import error.
=> Fix code style

output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, specification/_global/search/SearchRequest.ts
https://github.com/elastic/elasticsearch-specification/pull/2861 addresses the failing build.
=> Disable _search rank on serverless

docs/overlays/elasticsearch-serverless-openapi-overlays.yaml
This PR removes the `info.license` overlay implemented in https://github.com/elastic/elasticsearch-specification/pull/2817, since per https://spec.openapis.org/oas/v3.0.3#info-object the info.license pertains to the API license, not the documentation license.
I've moved the documentation license information to a custom extension and to the info.description until that extension is supported. I've also added a comment about which branch and repo the documentation is derived from.
=> [OAS][DOCS] Clarify license, version, and source URL 

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_types/aggregations/bucket.ts
This fixes the following YAML test in the Search API:
```json
{
"api": "search",
"file": "/test/free/aggregations/range.yml",
"name": "Null to and from",
"origin": "yaml",
"request": {
"args": {
"body": {
"aggs": {
"double_range": {
"range": {
"field": "double",
"ranges": [
{
"from": null,
"to": 50
},
{
"from": 50,
"to": 150
},
{
"from": 150,
"to": null
}
]
}
}
},
"size": 0
},
"index": "test",
"typed_keys": true
}
},
"response": {
"headers": {
"content-encoding": "gzip",
"content-type": "application/json",
"transfer-encoding": "chunked",
"x-elastic-product": "Elasticsearch"
},
"payload": {
"_shards": {
"failed": 0,
"skipped": 0,
"successful": 1,
"total": 1
},
"aggregations": {
"range#double_range": {
"buckets": [
{
"doc_count": 1,
"key": "*-50.0",
"to": 50
},
{
"doc_count": 2,
"from": 50, …
```
=> Allow null from/to in range aggregation

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_types/aggregations/Aggregate.ts, specification/_types/aggregations/AggregationContainer.ts, specification/_types/aggregations/bucket.ts
This fixes 15 YAML tests for the Search API (2191/2271 -> 2206/2271)
Here's an example request/response:
```json
{
"api": "search",
"file": "/test/free/aggregations/time_series.yml",
"name": "Number for keyword routing field",
"origin": "yaml",
"request": {
"args": {
"body": {
"aggs": {
"ts": {
"time_series": {
"keyed": false
}
}
},
"query": {
"range": {
"@timestamp": {
"gte": "2021-10-01T00:00:00Z"
}
}
},
"size": 0
},
"index": "tsdb",
"typed_keys": true
}
},
"response": {
"headers": {
"content-encoding": "gzip",
"content-type": "application/json",
"transfer-encoding": "chunked",
"x-elastic-product": "Elasticsearch"
},
"payload": {
"_shards": {
"failed": 0,
"skipped": 0,
"successful": 1,
"total": 1
},
"aggregations": {
"time_series#ts": {
"buckets": [
{
"doc_count": 1,
"key": {
"key": …
```
=> Add time series aggregation

specification/_json_spec/ingest.put_geoip_database.json
I've opened https://github.com/elastic/elasticsearch/pull/112581 too with the same contents. This is breaking the Python code generator, so I would appreciate merging this ahaed of the Elasticsearch pull request.
=> Fix content-type of put_geoip_database.json

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_types/analysis/analyzers.ts, specification/_types/analysis/nori-plugin.ts, specification/_types/analysis/tokenizers.ts
And also:
* Sort tokenizers alphabetically
* Move NoriTokenizer to its own file like other plugins
I can split this in multiple commits if that would help review.
=> Add missing tokenizers

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/nodes/_types/Stats.ts
Splitting IngestTotal in two allowed me to remove all optional fields. I have no idea if this can break typed clients or not.
=> Fix ingest statistics in cluster.info

.gitignore, Makefile, docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-example-overlays.yaml
Relates to https://github.com/elastic/elasticsearch-specification/issues/2144, https://github.com/elastic/elasticsearch-specification/issues/2482
Until we can automatically include examples in the OpenAPI documents, they are being applied by using https://github.com/elastic/elasticsearch-specification/tree/main/docs/overlays
In preparation for publishing https://github.com/elastic/elasticsearch-specification/blob/main/output/openapi/elasticsearch-openapi.json, this PR splits the existing overlay into (1) an overlay that is specific to the serverless openAPI document, (2) an overlay that is specific to the non-serverless openAPI document, and (3) an overlay that contains any common updates such as examples that are applicable to both.
The make overlay-docs command is updated to apply all …
=> Add examples to both OpenAPI documents via overlays

output/openapi/elasticsearch-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/nodes/_types/Stats.ts
This was added in https://github.com/elastic/elasticsearch/pull/99852. The `toXContent` code is fairly easy to follow in [HttpRouteStats.java](https://github.com/elastic/elasticsearch/blob/v8.15.1/server/src/main/java/org/elasticsearch/http/HttpRouteStats.java).
This also happens to fix the cluster.info API.
=> Add HTTP routes to cluster/nodes stats

compiler/run-validations.js
Without this fix, `make validate` does not take into account specification changes as it was generating them in the wrong directory. (You can check that this is the correct directory in the Makefile.) This is also why we had to add output/schema/schema to the .gitignore file.
=> Fix make validate generation

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_types/query_dsl/term.ts
Elasticsearch has supported the `minimum_should_match` parameter to `terms_set` since 8.10.0 (see https://github.com/elastic/elasticsearch/pull/96082), but it is not reflected here, so the parameter is not exposed in the autogenerated clients.
Closes https://github.com/elastic/elasticsearch-specification/pull/2908
=> Add minimum_should_match to terms_set

specification/ml/_types/CalendarEvent.ts
ML Calendar Events were updated with new fields in https://github.com/elastic/elasticsearch/pull/112837, this is the corresponding PR to update the spec
=> [ML] Add new calendar event fields

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_types/mapping/core.ts
The [default value](https://github.com/elastic/elasticsearch/blob/8e289f2b10f86959393b43bbf6c77abeb3a12622/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java#L274-L277) of the indexPrefixes [Parameter](https://github.com/elastic/elasticsearch/blob/8e289f2b10f86959393b43bbf6c77abeb3a12622/server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java#L764-L785) is null, which is what gets returned with the `include_defaults` parameter.
I'm not sure why `similarity` can be null (other than seeing it in a YAML test), but I did notice that https://github.com/elastic/elasticsearch/pull/58439 (shipped to 8.0) moved it so that it only applies to text, keyword and search as you type.
=> Fix get field mapping API response

output/openapi/elasticsearch-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/security/_types/Privileges.ts, specification/security/put_role/SecurityPutRoleRequest.ts
As documented in https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role.html. Note that `remote_cluster` is still missing, so that won't fully fix the validation.
=> Add remote_indices to Create or update roles API

.spectral.yaml, Makefile, docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-serverless-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json
Backports https://github.com/elastic/elasticsearch-specification/pull/2904
This PR also updates the branch detail in the overlays (from `main` to `8.x`) and adds the `path-params` rule to the `.spectral` linting rules. The latter is done so that this message can be downgraded from an error to a warning:
```
24597:24  error  path-params  Paths "/_nodes/{node_id}" and "/_nodes/{metric}" must not be equivalent.  paths./_nodes/{metric}
```
=> [Backport][8.x] Add overlay for deep objects in ML analysis_config, datafeed_config, and transform source #2904

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/snapshot/_types/SnapshotShardFailure.ts
I'm not sure when this was added, but we only notice it now because of the new YAML test added in https://github.com/elastic/elasticsearch/pull/113233.
This field is also used in `snapshot.get`.
=> Fix snapshot.create response

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_json_spec/snapshot.repository_verify_integrity.json, specification/snapshot/repository_verify_integrity/SnapshotRepositoryVerifyIntegrityRequest.ts, specification/snapshot/repository_verify_integrity/SnapshotRepositoryVerifyIntegrityResponse.ts
Mapping the new [repository integrity verification API](https://github.com/elastic/elasticsearch/pull/112348), allowing to merge the [latest spec update](https://github.com/elastic/elasticsearch-specification/pull/2890) without introducing new validation errors.
The query parameter `max_bytes_per_sec` is a string, but it has a specific format: `<<size-units, size units>>`. Considering it's the same in the DevTools I think we can keep it as a string for now.
=> Approximate snapshot verify integrity mapping

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_global/search/_types/hits.ts
There are still three failing test on the search response side, this fixes one of them. In [this YAML test](https://github.com/elastic/elasticsearch/blob/8dbc9f34d622711405a04793df6af7282a02169e/rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search/600_flattened_ignore_above.yml#L28-L45), the ignored field value is:
```json
{
"key": "foo bar key",
"value": "foo bar"
}
```
=> Fix ignored_field_values type

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, specification/_types/query_dsl/term.ts
As done in https://github.com/elastic/elasticsearch/pull/113286. Those parameters will be removed in 9.0.
=> Deprecate legacy params from range query

docs/overlays/elasticsearch-openapi-overlays.yaml
This PR addresses an error that occurs when you run the "make overlay-docs" command due to invalid spacing in the overlay file.
=> Fix overlay syntax error

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/search_application/delete/SearchApplicationsDeleteRequest.ts, specification/search_application/delete_behavioral_analytics/BehavioralAnalyticsDeleteRequest.ts, specification/search_application/get/SearchApplicationsGetRequest.ts, specification/search_application/get_behavioral_analytics/BehavioralAnalyticsGetRequest.ts, specification/search_application/put/SearchApplicationsPutRequest.ts, specification/search_application/put_behavioral_analytics/BehavioralAnalyticsPutRequest.ts, specification/search_application/search/SearchApplicationsSearchRequest.ts
This PR edits the operation summaries for the [search application](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-application-apis.html) and [behavioral analytics](https://www.elastic.co/guide/en/elasticsearch/reference/current/behavioral-analytics-apis.html) APIs.
=> [OpenAPI] Edit search application summaries

output/typescript/types.ts, specification/ml/_types/TrainedModel.ts
Fixes #2941.
While the server uses the [AssignmentState](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/assignment/AssignmentState.java#L13) enum for both the [state](https://github.com/elastic/elasticsearch/blob/99015aa948d3244deb924865b91317ac53ff75bd/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/assignment/AssignmentStats.java#L418) and [assignment_state](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/assignment/TrainedModelAssignment.java#L104) fields, the spec defines two different enums ([DeploymentState](https://github.com/elastic/elasticsearch-specification/blob/44322a45a33639817b972864bbe2164b86d4 …
=> Replace DeploymentState with DeploymentAssignmentState

output/typescript/types.ts, specification/nodes/info/types.ts
If security is disabled all other values are null, so `http` has to be optional as well
=> 7.17 - Fix nodes security response

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/ingest/_types/Processors.ts, specification/ingest/simulate/types.ts
As added in https://github.com/elastic/elasticsearch/pull/113552.
=> Add trace_redact to RedactProcessor

.github/download-artifacts/index.js, .github/workflows/update-rest-api-json.yml
We were still using the Artifacts API, which has no notion of "8.x", which is why builds were still failing: https://github.com/elastic/elasticsearch-specification/actions/runs/11064313424/job/30741882039.
This can be tested with:
```bash
make setup
npm install .github/download-artifacts
node .github/download-artifacts/index.js --branch 8.x
git status   # notice that we did change specification/_json_spec, it's just not formatted yet
make contrib
git status   # after formatting, there's no change left
```
=> Fetch JSON spec from Artifacts Snapshot API

.github/download-artifacts/index.js, .github/workflows/update-rest-api-json.yml
(cherry picked from commit 0464df58867761123eec71e31bde5575189fceb3)
=> [Backport 8.15] Fetch JSON spec from Artifacts Snapshot API (#2949)

.github/download-artifacts/index.js, .github/workflows/update-rest-api-json.yml
Backports #2949 and earlier related changes.
=> [7.17] Copy update-rest-api-json workflow from main

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_types/Base.ts, specification/_types/analysis/tokenizers.ts, specification/ilm/move_to_step/MoveToStepRequest.ts, specification/ilm/move_to_step/types.ts, specification/indices/_types/DataStream.ts
- [877](https://github.com/elastic/elasticsearch-java/issues/877): some optional values in ngram and edge tokenizer (details and server code references in the issue).
- [880](https://github.com/elastic/elasticsearch-java/issues/880): ForceMergeRequest accepts `wait_for_competion`, so the response should be optional to handle both `wait_for_competion` cases.
- [881](https://github.com/elastic/elasticsearch-java/issues/881): added missing `allow_custom_routing` to PutIndexTemplate. [server code](https://github.com/elastic/elasticsearch/blob/7b523568fac465f989910d7f58ad6abae68c05ff/server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java#L366) - `failure_store` is internal.
- [883](https://github.com/elastic/elasticsearch-java/issues/883): we use StepKey as both …
=> Java issues batch 8

.github/download-artifacts/index.js
The Artifacts Snapshot API still uses 'master'. I forgot to test https://github.com/elastic/elasticsearch-specification/pull/2949 on main. Here's how to do it:
```bash
make setup
npm install .github/download-artifacts
node .github/download-artifacts/index.js --branch main
make contrib
git status 
```
=> Fix download-artifacts on main branch

.github/CODEOWNERS
As part of the GitHub teams renaming initiative, it's required to replace the @elastic/clients-team with @elastic/devtools-team.
This PR is dedicated to renaming @elastic/clients-team to @elastic/devtools-team
=> Rename the clients-team

docs/overlays/elasticsearch-shared-overlays.yaml
This PR replaces occurrences of `x-abbreviated` with the `x-model` extension, which is being implemented by Bump.sh as a work-around for overly deep schema objects.
It also adds this extension to `_types.query_dsl:QueryContainer` since those details are more appropriately discussed in the Query DSL docs, which are linked as `externalDocs`.
=> Add x-model for QueryContainer

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, specification/indices/add_block/IndicesAddBlockResponseExample1.yaml, specification/indices/analyze/indicesAnalyzeRequestExample1.yaml, specification/indices/clone/indicesCloneRequestExample1.yaml, specification/indices/close/indicesCloseResponseExample1.yaml, specification/indices/create/indicesCreateRequestExample1.yaml, specification/indices/create/indicesCreateRequestExample2.yaml, specification/indices/data_streams_stats/indicesDataStreamStatsResponseExample1.yaml, specification/indices/delete_data_lifecycle/IndicesDeleteDataLifecycleResponseExample1.yaml, specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleResponseExample1.yaml, specification/indices/get_data_lifecycle/IndicesGetDataLifecycleResponseExample1.yaml, specification/indices/get_data_stream/indicesGetDataStreamResponseExample1.yaml, specification/indices/open/indicesOpenResponseExample1.yaml, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequestExample1.yaml, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequestExample2.yaml, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleResponseExample1.yaml
Backports the changes of the following PR to the 8.x branch:
Adds index API requests and responses - part 1 #2979
=> [8.x] Adds index API requests and responses - part 1

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/snapshot/restore/SnapshotRestoreResponse.ts
This is one of the many endpoints which changes its response depending if `wait_for_completion` was set as true or false in the request. [server code](https://github.com/elastic/elasticsearch/blob/21e3a17e5b70a26c6703590d10bd4305ca81425b/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotResponse.java#L64)
=> Fixing snapshot restore response

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/inference/_types/Services.ts
`task_settings` are optional when creating an endpoint in the Inference API and may not be returned in the GET response. The spec incorrectly has `task_settings` as required for both creation (PUT) and retrieval (GET), this PR changes that
The Elasticsearch documentation contains an example where an endpoint is created without task_settings ,see [creating the ELSER service](https://www.elastic.co/guide/en/elasticsearch/reference/current/infer-service-elser.html#inference-example-elser).
=> Make Inference API task_settings optional

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/nodes/info/types.ts
The ml field in NodeInfoXpackSecurity is used in start-local.
A java user [reported](https://github.com/elastic/elasticsearch-java/issues/892) that having an anonymous realm means the realm field is null (and according to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/anonymous-access.html), probably also the token field).
Unfortunately I couldn't find any server side proof, let's see what the validation says.
=> Xpack settings fixes

specification/security/_types/Privileges.ts, specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesResponse.ts
From the documentation, it seems that the security APIs always uses `IndexName[]` instead of `Indices`. The latter type has some special semantics, like e.g. `"_all"` string representation - which is not valid in the context of the security APIs.
Related to:
https://github.com/elastic/elasticsearch-net/issues/8377
=> Security APIs: Change `Indices` -> `IndexName[]`

specification/_doc_ids/table.csv, specification/ingest/_types/Processors.ts
Add ingest processor definitions for `community_id`, `fingerprint`, `network_direction`, and `registered_domain` processors. All parameters and descriptions were scraped from the 8.16 docs.
Add `ip` to the list of types supported by the `convert` processor.
Add `ecs_compatibility` to grok processor.
Add `output_format` to date processor.
Related issues
- Fixes #2309
- Fixes #2553
- Fixes #2593
- Fixes #2617
=> Add community_id, fingerprint, and network_direction processors

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/async_search/delete/AsyncSearchDeleteRequest.ts, specification/async_search/get/AsyncSearchGetRequest.ts, specification/async_search/status/AsyncSearchStatusRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts, specification/indices/analyze/IndicesAnalyzeRequest.ts
This PR improves the operation summary for the [analyze API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html) and [async search](https://www.elastic.co/guide/en/elasticsearch/reference/current/async-search.html)
Note that it adds a link from the API docs to the Elasticsearch Guide, which relates to https://github.com/elastic/elasticsearch-specification/issues/2748. If this is problematic per discussions in https://github.com/elastic/elasticsearch-specification/issues/2758, I can omit it for now.
=> [OpenAPI] Improve analyze and async search summaries

docs/overlays/elasticsearch-shared-overlays.yaml
This PR adds the `x-model` extension to tokenizer, filter, and char_filter schemas in the OpenAPI documents, since those are more appropriate described in the tokenizer reference docs.
This matches the handling of those items in the current [analyze API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html) docs, for example.
=> Add x-model overlays for tokenizer, filter, charfilter schemas

docs/overlays/elasticsearch-shared-overlays.yaml
This PR adds the `x-model` extension for the role template query schema in the role APIs, since it is too deep to display well at this time. It also adds a link to https://www.elastic.co/guide/en/elasticsearch/reference/master/field-and-document-access-control.html#templating-role-query
=> Add overlay for deep object in security APIs

docs/overlays/elasticsearch-shared-overlays.yaml
Backport e7547bb90da03348df819aeb1812af0b16b577da from https://github.com/elastic/elasticsearch-specification/pull/2914
=> [Backport 8.x] Add overlay for deep object in security APIs (#2914)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/connector/_types/Connector.ts
Fix type mismatch between definition in ES, in ES we define the advancedSnippet value as `Object`, see [code reference](https://github.com/elastic/elasticsearch/blob/6d039c2b9dfb1dfc1eaac86ecff37b3db6521908/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/filtering/FilteringAdvancedSnippet.java#L40)
This is because this can be either object or array of objects. Changing 
`Dictionary<string, UserDefinedValue>` to `UserDefinedValue`
Shoutout to @l-trotta for spotting the issue! 🏅
=> [Connectors API] Fix advanced snippet value type

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, specification/security/delete_role/SecurityDeleteRoleRequest.ts, specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesRequest.ts, specification/security/get_role/SecurityGetRoleRequest.ts, specification/security/put_role/SecurityPutRoleRequest.ts
There is a display glitch in the ES serverless API: see live [spec](https://www.elastic.co/docs/api/doc/elasticsearch-serverless/operation/operation-security-get-role).
where details of several APIs are rendered as API headers. This PR fixes the rendering issue by including the relevant header info in top-level comments for each affected API.
=> Fix role-related API spec

docs/doc-comments-guide.md
Update doc comments guidelines to ensure the best looking output in OpenAPI as well as in all other places which are using Markdown rendering.
The blank line creates a proper paragraph in all places other than the OpenAPI output - e.g. the in-code documentation of the generated clients. Without this, the text looks very squashed.
=> Update doc comments guidelines

specification/ccr/follow/CreateFollowIndexRequest.ts, specification/ccr/follow_info/types.ts
Add missing `data_stream_name` and `settings` field to `CreateFollowIndexRequest`.
As well update some fields to use the correct types and add documentation.
=> Add missing fields to `CreateFollowIndexRequest`

specification/search_application/_types/SearchApplication.ts, specification/search_application/_types/SearchApplicationParameters.ts, specification/search_application/_types/SearchApplicationTemplate.ts, specification/search_application/get/SearchApplicationsGetResponse.ts, specification/search_application/put/SearchApplicationsPutRequest.ts
The `SearchApplication` was used as the body for `search_application.put` as well as `search_application.get`.
This caused problems, because the `name` field was mandatory, but is actually not required in case of `PUT`.
In this PR, I remove `name` from `SearchApplication` and rename this type to `SearchApplicationParameters`.
The current `SearchApplication` now derives from `SearchApplicationParameters` and adds back the `name` field. This type is used as the response for `search_application.get` and `search_application.list` (instead of `SearchApplicationListItem` which became redundant).
=> Improve `SearchApplication` definition (and related)

specification/indices/_types/DataStreamLifecycle.ts, specification/indices/get_data_lifecycle/IndicesGetDataLifecycleResponse.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
The `enabled` field was missing from `DataStreamLifecycle`.
While working on this, I noticed that the specification can be simplified by re-using the `DataStreamLifecycle` on some places.
Besides that, `DataStreamWithLifecycle` incorrectly used `DataStreamLifecycle` instead of `DataStreamLifecycleWithRollover` for the `lifecycle` field.
=> Improve `DataStreamLifecycle` definitions (and related)

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/knn_search/KnnSearchRequest.ts, specification/_types/Knn.ts, specification/_types/aggregations/Aggregate.ts, specification/_types/aggregations/AggregationContainer.ts, specification/_types/aggregations/bucket.ts, specification/_types/aggregations/metric.ts, specification/_types/aggregations/pipeline.ts, specification/_types/analysis/char_filters.ts, specification/_types/analysis/token_filters.ts, specification/_types/analysis/tokenizers.ts, specification/_types/query_dsl/MatchAllQuery.ts, specification/_types/query_dsl/MatchNoneQuery.ts, specification/_types/query_dsl/SemanticQuery.ts, specification/_types/query_dsl/SparseVectorQuery.ts, specification/_types/query_dsl/TextExpansionQuery.ts, specification/_types/query_dsl/WeightedTokensQuery.ts, specification/_types/query_dsl/abstractions.ts, specification/_types/query_dsl/compound.ts, specification/_types/query_dsl/fulltext.ts, specification/_types/query_dsl/geo.ts, specification/_types/query_dsl/joining.ts, specification/_types/query_dsl/span.ts, specification/_types/query_dsl/specialized.ts, specification/_types/query_dsl/term.ts, specification/ml/_types/Analysis.ts, specification/ml/_types/Datafeed.ts
This PR adds the `x-model` extension and `externalDocs` links to appropriate pages in the Query DSL reference via overlays.
In the longer term, the addition of these `x-model` extensions ideally should be implemented in the specifications rather than in overlays, per https://github.com/elastic/elasticsearch-specification/issues/3034
=> [OpenAPI] Add x-model to specialized queries

compiler/package-lock.json, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, package-lock.json, package.json, specification/_doc_ids/table.csv, specification/security/get_user_privileges/SecurityGetUserPrivilegesRequest.ts, specification/security/get_user_profile/Request.ts, specification/security/grant_api_key/SecurityGrantApiKeyRequest.ts, specification/security/has_privileges/SecurityHasPrivilegesRequest.ts, specification/security/has_privileges_user_profile/Request.ts, specification/security/invalidate_api_key/SecurityInvalidateApiKeyRequest.ts, specification/security/invalidate_token/SecurityInvalidateTokenRequest.ts, specification/security/put_privileges/SecurityPutPrivilegesRequest.ts, specification/security/put_role/SecurityPutRoleRequest.ts, specification/security/put_role_mapping/SecurityPutRoleMappingRequest.ts, specification/security/put_user/SecurityPutUserRequest.ts, specification/security/query_api_keys/QueryApiKeysRequest.ts, specification/security/query_role/QueryRolesRequest.ts, specification/security/query_user/SecurityQueryUserRequest.ts, specification/security/saml_authenticate/Request.ts, specification/security/saml_complete_logout/Request.ts, specification/security/saml_invalidate/Request.ts, specification/security/saml_logout/Request.ts, specification/security/saml_prepare_authentication/Request.ts, specification/security/saml_service_provider_metadata/Request.ts, specification/security/suggest_user_profiles/Request.ts, specification/security/update_api_key/Request.ts, specification/security/update_user_profile_data/Request.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/2635, https://github.com/elastic/elasticsearch-specification/pull/3033, https://github.com/elastic/elasticsearch-specification/pull/3035
This PR adds/edits summaries for the remainder of the security APIs. The first phrase is used as the "operation summary" and should basically align with what existed in the table of contents in https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api.html (omitting "API" from the end of the phrase, however). Any subsequent information gets published as the "operation description".
=> [OpenAPI] Edit more security API summaries

specification/_types/query_dsl/term.ts
This seems to be a copy/paste mistake made by me when I implemented the `behavior_meta` tag.
@swallez @Anaethelion @ezimuel @picandocodigo @miguelgrinberg @l-trotta @pquentin @JoshMock   Please check, if this is a breaking change in any of your clients. Most likely only the static language clients should be affected - if at all.
=> Fix additional property name for `TermsQuery`

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts, specification/_global/mget/MultiGetRequest.ts, specification/_global/mtermvectors/MultiTermVectorsRequest.ts, specification/_global/reindex_rethrottle/ReindexRethrottleRequest.ts, specification/_global/update_by_query_rethrottle/UpdateByQueryRethrottleRequest.ts
This PR adds a summary and description for the mget, multi term vector, and terms enum APIs (copied from https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html,  https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-multi-termvectors.html, and https://www.elastic.co/guide/en/elasticsearch/reference/master/search-terms-enum.html).
It also changes their tags from "mget", "mtermvectors", and "terms_enum" to "search" so that they're grouped with the other document APIs.
=> [OpenAPI] Edit mget, multi term vectors, and terms enum APIs

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/msearch/MultiSearchRequest.ts, specification/_global/scroll/ScrollRequest.ts, specification/_global/terms_enum/TermsEnumRequest.ts
This PR adds a summary and description for the multi search and scroll APIs (copied from https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html).
It also changes their tags from "msearch" and "scroll" to "search" so that they're grouped with the other search APIs.
=> [OpenAPI] Edit multi search and scroll API

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/_global/get_script_context/GetScriptContextRequest.ts, specification/_global/get_script_languages/GetScriptLanguagesRequest.ts
This PR updates the tags and summaries for the get script language and context APIs (copied from https://www.elastic.co/guide/en/elasticsearch/reference/master/get-script-languages-api.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/get-script-contexts-api.html).
It also adds the `@doc_tag` property so that the APIs are grouped with the other script APIs.
=> [OpenAPI] Edit script language and context APIs

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/dangling_indices/delete_dangling_index/DeleteDanglingIndexRequest.ts, specification/dangling_indices/import_dangling_index/ImportDanglingIndexRequest.ts, specification/dangling_indices/list_dangling_indices/ListDanglingIndicesRequest.ts
This PR updates the tags and summaries for the dangling indices APIs (copied from https://www.elastic.co/guide/en/elasticsearch/reference/master/dangling-indices-list.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/dangling-index-delete.html, and https://www.elastic.co/guide/en/elasticsearch/reference/master/dangling-index-import.html).
It also adds the @doc_tag property so that the APIs are grouped with the other index APIs.
=> [OpenAPI] Edits dangling index APIs

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/ssl/certificates/GetCertificatesRequest.ts
This PR adds a summary and description for the SSL certificate API (copied from https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-ssl.html).
It also adds the @doc_tag property so that the API is grouped with the other security APIs.
=> [OpenAPI] Edit SSL certificate API

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/connector/check_in/ConnectorCheckInRequest.ts, specification/connector/delete/ConnectorDeleteRequest.ts, specification/connector/get/ConnectorGetRequest.ts, specification/connector/last_sync/ConnectorUpdateLastSyncRequest.ts, specification/connector/list/ConnectorListRequest.ts, specification/connector/post/ConnectorPostRequest.ts, specification/connector/put/ConnectorPutRequest.ts, specification/connector/sync_job_cancel/SyncJobCancelRequest.ts, specification/connector/sync_job_delete/SyncJobDeleteRequest.ts, specification/connector/sync_job_get/SyncJobGetRequest.ts, specification/connector/sync_job_list/SyncJobListRequest.ts, specification/connector/sync_job_post/SyncJobPostRequest.ts, specification/connector/update_active_filtering/ConnectorUpdateActiveFilteringRequest.ts, specification/connector/update_api_key_id/ConnectorUpdateAPIKeyIDRequest.ts, specification/connector/update_configuration/ConnectorUpdateConfigurationRequest.ts, specification/connector/update_error/ConnectorUpdateErrorRequest.ts, specification/connector/update_filtering/ConnectorUpdateFilteringRequest.ts, specification/connector/update_filtering_validation/ConnectorUpdateFilteringValidationRequest.ts, specification/connector/update_index_name/ConnectorUpdateIndexNameRequest.ts, specification/connector/update_name/ConnectorUpdateNameRequest.ts, specification/connector/update_native/ConnectorUpdateNativeRequest.ts, specification/connector/update_pipeline/ConnectorUpdatePipelineRequest.ts, specification/connector/update_scheduling/ConnectorUpdateSchedulingRequest.ts, specification/connector/update_service_type/ConnectorUpdateServiceTypeRequest.ts, specification/connector/update_status/ConnectorUpdateStatusRequest.ts
This PR updates the operation summaries and a few operation descriptions with content copied from https://www.elastic.co/guide/en/elasticsearch/reference/master/connector-apis.html
NOTE: I didn't see a difference in the old docs between the "update filtering" and "update active filtering", so I left the text as-is in the latter.
=> [OpenAPI] Edits connector API summaries

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/msearch/types.ts, specification/_global/search/_types/FieldCollapse.ts
This PR adds more `@ext_doc_id` values and more `x-model` overlays for deeply nested Elasticsearch schema objects.
It also adds a comment in the introduction about the "work-in-progress" state of content on the "main" branch, to match what's in our other docs.
=> [OpenAPI] Add more x-model and @ext_doc_id values

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/_json_spec/indices.segments.json, specification/indices/segments/IndicesSegmentsRequest.ts
See https://github.com/elastic/elasticsearch/pull/116030.
=> Remove `?verbose` from `_segments` API

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/security/_types/Access.ts, specification/security/_types/Privileges.ts, specification/security/create_cross_cluster_api_key/CreateCrossClusterApiKeyRequest.ts, specification/security/create_cross_cluster_api_key/CreateCrossClusterApiKeyResponse.ts, specification/security/update_cross_cluster_api_key/UpdateCrossClusterApiKeyRequest.ts, specification/security/update_cross_cluster_api_key/UpdateCrossClusterApiKeyResponse.ts
The create and update cross cluster key APIs were not appearing in the OpenAPI output, so I've created an initial pass at the necessary files per https://github.com/elastic/elasticsearch-specification/blob/main/docs/add-new-api.md
The descriptions are copied from https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-update-cross-cluster-api-key.html and
=> Add cross cluster security APIs

output/typescript/types.ts, specification/_types/Retriever.ts
Backports https://github.com/elastic/elasticsearch-specification/pull/3078 to 8.x. 
Text similarity came with it, but since it's in 8.15 that's probably OK
=> [8.x] Add specification for query rules retriever

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_json_spec/cat.aliases.json, specification/_json_spec/indices.exists_alias.json, specification/_json_spec/indices.get_alias.json, specification/indices/exists_alias/IndicesExistsAliasRequest.ts, specification/indices/get_alias/IndicesGetAliasRequest.ts
This updates the specification to reflect the changes in https://github.com/elastic/elasticsearch/pull/115393.
=> Remove deprecated local parameter from alias APIs

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, specification/indices/exists_alias/IndicesExistsAliasRequest.ts, specification/indices/get_alias/IndicesGetAliasRequest.ts
Following https://github.com/elastic/elasticsearch-specification/pull/3059, which removes the `local` parameter from alias requests in version 9, we should mark it as deprecated in 8
=> deprecating local param from alias req

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/clear_scroll/ClearScrollRequest.ts, specification/_global/close_point_in_time/ClosePointInTimeRequest.ts, specification/_global/field_caps/FieldCapabilitiesRequest.ts, specification/_global/knn_search/KnnSearchRequest.ts, specification/_global/msearch_template/MultiSearchTemplateRequest.ts, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_global/rank_eval/RankEvalRequest.ts, specification/_global/render_search_template/RenderSearchTemplateRequest.ts, specification/_global/search/SearchRequest.ts, specification/_global/search_mvt/SearchMvtRequest.ts, specification/_global/search_shards/SearchShardsRequest.ts, specification/_global/search_template/SearchTemplateRequest.ts, specification/_global/termvectors/TermVectorsRequest.ts, specification/async_search/delete/AsyncSearchDeleteRequest.ts, specification/async_search/get/AsyncSearchGetRequest.ts, specification/async_search/status/AsyncSearchStatusRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts
This PR edits the summaries for a subset of search APIs, such that they more closely align with our style recommendations and the titles from https://www.elastic.co/guide/en/elasticsearch/reference/master/search.html
Since the openAPI document is too big for previews and not hooked into buildkite previews yet, if reviewers are wanting to review the strings, they all appear in the output/openapi/elasticsearch-openapi.json file. The serverless file in that folder is the same or smaller subset so it's not necessary to compare both output for the purposes of these text edits.
=> [OpenAPI] Edit search API summaries

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/autoscaling/_types/AutoscalingPolicy.ts, specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts, specification/autoscaling/delete_autoscaling_policy/autoscalingApisDeleteAutoscalingPolicyResponseExample1.json, specification/autoscaling/delete_autoscaling_policy/autoscalingApisDeleteAutoscalingPolicyResponseExample1.yaml, specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts, specification/autoscaling/get_autoscaling_capacity/autoscalingApisGetAutoscalingCapacityResponseExample1.json, specification/autoscaling/get_autoscaling_capacity/autoscalingApisGetAutoscalingCapacityResponseExample1.yaml, specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts, specification/autoscaling/get_autoscaling_policy/autoscalingApisGetAutoscalingPolicyResponseExample1.json, specification/autoscaling/get_autoscaling_policy/autoscalingApisGetAutoscalingPolicyResponseExample1.yaml, specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts, specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample1.json, specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample1.yaml, specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample2.json, specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample2.yaml, specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyResponseExample1.json, specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyResponseExample1.yaml
Backports https://github.com/elastic/elasticsearch-specification/pull/3081 from https://github.com/elastic/elasticsearch-specification/commit/b0860fca5b1e7049848d622b31481ff5f02a1a47
=> [8.16][OpenAPI] Edits the autoscaling APIs (#3081)

specification/_global/knn_search/KnnSearchRequest.ts
The message is defined in the rest-api-spec, but schema.json uses the value from the specification request, so I copied it from there:
https://github.com/elastic/elasticsearch-specification/blob/b59191910c29f38113114ba7336a812eb7cc87e7/specification/_json_spec/knn_search.json#L10
=> Fix knn_search deprecation message

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_spec_utils/behaviors.ts, specification/cat/allocation/CatAllocationRequest.ts, specification/cat/component_templates/CatComponentTemplatesRequest.ts, specification/cat/indices/CatIndicesRequest.ts, specification/cat/master/CatMasterRequest.ts, specification/cat/nodeattrs/CatNodeAttributesRequest.ts, specification/cat/pending_tasks/CatPendingTasksRequest.ts, specification/cat/plugins/CatPluginsRequest.ts, specification/cat/segments/CatSegmentsRequest.ts, specification/cat/templates/CatTemplatesRequest.ts, specification/cat/thread_pool/CatThreadPoolRequest.ts
Followup of #3059, removing `local` from common cat parameters and adding it only to those requests which allow it. 
I can't test it with java because it has its own handcrafted test types, but it seems straightforward enough.
=> "local" parameter only in compatible cat requests

output/schema/schema-serverless.json, specification/_json_spec/indices.delete_data_lifecycle.json, specification/_json_spec/indices.explain_data_lifecycle.json, specification/_json_spec/indices.get_data_lifecycle.json, specification/_json_spec/indices.put_data_lifecycle.json
As noticed in https://github.com/elastic/elasticsearch-specification/pull/3019, but extracting it into its own pull request is easier until the IP location APIs are merged. This also include an unrelated fix to the same APIs that I submitted to Elasticsearch: https://github.com/elastic/elasticsearch/pull/116292
=> Mark data lifecycle APIs as stable

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/search/SearchRequest.ts, specification/_json_spec/search.json, specification/async_search/submit/AsyncSearchSubmitRequest.ts, specification/fleet/search/SearchRequest.ts
As done in https://github.com/elastic/elasticsearch/pull/114713 and picked up by https://github.com/elastic/elasticsearch-specification/pull/3019.
=> Remove min_compatible_shard_mode field

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/ingest/_types/Processors.ts
As added in https://github.com/elastic/elasticsearch/pull/114548. An alternative to fix the failure is to ignore the new "Test ip_location processor with defaults" test.
=> Add ip_location ingest processor

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/tasks/list/ListTasksRequest.ts
Closes https://github.com/elastic/elasticsearch-specification/issues/3112, closes https://github.com/elastic/elasticsearch-specification/pull/3114
Use parameter `nodes` instead of `node_id` on `task.list`.
=> Set parameter nodes instead of node_id on task.list

output/schema/schema-serverless.json, specification/_json_spec/indices.delete_data_lifecycle.json, specification/_json_spec/indices.explain_data_lifecycle.json, specification/_json_spec/indices.get_data_lifecycle.json, specification/_json_spec/indices.put_data_lifecycle.json
(cherry picked from commit 17693a6ccd679cb943c952838a700c673b13b9ad)
=> [Backport 8.x] Mark data lifecycle APIs as stable (#3109)

specification/security/_types/Privileges.ts
* Documented in https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-cross-cluster-api-key.html#security-api-create-cross-cluster-api-key-request-body
* Implemented in https://github.com/elastic/elasticsearch/blob/a04fd2668b82e0c4324b2cc8afe03eb9b0113ac2/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleDescriptor.java#L949-L960
* Tested in https://github.com/elastic/elasticsearch/blob/a04fd2668b82e0c4324b2cc8afe03eb9b0113ac2/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/api_key/50_cross_cluster.yml#L62C20-L62C44
=> Add missing allow_restricted_indices to cross cluster api key APIs

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/migration/deprecations/DeprecationInfoResponse.ts
We added a new `data_streams` section to the deprecation info api response in https://github.com/elastic/elasticsearch/pull/116447
Closes https://github.com/elastic/elasticsearch-specification/pull/3133
=> Add data_streams to the deprecation info api response

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/indices/_types/IndexTemplate.ts
Adds the missing `deprecated` and `ignore_missing_component_templates` fields to `IndexTemplate`.
Closes https://github.com/elastic/elasticsearch-specification/pull/3135
=> Add missing fields to `IndexTemplate`

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/security/_types/Privileges.ts
Motivated by [this YAML test](https://github.com/elastic/elasticsearch/blob/a04fd2668b82e0c4324b2cc8afe03eb9b0113ac2/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/roles/60_bulk_roles.yml#L39-L46) I realized that `index` in various privileges classes can always be an index pattern, ie. a string.
For references, here is how IndexName and Indices are defined:
```ts
export type IndexName = string
export type Indices = IndexName | IndexName[]
```
This fixes `security.bulk_put_role`, as can be tested with `make validate api=security.bulk_put_role branch=main`.
=> Allow index name patterns in Privileges index fields

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/security/_types/RoleDescriptor.ts
This allows representing the following YAML test:
```typescript
// Test file: /test/platinum/entsearch/search/56_search_application_search_with_apikey.yml
// Test name: Query Search Application with API key
import { expectAssignable } from 'tsd'
import * as T from '../types'
expectAssignable<T.SecurityCreateApiKeyRequest>({
"body": {
"name": "search-application-1-api-key",
"role_descriptors": {
"role": {
"index": [
{
"names": [
"test-search-application-1"
],
"privileges": [
"read"
]
}
],
"restriction": {
"workflows": [
"search_application_query"
]
}
}
}
}
})
```
=> Add restriction to RoleDescriptor

specification/security/_types/Privileges.ts, specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesResponse.ts, specification/security/put_role/SecurityPutRoleRequest.ts
Availability on types should not be used (see #2643 and #2830).
The PR moves the `@availability` tag from the type itself to the place(s) where the type is used.
Without this change, the .NET generator produced an enum without a member for the `serverless` flavor.
=> Fix `RemoteClusterPrivilege` availability

output/openapi/elasticsearch-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/security/_types/Privileges.ts, specification/security/_types/RoleDescriptor.ts, specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesResponse.ts, specification/security/get_role/types.ts, specification/security/put_role/SecurityPutRoleRequest.ts
This commit adds support for the remote_cluster in the role and role descriptors. Additionally:
* adds missing references to remote_indices
* add new cluster privilege monitor_stats
* adds related version information where applicable
* updates references to cluster from string[] to proper enumeration
(cherry picked from commit dac7201aa2a52228954f70195c478647caeae7c1)
=> [8.x] Support for security remote_cluster and associated privileges (#3125)

output/typescript/types.ts, specification/query_rules/list_rulesets/types.ts
Adds the `rule_type_counts` added in https://github.com/elastic/elasticsearch/pull/116357 to the specification
=> Add rule_type_counts to QueryRulesetListResponse spec

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_json_spec/open_point_in_time.json
`allow_partial_search_results` was made available for the `OpenPointInTime` request in https://github.com/elastic/elasticsearch/pull/111516 but the specs weren't properly updated. This PR adds a new `allow_partial_search_results` parameter to the `OpenPointInTime` spec, which default to `false`, and specifies whether we should be lenient if a shard is missing when creating a point in time reference, or if we should throw.  
Closes https://github.com/elastic/elasticsearch-specification/issues/3144
=> Adding allow_partial_search_results parameter to OpenPointInTime action

docs/overlays/elasticsearch-serverless-openapi-overlays.yaml
This PR removes the "technical preview" text from the introduction of the Elasticsearch Serverless API docs.
=> [DOCS] Remove technical preview from serverless APIs

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts, specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts, specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts, specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts
In https://github.com/elastic/elasticsearch/pull/108759, @DaveCTurner added `master_timeout` support for autoscaling APIs. We were also already misssing `timeout` parameters. Note that adding those entries removes all the `autoscaling` entries in `output/schema/validation-errors.json`.
=> Add missing autoscaling timeout parameters

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/security/_types/ApiKey.ts, specification/security/authenticate/SecurityAuthenticateResponse.ts, specification/security/get_api_key/SecurityGetApiKeyResponse.ts, specification/security/query_api_keys/QueryApiKeysResponse.ts
* Added missing fields invalidation, access and type.
* Added ApiKeyRead using the [OverloadOf](https://github.com/elastic/elasticsearch-specification/blob/c80b3fd2c3df8d5ecabaa6ad7884faa68312f261/docs/behaviors.md#overloadof) behavior as some fields are optional with the Authenticate API but always defined when reading API keys.
=> Fix security.get_api_key and security.query_api_keys APIs

compiler/package.json
Today, `make spec-format-fix` (a dependency of make contrib) nearly prints 2000 lines of output, which isn't useful while making the validation errors less visible.
=> Silence formatting output

compiler/run-validations.js
With the corresponding clients-flight-recorder pull request, this requires running `make validate-no-cache` instead of simply `make validate`. For example:
```bash
❯ make validate-no-cache api=xpack.info branch=main
Validating endpoints
Validating xpack.info
xpack.info request has been successfully validated!
✔ 8 out of 8 test request cases are passing.
✔ 4 out of 4 test response cases are passing.
```
=> Use git recordings when running `make validate`

output/typescript/types.ts, package-lock.json, package.json, specification/watcher/_types/Schedule.ts
This change adds timezone support to Watcher schedules added in https://github.com/elastic/elasticsearch/pull/117033
=> Add support for new timezone field in watch schedules

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, package-lock.json, specification/async_search/status/AsyncSearchStatusRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts
- [Fix async_search query parameter validation (#3167)](https://github.com/elastic/elasticsearch-specification/pull/3167)
=> [8.x] Fix async_search query parameter validation (#3167)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/async_search/status/AsyncSearchStatusRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts
This will backport the following commits from `main` to `8.16`:
- [Fix async_search query parameter validation (#3167)](https://github.com/elastic/elasticsearch-specification/pull/3167)
=> [8.16] Fix async_search query parameter validation (#3167)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/async_search/status/AsyncSearchStatusRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts
- [Fix async_search query parameter validation (#3167)](https://github.com/elastic/elasticsearch-specification/pull/3167)
=> [8.17] Fix async_search query parameter validation (#3167)

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-serverless-openapi-overlays.yaml
Relates to https://github.com/elastic/docs-content/issues/192
This PR adds overlays for the missing `securityScheme` and `security` objects.
The result is that the Elasticsearch API documents will have a page equivalent to this: https://www.elastic.co/docs/api/doc/serverless/authentication
=> [OpenAPI] Add securitySchemes and security in overlays

docs/overlays/elasticsearch-openapi-overlays.yaml
Backports https://github.com/elastic/elasticsearch-specification/pull/3198
=> [8.x][OpenAPI] Add securitySchemes and security in overlays #3198

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/nodes/info/types.ts
Reported in https://github.com/elastic/go-elasticsearch/issues/911
Turns out the `data` key is in fact a union over a string and an array. [server code for reference.](https://github.com/elastic/elasticsearch/blob/e5bcb0c5b3563044edf96ee9c57f03733cd888a8/server/src/main/java/org/elasticsearch/env/Environment.java#L131)
=> [Nodes.Info] Fix NodeInfoPath data

specification/indices/_types/IndexSettings.ts
All index settings can be strings, as can be seen in https://github.com/elastic/elasticsearch/blame/6d155fcc5af670638be4961ac1e17f4d0a217658/rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/logsdb/10_settings.yml#L623-L624.
=> Allow string for total_fields index settings

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/sql/clear_cursor/ClearSqlCursorRequest.ts, specification/sql/delete_async/SqlDeleteAsyncRequest.ts, specification/sql/get_async/SqlGetAsyncRequest.ts, specification/sql/get_async_status/SqlGetAsyncStatusRequest.ts, specification/sql/query/QuerySqlRequest.ts, specification/sql/translate/TranslateSqlRequest.ts
Adds summaries to https://www.elastic.co/docs/api/doc/elasticsearch-serverless/group/endpoint-sql based on https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-apis.html
=> [DOCS] Add SQL operation summaries

output/openapi/elasticsearch-openapi.json, specification/fleet/global_checkpoints/GlobalCheckpointsRequest.ts, specification/fleet/msearch/MultiSearchRequest.ts, specification/fleet/search/SearchRequest.ts
This PR edits the Fleet summaries in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-fleet based on content from https://www.elastic.co/guide/en/elasticsearch/reference/current/fleet-apis.html
=> [DOCS] Edit Fleet operation summaries

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/count/CountRequest.ts, specification/enrich/execute_policy/ExecuteEnrichPolicyRequest.ts, specification/indices/exists_index_template/IndicesExistsIndexTemplateRequest.ts, specification/indices/resolve_index/ResolveIndexRequest.ts
This PR edits a handful of operation summaries.
=> [DOCS] Edit some operation summaries

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/ingest/delete_geoip_database/DeleteGeoipDatabaseRequest.ts, specification/ingest/delete_pipeline/DeletePipelineRequest.ts, specification/ingest/geo_ip_stats/IngestGeoIpStatsRequest.ts, specification/ingest/get_geoip_database/GetGeoipDatabaseRequest.ts, specification/ingest/get_pipeline/GetPipelineRequest.ts, specification/ingest/processor_grok/GrokProcessorPatternsRequest.ts, specification/ingest/put_geoip_database/PutGeoipDatabaseRequest.ts, specification/ingest/put_pipeline/PutPipelineRequest.ts, specification/ingest/simulate/SimulatePipelineRequest.ts
This PR edits the summaries in https://www.elastic.co/docs/api/doc/elasticsearch-serverless/group/endpoint-ingest based on https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-apis.html
=> [DOCS] Add ingest operation summaries

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/esql/query/QueryRequest.ts
This PR edits the summary in https://www.elastic.co/docs/api/doc/elasticsearch-serverless/group/endpoint-esql based on https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-apis.html
=> [DOCS] Add ES|QL search operation summary

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/query_rules/delete_rule/QueryRuleDeleteRequest.ts, specification/query_rules/delete_ruleset/QueryRulesetDeleteRequest.ts, specification/query_rules/get_rule/QueryRuleGetRequest.ts, specification/query_rules/get_ruleset/QueryRulesetGetRequest.ts, specification/query_rules/list_rulesets/QueryRulesetListRequest.ts, specification/query_rules/put_rule/QueryRulePutRequest.ts, specification/query_rules/put_ruleset/QueryRulesetPutRequest.ts, specification/query_rules/test/QueryRulesetTestRequest.ts
This PR edits the summaries in https://www.elastic.co/docs/api/doc/elasticsearch-serverless/group/endpoint-query_rules based on https://www.elastic.co/guide/en/elasticsearch/reference/current/query-rules-apis.html
=> [DOCS] Add query rule operation summaries

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/graph/explore/GraphExploreRequest.ts
This PR edits the summary in https://www.elastic.co/docs/api/doc/elasticsearch-serverless/operation/operation-graph-explore based on https://www.elastic.co/guide/en/elasticsearch/reference/current/graph-explore-api.html
=> [DOCS] Add graph explore operation summary

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/indices/exists_alias/IndicesExistsAliasRequest.ts, specification/indices/get_alias/IndicesGetAliasRequest.ts
Removes validation errors in https://github.com/elastic/elasticsearch-specification/pull/3251
=> Added missing master timeout

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/eql/delete/EqlDeleteRequest.ts, specification/eql/get/EqlGetRequest.ts, specification/eql/get_status/EqlGetStatusRequest.ts, specification/eql/search/EqlSearchRequest.ts
- [[DOCS] Adds EQL operation summaries (#3207)](https://github.com/elastic/elasticsearch-specification/pull/3207)
=> [8.x] [DOCS] Adds EQL operation summaries (#3207)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/eql/delete/EqlDeleteRequest.ts, specification/eql/get/EqlGetRequest.ts, specification/eql/get_status/EqlGetStatusRequest.ts, specification/eql/search/EqlSearchRequest.ts
- [[DOCS] Adds EQL operation summaries (#3207)](https://github.com/elastic/elasticsearch-specification/pull/3207)
=> [8.17] [DOCS] Adds EQL operation summaries (#3207)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/eql/delete/EqlDeleteRequest.ts, specification/eql/get/EqlGetRequest.ts, specification/eql/get_status/EqlGetStatusRequest.ts, specification/eql/search/EqlSearchRequest.ts
This will backport the following commits from `main` to `8.16`:
- [[DOCS] Adds EQL operation summaries (#3207)](https://github.com/elastic/elasticsearch-specification/pull/3207)
=> [8.16] [DOCS] Adds EQL operation summaries (#3207)

compiler/src/steps/validate-rest-spec.ts, output/schema/validation-errors.json
The JSON rest-api-spec generally encodes those cat parameters, so this reduces the number of errors.
This reduces the number of validation errors from 329 to 213.
=> Consider CommonCatQueryParameters to validate query parameters

compiler/src/steps/validate-rest-spec.ts, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts
The JSON rest-api-spec generally encodes this parameters, so that reduces the number of validation errors.
(cherry picked from commit d9bf86fe712f25f7ef5c0037eab484a22008c896)
=> [8.x] Consider CommonCatQueryParameters to validate query parameters (#3260)

.gitattributes, compiler/src/steps/validate-rest-spec.ts, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts
(cherry picked from commit 7dc96a367df1eef610e42414659899d0983f609d)
=> [8.x] Ignore missing query parameters in fleet rest-api-spec (#3166)

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, specification/indices/put_index_template/IndicesPutIndexTemplateRequestExample1.yaml, specification/indices/put_mapping/indicesPutMappingRequestExample1.yaml, specification/indices/put_settings/IndicesPutSettingsRequestExample1.yaml, specification/indices/put_template/indicesPutTemplateRequestExample1.yaml, specification/indices/recovery/indicesRecoveryResponseExample1.yaml, specification/indices/resolve_cluster/ResolveClusterResponseExample1.yaml, specification/indices/resolve_index/indicesResolveResponseExample1.yaml, specification/indices/rollover/indicesRolloverRequestExample1.yaml, specification/indices/rollover/indicesRolloverResponseExample1.yaml, specification/indices/shrink/indicesShrinkRequestExample1.yaml, specification/indices/split/indicesSplitRequestExample1.yaml
- [Adds index API requests and responses - part 2 (#2993)](https://github.com/elastic/elasticsearch-specification/pull/2993)
=> [8.x] Adds index API requests and responses - part 2 (#2993)

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, specification/indices/put_index_template/IndicesPutIndexTemplateRequestExample1.yaml, specification/indices/put_mapping/indicesPutMappingRequestExample1.yaml, specification/indices/put_settings/IndicesPutSettingsRequestExample1.yaml, specification/indices/put_template/indicesPutTemplateRequestExample1.yaml, specification/indices/recovery/indicesRecoveryResponseExample1.yaml, specification/indices/resolve_cluster/ResolveClusterResponseExample1.yaml, specification/indices/resolve_index/indicesResolveResponseExample1.yaml, specification/indices/rollover/indicesRolloverRequestExample1.yaml, specification/indices/rollover/indicesRolloverResponseExample1.yaml, specification/indices/shrink/indicesShrinkRequestExample1.yaml, specification/indices/split/indicesSplitRequestExample1.yaml
- [Adds index API requests and responses - part 2 (#2993)](https://github.com/elastic/elasticsearch-specification/pull/2993)
=> [8.17] Adds index API requests and responses - part 2 (#2993)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/indices/clear_cache/IndicesIndicesClearCacheRequest.ts, specification/indices/clone/IndicesCloneRequest.ts, specification/indices/close/CloseIndexRequest.ts, specification/indices/disk_usage/IndicesDiskUsageRequest.ts, specification/indices/downsample/Request.ts, specification/indices/field_usage_stats/IndicesFieldUsageStatsRequest.ts, specification/indices/flush/IndicesFlushRequest.ts, specification/indices/forcemerge/IndicesForceMergeRequest.ts, specification/indices/promote_data_stream/IndicesPromoteDataStreamRequest.ts, specification/indices/put_template/IndicesPutTemplateRequest.ts, specification/indices/recovery/IndicesRecoveryRequest.ts, specification/indices/reload_search_analyzers/ReloadSearchAnalyzersRequest.ts, specification/indices/resolve_cluster/ResolveClusterRequest.ts, specification/indices/segments/IndicesSegmentsRequest.ts, specification/indices/shard_stores/IndicesShardStoresRequest.ts, specification/indices/shrink/IndicesShrinkRequest.ts, specification/indices/split/IndicesSplitRequest.ts, specification/indices/stats/IndicesStatsRequest.ts, specification/indices/unfreeze/IndicesUnfreezeRequest.ts
- [[DOCS] Edit index operation summaries (#3268)](https://github.com/elastic/elasticsearch-specification/pull/3268)
=> [8.x] [DOCS] Edit index operation summaries (#3268)

output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/ccr/delete_auto_follow_pattern/DeleteAutoFollowPatternRequest.ts, specification/ccr/follow/CreateFollowIndexRequest.ts, specification/ccr/follow_info/FollowInfoRequest.ts, specification/ccr/follow_stats/FollowIndexStatsRequest.ts, specification/ccr/forget_follower/ForgetFollowerIndexRequest.ts, specification/ccr/get_auto_follow_pattern/GetAutoFollowPatternRequest.ts, specification/ccr/pause_auto_follow_pattern/PauseAutoFollowPatternRequest.ts, specification/ccr/pause_follow/PauseFollowIndexRequest.ts, specification/ccr/put_auto_follow_pattern/PutAutoFollowPatternRequest.ts, specification/ccr/resume_auto_follow_pattern/ResumeAutoFollowPatternRequest.ts, specification/ccr/resume_follow/ResumeFollowIndexRequest.ts, specification/ccr/stats/CcrStatsRequest.ts, specification/ccr/unfollow/UnfollowIndexRequest.ts
- [[DOCS] Edit CCR operation summaries (#3266)](https://github.com/elastic/elasticsearch-specification/pull/3266)
=> [8.x] [DOCS] Edit CCR operation summaries (#3266)

output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/bulk/BulkRequest.ts, specification/_json_spec/bulk.json
Depends on https://github.com/elastic/elasticsearch/pull/118415. Unlike the Elasticsearch pull request, it can be backported, because the `type` parameter is only used by v7 clients.
=> Fix validation errors for bulk API

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_types/common.ts, specification/ml/_types/Analysis.ts, specification/ml/_types/Bucket.ts, specification/ml/_types/Datafeed.ts, specification/ml/_types/DataframeAnalytics.ts, specification/ml/_types/Detector.ts, specification/ml/_types/DiscoveryNode.ts, specification/ml/_types/Job.ts, specification/ml/_types/Model.ts, specification/ml/_types/TrainedModel.ts, specification/ml/_types/inference.ts, specification/ml/get_trained_models/MlGetTrainedModelRequest.ts, specification/ml/info/types.ts, specification/ml/post_data/MlPostJobDataResponse.ts, specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts, specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsResponse.ts, specification/ml/put_datafeed/MlPutDatafeedRequest.ts, specification/ml/put_job/MlPutJobRequest.ts, specification/ml/update_job/MlUpdateJobRequest.ts
References for the fixes:
The only thins missing server-side proof is `ignore_throttled` as query parameter in `MlPutJobRequest`, I couldn't find it in parent classes either, so I'm trusting the validation on that one.
=> Fix most ML APIs

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/license/delete/DeleteLicenseRequest.ts, specification/license/get/GetLicenseRequest.ts, specification/license/get_basic_status/GetBasicLicenseStatusRequest.ts, specification/license/get_trial_status/GetTrialLicenseStatusRequest.ts, specification/license/post/PostLicenseRequest.ts, specification/license/post_start_basic/StartBasicLicenseRequest.ts, specification/license/post_start_trial/StartTrialLicenseRequest.ts
This PR edits the summaries and descriptions in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-license based on information from https://www.elastic.co/guide/en/elasticsearch/reference/master/licensing-apis.html
=> [DOCS] Edit licensing API summaries

docs/overlays/elasticsearch-openapi-overlays.yaml
This PR fixes the branch information in the introductory content for the OpenAPI document.
It ultimately appears in https://www.elastic.co/docs/api/doc/elasticsearch/v8#topic-documentation-source-and-versions
=> [DOCS] Update branch information in overlay

compiler/src/steps/validate-model.ts, output/schema/validation-errors.json
This PR fixes a few issues in the specification validation code. Every commit fixes a different issue:
* fix validation of generic parameters in type aliases
* adding the `void` and `binary` builtin types
* allow union types to have generic parameters
=> Fix spec validator bugs

compiler/src/steps/validate-model.ts, output/schema/validation-errors.json
- [Fix spec validator bugs (#3295)](https://github.com/elastic/elasticsearch-specification/pull/3295)
=> [8.x] Fix spec validator bugs (#3295)

compiler/src/steps/validate-model.ts, output/schema/validation-errors.json
- [Fix spec validator bugs (#3295)](https://github.com/elastic/elasticsearch-specification/pull/3295)
=> [8.17] Fix spec validator bugs (#3295)

.github/workflows/update-rest-api-json.yml
Example failure:https://github.com/elastic/elasticsearch-specification/actions/runs/12289629442/job/34298075094
=> Fix update-rest-api-spec for 7.17 branch

output/openapi/elasticsearch-openapi.json, specification/migration/deprecations/DeprecationInfoRequest.ts, specification/migration/get_feature_upgrade_status/GetFeatureUpgradeStatusRequest.ts, specification/migration/post_feature_upgrade/PostFeatureUpgradeRequest.ts
This PR edits the migration API summaries (https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-migration) based on information from https://www.elastic.co/guide/en/elasticsearch/reference/master/migration-api.html
=> [DOCS] Edit migration summaries

output/openapi/elasticsearch-openapi.json, specification/migration/deprecations/DeprecationInfoRequest.ts, specification/migration/get_feature_upgrade_status/GetFeatureUpgradeStatusRequest.ts, specification/migration/post_feature_upgrade/PostFeatureUpgradeRequest.ts
- [[DOCS] Edit migration summaries (#3298)](https://github.com/elastic/elasticsearch-specification/pull/3298)
=> [8.x] [DOCS] Edit migration summaries (#3298)

output/openapi/elasticsearch-openapi.json, specification/ml/info/MlInfoRequest.ts, specification/ml/validate_detector/MlValidateDetectorRequest.ts
This PR edits some machine learning API summaries (https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-ml) based on https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-apis.html
FYI After https://github.com/elastic/elasticsearch-specification/issues/3300 is fixed any of these operations that have visibility set to "private" will not be included in the OpenAPI document.
=> [DOCS] Edit machine learning summaries

output/openapi/elasticsearch-openapi.json, specification/monitoring/bulk/BulkMonitoringRequest.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/3226, https://github.com/elastic/elasticsearch-specification/issues/3300
This PR edits the monitoring API summaries (https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-monitoring) and copies the "visibility=private" from the JSON spec so that it can be properly excluded from the OpenAPI document.
=> [DOCS] Fix monitoring operation summary and visibility

output/openapi/elasticsearch-openapi.json, specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts, specification/shutdown/get_node/ShutdownGetNodeRequest.ts, specification/shutdown/put_node/ShutdownPutNodeRequest.ts
This PR edits the node lifecycle APIs (https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-shutdown) based on the information in https://www.elastic.co/guide/en/elasticsearch/reference/current/node-lifecycle-api.html
=> [DOCS] Edit node lifecycle summaries

output/openapi/elasticsearch-openapi.json, specification/searchable_snapshots/cache_stats/Request.ts, specification/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheRequest.ts, specification/searchable_snapshots/mount/SearchableSnapshotsMountRequest.ts, specification/searchable_snapshots/stats/SearchableSnapshotsStatsRequest.ts
This PR edits the searchable snapshot summaries and descriptions in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-searchable_snapshots based on https://www.elastic.co/guide/en/elasticsearch/reference/master/searchable-snapshots-apis.html
=> [DOCS] Edit searchable snapshot summaries

output/openapi/elasticsearch-openapi.json, specification/rollup/delete_job/DeleteRollupJobRequest.ts, specification/rollup/get_jobs/GetRollupJobRequest.ts, specification/rollup/get_rollup_caps/GetRollupCapabilitiesRequest.ts, specification/rollup/get_rollup_index_caps/GetRollupIndexCapabilitiesRequest.ts, specification/rollup/put_job/CreateRollupJobRequest.ts, specification/rollup/rollup_search/RollupSearchRequest.ts, specification/rollup/start_job/StartRollupJobRequest.ts, specification/rollup/stop_job/StopRollupJobRequest.ts
This PR edits the rollup APIs in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-rollup based on the information from https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-apis.html
The extra content copied into the description of the "delete a rollup job" API looks like this in Bump.sh:
=> [DOCS] Edits rollup summaries

output/openapi/elasticsearch-openapi.json, specification/transform/upgrade_transforms/UpgradeTransformsRequest.ts, specification/xpack/info/XPackInfoRequest.ts, specification/xpack/usage/XPackUsageRequest.ts
This API updates https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-xpack based on information from https://www.elastic.co/guide/en/elasticsearch/reference/master/info-api.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/usage-api.html
It also edits the "upgrade transforms" API based on information from https://www.elastic.co/guide/en/elasticsearch/reference/master/upgrade-transforms.html
=> [DOCS] Edit usage and info API summaries

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/tasks/_types/TaskInfo.ts, specification/tasks/cancel/CancelTasksRequest.ts, specification/tasks/get/GetTaskRequest.ts, specification/tasks/list/ListTasksRequest.ts
This PR edits the task management APIs https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-tasks based on information from https://www.elastic.co/guide/en/elasticsearch/reference/master/tasks.html
=> [DOCS] Edit task management summaries

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/watcher/ack_watch/WatcherAckWatchRequest.ts, specification/watcher/activate_watch/WatcherActivateWatchRequest.ts, specification/watcher/deactivate_watch/DeactivateWatchRequest.ts, specification/watcher/delete_watch/DeleteWatchRequest.ts, specification/watcher/execute_watch/WatcherExecuteWatchRequest.ts, specification/watcher/get_watch/GetWatchRequest.ts, specification/watcher/put_watch/WatcherPutWatchRequest.ts, specification/watcher/query_watches/WatcherQueryWatchesRequest.ts, specification/watcher/start/WatcherStartRequest.ts, specification/watcher/stats/WatcherStatsRequest.ts, specification/watcher/stop/WatcherStopRequest.ts
This PR edits the Watcher APIs (https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-watcher) based on the information in https://www.elastic.co/guide/en/elasticsearch/reference/master/watcher-api.html
It also adds a link and description to the "Watcher" tag and edits some of the other tag links for consistency.
=> [DOCS] Edit the Watcher summaries and descriptions

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/tasks/_types/TaskInfo.ts, specification/tasks/cancel/CancelTasksRequest.ts, specification/tasks/get/GetTaskRequest.ts, specification/tasks/list/ListTasksRequest.ts
- [[DOCS] Edit task manager summaries (#3343)](https://github.com/elastic/elasticsearch-specification/pull/3343)
=> [8.x] [DOCS] Edit task manager summaries (#3343)

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/watcher/ack_watch/WatcherAckWatchRequest.ts, specification/watcher/activate_watch/WatcherActivateWatchRequest.ts, specification/watcher/deactivate_watch/DeactivateWatchRequest.ts, specification/watcher/delete_watch/DeleteWatchRequest.ts, specification/watcher/execute_watch/WatcherExecuteWatchRequest.ts, specification/watcher/get_watch/GetWatchRequest.ts, specification/watcher/put_watch/WatcherPutWatchRequest.ts, specification/watcher/query_watches/WatcherQueryWatchesRequest.ts, specification/watcher/start/WatcherStartRequest.ts, specification/watcher/stats/WatcherStatsRequest.ts, specification/watcher/stop/WatcherStopRequest.ts
- [[DOCS] Edit the Watcher summaries and descriptions (#3345)](https://github.com/elastic/elasticsearch-specification/pull/3345)
=> [8.x] [DOCS] Edit the Watcher summaries and descriptions (#3345)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/eql/search/EqlSearchRequest.ts
Add spec for EQL `allow_partial_search_results` and for `allow_partial_search_results` parameters.
These allow EQL queries to keep running in case of shard failures.
Relates to https://github.com/elastic/elasticsearch/pull/116388
=> Add spec for EQL allow_partial_search_results

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_spec_utils/behaviors.ts, specification/cat/aliases/CatAliasesRequest.ts, specification/cat/allocation/CatAllocationRequest.ts, specification/cat/component_templates/CatComponentTemplatesRequest.ts, specification/cat/master/CatMasterRequest.ts, specification/cat/nodeattrs/CatNodeAttributesRequest.ts, specification/cat/pending_tasks/CatPendingTasksRequest.ts, specification/cat/plugins/CatPluginsRequest.ts, specification/cat/segments/CatSegmentsRequest.ts, specification/cat/templates/CatTemplatesRequest.ts, specification/cat/thread_pool/CatThreadPoolRequest.ts
- [&quot;local&quot; parameter only in compatible cat requests (#3096)](https://github.com/elastic/elasticsearch-specification/pull/3096)
=> [8.x] "local" parameter only in compatible cat requests (#3096)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_spec_utils/behaviors.ts, specification/cat/aliases/CatAliasesRequest.ts, specification/cat/allocation/CatAllocationRequest.ts, specification/cat/component_templates/CatComponentTemplatesRequest.ts, specification/cat/master/CatMasterRequest.ts, specification/cat/nodeattrs/CatNodeAttributesRequest.ts, specification/cat/pending_tasks/CatPendingTasksRequest.ts, specification/cat/plugins/CatPluginsRequest.ts, specification/cat/segments/CatSegmentsRequest.ts, specification/cat/templates/CatTemplatesRequest.ts, specification/cat/thread_pool/CatThreadPoolRequest.ts
- [&quot;local&quot; parameter only in compatible cat requests (#3096)](https://github.com/elastic/elasticsearch-specification/pull/3096)
=> [8.17] "local" parameter only in compatible cat requests (#3096)

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/ingest/_types/Database.ts
We merged https://github.com/elastic/elasticsearch-specification/pull/3107 which adds a class extending a container, which java doesn't support. I could add an exception in the generator, but since it's only two fields I'd prefer writing the extended class definition.
=> avoiding container extension

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/indices/delete_data_stream/IndicesDeleteDataStreamRequest.ts, specification/indices/downsample/Request.ts, specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleRequest.ts, specification/indices/promote_data_stream/IndicesPromoteDataStreamRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
This PR adds `@doc_tag data stream` to some APIs to align with the grouping in https://www.elastic.co/guide/en/elasticsearch/reference/master/data-stream-apis.html
=> [DOCS] Update tag for data stream APIs

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/connector/_types/Connector.ts, specification/connector/update_features/ConnectorUpdateFeaturesRequest.ts, specification/connector/update_features/ConnectorUpdateFeaturesResponse.ts
This PR adds a specification to match https://www.elastic.co/guide/en/elasticsearch/reference/master/update-connector-features-api.html
=> Add specification for update connector features

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/connector/sync_job_check_in/SyncJobCheckInRequest.ts, specification/connector/sync_job_check_in/SyncJobCheckInResponse.ts
This PR adds a specification to align with https://www.elastic.co/guide/en/elasticsearch/reference/master/check-in-connector-sync-job-api.html
=> Add specification for check in connector sync job

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/text_structure/_types/Structure.ts, specification/text_structure/find_field_structure/FindFieldStructureRequest.ts, specification/text_structure/find_field_structure/FindFieldStructureResponse.ts, specification/text_structure/find_message_structure/FindMessageStructureRequest.ts, specification/text_structure/find_message_structure/FindMessageStructureResponse.ts, specification/text_structure/find_structure/FindStructureRequest.ts, specification/text_structure/find_structure/FindStructureResponse.ts
This PR adds specifications based on the following documentation:
- https://www.elastic.co/guide/en/elasticsearch/reference/master/find-field-structure.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/find-message-structure.html
=> Add find field structure and find messages structure APIs

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/indices/delete_data_stream/IndicesDeleteDataStreamRequest.ts, specification/indices/downsample/Request.ts, specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleRequest.ts, specification/indices/promote_data_stream/IndicesPromoteDataStreamRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
- [[DOCS] Update tag for data stream APIs (#3369)](https://github.com/elastic/elasticsearch-specification/pull/3369)
=> [8.x] [DOCS] Update tag for data stream APIs (#3369)

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/connector/sync_job_claim/SyncJobClaimRequest.ts, specification/connector/sync_job_claim/SyncJobClaimResponse.ts
This PR adds a specification to align with https://www.elastic.co/guide/en/elasticsearch/reference/master/claim-connector-sync-job-api.html
=> Add specification for claim connector sync job

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/tasks/_types/TaskInfo.ts, specification/tasks/cancel/CancelTasksRequest.ts, specification/tasks/get/GetTaskRequest.ts, specification/tasks/list/ListTasksRequest.ts
- [[DOCS] Edit task manager summaries (#3343)](https://github.com/elastic/elasticsearch-specification/pull/3343)
=> [Backport 8.17] [DOCS] Edit task manager summaries (#3343)

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/watcher/ack_watch/WatcherAckWatchRequest.ts, specification/watcher/activate_watch/WatcherActivateWatchRequest.ts, specification/watcher/deactivate_watch/DeactivateWatchRequest.ts, specification/watcher/delete_watch/DeleteWatchRequest.ts, specification/watcher/execute_watch/WatcherExecuteWatchRequest.ts, specification/watcher/get_watch/GetWatchRequest.ts, specification/watcher/put_watch/WatcherPutWatchRequest.ts, specification/watcher/query_watches/WatcherQueryWatchesRequest.ts, specification/watcher/start/WatcherStartRequest.ts, specification/watcher/stats/WatcherStatsRequest.ts, specification/watcher/stop/WatcherStopRequest.ts
- [[DOCS] Edit the Watcher summaries and descriptions (#3345)](https://github.com/elastic/elasticsearch-specification/pull/3345)
=> [Backport 8.17] [DOCS] Edit the Watcher summaries and descriptions (#3345)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/indices/delete_data_stream/IndicesDeleteDataStreamRequest.ts, specification/indices/downsample/Request.ts, specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleRequest.ts, specification/indices/promote_data_stream/IndicesPromoteDataStreamRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
- [[DOCS] Update tag for data stream APIs (#3369)](https://github.com/elastic/elasticsearch-specification/pull/3369)
=> [Backport 8.17] [DOCS] Update tag for data stream APIs (#3369)

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/connector/sync_job_claim/SyncJobClaimRequest.ts, specification/connector/sync_job_claim/SyncJobClaimResponse.ts
- [Add specification for claim connector sync job (#3366)](https://github.com/elastic/elasticsearch-specification/pull/3366)
=> [Backport 8.17] Add specification for claim connector sync job (#3366)

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/connector/sync_job_error/SyncJobErrorRequest.ts, specification/connector/sync_job_error/SyncJobErrorResponse.ts
- [Add specification for set connector sync job error (#3367)](https://github.com/elastic/elasticsearch-specification/pull/3367)
=> [Backport 8.17] Add specification for set connector sync job error (#3367)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/eql/_types/EqlSearchResponseBase.ts
Adding shard_failures to the EQL response specification
Related to https://github.com/elastic/elasticsearch/pull/116388 
Follow-up to https://github.com/elastic/elasticsearch-specification/pull/3342
=> Add shard_failures to EQL response spec

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, package-lock.json, specification/eql/_types/EqlSearchResponseBase.ts, specification/eql/search/EqlSearchRequest.ts
(cherry picked from commit 5987f79aed121f3657fc75769e494b26404d512b)
=> [8.x] Add allow_partial_search_results and shard_failures to EQL (#3342)

output/openapi/elasticsearch-openapi.json, specification/ingest/_types/Database.ts, specification/ingest/delete_ip_location_database/DeleteIpLocationDatabaseRequest.ts, specification/ingest/get_ip_location_database/GetIpLocationDatabaseRequest.ts, specification/ingest/put_geoip_database/PutGeoipDatabaseRequest.ts, specification/ingest/put_ip_location_database/PutIpLocationDatabaseRequest.ts
This PR edits some summaries and descriptions in the ingest APIs based on information derived from https://www.elastic.co/guide/en/elasticsearch/reference/master/delete-ip-location-database-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/get-ip-location-database-api.html, and https://www.elastic.co/guide/en/elasticsearch/reference/master/put-ip-location-database-api.html.
NOTE: https://www.elastic.co/guide/en/elasticsearch/reference/master/put-geoip-database-api.html exists only in the "deleted pages" section of the Elasticsearch Guide, so I'm assuming it will eventually be deprecated and removed from the specifications but that doesn't seem to have happened yet.
=> [DOCS] Edit ingest ip_location summaries

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/_types/mapping/Property.ts, specification/_types/mapping/complex.ts
It was added in 8.13, and made visible in our tests by an unrelated `get_document_template` YAML test: https://github.com/elastic/elasticsearch/compare/c662aecac3bbef1abcfb801a6a0b8326c3dfba0d...43e6fad99cfa6010f620ad2c39db93ea724a18f6. (Which means this can be tested with `make api=cluster.get_component_template branch=main`.)
=> Add passthrough mapping type

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, package-lock.json, specification/_types/mapping/Property.ts, specification/_types/mapping/complex.ts
- [Add passthrough mapping type (#3404)](https://github.com/elastic/elasticsearch-specification/pull/3404)
Closes https://github.com/elastic/elasticsearch-specification/pull/3408
=> [8.x] Add passthrough mapping type (#3404)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, output/typescript/types.ts, specification/security/_types/Privileges.ts, specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesResponse.ts
- [Change &#x60;Indices&#x60; -&gt; &#x60;IndexName[]&#x60; (#3016)](https://github.com/elastic/elasticsearch-specification/pull/3016)
=> [8.x] Change `Indices` -> `IndexName[]` (#3016)

specification/security/_types/Privileges.ts, specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesResponse.ts, specification/security/put_role/SecurityPutRoleRequest.ts
- [Fix &#x60;RemoteClusterPrivilege&#x60; availability (#3145)](https://github.com/elastic/elasticsearch-specification/pull/3145)
=> [8.x] Fix `RemoteClusterPrivilege` availability (#3145)

docs/doc-comments-guide.md
- [Update doc comments guidelines (#3037)](https://github.com/elastic/elasticsearch-specification/pull/3037)
=> [8.x] Update doc comments guidelines (#3037)

specification/indices/_types/DataStreamLifecycle.ts, specification/indices/get_data_lifecycle/IndicesGetDataLifecycleResponse.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
- [Improve &#x60;DataStreamLifecycle&#x60; definitions (and related) (#3039)](https://github.com/elastic/elasticsearch-specification/pull/3039)
=> [8.x] Improve `DataStreamLifecycle` definitions (and related) (#3039)

specification/ccr/follow/CreateFollowIndexRequest.ts, specification/ccr/follow_info/types.ts
- [Add missing fields to &#x60;CreateFollowIndexRequest&#x60; (#3042)](https://github.com/elastic/elasticsearch-specification/pull/3042)
=> [8.x] Add missing fields to `CreateFollowIndexRequest` (#3042)

specification/search_application/_types/SearchApplication.ts, specification/search_application/_types/SearchApplicationParameters.ts, specification/search_application/_types/SearchApplicationTemplate.ts, specification/search_application/get/SearchApplicationsGetResponse.ts, specification/search_application/put/SearchApplicationsPutRequest.ts
- [Improve &#x60;SearchApplication&#x60; definition (and related) (#3040)](https://github.com/elastic/elasticsearch-specification/pull/3040)
=> [8.x] Improve `SearchApplication` definition (and related) (#3040)

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/search_application/render_query/SearchApplicationsRenderQueryRequest.ts, specification/search_application/render_query/SearchApplicationsRenderQueryRequestExample1.yaml, specification/search_application/render_query/SearchApplicationsRenderQueryResponse.ts, specification/search_application/render_query/SearchApplicationsRenderQueryResponseExample1.yaml
- [Add search_application.render_query (#3401)](https://github.com/elastic/elasticsearch-specification/pull/3401)
=> [8.x] Add search_application.render_query (#3401)

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/search_application/render_query/SearchApplicationsRenderQueryRequest.ts, specification/search_application/render_query/SearchApplicationsRenderQueryRequestExample1.yaml, specification/search_application/render_query/SearchApplicationsRenderQueryResponse.ts, specification/search_application/render_query/SearchApplicationsRenderQueryResponseExample1.yaml
- [Add search_application.render_query (#3401)](https://github.com/elastic/elasticsearch-specification/pull/3401)
=> [8.17] Add search_application.render_query (#3401)

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/license/get/GetLicenseResponseExample1.yaml, specification/license/get_basic_status/GetBasicLicenseStatusResponseExample1.yaml, specification/license/get_trial_status/GetTrialLicenseStatusResponseExample1.yaml, specification/license/post/PostLicenseRequestExample1.yaml, specification/license/post/PostLicenseResponseExample1.yaml, specification/license/post_start_basic/StartBasicLicenseResponseExample1.yaml, specification/license/post_start_trial/StartTrialLicenseRequest.ts, specification/license/post_start_trial/StartTrialLicenseResponseExample1.yaml
- [Add examples to licensing APIs (#3420)](https://github.com/elastic/elasticsearch-specification/pull/3420)
=> [8.x] Add examples to licensing APIs (#3420)

compiler/src/model/utils.ts, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/search_application/delete/SearchApplicationsDeleteRequest.ts, specification/search_application/get/SearchApplicationGetResponseExample1.yaml, specification/search_application/get/SearchApplicationsGetRequest.ts, specification/search_application/get_behavioral_analytics/BehavioralAnalyticsGetResponseExample1.yaml, specification/search_application/list/SearchApplicationsListRequest.ts, specification/search_application/list/SearchApplicationsListResponseExample1.yaml, specification/search_application/put/SearchApplicationPutRequestExample1.yaml, specification/search_application/put/SearchApplicationsPutRequest.ts, specification/search_application/search/SearchApplicationsSearchRequestExample1.yaml
- [[DOCS] Add behavioral analytics and search application examples (#3392)](https://github.com/elastic/elasticsearch-specification/pull/3392)
=> [8.x] [DOCS] Add behavioral analytics and search application examples (#3392)

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, specification/license/get/GetLicenseResponseExample1.yaml, specification/license/get_basic_status/GetBasicLicenseStatusResponseExample1.yaml, specification/license/get_trial_status/GetTrialLicenseStatusResponseExample1.yaml, specification/license/post/PostLicenseRequestExample1.yaml, specification/license/post/PostLicenseResponseExample1.yaml, specification/license/post_start_basic/StartBasicLicenseResponseExample1.yaml, specification/license/post_start_trial/StartTrialLicenseRequest.ts, specification/license/post_start_trial/StartTrialLicenseResponseExample1.yaml
- [Add examples to licensing APIs (#3420)](https://github.com/elastic/elasticsearch-specification/pull/3420)
=> [8.17] Add examples to licensing APIs (#3420)

compiler/src/model/utils.ts, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/search_application/delete/SearchApplicationsDeleteRequest.ts, specification/search_application/get/SearchApplicationGetResponseExample1.yaml, specification/search_application/get/SearchApplicationsGetRequest.ts, specification/search_application/get_behavioral_analytics/BehavioralAnalyticsGetResponseExample1.yaml, specification/search_application/list/SearchApplicationsListRequest.ts, specification/search_application/list/SearchApplicationsListResponseExample1.yaml, specification/search_application/put/SearchApplicationPutRequestExample1.yaml, specification/search_application/put/SearchApplicationsPutRequest.ts, specification/search_application/search/SearchApplicationsSearchRequestExample1.yaml
- [[DOCS] Add behavioral analytics and search application examples (#3392)](https://github.com/elastic/elasticsearch-specification/pull/3392)
=> [8.17] [DOCS] Add behavioral analytics and search application examples (#3392)

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/schema/schema-serverless.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/search_application/post_behavioral_analytics_event/BehavioralAnalyticsEventPostRequest.ts, specification/search_application/post_behavioral_analytics_event/BehavioralAnalyticsEventPostRequestExample1.yaml, specification/search_application/post_behavioral_analytics_event/BehavioralAnalyticsEventPostResponse.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/3377, https://github.com/elastic/elasticsearch-specification/issues/2482
This PR adds a specification so that we can retire https://www.elastic.co/guide/en/elasticsearch/reference/master/post-analytics-collection-event.html
=> Add specification for post event to an analytics collection

.github/workflows/check-backport-labels.yml
If no backport is needed, we must apply skip-backport to pass CI.
And yes, this pull request must not be backported. :)
=> Enforce backport label

specification/ml/validate/MlValidateJobRequest.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/3300
The  `_ml/anomaly_detectors/_validate` [endpoint](https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-ml-validate) is currently appearing in the `machine learning` group instead of the `machine learning anomaly detection` group and is missing a summary.
When the referenced issue is fixed, it should not be published but until then I've fixed the doc tag and summary.
=> Add summary and tag to ml.validate

specification/indices/downsample/RequestExample1.yaml, specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleResponseExample1.yaml, specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleResponseExample2.yaml, specification/indices/get_data_lifecycle/IndicesGetDataLifecycleResponseExample1.yaml
This PR copies examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/data-stream-apis.html
=> Add datastream API examples

output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/migration/deprecations/DeprecationInfoRequest.ts, specification/migration/deprecations/DeprecationInfoResponse.ts, specification/migration/deprecations/DeprecationInfoResponseExample1.yaml, specification/migration/deprecations/types.ts, specification/migration/get_feature_upgrade_status/GetFeatureUpgradeStatusRequest.ts, specification/migration/get_feature_upgrade_status/GetFeatureUpgradeStatusResponseExample1.yaml, specification/migration/post_feature_upgrade/PostFeatureUpgradeRequest.ts, specification/migration/post_feature_upgrade/PostFeatureUpgradeResponseExample1.yaml
This PR copies examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/migration-api-deprecation.html
=> Add migration API examples

output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts, specification/shutdown/delete_node/ShutdownDeleteNodeResponseExample1.yaml, specification/shutdown/get_node/ShutdownGetNodeRequest.ts, specification/shutdown/get_node/ShutdownGetNodeResponseExample1.yaml, specification/shutdown/put_node/ShutdownPutNodeRequest.ts, specification/shutdown/put_node/ShutdownPutNodeRequestExample1.yaml
This PR copies examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/node-lifecycle-api.html
=> Add shutdown API examples

compiler/src/model/utils.ts, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/query_rules/_types/QueryRuleset.ts, specification/query_rules/delete_rule/QueryRuleDeleteRequest.ts, specification/query_rules/delete_ruleset/QueryRulesetDeleteRequest.ts, specification/query_rules/get_rule/QueryRuleGetRequest.ts, specification/query_rules/get_rule/QueryRuleGetResponseExample1.yaml, specification/query_rules/get_ruleset/QueryRulesetGetRequest.ts, specification/query_rules/get_ruleset/QueryRulesetGetResponseExample1.yaml, specification/query_rules/list_rulesets/QueryRulesetListRequest.ts, specification/query_rules/list_rulesets/QueryRulesetListResponseExample1.yaml, specification/query_rules/list_rulesets/types.ts, specification/query_rules/put_rule/QueryRulePutRequest.ts, specification/query_rules/put_rule/QueryRulePutRequestExample1.yaml, specification/query_rules/put_ruleset/QueryRulesetPutRequest.ts, specification/query_rules/put_ruleset/QueryRulesetPutRequestExample1.yaml, specification/query_rules/test/QueryRulesetTestRequest.ts, specification/query_rules/test/QueryRulesetTestRequestExample1.yaml, specification/query_rules/test/QueryRulesetTestResponseExample1.yaml
This PR copies examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/query-rules-apis.html
=> Add query rule API examples

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/connector/sync_job_update_stats/SyncJobUpdateStatsRequest.ts, specification/connector/sync_job_update_stats/SyncJobUpdateStatsResponse.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/3377
This PR adds a specification to match https://www.elastic.co/guide/en/elasticsearch/reference/master/set-connector-sync-job-stats-api.html
=> Add specification for set connector sync job stats

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_types/query_dsl/abstractions.ts, specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts, specification/ml/put_datafeed/MlPutDatafeedRequest.ts, specification/ml/put_job/MlPutJobRequest.ts
- [Add missing default ML query descriptions (#2917)](https://github.com/elastic/elasticsearch-specification/pull/2917)
=> [8.x] Add missing default ML query descriptions (#2917)

output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/searchable_snapshots/cache_stats/Request.ts, specification/searchable_snapshots/cache_stats/examples/response/ResponseExample1.yaml, specification/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheRequest.ts, specification/searchable_snapshots/mount/SearchableSnapshotsMountRequest.ts, specification/searchable_snapshots/mount/examples/request/SearchableSnapshotsMountSnapshotRequestExample1.yaml, specification/searchable_snapshots/stats/SearchableSnapshotsStatsRequest.ts
This PR copies examples and descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/master/searchable-snapshots-apis.html.
It also adds `doc_id` values in preparation for redirects.
=> Add searchable snapshot API examples

output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/searchable_snapshots/cache_stats/Request.ts, specification/searchable_snapshots/cache_stats/examples/response/ResponseExample1.yaml, specification/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheRequest.ts, specification/searchable_snapshots/mount/SearchableSnapshotsMountRequest.ts, specification/searchable_snapshots/mount/examples/request/SearchableSnapshotsMountSnapshotRequestExample1.yaml, specification/searchable_snapshots/stats/SearchableSnapshotsStatsRequest.ts
- [Add search snapshot API examples (#3459)](https://github.com/elastic/elasticsearch-specification/pull/3459)
=> [8.x] Add search snapshot API examples (#3459)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/schema-serverless.json, specification/security/query_role/QueryRolesRequest.ts
Marks [Query Role API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-query-role.html) as public in Serverless and generates related specification.
Relates to elastic/elasticsearch#118798
=> Mark query roles API public in Serverless

output/openapi/elasticsearch-openapi.json, specification/text_structure/find_field_structure/FindFieldStructureRequest.ts, specification/text_structure/find_field_structure/examples/response/FindFieldStructureResponseExample1.yaml, specification/text_structure/find_message_structure/FindMessageStructureRequest.ts, specification/text_structure/find_message_structure/examples/request/FindMessageStructureRequestExample1.yaml, specification/text_structure/find_message_structure/examples/response/FindMessageStructureResponseExample1.yaml, specification/text_structure/find_structure/FindStructureRequest.ts, specification/text_structure/find_structure/FindStructureResponse.ts, specification/text_structure/find_structure/examples/request/FindStructureRequestExample1.yaml, specification/text_structure/find_structure/examples/response/FindStructureResponseExample1.yaml, specification/text_structure/test_grok_pattern/TestGrokPatternRequest.ts, specification/text_structure/test_grok_pattern/examples/request/TestGrokPatternRequestExample1.yaml, specification/text_structure/test_grok_pattern/examples/response/TestGrokPatternResponseExample1.yaml
This PR copies examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/text-structure-apis.html
It also edits some descriptions and adds missing `doc_id` values.
=> Add text structure API examples

compiler/src/model/utils.ts, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/synonyms/_types/SynonymRule.ts, specification/synonyms/_types/SynonymsUpdateResult.ts, specification/synonyms/delete_synonym/SynonymsDeleteRequest.ts, specification/synonyms/delete_synonym_rule/SynonymRuleDeleteRequest.ts, specification/synonyms/delete_synonym_rule/examples/response/SynonymRuleDeleteResponseExample1.yaml, specification/synonyms/get_synonym/SynonymsGetRequest.ts, specification/synonyms/get_synonym/SynonymsGetResponse.ts, specification/synonyms/get_synonym/examples/response/SynonymsGetResponseExample1.yaml, specification/synonyms/get_synonym_rule/SynonymRuleGetRequest.ts, specification/synonyms/get_synonym_rule/examples/response/SynonymRuleGetResponseExample1.yaml, specification/synonyms/get_synonyms_sets/SynonymsSetsGetRequest.ts, specification/synonyms/get_synonyms_sets/SynonymsSetsGetResponse.ts, specification/synonyms/get_synonyms_sets/examples/response/SynonymsSetsGetResponseExample1.yaml, specification/synonyms/put_synonym/SynonymsPutRequest.ts, specification/synonyms/put_synonym/examples/400_response/SynonymsPutRequestExample1.yaml, specification/synonyms/put_synonym/examples/400_response/SynonymsPutResponseExample1.yaml, specification/synonyms/put_synonym_rule/SynonymRulePutRequest.ts, specification/synonyms/put_synonym_rule/examples/request/SynonymRulePutRequestExample1.yaml, specification/synonyms/put_synonym_rule/examples/response/SynonymRuleResponseExample1.yaml
This PR copies the examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/synonyms-apis.html
It also adds the missing `doc_id` values and edits some descriptions.
=> Add synonym API examples

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/watcher/get_settings/WatcherGetSettingsRequest.ts, specification/watcher/get_settings/WatcherGetSettingsResponse.ts, specification/watcher/get_settings/examples/200_response/WatcherGetSettingsResponseExample1.yaml, specification/watcher/update_settings/WatcherUpdateSettingsRequest.ts, specification/watcher/update_settings/WatcherUpdateSettingsResponse.ts, specification/watcher/update_settings/examples/request/WatcherUpdateSettingsRequestExample1.yaml
Relates to https://github.com/elastic/elasticsearch-specification/issues/3377
This PR adds two missing specifications based on information in https://www.elastic.co/guide/en/elasticsearch/reference/master/watcher-api-get-settings.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/watcher-api-update-settings.html
=> Add watcher.get_settings and watcher.update_settings

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/watcher/get_settings/WatcherGetSettingsRequest.ts, specification/watcher/get_settings/WatcherGetSettingsResponse.ts, specification/watcher/get_settings/examples/200_response/WatcherGetSettingsResponseExample1.yaml, specification/watcher/update_settings/WatcherUpdateSettingsRequest.ts, specification/watcher/update_settings/WatcherUpdateSettingsResponse.ts, specification/watcher/update_settings/examples/request/WatcherUpdateSettingsRequestExample1.yaml
- [Add watcher.get_settings and watcher.update_settings (#3397)](https://github.com/elastic/elasticsearch-specification/pull/3397)
=> [8.x] Add watcher.get_settings and watcher.update_settings (#3397)

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/watcher/get_settings/WatcherGetSettingsRequest.ts, specification/watcher/get_settings/WatcherGetSettingsResponse.ts, specification/watcher/get_settings/examples/200_response/WatcherGetSettingsResponseExample1.yaml, specification/watcher/update_settings/WatcherUpdateSettingsRequest.ts, specification/watcher/update_settings/WatcherUpdateSettingsResponse.ts, specification/watcher/update_settings/examples/request/WatcherUpdateSettingsRequestExample1.yaml
- [Add watcher.get_settings and watcher.update_settings (#3397)](https://github.com/elastic/elasticsearch-specification/pull/3397)
=> [8.17] Add watcher.get_settings and watcher.update_settings (#3397)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_types/query_dsl/abstractions.ts, specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts, specification/ml/put_datafeed/MlPutDatafeedRequest.ts, specification/ml/put_job/MlPutJobRequest.ts
- [Add missing default ML query descriptions (#2917)](https://github.com/elastic/elasticsearch-specification/pull/2917)
=> [8.17] Add missing default ML query descriptions (#2917)

output/openapi/elasticsearch-openapi.json, specification/_doc_ids/table.csv, specification/searchable_snapshots/cache_stats/Request.ts, specification/searchable_snapshots/cache_stats/examples/response/ResponseExample1.yaml, specification/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheRequest.ts, specification/searchable_snapshots/mount/SearchableSnapshotsMountRequest.ts, specification/searchable_snapshots/mount/examples/request/SearchableSnapshotsMountSnapshotRequestExample1.yaml, specification/searchable_snapshots/stats/SearchableSnapshotsStatsRequest.ts
- [Add search snapshot API examples (#3459)](https://github.com/elastic/elasticsearch-specification/pull/3459)
=> [8.17] Add search snapshot API examples (#3459)

output/openapi/elasticsearch-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/security/_types/SecuritySettings.ts, specification/security/get_settings/SecurityGetSettingsRequest.ts, specification/security/get_settings/SecurityGetSettingsResponse.ts, specification/security/update_settings/SecurityUpdateSettingsRequest.ts, specification/security/update_settings/SecurityUpdateSettingsResponse.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/3377
This PR adds two missing specifications based on information in https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-update-settings.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-get-settings.html
=> Add security.update_settings and security.get_settings

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/cat/component_templates/types.ts
https://github.com/elastic/elasticsearch/pull/119920 added YAML tests for this API, which uncovered that [ComponentTemplate.version()](https://github.com/elastic/elasticsearch/blob/0a98bf8e68e678a159c904203c040b848ce92a3c/server/src/main/java/org/elasticsearch/rest/action/cat/RestCatComponentTemplateAction.java#L100) can [be null](https://github.com/elastic/elasticsearch/blob/0a98bf8e68e678a159c904203c040b848ce92a3c/server/src/main/java/org/elasticsearch/cluster/metadata/ComponentTemplate.java#L107-L110).
=> Allow null version in cat component templates API

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/bulk/BulkRequest.ts, specification/_global/bulk/BulkResponse.ts, specification/_global/bulk/examples/request/BulkRequestExample1.yaml, specification/_global/bulk/examples/request/BulkRequestExample2.yaml, specification/_global/bulk/examples/request/BulkRequestExample3.yaml, specification/_global/bulk/examples/request/BulkRequestExample4.yaml, specification/_global/bulk/examples/response/BulkResponseExample1.yaml, specification/_global/bulk/examples/response/BulkResponseExample2.yaml, specification/_global/bulk/examples/response/BulkResponseExample3.yaml, specification/_global/bulk/types.ts, specification/_global/clear_scroll/ClearScrollRequest.ts, specification/_global/clear_scroll/ClearScrollResponse.ts, specification/_global/clear_scroll/examples/request/ClearScrollRequestExample1.yaml, specification/_global/close_point_in_time/ClosePointInTimeRequest.ts, specification/_global/close_point_in_time/ClosePointInTimeResponse.ts, specification/_global/close_point_in_time/examples/200_response/ClosePointInTimeResponseExample1.yaml, specification/_global/close_point_in_time/examples/request/ClosePointInTimeRequestExample1.yaml, specification/_global/count/CountRequest.ts, specification/_global/count/examples/200_response/CountResponseExample1.yaml, specification/_global/count/examples/request/CountRequestExample1.yaml, specification/_types/Errors.ts, specification/_types/Stats.ts
This PR adds examples and edits descriptions derived from https://www.elastic.co/guide/en/elasticsearch/reference/master/search-count.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/point-in-time-api.html#close-point-in-time-api, https://www.elastic.co/guide/en/elasticsearch/reference/master/clear-scroll-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-bulk.html
=> Add bulk, count, clear scroll, close PIT examples

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/bulk/BulkRequest.ts, specification/_global/bulk/BulkResponse.ts, specification/_global/bulk/examples/request/BulkRequestExample1.yaml, specification/_global/bulk/examples/request/BulkRequestExample2.yaml, specification/_global/bulk/examples/request/BulkRequestExample3.yaml, specification/_global/bulk/examples/request/BulkRequestExample4.yaml, specification/_global/bulk/examples/response/BulkResponseExample1.yaml, specification/_global/bulk/examples/response/BulkResponseExample2.yaml, specification/_global/bulk/examples/response/BulkResponseExample3.yaml, specification/_global/bulk/types.ts, specification/_global/clear_scroll/ClearScrollRequest.ts, specification/_global/clear_scroll/ClearScrollResponse.ts, specification/_global/clear_scroll/examples/request/ClearScrollRequestExample1.yaml, specification/_global/close_point_in_time/ClosePointInTimeRequest.ts, specification/_global/close_point_in_time/ClosePointInTimeResponse.ts, specification/_global/close_point_in_time/examples/200_response/ClosePointInTimeResponseExample1.yaml, specification/_global/close_point_in_time/examples/request/ClosePointInTimeRequestExample1.yaml, specification/_global/count/CountRequest.ts, specification/_global/count/examples/200_response/CountResponseExample1.yaml, specification/_global/count/examples/request/CountRequestExample1.yaml, specification/_types/Errors.ts, specification/_types/Stats.ts, specification/security/activate_user_profile/examples/request/RequestExample1.yaml
- [Add bulk, count, clear scroll, close PIT examples (#3510)](https://github.com/elastic/elasticsearch-specification/pull/3510)
=> [8.17] Add bulk, count, clear scroll, close PIT examples (#3510)

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/esql.async_query_delete.json, specification/esql/_types/QueryParameters.ts, specification/esql/async_query/AsyncQueryRequest.ts, specification/esql/async_query/AsyncQueryResponse.ts, specification/esql/async_query/examples/request/AsyncQueryRequestExample1.yaml, specification/esql/async_query_delete/AsyncQueryDeleteRequest.ts, specification/esql/async_query_delete/AsyncQueryDeleteResponse.ts, specification/esql/async_query_get/AsyncQueryGetRequest.ts, specification/esql/async_query_get/AsyncQueryGetResponse.ts, specification/esql/query/QueryRequest.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/3377, https://github.com/elastic/elasticsearch/pull/119472
This PR adds three missing specifications based on https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-async-query-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-async-query-get-api.html, and https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-async-query-delete-api.html
=> Add esql.async_query, esql.async_query_get, esql.async_query_delete

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/esql.async_query_delete.json, specification/esql/_types/QueryParameters.ts, specification/esql/async_query/AsyncQueryRequest.ts, specification/esql/async_query/AsyncQueryResponse.ts, specification/esql/async_query/examples/request/AsyncQueryRequestExample1.yaml, specification/esql/async_query_delete/AsyncQueryDeleteRequest.ts, specification/esql/async_query_delete/AsyncQueryDeleteResponse.ts, specification/esql/async_query_get/AsyncQueryGetRequest.ts, specification/esql/async_query_get/AsyncQueryGetResponse.ts, specification/esql/query/QueryRequest.ts
- [Add esql.async_query, esql.async_query_get, esql.async_query_delete (#3398)](https://github.com/elastic/elasticsearch-specification/pull/3398)
=> [8.17] Add esql.async_query, esql.async_query_get, esql.async_query_delete (#3398)

specification/_global/create/CreateRequest.ts, specification/_global/index/IndexRequest.ts, specification/_global/reindex/ReindexRequest.ts
I noticed that when finally implementing Markdown in my client.
=> Fix Markdown header syntax

specification/_types/Knn.ts, specification/_types/Retriever.ts
- [Add availability annotation to rescore_vector (#3560)](https://github.com/elastic/elasticsearch-specification/pull/3560)
=> [8.x] Add availability annotation to rescore_vector (#3560)

docs/overlays/elasticsearch-openapi-overlays.yaml
There was a redundant line in one of the overlay files, likely caused by a merge conflict.
It was caught by our linter, so this is just a quick fix.
=> Fix typo in overlays

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_global/open_point_in_time/examples/response/OpenPointInTimeResponseExample1.yaml, specification/_global/search/SearchRequest.ts, specification/_global/search/SearchResponse.ts, specification/_global/search/examples/200_response/SearchResponseExample1.yaml, specification/_global/search/examples/request/SearchRequestExample1.yaml, specification/_global/search/examples/request/SearchRequestExample2.yaml, specification/_global/search/examples/request/SearchRequestExample3.yaml, specification/_types/query_dsl/abstractions.ts
This PR adds descriptions and examples from https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html
=> Add examples to search and open PIT APIs

output/openapi/elasticsearch-openapi.json, specification/migrate/cancel_reindex/MigrateCancelReindexRequest.ts, specification/migrate/create_from/MigrateCreateFromRequest.ts, specification/migrate/get_reindex_status/MigrateGetReindexStatusRequest.ts, specification/migrate/reindex/MigrateReindexRequest.ts
Relates to https://github.com/elastic/elasticsearch-specification/pull/3518, https://github.com/elastic/elasticsearch/pull/118291
This PR addresses the following errors returned from `make lint-docs-errs`:
```
18464:11  error  operation-tag-defined  Operation tags must be defined in global tags.                            paths./_migration/reindex/{index}/_cancel.post.tags[0]
18499:11  error  operation-tag-defined  Operation tags must be defined in global tags.                            paths./_create_from/{source}/{dest}.put.tags[0]
18524:11  error  operation-tag-defined  Operation tags must be defined in global tags.                            paths./_create_from/{source}/{dest}.post.tags[0]
18551:11  error  operation-tag-defined  Operation tags must be defined in global tags. …
```
=> Update doc tag for migration APIs

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_global/open_point_in_time/examples/response/OpenPointInTimeResponseExample1.yaml, specification/_global/search/SearchRequest.ts, specification/_global/search/SearchResponse.ts, specification/_global/search/examples/200_response/SearchResponseExample1.yaml, specification/_global/search/examples/request/SearchRequestExample1.yaml, specification/_global/search/examples/request/SearchRequestExample2.yaml, specification/_global/search/examples/request/SearchRequestExample3.yaml, specification/_types/query_dsl/abstractions.ts
- [Add examples to search and open PIT APIs (#3561)](https://github.com/elastic/elasticsearch-specification/pull/3561)
=> [8.x] Add examples to search and open PIT APIs (#3561)

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/migrate/create_from/MigrateCreateFromRequest.ts
Add a new parameter to the request body for `_create_from/{source}/{dest}` api.
Parameter is an optional boolean called `remove_index_blocks`.
Add to ES in https://github.com/elastic/elasticsearch/pull/120548/files
=> Add remove_index_blocks param to _create_from

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/xpack/info/examples/response/XPackInfoResponseExample1.yaml, specification/xpack/info/types.ts, specification/xpack/usage/XPackUsageResponse.ts, specification/xpack/usage/examples/response/XPackUsageResponseExample1.yaml, specification/xpack/usage/types.ts
This reflects the changes in
https://github.com/elastic/elasticsearch/pull/119890.
=> Remove frozen indices telemetry from spec

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/delete_by_query/DeleteByQueryRequest.ts, specification/_global/delete_by_query/DeleteByQueryResponse.ts, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample1.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample2.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample3.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample4.yaml, specification/_global/delete_by_query/examples/response/DeleteByQueryResponseExample1.yaml, specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts, specification/tasks/get/examples/200_response/GetTaskResponseExample1.yaml, specification/tasks/get/examples/200_response/GetTaskResponseExample2.yaml
This PR adds examples copied from https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-delete-by-query.html. It also edits the descriptions and adds missing `@doc_id` details.
=> [DOCS] Add examples for delete by query API

output/openapi/elasticsearch-openapi.json, specification/indices/cancel_migrate_reindex/MigrateCancelReindexRequest.ts, specification/indices/create_from/MigrateCreateFromRequest.ts, specification/indices/get_migrate_reindex_status/MigrateGetReindexStatusRequest.ts, specification/indices/migrate_reindex/MigrateReindexRequest.ts
This PR edits the operation summaries for the new APIs that appear in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-migration
That first line needs to be short and sweet and start with a verb to align with all the other titles that appear in the left-hand navigation. There's some more guidance in https://github.com/elastic/elasticsearch-specification/blob/main/docs/doc-comments-guide.md with more to come soon.
NOTE: I have not drafted descriptions for all the request body and response body properties, but those should eventually be added for clarity and completeness too.
=> Edit migration reindexing summaries

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/delete_by_query/DeleteByQueryRequest.ts, specification/_global/delete_by_query/DeleteByQueryResponse.ts, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample1.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample2.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample3.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample4.yaml, specification/_global/delete_by_query/examples/response/DeleteByQueryResponseExample1.yaml, specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts, specification/tasks/get/examples/200_response/GetTaskResponseExample1.yaml, specification/tasks/get/examples/200_response/GetTaskResponseExample2.yaml
- [Add examples for delete by query API (#3574)](https://github.com/elastic/elasticsearch-specification/pull/3574)
=> [8.17] Add examples for delete by query API (#3574)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/delete_by_query/DeleteByQueryRequest.ts, specification/_global/delete_by_query/DeleteByQueryResponse.ts, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample1.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample2.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample3.yaml, specification/_global/delete_by_query/examples/request/DeleteByQueryRequestExample4.yaml, specification/_global/delete_by_query/examples/response/DeleteByQueryResponseExample1.yaml, specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts, specification/tasks/get/examples/200_response/GetTaskResponseExample1.yaml, specification/tasks/get/examples/200_response/GetTaskResponseExample2.yaml
- [Add examples for delete by query API (#3574)](https://github.com/elastic/elasticsearch-specification/pull/3574)
=> [8.x] Add examples for delete by query API (#3574)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_global/open_point_in_time/examples/response/OpenPointInTimeResponseExample1.yaml, specification/_global/search/SearchRequest.ts, specification/_global/search/SearchResponse.ts, specification/_global/search/examples/200_response/SearchResponseExample1.yaml, specification/_global/search/examples/request/SearchRequestExample1.yaml, specification/_global/search/examples/request/SearchRequestExample2.yaml, specification/_global/search/examples/request/SearchRequestExample3.yaml, specification/_types/query_dsl/abstractions.ts
- [Add examples to search and open PIT APIs (#3561)](https://github.com/elastic/elasticsearch-specification/pull/3561)
=> [8.17] Add examples to search and open PIT APIs (#3561)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_global/scripts_painless_execute/ExecutePainlessScriptRequest.ts, specification/_global/scripts_painless_execute/examples/request/ExecutePainlessScriptRequestExample1.yaml, specification/_global/scripts_painless_execute/examples/request/ExecutePainlessScriptRequestExample2.yaml, specification/_global/scripts_painless_execute/examples/request/ExecutePainlessScriptRequestExample3.yaml, specification/_global/scripts_painless_execute/examples/response/ExecutePainlessScriptResponseExample1.yaml, specification/_global/scripts_painless_execute/examples/response/ExecutePainlessScriptResponseExample2.yaml, specification/_global/scripts_painless_execute/examples/response/ExecutePainlessScriptResponseExample3.yaml, specification/_global/scripts_painless_execute/types.ts
This PR copies descriptions and examples from https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-execute-api.html to augment what's in https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-scripts-painless-execute. It also adds an enumeration for the `context`.
=> Augment painless execute API

Makefile
This will help us see issues like https://github.com/elastic/elasticsearch-specification/pull/3564 much sooner.
=> Run docs lint as part of CI

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts
Partially reverts #3199. This bug was also shipped to 8.17 in #3200 and 8.x in #3201, which explains the backports. The same revert is done on the rest-api-spec side in https://github.com/elastic/elasticsearch/pull/120781.
The Kibana team, specifically @lukasolson, noticed this. Thank you!
=> Add back keep_alive to async_search.submit

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/Property.ts, specification/_types/mapping/specialized.ts
It's still [undocumented](https://github.com/elastic/elasticsearch/issues/115964) but is [implemented here](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/mapper-counted-keyword/src/main/java/org/elasticsearch/xpack/countedkeyword/CountedKeywordFieldMapper.java). [YAML tests are here](https://github.com/elastic/elasticsearch/tree/main/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/counted_keyword).
I'm not implementing the aggregation yet, only the mapping type.
=> Add counted_keyword mapping type

specification/indices/create_from/MigrateCreateFromRequest.ts
In the `_create_from` API, the default value for the optional boolean parameter `remove_index_blocks` was changed from false to true. ES ticket: https://github.com/elastic/elasticsearch/pull/120643
=> Change default of _create_from remove_index_blocks param to true

Makefile
- [Run docs lint as part of CI (#3575)](https://github.com/elastic/elasticsearch-specification/pull/3575)
=> [8.x] Run docs lint as part of CI (#3575)

Makefile
- [Run docs lint as part of CI (#3575)](https://github.com/elastic/elasticsearch-specification/pull/3575)
=> [8.17] Run docs lint as part of CI (#3575)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/update_by_query/UpdateByQueryRequest.ts, specification/_global/update_by_query/UpdateByQueryResponse.ts, specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample1.yaml, specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample2.yaml, specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample3.yaml, specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample4.yaml, specification/_global/update_by_query_rethrottle/UpdateByQueryRethrottleRequest.ts
- [[DOCS] Add examples for update by query (#3597)](https://github.com/elastic/elasticsearch-specification/pull/3597)
=> [8.17] [DOCS] Add examples for update by query (#3597)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/Property.ts, specification/indices/_types/IndexSettings.ts
- [Support synthetic_source_keep and mapping.source.mode (#3596)](https://github.com/elastic/elasticsearch-specification/pull/3596)
=> [8.17] Support synthetic_source_keep and mapping.source.mode (#3596)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_global/explain/ExplainRequest.ts, specification/_global/explain/examples/request/ExplainRequestExample1.yaml, specification/_global/explain/examples/response/ExplainResponseExample1.yaml, specification/_global/mtermvectors/MultiTermVectorsRequest.ts, specification/_global/mtermvectors/examples/request/MultiTermVectorsRequestExample1.yaml, specification/_global/mtermvectors/examples/request/MultiTermVectorsRequestExample2.yaml, specification/_global/mtermvectors/examples/request/MultiTermVectorsRequestExample3.yaml, specification/_global/render_search_template/RenderSearchTemplateRequest.ts, specification/_global/render_search_template/examples/request/RenderSearchTemplateRequestExample1.yaml, specification/_global/search_shards/SearchShardsRequest.ts, specification/_global/search_shards/examples/response/SearchShardsResponseExample1.yaml, specification/_global/search_template/SearchTemplateRequest.ts, specification/_global/search_template/examples/request/SearchTemplateRequestExample1.yaml, specification/_global/termvectors/TermVectorsRequest.ts, specification/_global/termvectors/examples/request/TermVectorsRequestExample1.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample2.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample3.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample4.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample5.yaml, specification/_global/termvectors/examples/response/TermVectorsResponseExample1.yaml, specification/_global/termvectors/examples/response/TermVectorsResponseExample2.yaml, specification/_global/termvectors/examples/response/TermVectorsResponseExample3.yaml, specification/_global/termvectors/types.ts
This PR adds examples and descriptions copied from https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template-api.html,[https://www.elastic.co/guide/en/elasticsearch/reference/current/render-search-template-api.html,https://www.elastic.co/guide/en/elasticsearch/reference/current/search-shards.html, https://www.elastic.co/guide/en/elasticsearch/reference/current/search-explain.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-multi-termvectors.html, https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-termvectors.html
=> [DOCS] Add examples and descriptions for explain, termvector, search APIs

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, specification/_doc_ids/table.csv, specification/_global/delete_script/DeleteScriptRequest.ts, specification/_global/get_script/GetScriptRequest.ts, specification/_global/get_script_context/GetScriptContextRequest.ts, specification/_global/get_script_languages/GetScriptLanguagesRequest.ts, specification/_global/put_script/PutScriptRequest.ts, specification/_global/put_script/examples/request/PutScriptRequestExample1.yaml, specification/_global/put_script/examples/request/PutScriptRequestExample2.yaml, specification/_types/Scripting.ts
This PR copies examples and descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/current/get-script-contexts-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/current/get-script-languages-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/current/get-stored-script-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/current/delete-stored-script-api.html, https://www.elastic.co/guide/en/elasticsearch/reference/current/create-stored-script-api.html
=> [DOCS] Add examples and descriptions for script APIs

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/cluster/_types/ComponentTemplate.ts
`deprecated` was added by https://github.com/elastic/elasticsearch/pull/101148
=> Fix cluster.get_component_template API

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, specification/_doc_ids/table.csv, specification/_global/delete_script/DeleteScriptRequest.ts, specification/_global/get_script/GetScriptRequest.ts, specification/_global/get_script_context/GetScriptContextRequest.ts, specification/_global/get_script_languages/GetScriptLanguagesRequest.ts, specification/_global/put_script/PutScriptRequest.ts, specification/_global/put_script/examples/request/PutScriptRequestExample1.yaml, specification/_global/put_script/examples/request/PutScriptRequestExample2.yaml, specification/_types/Scripting.ts
- [[DOCS] Add examples and descriptions for script APIs (#3613)](https://github.com/elastic/elasticsearch-specification/pull/3613)
=> [8.17] [DOCS] Add examples and descriptions for script APIs (#3613)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_global/explain/ExplainRequest.ts, specification/_global/explain/examples/request/ExplainRequestExample1.yaml, specification/_global/explain/examples/response/ExplainResponseExample1.yaml, specification/_global/mtermvectors/MultiTermVectorsRequest.ts, specification/_global/mtermvectors/examples/request/MultiTermVectorsRequestExample1.yaml, specification/_global/mtermvectors/examples/request/MultiTermVectorsRequestExample2.yaml, specification/_global/mtermvectors/examples/request/MultiTermVectorsRequestExample3.yaml, specification/_global/render_search_template/RenderSearchTemplateRequest.ts, specification/_global/render_search_template/examples/request/RenderSearchTemplateRequestExample1.yaml, specification/_global/search_shards/SearchShardsRequest.ts, specification/_global/search_shards/examples/response/SearchShardsResponseExample1.yaml, specification/_global/search_template/SearchTemplateRequest.ts, specification/_global/search_template/examples/request/SearchTemplateRequestExample1.yaml, specification/_global/termvectors/TermVectorsRequest.ts, specification/_global/termvectors/examples/request/TermVectorsRequestExample1.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample2.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample3.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample4.yaml, specification/_global/termvectors/examples/request/TermVectorsRequestExample5.yaml, specification/_global/termvectors/examples/response/TermVectorsResponseExample1.yaml, specification/_global/termvectors/examples/response/TermVectorsResponseExample2.yaml, specification/_global/termvectors/examples/response/TermVectorsResponseExample3.yaml, specification/_global/termvectors/types.ts
- [[DOCS] Add examples and descriptions for explain, termvector, search APIs (#3614)](https://github.com/elastic/elasticsearch-specification/pull/3614)
=> [8.17] [DOCS] Add examples and descriptions for explain, termvector, search APIs (#3614)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/count/CountRequest.ts
Applies changes from https://github.com/elastic/elasticsearch/pull/120564: notes that you can use the `q` parameter or a query in the request body, but not both. Plus other incidental sprucing.
=> [DOCS] Clarify Count API query options

output/openapi/elasticsearch-openapi.json, specification/snapshot/_types/SnapshotRepository.ts
I found it by accidentally grepping for `server_default` in the `output` folder. This was added in https://github.com/elastic/elasticsearch-specification/pull/3462.
=> Fix server_default annotation

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, specification/_global/info/RootNodeInfoRequest.ts
This PR updates the overlay to pull examples into the OpenAPI document for the `_global` specifications.
=> [DOCS] Add overlays to pull in _global examples

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, specification/_global/info/RootNodeInfoRequest.ts
- [[DOCS] Add overlays to pull in _global examples (#3634)](https://github.com/elastic/elasticsearch-specification/pull/3634)
This PR must be merged after https://github.com/elastic/elasticsearch-specification/pull/3609
=> [8.x] [DOCS] Add overlays to pull in _global examples (#3634)

docs/overlays/elasticsearch-shared-overlays.yaml, specification/_global/exists/examples/xCodeSamples/DocumentExistsConsoleExample1.yaml, specification/_global/exists/examples/xCodeSamples/DocumentExistsCurlExample1.yaml, specification/_global/exists/examples/xCodeSamples/DocumentExistsJavaScriptExample1.yaml, specification/_global/exists/examples/xCodeSamples/DocumentExistsPythonExample1.yaml, specification/_global/exists/examples/xCodeSamples/DocumentExistsRubyExample1.yaml
This PR tests the addition of some `x-codeSamples` per https://docs.bump.sh/help/specification-support/doc-code-samples/ via an overlay for https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-exists
The examples are copied from https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html
The examples show up in a Bump.sh preview like this:
=> Add x-codeSamples to check document API

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/Binary.ts, specification/esql/async_query/AsyncQueryResponse.ts, specification/esql/async_query_get/AsyncQueryGetResponse.ts, specification/esql/query/QueryResponse.ts
The esql async API response format varies depending on the format chosen in the request, also it's not supported when using formats that are not json compatible (so it only supported by json, yaml, cbor, smile). The spec as it is only supports json results, so all the responses should be changed to a binary representation, and the clients will choose which to support. 
In the backports PR the package change for EsqlFormat will be reversed, as it is a breaking change that we can introduce in the next major.
=> Making async esql responses binary

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml
This PR adds the connector API examples to the OpenAPI document via overlays.
It also fixes some duplicate labels and incorrect entries (e.g. cat threadpool should not exist in Serverless) in the overlay files.
=> [DOCS] Add overlays for connector API examples

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/esql.async_query_stop.json, specification/esql/async_query_get/AsyncQueryGetResponse.ts, specification/esql/async_query_stop/AsyncQueryStopRequest.ts, specification/esql/async_query_stop/AsyncQueryStopResponse.ts
Update spec for:
* ESQL async `POST query/stop` API
* is_partial in ESQL query response
=> Update spec for ESQL async query stop

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/esql.async_query_stop.json, specification/esql/async_query_stop/AsyncQueryStopRequest.ts, specification/esql/async_query_stop/AsyncQueryStopResponse.ts
* Update spec for ESQL async query stop
(cherry picked from commit 585f69729291cfda4acb5c47a7466abe6c42e9c0)
=> Update spec for ESQL async query stop (#3643)

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, package-lock.json, specification/migration/deprecations/DeprecationInfoResponse.ts
We added a two new fields in the deprecation info api response in https://github.com/elastic/elasticsearch/pull/120505, namely `templates` and `ilm_policies`.
=> Add templates and ilm_policies to the Deprecation API response.

specification/eql/search/EqlSearchRequest.ts
Adding description and default values for EQL allow_partial_search_results and allow_partial_sequence_results
Wait for https://github.com/elastic/elasticsearch/pull/120887 before backporting
=> Add default values for EQL allow_partial_search_results and allow_partial_sequence_results

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/snapshot/repository_analyze/SnapshotAnalyzeRepositoryResponse.ts
We should avoid using the same name for different types
=> Remove duplicate name

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-openapi.json
- [[DOCS] Add overlays for connector API examples (#3644)](https://github.com/elastic/elasticsearch-specification/pull/3644)
=> [8.x] [DOCS] Add overlays for connector API examples (#3644)

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/_json_spec/indices.resolve_cluster.json, specification/cluster/remote_info/ClusterRemoteInfoRequest.ts, specification/cluster/remote_info/ClusterRemoteInfoResponse.ts, specification/indices/resolve_cluster/ResolveClusterRequest.ts, specification/indices/resolve_cluster/examples/200_response/ResolveClusterResponseExample2.yaml
- [[DOCS] Clarify remote/info and resolve/cluster descriptions (#3655)](https://github.com/elastic/elasticsearch-specification/pull/3655)
=> [8.x] [DOCS] Clarify remote/info and resolve/cluster descriptions (#3655)

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/cluster/remote_info/ClusterRemoteInfoResponse.ts
Relates to https://github.com/elastic/elasticsearch-specification/pull/3655
This PR updates our overlays to pick up the second example for the resolve cluster API and attaches them to where they now exist in the OpenAPI output (in the components section instead of the paths section).
It also fixes one description string.
=> [DOCS] Fix overlay for resolve cluster

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, specification/cluster/remote_info/ClusterRemoteInfoResponse.ts
- [[DOCS] Fix overlay for resolve cluster (#3670)](https://github.com/elastic/elasticsearch-specification/pull/3670)
=> [8.x] [DOCS] Fix overlay for resolve cluster (#3670)

docs/overlays/elasticsearch-openapi-overlays.yaml, output/openapi/elasticsearch-openapi.json, specification/cluster/remote_info/ClusterRemoteInfoResponse.ts
- [[DOCS] Fix overlay for resolve cluster (#3670)](https://github.com/elastic/elasticsearch-specification/pull/3670)
=> [8.18] [DOCS] Fix overlay for resolve cluster (#3670)

output/typescript/types.ts, specification/inference/_types/Results.ts
In https://github.com/elastic/elasticsearch/pull/120751, added `text_embedding_bits` as an output field to store binary embeddings from the Cohere inference API. Although the field name is different, the type is the same as `text_embedding_bytes` because Cohere returns binary embeddings encoded as bytes with `int8` precision.
=> [ML] Adding text embedding bit to inference result output 

output/typescript/types.ts, specification/_global/bulk/types.ts
As per:
* https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/bulk/BulkItemResponse.java
* https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/bulk/IndexDocFailureStoreStatus.java
=> Add failure_store enum to bulk responses

README.md
It may seem like a small change, but 0.39.1 was released more than three years ago.
=> Bump nvm version

output/typescript/types.ts, specification/_global/search/_types/hits.ts, specification/_types/common.ts, specification/esql/async_query/AsyncQueryRequest.ts, specification/esql/query/QueryRequest.ts
Some types like e.g. `TermQuery` have a shortcut to a property with the `FieldValue` type.
According to the specification, `FieldValue` was allowed to contain `UserDefinedValue`/`any`. This complicates deserialization in the shortcut property case since we can't simply rely on the JSON token type (`!= Object`) to know that we are handling a shortcut property. While this can be worked around, I still started to check, if `FieldValue` should even be supposed to contain non-scalar values.
@pquentin checked the validation results and found 3 issues:
1. ES|QL queries where params is typed as `FieldValue[]` but named parameters like `{"n1": 300}` are allowed.
2. [ignored_field_values](https://github.com/elastic/elasticsearch-specification/blob/41f2f0a0e1a4df480de14d2d0de5b72861c2f187/specificati …
=> Remove `UserDefinedValue` from `FieldValue`

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/inference/_types/Results.ts
When we call the inference rerank interface using the Elasticsearch Java client, we encountered the following error：
```
status: 200, [es/inference.inference] Failed to decode response
at co.elastic.clients.transport.ElasticsearchTransportBase.decodeTransportResponse(ElasticsearchTransportBase.java:404)
at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:363)
at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147)
at co.elastic.clients.elasticsearch.inference.ElasticsearchInferenceClient.inference(ElasticsearchInferenceClient.java:162)
at org.example.Main.main(Main.java:50)
Caused by: co.elastic.clients.json.JsonpMappingException: Error deserializing …
```
=> [ML]rename rerank score to relevance_score

docs/overlays/elasticsearch-shared-overlays.yaml
Follow up on https://github.com/elastic/elasticsearch-specification/pull/3721, because that info is [not visible currently](https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-connector-check-in)
=> [DOCS] Trim connector intro to make all relevant info visible

.github/validate-pr/index.js, .github/validate-pr/package.json
This is required as the types-validator package in clients-flight-recorder was migrated to ESM. The CI is currently broken.
=> Switch validate-pr to ESM

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/esql/async_query/AsyncQueryRequest.ts, specification/esql/async_query/examples/request/AsyncQueryRequestExample1.yaml, specification/esql/query/QueryRequest.ts, specification/esql/query/examples/request/QueryRequestExample1.yaml
- [Add missing &#x60;include_ccs_metadata&#x60; to ES|QL query endpoints (#3743)](https://github.com/elastic/elasticsearch-specification/pull/3743)
=> [8.17] Add missing `include_ccs_metadata` to ES|QL query endpoints (#3743)

.github/validate-pr/index.js, .github/validate-pr/package.json
- [Switch validate-pr to ESM (#3774)](https://github.com/elastic/elasticsearch-specification/pull/3774)
=> [8.17] Switch validate-pr to ESM (#3774)

.github/validate-pr/index.js, .github/validate-pr/package.json
- [Switch validate-pr to ESM (#3774)](https://github.com/elastic/elasticsearch-specification/pull/3774)
=> [8.18] Switch validate-pr to ESM (#3774)

.github/validate-pr/index.js, .github/validate-pr/package.json
- [Switch validate-pr to ESM (#3774)](https://github.com/elastic/elasticsearch-specification/pull/3774)
=> [8.x] Switch validate-pr to ESM (#3774)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/inference/_types/Services.ts
This PR adds the [`chunking_settings`](https://www.elastic.co/guide/en/elasticsearch/reference/8.17/infer-service-anthropic.html#infer-service-anthropic-api-request-body) parameter to the inference API spec. The parameter was introduced in 8.16.
=> [Inference API] Adds chunking_settings to PUT inference API

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
https://github.com/elastic/elasticsearch-specification/pull/3039 extracted DataStreamLifecycle to avoid copying its definition twice. However, it's a breaking change, affecting Kibana. Should we revert the refactoring? The downside is that any fixes will have to be made to the two versions, and we'll certainly forget.
=> Switch back to properties body in put_data_lifecycle request

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
- [Switch back to properties body in put_data_lifecycle request (#3787)](https://github.com/elastic/elasticsearch-specification/pull/3787)
=> [8.18] Switch back to properties body in put_data_lifecycle request (#3787)

.github/validate-pr/index.js, .github/validate-pr/package.json
This will backport the following commits from `main` to `8.16`:
- [Switch validate-pr to ESM (#3774)](https://github.com/elastic/elasticsearch-specification/pull/3774)
=> [8.16] Switch validate-pr to ESM (#3774)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_spec_utils/behaviors.ts, specification/cat/aliases/CatAliasesRequest.ts, specification/cat/allocation/CatAllocationRequest.ts, specification/cat/component_templates/CatComponentTemplatesRequest.ts, specification/cat/count/CatCountRequest.ts, specification/cat/fielddata/CatFielddataRequest.ts, specification/cat/health/CatHealthRequest.ts, specification/cat/indices/CatIndicesRequest.ts, specification/cat/master/CatMasterRequest.ts, specification/cat/nodeattrs/CatNodeAttributesRequest.ts, specification/cat/nodes/CatNodesRequest.ts, specification/cat/pending_tasks/CatPendingTasksRequest.ts, specification/cat/plugins/CatPluginsRequest.ts, specification/cat/recovery/CatRecoveryRequest.ts, specification/cat/repositories/CatRepositoriesRequest.ts, specification/cat/segments/CatSegmentsRequest.ts, specification/cat/shards/CatShardsRequest.ts, specification/cat/snapshots/CatSnapshotsRequest.ts, specification/cat/tasks/CatTasksRequest.ts, specification/cat/templates/CatTemplatesRequest.ts, specification/cat/thread_pool/CatThreadPoolRequest.ts
This required removing `h` and `s` from the base of cat APIs.
=> Fix property defined in an ancestor class errors

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts
- [Add back keep_alive to async_search.submit (#3601)](https://github.com/elastic/elasticsearch-specification/pull/3601)
=> [8.18] Add back keep_alive to async_search.submit (#3601)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts
- [Add back keep_alive to async_search.submit (#3601)](https://github.com/elastic/elasticsearch-specification/pull/3601)
=> [8.17] Add back keep_alive to async_search.submit (#3601)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_spec_utils/behaviors.ts, specification/cat/aliases/CatAliasesRequest.ts, specification/cat/allocation/CatAllocationRequest.ts, specification/cat/component_templates/CatComponentTemplatesRequest.ts, specification/cat/count/CatCountRequest.ts, specification/cat/fielddata/CatFielddataRequest.ts, specification/cat/health/CatHealthRequest.ts, specification/cat/indices/CatIndicesRequest.ts, specification/cat/master/CatMasterRequest.ts, specification/cat/nodeattrs/CatNodeAttributesRequest.ts, specification/cat/nodes/CatNodesRequest.ts, specification/cat/pending_tasks/CatPendingTasksRequest.ts, specification/cat/plugins/CatPluginsRequest.ts, specification/cat/recovery/CatRecoveryRequest.ts, specification/cat/repositories/CatRepositoriesRequest.ts, specification/cat/segments/CatSegmentsRequest.ts, specification/cat/shards/CatShardsRequest.ts, specification/cat/snapshots/CatSnapshotsRequest.ts, specification/cat/tasks/CatTasksRequest.ts, specification/cat/templates/CatTemplatesRequest.ts, specification/cat/thread_pool/CatThreadPoolRequest.ts
- [Fix property defined in an ancestor class errors (#3800)](https://github.com/elastic/elasticsearch-specification/pull/3800)
=> [8.x] Fix property defined in an ancestor class errors (#3800)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_spec_utils/behaviors.ts, specification/cat/aliases/CatAliasesRequest.ts, specification/cat/allocation/CatAllocationRequest.ts, specification/cat/component_templates/CatComponentTemplatesRequest.ts, specification/cat/count/CatCountRequest.ts, specification/cat/fielddata/CatFielddataRequest.ts, specification/cat/health/CatHealthRequest.ts, specification/cat/indices/CatIndicesRequest.ts, specification/cat/master/CatMasterRequest.ts, specification/cat/nodeattrs/CatNodeAttributesRequest.ts, specification/cat/nodes/CatNodesRequest.ts, specification/cat/pending_tasks/CatPendingTasksRequest.ts, specification/cat/plugins/CatPluginsRequest.ts, specification/cat/recovery/CatRecoveryRequest.ts, specification/cat/repositories/CatRepositoriesRequest.ts, specification/cat/segments/CatSegmentsRequest.ts, specification/cat/shards/CatShardsRequest.ts, specification/cat/snapshots/CatSnapshotsRequest.ts, specification/cat/tasks/CatTasksRequest.ts, specification/cat/templates/CatTemplatesRequest.ts, specification/cat/thread_pool/CatThreadPoolRequest.ts
- [Fix property defined in an ancestor class errors (#3800)](https://github.com/elastic/elasticsearch-specification/pull/3800)
=> [8.18] Fix property defined in an ancestor class errors (#3800)

specification/_json_spec/search_application.delete_behavioral_analytics.json, specification/_json_spec/search_application.get_behavioral_analytics.json, specification/_json_spec/search_application.post_behavioral_analytics_event.json, specification/_json_spec/search_application.put_behavioral_analytics.json, specification/search_application/delete_behavioral_analytics/BehavioralAnalyticsDeleteRequest.ts, specification/search_application/get_behavioral_analytics/BehavioralAnalyticsGetRequest.ts, specification/search_application/post_behavioral_analytics_event/BehavioralAnalyticsEventPostRequest.ts, specification/search_application/put_behavioral_analytics/BehavioralAnalyticsPutRequest.ts
Marks the Behavioral Analytics CRUD APIs as deprecated, to go along with https://github.com/elastic/elasticsearch/pull/122960 
See SEARCH-862 for more information.
=> Mark Behavioral Analytics CRUD APIs as deprecated in 9.0.0

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_json_spec/ml.start_trained_model_deployment.json, specification/ml/_types/TrainedModel.ts, specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentRequest.ts, specification/ml/update_trained_model_deployment/MlUpdateTrainedModelDeploymentRequest.ts
The `ml.start_trained_model_deployment` and `ml.update_trained_model_deployment` methods are outdated. Therefore, we currently use `transport.request` with manual type definitions: https://github.com/elastic/kibana/blob/main/x-pack/platform/plugins/shared/ml/server/lib/ml_client/ml_client.ts#L526
The API has been updated to correctly accept `adaptive_allocations` settings inside the request body.
=> [ML] Update start model deployment & update model deployment APIs

specification/cat/recovery/CatRecoveryRequest.ts
While it is redundant with the path part with the same name, it is indeed accepted.
=> Add missing index parameter to _cat/recovery

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/Errors.ts
`type` is currently required in `BulkIndexByScrollFailure`, but it's actually never serialized there, only inside the `cause` field, where we already have it correctly as a required field. 
Server code: [BulkByScrollResponse](https://github.com/elastic/elasticsearch/blob/22103de1504958a293291d9d7664de6ec2feb386/server/src/main/java/org/elasticsearch/index/reindex/BulkByScrollResponse.java#L36), [failures toXcontent](https://github.com/elastic/elasticsearch/blob/22103de1504958a293291d9d7664de6ec2feb386/server/src/main/java/org/elasticsearch/action/bulk/BulkItemResponse.java#L303), [Exception toXcontent ](https://github.com/elastic/elasticsearch/blob/22103de1504958a293291d9d7664de6ec2feb386/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L386) -> showing where `type` is.
=> Error type already in cause

specification/indices/put_mapping/IndicesPutMappingRequest.ts
As titled.
Related server test: https://github.com/elastic/elasticsearch/blob/f5e2a92a3171808bd163570c3e1546230ec7c5ac/server/src/test/java/org/elasticsearch/index/mapper/DynamicTemplatesTests.java?email_source=slack
Thanks @l-trotta for confirming.
Related to: https://github.com/elastic/elasticsearch-net/issues/7968
=> `IndicesPutMappingRequest.dynamic_templates` should not be "single or many"

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/dynamic-template.ts
Currently, in DynamicTemplate class, the "runtime" property has "Property" type.
This PR aims to fix that by referencing "RuntimeField" type.
=> fix 'runtime' property type in DynamicTemplate class

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/security/_types/Privileges.ts
Fixing an error introduced in https://github.com/elastic/elasticsearch-specification/pull/3841. `extends` should not be used for already existing classes which are not "base" classes (breaks the java client).
=> avoid extending non base class

catalog-info.yaml
Since we're testing against Kibana main, using 8.x branches is not going to work. If needed, in the future, we can test Kibana 8.x against branch 8.x of the Elasticsearch specification.
=> Disable Kibana checks for 8.x branches

README.md, docs/overlays/elasticsearch-shared-overlays.yaml, specification/_doc_ids/table.csv, specification/indices/migrate_to_data_stream/IndicesMigrateToDataStreamRequest.ts, specification/indices/modify_data_stream/IndicesModifyDataStreamRequest.ts, specification/indices/promote_data_stream/IndicesPromoteDataStreamRequest.ts, specification/indices/put_alias/IndicesPutAliasRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts, specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts, specification/indices/update_aliases/IndicesUpdateAliasesRequest.ts, specification/indices/validate_query/IndicesValidateQueryRequest.ts
- [Replace broken master links (#3858)](https://github.com/elastic/elasticsearch-specification/pull/3858)
NOTE: This PR has different URLs for the doc IDs, since they must point to the v8 APIs.
=> [8.x] Replace broken master links (#3858)

README.md
This PR adds an OpenAPI section to the readme, so that we can reference it from https://github.com/elastic/elasticsearch/blob/main/docs/README.md
=> Add OpenAPI steps to Readme.md

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/TypeMapping.ts, specification/_types/mapping/complex.ts
This fixes validation for `cluster.put_component_template`.
=> Support subobjects: auto

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_json_spec/ml.get_trained_models.json, specification/_json_spec/ml.infer_trained_model.json, specification/_json_spec/ml.stop_datafeed.json, specification/ml/get_trained_models/MlGetTrainedModelRequest.ts, specification/ml/infer_trained_model/MlInferTrainedModelRequest.ts
The path and options were deprecated in 8 for removal in 9. The corresponding Elasticsearch change is in https://github.com/elastic/elasticsearch/pull/124019
=> Remove deprecated ML path and options

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.watsonx.json, specification/inference/_types/Services.ts, specification/inference/put_watsonx/PutWatsonxRequest.ts, specification/inference/put_watsonx/PutWatsonxResponse.ts, specification/inference/put_watsonx/examples/request/InferenceRequestExample1.yaml
Relates to https://github.com/elastic/elasticsearch-specification/issues/3821, https://github.com/elastic/elasticsearch/pull/115088
This PR is an attempt to handle the Watsonx inference use case, with content derived from https://www.elastic.co/guide/en/elasticsearch/reference/current/infer-service-watsonx-ai.html
The following linting error occurs:
```
9040:5    warning  no-identical-paths             The path already exists which differs only by path parameter name(s): `/_inference/{task_type}/{inference_id}` and `/_inference/{task_type}/{watsonx_inference_id}`.
```
This is essentially because there are multiple paths that are interchangeable (since neither the task type nor the inference ID in the path are unique to each of these variations). We are currently treating that type of lint …
=> Draft Watsonx inference API

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.watsonx.json, specification/inference/_types/Services.ts, specification/inference/put_watsonx/PutWatsonxRequest.ts, specification/inference/put_watsonx/PutWatsonxResponse.ts, specification/inference/put_watsonx/examples/request/InferenceRequestExample1.yaml
- [Draft Watsonx inference API (#3866)](https://github.com/elastic/elasticsearch-specification/pull/3866)
=> [8.x] Draft Watsonx inference API (#3866)

README.md, docs/overlays/elasticsearch-shared-overlays.yaml, specification/_doc_ids/table.csv, specification/indices/migrate_to_data_stream/IndicesMigrateToDataStreamRequest.ts, specification/indices/modify_data_stream/IndicesModifyDataStreamRequest.ts, specification/indices/promote_data_stream/IndicesPromoteDataStreamRequest.ts, specification/indices/put_alias/IndicesPutAliasRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts, specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts, specification/indices/update_aliases/IndicesUpdateAliasesRequest.ts, specification/indices/validate_query/IndicesValidateQueryRequest.ts
- [Replace broken master links (#3858)](https://github.com/elastic/elasticsearch-specification/pull/3858)
NOTE: This PR has different URLs for the doc IDs, since they must point to the v8 APIs.  I have also updated the URLs in the overlays to use `8.18` instead of `8.x` too, since the former branch now exists.
=> [8.18] Replace broken master links (#3858)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.watsonx.json, specification/inference/_types/Services.ts, specification/inference/put_watsonx/PutWatsonxRequest.ts, specification/inference/put_watsonx/PutWatsonxResponse.ts, specification/inference/put_watsonx/examples/request/InferenceRequestExample1.yaml
- [Draft Watsonx inference API (#3866)](https://github.com/elastic/elasticsearch-specification/pull/3866)
=> [8.18] Draft Watsonx inference API (#3866)

output/openapi/elasticsearch-serverless-openapi.json, specification/indices/_types/IndexSettings.ts
Marking number_of_shards and number_of_replicas as not available in serverless mode.
=> correct availability

output/typescript/types.ts, specification/_types/mapping/core.ts
As added in https://github.com/elastic/elasticsearch/pull/71633.
Today, the code is in [DateFieldMapper.Builder](https://github.com/elastic/elasticsearch/blob/c702eb9efad65a09ae01fe049e314923934a18da/server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java#L262-L266) and [CONTENT_TYPE/DATE_NANOS_CONTENT_TYPE](https://github.com/elastic/elasticsearch/blob/c702eb9efad65a09ae01fe049e314923934a18da/server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java#L91-L92) suggests that it applies both to `date` and `date_nanos`.
This fixes the indices.get_index_template API.
=> Add index-time scripts to date properties

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/analysis/analyzers.ts, specification/_types/analysis/languages.ts
The "language" analyzer does not exist at least since Elasticsearch 8.
If I try to create this index:
``` json
PUT my_index
{
"settings": {
"analysis": {
"analyzer": {
"default": {
"type": "language",
"language": "french",
"stem_exclusion": ["some_token"]
}
}
}
}
}
```
I got this error:
``` json
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "Unknown analyzer type [language] for [default]"
}
],
"type": "illegal_argument_exception",
"reason": "Unknown analyzer type [language] for [default]"
},
"status": 400
}
```
That's why this PR aims to remove LanguageAnalyzer class in elasticsearch-specification.
=> remove LanguageAnalyzer

output/openapi/elasticsearch-openapi.json, output/typescript/types.ts, specification/simulate/ingest/SimulateIngestRequest.ts
A failure in the request converter integration tests led me to find this typo.
=> fix typo in `index_template_substitutions` body argument

specification/_types/mapping/TypeMapping.ts, specification/indices/put_mapping/IndicesPutMappingRequest.ts
As titled. Thanks for checking the server code @l-trotta .
=> Fix `dynamic_templates` type

specification/_json_spec/inference.stream_completion.json
Elasticsearch's description for the `inference.stream_completion` api is here: https://github.com/elastic/elasticsearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/inference.stream_completion.json#L5
This PR just aligns them to `Perform streaming completion inference`
=> [ML] Updating the streaming completion description to match what is in ES

output/typescript/types.ts, specification/security/_types/RoleMappingRule.ts
=> Improve `RoleMappingRule` definition

docs/overlays/elasticsearch-openapi-overlays.yaml
This PR fixes the following error that occurs when `make overlay-docs` runs:
```
Error: Error opening file "elasticsearch-specification/specification/inference/stream_inference/examples/request/StreamInferenceRequestExample1.yaml" 
›   ENOENT: no such file or directory...
```
I believe this is due to files that moved in https://github.com/elastic/elasticsearch-specification/pull/3545
This is the type of overlay fragility that will be fixed by https://github.com/elastic/elasticsearch-specification/pull/3737
=> Fix overlay for inference stream

specification/connector/update_filtering_validation/ConnectorUpdateFilteringValidationRequest.ts, specification/fleet/msearch/MultiSearchResponse.ts, specification/tsconfig.json
Level the imports declaration with the rest of the spec.
Makes the type tree compatible with the current `typescript-go` state for testing purposes.
=> Use path alias in imports

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.openai.json, specification/inference/_types/Services.ts, specification/inference/put_openai/PutOpenAiRequest.ts, specification/inference/put_openai/PutOpenAiResponse.ts, specification/inference/put_openai/examples/request/PutOpenAiRequestExample1.yaml, specification/inference/put_openai/examples/request/PutOpenAiRequestExample2.yaml, specification/inference/put_watsonx/PutWatsonxRequest.ts
- [Add OpenAI inference details (#3929)](https://github.com/elastic/elasticsearch-specification/pull/3929)
=> [8.x] Add OpenAI inference details (#3929)

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/core.ts
Backport https://github.com/elastic/elasticsearch-specification/commit/e4cedeed985b83c9bea600012d0201ae2ab38b2d from https://github.com/elastic/elasticsearch-specification/pull/3901.
=> [Backport 9.0] Add search_inference_id property

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/core.ts
Backport https://github.com/elastic/elasticsearch-specification/commit/e4cedeed985b83c9bea600012d0201ae2ab38b2d from https://github.com/elastic/elasticsearch-specification/pull/3901.
=> [Backport 8.17] Add search_inference_id property

.buildkite/kibana.sh, .buildkite/kibana.yml
This avoids relying on elasticsearch-js merges, which happens at most once per week.
=> Generate elasticsearch-js before Kibana type checks

output/openapi/elasticsearch-openapi.json, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/indices/_types/DataStream.ts
Relates to https://github.com/elastic/elasticsearch/pull/122486
Closes #3958
=> Add the index mode to the output of get-data-stream API.

output/typescript/types.ts, specification/nodes/_types/NodeReloadResult.ts
We had a redundant type in ReloadSecureSettingsResponse.ts, the [server response](https://github.com/elastic/elasticsearch/blob/7023fe994e38b91783f88e828257ce538bed9f82/server/src/main/java/org/elasticsearch/action/admin/cluster/node/reload/NodesReloadSecureSettingsResponse.java#L50) is actually simpler than the spec mapping.
=> Removing unnecessary union in node reload result

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/RuntimeFields.ts, specification/_types/mapping/geo.ts
* Runtime fields support `geo_shape` since https://github.com/elastic/elasticsearch/pull/100492 (Elasticsearch 8.12) and are tested in [130_geo_shape_runtime.yml](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/spatial/130_geo_shape_runtime.yml).
* `index: false` for `geo_shape` was added in https://github.com/elastic/elasticsearch/pull/94396 (Elasticsearch 8.8) and is tested in [110_geo_shape_parameters.yml ](https://github.com/elastic/elasticsearch/blob/a77bf7f1a6a5899c12a6b28c1f1d118289f84b14/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/spatial/110_geo_shape_parameters.yml#L19)
=> Fix indices.get_mapping API

output/openapi/elasticsearch-serverless-openapi.json, specification/indices/get_mapping/IndicesGetMappingRequest.ts
This was [deprecated in 7.8](https://github.com/elastic/elasticsearch/commit/0b041cccd894f01d723fb2979f70c1cf279700a6), but we don't copy this information from the JSON spec, which is a bug.
=> Deprecate local param in indices.get_mapping

specification/eql/search/EqlSearchRequest.ts
I missed that when merging https://github.com/elastic/elasticsearch-specification/pull/3817. Thanks @flobernd for noticing!
=> [9.0] Fix allow_partial_search_results default value

compiler/src/model/build-model.ts
As titled.
The `@codegen_name` tag for **response** value bodies was not correctly emitted to the `schema.json` before.
I took the corresponding code (including the assertion) from the **request** counterpart. It's debatable wether this should be a hard error or just a validation warning. The assertion is disabled for now, until all places with missing response value body tags are fixed.
=> Emit `codegen_name` for response value bodies

compiler/src/model/build-model.ts, output/openapi/elasticsearch-serverless-openapi.json
- [Emit `codegen_name` for response value bodies (#3953)](https://github.com/elastic/elasticsearch-specification/pull/3953)
=> [8.x] Emit `codegen_name` for response value bodies (#3953)

compiler/src/model/build-model.ts
- [Emit `codegen_name` for response value bodies (#3953)](https://github.com/elastic/elasticsearch-specification/pull/3953)
=> [8.18] Emit `codegen_name` for response value bodies (#3953)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_global/termvectors/TermVectorsRequest.ts, specification/esql/async_query/AsyncQueryRequest.ts, specification/security/oidc_logout/Request.ts
These fixes surfaced during my request converter testing.
- termvectors endpoint: several query parameters are also accepted as body parameters
- esql async_query endpoint: `wait_for_completion_timeout` is accepted also as a body parameter
- oidc_logout endpoint: the `access_token` parameter appears to be called `token` in this endpoint
=> Various schema fixes

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/indices/analyze/IndicesAnalyzeRequest.ts, specification/indices/clear_cache/IndicesClearCacheRequest.ts, specification/indices/exists_index_template/IndicesExistsIndexTemplateRequest.ts, specification/indices/field_usage_stats/IndicesFieldUsageStatsRequest.ts, specification/indices/put_settings/IndicesPutSettingsRequest.ts, specification/indices/reload_search_analyzers/ReloadSearchAnalyzersRequest.ts, specification/indices/rollover/IndicesRolloverRequest.ts, specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts, specification/indices/simulate_template/IndicesSimulateTemplateRequest.ts
The remaining `indices.put_template` error is on the rest-api-spec side.
=> Fix indices/ validation errors

compiler/run-validations.js
=> Fix cache on 'make validate'

compiler/src/model/build-model.ts
Reverts elastic/elasticsearch-specification#4008
As it's a breaking change, we're only going to do this in 9.0+
=> Revert "[8.18] Emit `codegen_name` for response value bodies (#3953)"

compiler/src/model/build-model.ts, output/openapi/elasticsearch-serverless-openapi.json
Reverts elastic/elasticsearch-specification#4007
As it's a breaking change, we're only going to do this in 9.0+
=> Revert "[8.x] Emit `codegen_name` for response value bodies (#3953)"

compiler/src/steps/validate-model.ts, output/schema/validation-errors.json
- [Stop reporting missing endpoints as errors (#4031)](https://github.com/elastic/elasticsearch-specification/pull/4031)
=> [8.x] Stop reporting missing endpoints as errors (#4031)

compiler/run-validations.js
I introduced this error in https://github.com/elastic/elasticsearch-specification/pull/4005. For some reason, it's not a parse error until the code is executed?
=> compiler: fix quote syntax

output/openapi/elasticsearch-serverless-openapi.json, specification/_global/delete_by_query/DeleteByQueryRequest.ts, specification/_global/update_by_query/UpdateByQueryRequest.ts
Hi, thanks for your work.
Based on this [issue](https://github.com/elastic/elasticsearch-py/issues/2813) I added the missing `from` documentation.
=> [DOCS] Add missing `from` documentation

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_jinaai.json, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_jinaai/PutJinaAiResponse.ts, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample1.yaml, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample2.yaml
Relates to https://github.com/elastic/elasticsearch-specification/issues/3821
This PR adds the JinaAI inference API details, derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-jinaai.html
=> Add JinaAI inference API details

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_hugging_face.json, specification/inference/put_hugging_face/PutHuggingFaceRequest.ts, specification/inference/put_hugging_face/PutHuggingFaceResponse.ts, specification/inference/put_hugging_face/examples/request/PutHuggingFaceRequestExample1.yaml
- [Add Hugging Face inference API details (#4029)](https://github.com/elastic/elasticsearch-specification/pull/4029)
=> [8.x] Add Hugging Face inference API details (#4029)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_googleaistudio.json, specification/inference/put_googleaistudio/PutGoogleAiStudioRequest.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioResponse.ts, specification/inference/put_googleaistudio/examples/request/PutGoogleAiStudioRequestExample1.yaml
Relates to https://github.com/elastic/elasticsearch-specification/issues/3821
This PR adds details for the Google AI Studio inference API, derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-google-ai-studio.html
=> Add Google AI Studio inference details

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_cohere.json, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_cohere/PutCohereResponse.ts, specification/inference/put_cohere/examples/request/PutCohereRequestExample1.yaml, specification/inference/put_cohere/examples/request/PutCohereRequestExample2.yaml
Adds details about the Cohere API, derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-cohere.html
=> Add Cohere inference API details

output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_jinaai.json, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_jinaai/PutJinaAiResponse.ts, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample1.yaml, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample2.yaml
- [Add JinaAI inference API details (#4030)](https://github.com/elastic/elasticsearch-specification/pull/4030)
=> [8.x] Add JinaAI inference API details (#4030)

output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_googlevertexai.json, specification/inference/put_googlevertexai/PutGoogleVertexAiRequest.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiResponse.ts, specification/inference/put_googlevertexai/examples/request/PutGoogleVertexAiRequestExample1.yaml, specification/inference/put_googlevertexai/examples/request/PutGoogleVertexAiRequestExample2.yaml
- [Add Google Vertex AI inference details (#4028)](https://github.com/elastic/elasticsearch-specification/pull/4028)
=> [8.x] Add Google Vertex AI inference details (#4028)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_hugging_face.json, specification/inference/put_hugging_face/PutHuggingFaceRequest.ts, specification/inference/put_hugging_face/PutHuggingFaceResponse.ts, specification/inference/put_hugging_face/examples/request/PutHuggingFaceRequestExample1.yaml
- [Add Hugging Face inference API details (#4029)](https://github.com/elastic/elasticsearch-specification/pull/4029)
=> [9.0] Add Hugging Face inference API details (#4029)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_hugging_face.json, specification/inference/put_hugging_face/PutHuggingFaceRequest.ts, specification/inference/put_hugging_face/PutHuggingFaceResponse.ts, specification/inference/put_hugging_face/examples/request/PutHuggingFaceRequestExample1.yaml
- [Add Hugging Face inference API details (#4029)](https://github.com/elastic/elasticsearch-specification/pull/4029)
=> [8.18] Add Hugging Face inference API details (#4029)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_jinaai.json, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_jinaai/PutJinaAiResponse.ts, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample1.yaml, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample2.yaml
- [Add JinaAI inference API details (#4030)](https://github.com/elastic/elasticsearch-specification/pull/4030)
=> [9.0] Add JinaAI inference API details (#4030)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, package-lock.json, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_jinaai.json, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_jinaai/PutJinaAiResponse.ts, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample1.yaml, specification/inference/put_jinaai/examples/request/PutJinaAiRequestExample2.yaml
- [Add JinaAI inference API details (#4030)](https://github.com/elastic/elasticsearch-specification/pull/4030)
=> [8.18] Add JinaAI inference API details (#4030)

output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_cohere.json, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_cohere/PutCohereResponse.ts, specification/inference/put_cohere/examples/request/PutCohereRequestExample1.yaml, specification/inference/put_cohere/examples/request/PutCohereRequestExample2.yaml
- [Add Cohere inference API details (#4025)](https://github.com/elastic/elasticsearch-specification/pull/4025)
=> [8.x] Add Cohere inference API details (#4025)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_azureopenai.json, specification/inference/put_azureopenai/PutAzureOpenAiRequest.ts, specification/inference/put_azureopenai/PutAzureOpenAiResponse.ts, specification/inference/put_azureopenai/examples/request/PutAzureOpenAiRequestExample1.yaml, specification/inference/put_azureopenai/examples/request/PutAzureOpenAiRequestExample2.yaml, specification/inference/put_openai/PutOpenAiRequest.ts
This PR adds details and examples derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-azure-openai.html
=> Add Azure OpenAI inference details

output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_elasticsearch.json, specification/inference/put_elasticsearch/PutElasticsearchRequest.ts, specification/inference/put_elasticsearch/PutElasticsearchResponse.ts, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample1.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample2.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample3.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample4.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample5.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample6.yaml, specification/inference/put_elasticsearch/examples/response/PutElasticsearchResponseExample1.yaml
- [Add Elasticsearch inference API details (#4024)](https://github.com/elastic/elasticsearch-specification/pull/4024)
=> [8.x] Add Elasticsearch inference API details (#4024)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, package-lock.json, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_amazonbedrock.json, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_amazonbedrock/PutAmazonBedrockResponse.ts, specification/inference/put_amazonbedrock/examples/request/PutAmazonBedrockRequestExample1.yaml, specification/inference/put_amazonbedrock/examples/request/PutAmazonBedrockRequestExample2.yaml, specification/inference/put_openai/examples/request/PutOpenAiRequestExample2.yaml
- [Add Amazon Bedrock inference API (#4022)](https://github.com/elastic/elasticsearch-specification/pull/4022)
=> [8.x] Add Amazon Bedrock inference API (#4022)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_azureaistudio.json, specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts, specification/inference/put_azureaistudio/PutAzureAiStudioResponse.ts, specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample1.yaml, specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample2.yaml
- [Add Azure AI Studio inference API (#4020)](https://github.com/elastic/elasticsearch-specification/pull/4020)
=> [8.x] Add Azure AI Studio inference API (#4020)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.mistral.json, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_mistral/PutMistralResponse.ts, specification/inference/put_mistral/examples/request/PutMistralRequestExample1.yaml
Relates to https://github.com/elastic/elasticsearch-specification/issues/3821
This PR adds the Mistral inference use case, with content derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-mistral.html
=> Add Mistral inference details

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.mistral.json, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_mistral/PutMistralResponse.ts, specification/inference/put_mistral/examples/request/PutMistralRequestExample1.yaml
- [Add Mistral inference details (#3997)](https://github.com/elastic/elasticsearch-specification/pull/3997)
=> [8.x] Add Mistral inference details (#3997)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.mistral.json, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_mistral/PutMistralResponse.ts, specification/inference/put_mistral/examples/request/PutMistralRequestExample1.yaml
- [Add Mistral inference details (#3997)](https://github.com/elastic/elasticsearch-specification/pull/3997)
=> [8.18] Add Mistral inference details (#3997)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put.mistral.json, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_mistral/PutMistralResponse.ts, specification/inference/put_mistral/examples/request/PutMistralRequestExample1.yaml
- [Add Mistral inference details (#3997)](https://github.com/elastic/elasticsearch-specification/pull/3997)
=> [9.0] Add Mistral inference details (#3997)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_azureaistudio.json, specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts, specification/inference/put_azureaistudio/PutAzureAiStudioResponse.ts, specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample1.yaml, specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample2.yaml
- [Add Azure AI Studio inference API (#4020)](https://github.com/elastic/elasticsearch-specification/pull/4020)
=> [9.0] Add Azure AI Studio inference API (#4020)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_elasticsearch.json, specification/inference/put_elasticsearch/PutElasticsearchRequest.ts, specification/inference/put_elasticsearch/PutElasticsearchResponse.ts, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample1.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample2.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample3.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample4.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample5.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample6.yaml, specification/inference/put_elasticsearch/examples/response/PutElasticsearchResponseExample1.yaml
- [Add Elasticsearch inference API details (#4024)](https://github.com/elastic/elasticsearch-specification/pull/4024)
=> [9.0] Add Elasticsearch inference API details (#4024)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_cohere.json, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_cohere/PutCohereResponse.ts, specification/inference/put_cohere/examples/request/PutCohereRequestExample1.yaml, specification/inference/put_cohere/examples/request/PutCohereRequestExample2.yaml
- [Add Cohere inference API details (#4025)](https://github.com/elastic/elasticsearch-specification/pull/4025)
=> [9.0] Add Cohere inference API details (#4025)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_json_spec/inference.put_elser.json, specification/inference/put_elser/PutElserRequest.ts, specification/inference/put_elser/PutElserResponse.ts, specification/inference/put_elser/examples/request/PutElserRequestExample1.yaml, specification/inference/put_elser/examples/request/PutElserRequestExample2.yaml, specification/inference/put_elser/examples/response/PutElserResponseExample1.yaml
- [Add ELSER inference API details (#4026)](https://github.com/elastic/elasticsearch-specification/pull/4026)
=> [9.0] Add ELSER inference API details (#4026)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_googleaistudio.json, specification/inference/put_googleaistudio/PutGoogleAiStudioRequest.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioResponse.ts, specification/inference/put_googleaistudio/examples/request/PutGoogleAiStudioRequestExample1.yaml
- [Add Google AI Studio inference details (#4027)](https://github.com/elastic/elasticsearch-specification/pull/4027)
=> [9.0] Add Google AI Studio inference details (#4027)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_googlevertexai.json, specification/inference/put_googlevertexai/PutGoogleVertexAiRequest.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiResponse.ts, specification/inference/put_googlevertexai/examples/request/PutGoogleVertexAiRequestExample1.yaml, specification/inference/put_googlevertexai/examples/request/PutGoogleVertexAiRequestExample2.yaml
- [Add Google Vertex AI inference details (#4028)](https://github.com/elastic/elasticsearch-specification/pull/4028)
=> [9.0] Add Google Vertex AI inference details (#4028)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_googlevertexai.json, specification/inference/put_googlevertexai/PutGoogleVertexAiRequest.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiResponse.ts, specification/inference/put_googlevertexai/examples/request/PutGoogleVertexAiRequestExample1.yaml, specification/inference/put_googlevertexai/examples/request/PutGoogleVertexAiRequestExample2.yaml
- [Add Google Vertex AI inference details (#4028)](https://github.com/elastic/elasticsearch-specification/pull/4028)
=> [8.18] Add Google Vertex AI inference details (#4028)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_googleaistudio.json, specification/inference/put_googleaistudio/PutGoogleAiStudioRequest.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioResponse.ts, specification/inference/put_googleaistudio/examples/request/PutGoogleAiStudioRequestExample1.yaml
- [Add Google AI Studio inference details (#4027)](https://github.com/elastic/elasticsearch-specification/pull/4027)
=> [8.18] Add Google AI Studio inference details (#4027)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_elser.json, specification/inference/put_elser/PutElserRequest.ts, specification/inference/put_elser/PutElserResponse.ts, specification/inference/put_elser/examples/request/PutElserRequestExample1.yaml, specification/inference/put_elser/examples/request/PutElserRequestExample2.yaml, specification/inference/put_elser/examples/response/PutElserResponseExample1.yaml
- [Add ELSER inference API details (#4026)](https://github.com/elastic/elasticsearch-specification/pull/4026)
=> [8.18] Add ELSER inference API details (#4026)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_cohere.json, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_cohere/PutCohereResponse.ts, specification/inference/put_cohere/examples/request/PutCohereRequestExample1.yaml, specification/inference/put_cohere/examples/request/PutCohereRequestExample2.yaml
- [Add Cohere inference API details (#4025)](https://github.com/elastic/elasticsearch-specification/pull/4025)
=> [8.18] Add Cohere inference API details (#4025)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_elasticsearch.json, specification/inference/put_elasticsearch/PutElasticsearchRequest.ts, specification/inference/put_elasticsearch/PutElasticsearchResponse.ts, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample1.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample2.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample3.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample4.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample5.yaml, specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample6.yaml, specification/inference/put_elasticsearch/examples/response/PutElasticsearchResponseExample1.yaml
- [Add Elasticsearch inference API details (#4024)](https://github.com/elastic/elasticsearch-specification/pull/4024)
=> [8.18] Add Elasticsearch inference API details (#4024)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_amazonbedrock.json, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_amazonbedrock/PutAmazonBedrockResponse.ts, specification/inference/put_amazonbedrock/examples/request/PutAmazonBedrockRequestExample1.yaml, specification/inference/put_amazonbedrock/examples/request/PutAmazonBedrockRequestExample2.yaml, specification/inference/put_openai/examples/request/PutOpenAiRequestExample2.yaml
- [Add Amazon Bedrock inference API (#4022)](https://github.com/elastic/elasticsearch-specification/pull/4022)
=> [8.18] Add Amazon Bedrock inference API (#4022)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/_json_spec/inference.put_azureaistudio.json, specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts, specification/inference/put_azureaistudio/PutAzureAiStudioResponse.ts, specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample1.yaml, specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample2.yaml
- [Add Azure AI Studio inference API (#4020)](https://github.com/elastic/elasticsearch-specification/pull/4020)
=> [8.18] Add Azure AI Studio inference API (#4020)

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_anthropic/PutAnthropicRequest.ts, specification/inference/put_elasticsearch/PutElasticsearchRequest.ts
- [Update doc_id URLs for inference APIs (#4127)](https://github.com/elastic/elasticsearch-specification/pull/4127)
=> [8.x] Update doc_id URLs for inference APIs (#4127)

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_anthropic/PutAnthropicRequest.ts, specification/inference/put_elasticsearch/PutElasticsearchRequest.ts
- [Update doc_id URLs for inference APIs (#4127)](https://github.com/elastic/elasticsearch-specification/pull/4127)
=> [8.18] Update doc_id URLs for inference APIs (#4127)

docs/overlays/elasticsearch-openapi-overlays.yaml
This PR updates the branch name that's included in the OpenAPI introduction now that we're publishing from the 9.0 branch.
=> Update branch in overlay

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/transform/get_transform/types.ts, specification/transform/get_transform_stats/types.ts
This is a field that we have missed until now even though [it was documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/get-transform-stats.html), except for type which was added in 8.8. It appeared [in this YAML test today](https://github.com/elastic/clients-flight-recordings/blob/10949c17ed2e1b71fc9d1020dfd94281b4455ccd/elasticsearch/tmp-platinum/transform.get_transform_stats/1109634f09aef2f8d962b498a381996e.json#L27-L34).
Regarding server code:
* issues is added in [TransformHealth.toXContent](https://github.com/elastic/elasticsearch/blob/9ec61d52fb62df85e88c360a8886a35b5b90c9b0/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/TransformHealth.java#L56-L58)
* issues is written in …
=> Add ml.get_transform_stats issues in response

specification/_global/msearch/types.ts, specification/_global/search/SearchRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts, specification/fleet/search/SearchRequest.ts
Should be `Array<SingleKeyDictionary<IndexName, double>>` instead of `Array<Dictionary<IndexName, double>>`.
=> Fix `indices_boost` type

compiler/src/steps/validate-model.ts, output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/aggregations/bucket.ts
fixes https://github.com/elastic/elasticsearch-specification/issues/2641
~~draft for now because I still have to figure out if we're mapping the responses right~~
=> making range aggregation untagged union

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/msearch/types.ts, specification/_global/msearch_template/types.ts, specification/_global/render_search_template/RenderSearchTemplateRequest.ts, specification/_global/search/SearchRequest.ts, specification/_global/search/_types/SearchRequestBody.ts, specification/_global/search/_types/suggester.ts, specification/_global/search_template/SearchTemplateRequest.ts, specification/_types/Scripting.ts, specification/_types/Transform.ts, specification/ingest/_types/Processors.ts, specification/watcher/_types/Conditions.ts
Originally reported as a [Java Client issue](https://github.com/elastic/elasticsearch-java/issues/876).
PutScript API support either the `source` of the script as a string, or as a Search Template object, which is equivalent to [the whole SearchRequest body](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#create-search-template).
Since the Search Request body is also needed by Multisearch, it was extracted as a separate class in the search package to that both Multisearch and StoredScript can use it (it was also ordered alphabetically).
`source` in StoredScript is now an externally tagged union. (potentially breaking for generators)
Ideally nothing else should be changed in the client codes as a result of this PR except for StoredScript, I'm setting …
=> Allow script to have string or object value

specification/inference/_types/CommonTypes.ts, specification/inference/chat_completion_unified/UnifiedRequest.ts, specification/inference/post_eis_chat_completion/PostEisChatCompletionRequest.ts
=> Inference: rename base type, no longer a base, grown into a property

specification/enrich/execute_policy/ExecuteEnrichPolicyResponse.ts, specification/enrich/execute_policy/types.ts
`task_id` in ExecuteEnrichPolicyResponse.ts actually being `task` -> [server code](https://github.com/elastic/elasticsearch/blob/1d6c6a59c86de232c65a29579a12e0fdb0eb97ad/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/enrich/action/ExecuteEnrichPolicyAction.java#L137)
missing `step` field in ExecuteEnrichPolicyStatus -> [server code](https://github.com/elastic/elasticsearch/blob/1d6c6a59c86de232c65a29579a12e0fdb0eb97ad/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/enrich/action/ExecuteEnrichPolicyStatus.java#L80)
missing CANCELLED phase in ExecuteEnrichPolicyStatus -> [server code](https://github.com/elastic/elasticsearch/blob/1d6c6a59c86de232c65a29579a12e0fdb0eb97ad/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/enrich/action/ExecuteEnrichPolic …
=> Fixing execute policy resp

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_global/msearch/MultiSearchRequest.ts, specification/_global/search/SearchRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts, specification/fleet/msearch/MultiSearchRequest.ts, specification/fleet/search/SearchRequest.ts
Since the long -> int changes in https://github.com/elastic/elasticsearch-specification/pull/4142 are breaking for Java and .NET for users that specify the `L` suffix or cast to long, I have extract them to this pull request that will only go in 9.x.
=> Fix type of max_concurrent_searches and max_concurrent_shard_requests

specification/watcher/update_settings/WatcherUpdateSettingsRequest.ts
This pull request includes an update to the `WatcherUpdateSettingsRequest` documentation to clarify which settings can be modified for the Watcher internal index after https://github.com/elastic/elasticsearch/pull/115251 was merged.
=> Update documentation for watcher update settings endpoint

output/openapi/elasticsearch-serverless-openapi.json, specification/_global/msearch/types.ts, specification/_global/search/SearchRequest.ts, specification/async_search/submit/AsyncSearchSubmitRequest.ts, specification/fleet/search/SearchRequest.ts
- [Clarify that min_score applies to aggs (#4180)](https://github.com/elastic/elasticsearch-specification/pull/4180)
Fixed a conflict with https://github.com/elastic/elasticsearch-specification/pull/2960.
=> [8.x] Clarify that min_score applies to aggs (#4180)

specification/ingest/_types/Processors.ts
[Docs](https://www.elastic.co/guide/en/elasticsearch/reference/8.17/inference-processor.html), [server code](https://github.com/elastic/elasticsearch/blob/a152b4e29b19fac4f5a36fed40a39611860f2827/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/ingest/InferenceProcessor.java#L103), [original report](https://github.com/elastic/elasticsearch-java/issues/985).
=> Missing fields in inference processor

specification/cluster/health/ClusterHealthRequest.ts, specification/cluster/health/types.ts
This type requires special handling / handcrafting in .NET in order to be used as a query parameter. It must be a named type in order to easily augment it.
=> Introduce `WaitForNodes` alias type

specification/cluster/health/ClusterHealthResponse.ts
`active_shards_percent_as_number` is not a string nor float, it's a [double](https://github.com/elastic/elasticsearch/blob/717d00d96de34b1c44610436e1e8942cda14f59d/server/src/main/java/org/elasticsearch/action/admin/cluster/health/ClusterHealthResponse.java#L231) - [server code](https://github.com/elastic/elasticsearch/blob/717d00d96de34b1c44610436e1e8942cda14f59d/server/src/main/java/org/elasticsearch/action/admin/cluster/health/ClusterHealthResponse.java#L277). 
also there's the optional string version of this field, `active_shards_percent` - [server code](https://github.com/elastic/elasticsearch/blob/717d00d96de34b1c44610436e1e8942cda14f59d/libs/x-content/src/main/java/org/elasticsearch/xcontent/XContentBuilder.java#L1183)
=> Missing field and wrong value in ClusterHealthResponse

specification/ingest/_types/Processors.ts
=> input_output array leniency

output/schema/validation-errors.json, output/typescript/types.ts, specification/snapshot/clone/SnapshotCloneRequest.ts
We removed it from 8.18 already. Server reference: https://github.com/elastic/elasticsearch/blob/6e4cb8142b9e51ad2be5c32b5daaa575585fd02d/server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestCloneSnapshotAction.java#L46-L61
It was added back by mistake in https://github.com/elastic/elasticsearch-specification/pull/3462. I'd like to not add it back in 9.0.
=> Remove timeout from clone snapshot API

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/Binary.ts, specification/esql/_types/EsqlResult.ts, specification/esql/async_query/AsyncQueryResponse.ts, specification/esql/async_query_get/AsyncQueryGetResponse.ts, specification/esql/async_query_stop/AsyncQueryStopResponse.ts, specification/esql/query/QueryResponse.ts
Adds the API spec for the JSON output of ES|QL query (other formats cannot be represented here).
=> Add ESQL result type definitions

docs/overlays/elasticsearch-shared-overlays.yaml
- [OpenAPI: Update overlays with new path separator (#4250)](https://github.com/elastic/elasticsearch-specification/pull/4250)
=> [8.x] OpenAPI: Update overlays with new path separator (#4250)

output/typescript/types.ts, specification/esql/async_query/AsyncQueryResponse.ts
Based on the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-async-query-api.html#esql-async-query-api-response-body, async query response's body type should be `AsyncEsqlResult` rather than `EsqlResult`. This allows accounting for the `id` and `is_running` details that are returned by the API.
=> fix: `AsyncQueryResponse`'s `body` should be `AsyncEsqlResult` and not `EsqlResult`

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_json_spec/inference.inference.json, specification/inference/_types/Results.ts, specification/inference/inference/InferenceRequest.ts, specification/inference/inference/InferenceResponse.ts
It’s important for Python and can be a fallback in cases where new providers are missing. Statically-typed clients are expected to exclude this endpoint.
I used https://github.com/elastic/elasticsearch-specification/tree/16c8bd383b6caa644ab64a57e989bb1d75b8b458/specification/inference as a reference, removing the examples that are now spread to provider-specific APIs.
=> Add back inference.inference API

specification/_doc_ids/table.csv
This PR updates a few more URLs in the `table.csv` file, since the appropriate target pages now exist due to https://github.com/elastic/elasticsearch/pull/126571 and https://github.com/elastic/elasticsearch/pull/126577
=> [DOCS] Update more URLs in table.csv

specification/_doc_ids/table.csv, specification/indices/cancel_migrate_reindex/MigrateCancelReindexRequest.ts, specification/indices/create_from/MigrateCreateFromRequest.ts, specification/indices/migrate_reindex/MigrateReindexRequest.ts
- [[DOCS] Fix connector, migration, and k-precision URLs (#4269)](https://github.com/elastic/elasticsearch-specification/pull/4269)
=> [9.0] [DOCS] Fix connector, migration, and k-precision URLs (#4269)

specification/_doc_ids/table.csv
- [[DOCS] Update more URLs in table.csv (#4262)](https://github.com/elastic/elasticsearch-specification/pull/4262)
=> [9.0] [DOCS] Update more URLs in table.csv (#4262)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/ChunkingSettings.ts, specification/_types/mapping/core.ts
Updates the specification to include `chunking_settings` for `semantic_text` fields which were added in https://github.com/elastic/elasticsearch/pull/121041
=> Add support for chunking_settings in semantic_text fields 

docs/overlays/elasticsearch-openapi-overlays.yaml
This PR updates the overlay for the OpenAPI document so that it mentions the `8.18` branch instead of the `8.x` branch.
=> [DOCS] Fix branch detail in OpenAPI overlay

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/search/SearchRequest.ts, specification/_global/search/_types/SearchRequestBody.ts
Fixes https://github.com/elastic/elasticsearch-specification/issues/4284
Note: If we find the magic combination of objects that must be abbreviated IMO we should ultimately get this detail pushed into the specification otherwise we'll break again if the specification once again changes. Overlays are fragile.
=> [DOCS] Add overlays to work around deployment failure

docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_global/search/SearchRequest.ts, specification/_global/search/_types/SearchRequestBody.ts
- [[DOCS] Add overlays to work around deployment failure (#4285)](https://github.com/elastic/elasticsearch-specification/pull/4285)
=> [9.0] [DOCS] Add overlays to work around deployment failure (#4285)

docs/overlays/elasticsearch-shared-overlays.yaml
Relates to https://github.com/elastic/elasticsearch-specification/pull/4285#issuecomment-2813842759
This PR removes two overlays that were temporary work-arounds.
The same change is included in the 9.0 branch via https://github.com/elastic/elasticsearch-specification/pull/4286
=> [DOCS] Remove deployment work-around from overlays

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/synonyms/_types/SynonymsUpdateResult.ts, specification/synonyms/delete_synonym_rule/SynonymRuleDeleteRequest.ts, specification/synonyms/put_synonym/SynonymsPutRequest.ts, specification/synonyms/put_synonym/SynonymsPutResponse.ts, specification/synonyms/put_synonym_rule/SynonymRulePutRequest.ts
Following https://github.com/elastic/elasticsearch/pull/126935, we will be adding a `refresh` parameter to the following Synonyms API requests:
- Update synonyms set
- Update synonym rule
- Delete synonym rule
When `refresh` is false, the reload analyzer details will not be present in the responses - they have been updated accordingly.
=> Synonyms API - Add refresh parameter

specification/ingest/_types/Simulation.ts
Fixes <https://github.com/elastic/elasticsearch-js/issues/2647>
=> Use correct status values for simulated ingest pipeline processor results

specification/_global/search/_types/hits.ts
Related to: https://github.com/elastic/elasticsearch-net/issues/8503
`Fields` was never the correct type.
=> Change `InnerHits.fields` from `Fields` to `Field[]`

specification/ilm/explain_lifecycle/types.ts
Reported in https://github.com/elastic/elasticsearch-java/issues/999, [server code](https://github.com/elastic/elasticsearch/blob/e222e5c636dfbd3e0ac68916c6a6cda7a191b275/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/IndexLifecycleExplainResponse.java#L91)
=> Phase optional lifecycle explain

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/cluster/stats/ClusterStatsResponse.ts, specification/cluster/stats/types.ts
Backport c9801b1b2d51276dd24f9254aa7c463ab6406939 from #4311.
=> [Backport 8.x] Backport 4311 to 8.x

output/typescript/types.ts, specification/cluster/stats/ClusterStatsResponse.ts, specification/cluster/stats/types.ts
Backport c9801b1b2d51276dd24f9254aa7c463ab6406939 from #4311.
=> [Backport 8.18] Backport 4311 to 8.18

specification/inference/put/PutRequest.ts, specification/inference/put_alibabacloud/PutAlibabaCloudRequest.ts, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_anthropic/PutAnthropicRequest.ts, specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts, specification/inference/put_azureopenai/PutAzureOpenAiRequest.ts, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioRequest.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiRequest.ts, specification/inference/put_hugging_face/PutHuggingFaceRequest.ts, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_openai/PutOpenAiRequest.ts, specification/inference/put_watsonx/PutWatsonxRequest.ts
This PR removes a paragraph of text from the various inference API integration docs pages that is only relevant for `elaser` and `elasticsearch`.
=> Removes erroneous flavour text from PUT inference API pages

specification/inference/put/PutRequest.ts, specification/inference/put_alibabacloud/PutAlibabaCloudRequest.ts, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_anthropic/PutAnthropicRequest.ts, specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts, specification/inference/put_azureopenai/PutAzureOpenAiRequest.ts, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioRequest.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiRequest.ts, specification/inference/put_hugging_face/PutHuggingFaceRequest.ts, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_openai/PutOpenAiRequest.ts, specification/inference/put_watsonx/PutWatsonxRequest.ts
Backport 5217f6665e932ec63ccfeb8eb50ec7da1fb0ec9a from #4357.
=> [Backport 9.0] Removes erroneous flavour text from PUT inference API pages

output/typescript/types.ts, specification/migration/post_feature_upgrade/PostFeatureUpgradeResponse.ts
Server code: https://github.com/elastic/elasticsearch/blob/a6ffeeeb710d72352a2d400c404c4543059f23d1/x-pack/plugin/migrate/src/main/java/org/elasticsearch/system_indices/action/PostFeatureUpgradeResponse.java#L65-L87
There's also the optional `ElasticsearchException` but that seems to tricky to model given the recursivity and overall complexity.
=> Add reason to migration.post_feature_upgrade API

specification/inference/_types/Services.ts, specification/inference/_types/TaskType.ts, specification/inference/put_jinaai/PutJinaAiResponse.ts
Backport of https://github.com/elastic/elasticsearch-specification/pull/4391
=> [Backport 8.18] Adds custom InferenceEndpointInfo class for JinaAI

specification/snapshot/repository_verify_integrity/SnapshotRepositoryVerifyIntegrityRequest.ts
This API was never meant to be private. This issue was fixed in https://github.com/elastic/elasticsearch/pull/128244. I then thought that https://github.com/elastic/elasticsearch-specification/pull/4401 would be sufficient to make it public, but it turns out that we don't enforce the visibility in the rest-api-spec to match ours.
=> Fix visibility of snapshot.repository_verify_integrity

specification/_types/query_dsl/term.ts
Range query fields `from` and `to` were deprecated in 8.16 and [are no longer exposed](https://github.com/elastic/elasticsearch/blob/79d3aa827789652cafba569e3261e5fd632d743e/server/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L46-L52) in 9.0+.
Fixes https://github.com/elastic/elasticsearch-js/issues/2846.
=> Range query from/to parameters were removed in 9.0

specification/inference/_types/CommonTypes.ts
Related to https://github.com/elastic/docs-content/issues/310
Two new embedding types are supported via https://github.com/elastic/elasticsearch/pull/120751. This PR expands the `embedding_type` value description of the PUT Cohere inference endpoint to reflect the changes.
=> Adds new `embedding_type` values to PUT Cohere inference endpoint

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/inference/_types/Services.ts, specification/inference/_types/TaskType.ts, specification/inference/put_alibabacloud/PutAlibabaCloudResponse.ts
The Response Attributes section of the reference documentation currently displays the task_types defined in the TaskType enum used by the InferenceEndpointInfo class. However, InferenceEndpointInfo is not specific to any particular inference API integration — it lists all available task types, not just those relevant to the specific integration being documented.
This PR introduces a new TaskTypeAlibabaCloud enum that includes only the relevant task types and references it in the newly added TaskTypeAlibabaCloud class. As a result, the documentation will now accurately display only the supported task types for this integration — even in the Response Attributes section.
https://github.com/elastic/developer-docs-team/issues/291
=> Adds custom InferenceEndpointInfo class for AlibabaCloudAI

.backportrc.json
Elastic engineers commonly use https://github.com/sorenlouv/backport to perform backports. I've been using it in the elasticsearch-specification repository for months now.
Since pull request forks are not accepted in this repository, committing the configuration is helpful to avoid backports being pushed to forks. It will mean that active branches will have to be maintained here, but that's okay. I've had this locally for a while now, and I update it whenever I notice any missing branches.
(I'm backporting this change because it's easy to do, but it's not needed as backports are done from main.)
=> Add configuration for sorenlouv/backport tool

specification/_types/Retriever.ts
Addition to #4420, but only for 9.1/8.19. `l2_norm` was recently added as option for ScoreNormalizer in LinearRetriever https://github.com/elastic/elasticsearch/pull/128504
=> Add l2 norm to linear retriever

specification/_doc_ids/table.csv, specification/cluster/get_settings/ClusterGetSettingsRequest.ts, specification/cluster/get_settings/ClusterGetSettingsResponse.ts, specification/cluster/put_settings/ClusterPutSettingsRequest.ts
- [[DOCS] Add link for cluster settings (#4491)](https://github.com/elastic/elasticsearch-specification/pull/4491)
NOTE that there is no equivalent "stack-settings" page in v8 docs, so the link target is an Elasticsearch settings page instead.
=> [8.19] [DOCS] Add link for cluster settings (#4491)

output/openapi/elasticsearch-serverless-openapi.json, specification/inference/_types/Services.ts
Relates to https://github.com/elastic/elasticsearch-specification/issues/2918, https://github.com/elastic/elasticsearch-specification/issues/4473
The details about the service-specific rate limit defaults are missing from the inference endpoints (for example in https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-inference-put-googlevertexai#operation-inference-put-googlevertexai-body-application-json-service_settings-rate_limit).  This PR copies those details into the description for the shared `RateLimitSetting` object.
=> [DOCS] Clarify default rate limit settings

output/schema/validation-errors.json, output/typescript/types.ts, specification/esql/async_query/AsyncQueryRequest.ts
`keep_alive`, `keep_on_completion` and `wait_for_completion_timeout` are body parameters for `AsyncQueryResuest`.
=> Fix AsyncQueryRequest - those parameters should be in the body

specification/_spec_utils/behaviors.ts
=> Fixes minor typo in `human` boolean parameter documentation

specification/_doc_ids/table.csv, specification/cluster/allocation_explain/ClusterAllocationExplainRequest.ts
Related to https://github.com/elastic/docs-projects/issues/302 and https://github.com/elastic/docs-content/pull/1698
DO NOT MERGE BEFORE https://github.com/elastic/docs-content/pull/1698
This PR adds a link to the Cluster allocation explain API description that points to the more complex API example page in the Troubleshooting section.
=> Adds an external link to Cluster allocation explain API spec

specification/_doc_ids/table.csv, specification/cluster/allocation_explain/ClusterAllocationExplainRequest.ts
Backport of Adds an external link to Cluster allocation explain API spec #4523
=> [Backport 9.0] Adds an external link to Cluster allocation explain API spec

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_global/search/_types/SourceFilter.ts
Add support for the exclude_vectors option (introduced in elastic/elasticsearch#128735) to the source filter specification.
=> Add exclude_vectors parameter to source filtering in _search

output/schema/validation-errors.json, output/typescript/types.ts, specification/esql/async_query/AsyncQueryRequest.ts
(cherry picked from commit 0ac4f3b154e93370517d5e6e3551e0a1be11470a)
=> [Backport 8.18] Fix AsyncQueryResuest - those parameters should be in the body (#4517)

.github/workflows/update-rest-api-json.yml
I'm fixing three unrelated things here:
* Remove 8.16 and 7.17 branches
* Use `make setup` instead of installing specific dependencies, as example generation was breaking validation here
* Stop trying to open an issue on failure, this has been broken since 2022
=> Fix update-rest-api-json CI

specification/_doc_ids/table.csv, specification/text_structure/find_structure/FindStructureRequest.ts
Related to https://github.com/elastic/docs-projects/issues/302 and https://github.com/elastic/elasticsearch/pull/129536
DO NOT MERGE BEFORE https://github.com/elastic/elasticsearch/pull/129536
This PR adds a link to the find text structure API description that points to the more complex API example page in the ES reference section.
=> Adds an external link to find text structure API

docs/add-new-api.md
- [Fix inference examples (#4566)](https://github.com/elastic/elasticsearch-specification/pull/4566)
NOTE: The other file changes in the original PR are not applicable to this branch.
=> [9.0] Fix example readme (#4566)

docs/add-new-api.md
- [Fix inference examples (#4566)](https://github.com/elastic/elasticsearch-specification/pull/4566)
NOTE: The other file changes in the original PR are not applicable to this branch.
=> [8.18] Fix example readme (#4566)

specification/_types/query_dsl/WeightedTokensQuery.ts
Partially reverting #4469, making the `tokens` field as lenient as it is in the server. No server side proof, all the variants were tested in the console. Thanks @flobernd for noticing the mistake!
=> Weighted token as lenient dict

specification/_doc_ids/table.csv, specification/watcher/ack_watch/WatcherAckWatchRequest.ts
DO NOT MERGE BEFORE https://github.com/elastic/docs-content/pull/1768
This PR adds an external link to the [Acknowledge a watch](https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-watcher-ack-watch-2) API.
=> Adds external link to ack_watch API

compiler/src/model/utils.ts, docs/modeling-guide.md, specification/_global/search/_types/suggester.ts, specification/_types/aggregations/Aggregate.ts, specification/ml/_types/inference.ts, specification/security/query_api_keys/types.ts
This PR changes the variant name `external` to `typed_keys_quirk` to better highlight its specific use.
The real external tagging being `container` resolving types by the field name and able to be non-exhaustive.
The internal naming `external_tag` remains intact for backward compatibility with existing generators.
=> [compiler] Rename external to typed_keys_quirk

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/indices/delete_data_lifecycle/IndicesDeleteDataLifecycleRequest.ts, specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleRequest.ts, specification/indices/get_data_lifecycle/IndicesGetDataLifecycleRequest.ts, specification/indices/get_data_lifecycle_stats/IndicesGetDataLifecycleStatsRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
This PR adds `@ext_doc_id` links to https://www.elastic.co/docs/manage-data/lifecycle/data-stream from APIs like [get data stream lifecycles](https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-indices-get-data-lifecycle), since the [Data streams group](https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-data-stream) currently only points to an overview of data streams.
This is a demo as part of a discussion with @stefnestor about how to add these types of links in general. The OpenAPI output is generated via [make generate](https://github.com/elastic/elasticsearch-specification?tab=readme-ov-file#how-to-generate-the-json-representation) and [make transform-to-openapi](https://github.com/elastic/elasticsearch-specification?tab=readme-ov-file#how-to-generate-t …
=> [DOCS] Add data stream lifecycle links

specification/_doc_ids/table.csv, specification/watcher/ack_watch/WatcherAckWatchRequest.ts
This PR backports the [Adds external link to ack_watch API](https://github.com/elastic/elasticsearch-specification/pull/4607) to 9.0
=> [Backport 9.0] Adds external link to ack_watch API #4607

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_global/search_shards/SearchShardsRequest.ts, specification/_global/search_template/SearchTemplateRequest.ts, specification/_global/update_by_query/UpdateByQueryRequest.ts, specification/indices/clear_cache/IndicesClearCacheRequest.ts, specification/indices/close/CloseIndexRequest.ts, specification/indices/delete/IndicesDeleteRequest.ts, specification/indices/exists/IndicesExistsRequest.ts, specification/indices/exists_alias/IndicesExistsAliasRequest.ts, specification/indices/flush/IndicesFlushRequest.ts, specification/indices/get_alias/IndicesGetAliasRequest.ts, specification/indices/get_data_lifecycle/IndicesGetDataLifecycleRequest.ts, specification/indices/get_field_mapping/IndicesGetFieldMappingRequest.ts, specification/indices/get_mapping/IndicesGetMappingRequest.ts, specification/indices/open/IndicesOpenRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts, specification/indices/put_mapping/IndicesPutMappingRequest.ts, specification/indices/refresh/IndicesRefreshRequest.ts, specification/indices/resolve_cluster/ResolveClusterRequest.ts, specification/indices/resolve_index/ResolveIndexRequest.ts, specification/indices/segments/IndicesSegmentsRequest.ts, specification/indices/validate_query/IndicesValidateQueryRequest.ts, specification/ml/put_job/MlPutJobRequest.ts, specification/ml/update_datafeed/MlUpdateDatafeedRequest.ts
- [[DOCS] Clean up more duplicated enum values (#4458)](https://github.com/elastic/elasticsearch-specification/pull/4458)
=> [9.0] [DOCS] Clean up more duplicated enum values (#4458)

docs/overlays/elasticsearch-openapi-overlays.yaml, docs/overlays/elasticsearch-shared-overlays.yaml, output/openapi/elasticsearch-serverless-openapi.json, specification/_global/open_point_in_time/OpenPointInTimeRequest.ts, specification/_global/search_shards/SearchShardsRequest.ts, specification/_global/search_template/SearchTemplateRequest.ts, specification/_global/update_by_query/UpdateByQueryRequest.ts, specification/indices/clear_cache/IndicesClearCacheRequest.ts, specification/indices/close/CloseIndexRequest.ts, specification/indices/delete/IndicesDeleteRequest.ts, specification/indices/exists/IndicesExistsRequest.ts, specification/indices/exists_alias/IndicesExistsAliasRequest.ts, specification/indices/flush/IndicesFlushRequest.ts, specification/indices/get_alias/IndicesGetAliasRequest.ts, specification/indices/get_data_lifecycle/IndicesGetDataLifecycleRequest.ts, specification/indices/get_field_mapping/IndicesGetFieldMappingRequest.ts, specification/indices/get_mapping/IndicesGetMappingRequest.ts, specification/indices/open/IndicesOpenRequest.ts, specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts, specification/indices/put_mapping/IndicesPutMappingRequest.ts, specification/indices/refresh/IndicesRefreshRequest.ts, specification/indices/resolve_cluster/ResolveClusterRequest.ts, specification/indices/resolve_index/ResolveIndexRequest.ts, specification/indices/segments/IndicesSegmentsRequest.ts, specification/indices/validate_query/IndicesValidateQueryRequest.ts, specification/ml/put_job/MlPutJobRequest.ts, specification/ml/update_datafeed/MlUpdateDatafeedRequest.ts
- [[DOCS] Clean up more duplicated enum values (#4458)](https://github.com/elastic/elasticsearch-specification/pull/4458)
=> [8.19] [DOCS] Clean up more duplicated enum values (#4458)

specification/security/update_cross_cluster_api_key/UpdateCrossClusterApiKeyRequest.ts
Related to https://github.com/elastic/docs-projects/issues/302 and https://github.com/elastic/elasticsearch/pull/129843
DO NOT MERGE BEFORE https://github.com/elastic/elasticsearch/pull/129843
This PR adds a link to the update cross cluster API key API description that points to the more complex API example page in the ES reference section.
=> Adds a link to the update cross cluster API key API spec

.github/validate-pr/index.js
The existing namespace computation was too naive. We now use this version instead:
```js
export function getNamespace (api) {
if (api.includes('.')) return api.split('.')[0]
return 'global'
}
```
=> Fix validation for _global APIs

.github/validate-pr/index.js, .github/workflows/validate-pr.yml
- [Update PR comments in place (#4620)](https://github.com/elastic/elasticsearch-specification/pull/4620)
=> [9.0] Update PR comments in place (#4620)

.github/validate-pr/index.js, .github/workflows/validate-pr.yml
- [Update PR comments in place (#4620)](https://github.com/elastic/elasticsearch-specification/pull/4620)
=> [8.19] Update PR comments in place (#4620)

.github/workflows/validate-pr.yml
- [Stop referencing GCS_CREDENTIALS (#4624)](https://github.com/elastic/elasticsearch-specification/pull/4624)
=> [8.19] Stop referencing GCS_CREDENTIALS (#4624)

.github/workflows/validate-pr.yml
This was changed in https://github.com/elastic/elasticsearch-specification/pull/4642.
=> Fix string used to find previous comment

specification/esql/async_query_get/AsyncQueryGetRequest.ts
This adds the missing `format` query string option to ESQL's `async_query_get` endpoint.
Reported in https://github.com/elastic/elasticsearch-py/pull/2987.
=> Add `format` query option to `esql.async_query_get` endpoint

.github/workflows/validate-pr.yml
- [Fix string used to find previous comment (#4677)](https://github.com/elastic/elasticsearch-specification/pull/4677)
=> [8.19] Fix string used to find previous comment (#4677)

.github/workflows/validate-pr.yml
- [Fix string used to find previous comment (#4677)](https://github.com/elastic/elasticsearch-specification/pull/4677)
=> [8.18] Fix string used to find previous comment (#4677)

.backportrc.json, .github/workflows/update-rest-api-json.yml
I also removed 8.17 since it's currently failing as I did not backport many of the recent changes to it: https://github.com/elastic/elasticsearch-specification/actions/runs/15892771826/job/44818325550.
=> Start automation on 9.1 branch

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/mapping/SemanticTextIndexOptions.ts, specification/_types/mapping/core.ts
Adds `index_options` for `semantic_text` fields to the specification, which were introduced through https://github.com/elastic/elasticsearch/pull/119967
Note: This design only supports `dense_vector` but we anticipate that `sparse_vector` will be a fast follow.
=> Add specs for Semantic Text index options

compiler-rs/clients_schema/src/transform/expand_generics.rs, compiler/src/steps/validate-model.ts, compiler/src/transform/expand-generics.ts, specification/indices/get_alias/_types/response.ts
Types only found in exceptions are not included in the final `schema.json` because the compiler has not "seen" them.
This fixes the `NotFoundAliases` exception present in `indices.get_alias`.
This adds the following to the output:
```json
{
"kind": "interface",
"name": {
"name": "IndexAliases",
"namespace": "indices.get_alias._types"
},
"properties": [
{
"name": "aliases",
"required": true,
"type": {
"kind": "dictionary_of",
"key": {
"kind": "instance_of",
"type": {
"name": "string",
"namespace": "_builtins"
}
},
"singleKey": false,
"value": {
"kind": "instance_of",
"type": {
"name": "AliasDefinition",
"namespace": "indices._types"
}
}
}
}
],
"specLocation": "indices/get_alias/_types/response.ts#L24-L26"
},
{
"kind": "interface",
"attachedBehaviors": [
"AdditionalProperties"
], …
```
=> [compiler] Include exceptions to schema

specification/indices/get_alias/_types/response.ts
This adds the missing `behavior_meta` to `NotFoundAliases`.
=> Add missing annotation on NotFoundAliases

.gitignore, Makefile
Relates to https://github.com/elastic/elasticsearch-specification/issues/4277 and https://github.com/elastic/elasticsearch-specification/pull/4415, which added the new `make transform-to-openapi-for-docs` command.
This PR updates the `make overlay-docs` to run against the output from `make transform-to-openapi-for-docs` instead of `make transform-to-openapi`. 
It also changes the output file name since the `.examples.json` file names imply something that isn't true anymore (and updates the `.gitignore` accordingly).
NOTE: This PR should not be merged until after we're ready to start publishing from the new `make transform-to-openapi-for-docs` output (i.e. we've established redirects for the paths that have been consolidated).
=> [DOCS] Change source for overlay-docs

.gitignore, Makefile
- [[DOCS] Change source for overlay-docs (#4504)](https://github.com/elastic/elasticsearch-specification/pull/4504)
=> [Backport 8.19] [DOCS] Change source for overlay-docs (#4504)

.gitignore, Makefile
- [[DOCS] Change source for overlay-docs (#4504)](https://github.com/elastic/elasticsearch-specification/pull/4504)
=> [Backport 8.18] [DOCS] Change source for overlay-docs (#4504)

compiler-rs/clients_schema/src/lib.rs, compiler-rs/clients_schema_to_openapi/src/cli.rs, compiler-rs/clients_schema_to_openapi/src/lib.rs, compiler-rs/clients_schema_to_openapi/src/schemas.rs
Closes https://github.com/elastic/elasticsearch-specification/issues/4628.
This doesn't affect main or 9.x, it's only an old docs system issue, but I'll port this everywhere for consistency.
In the old docs the branch name in `ext_docs_url` (`externalDocs` in openapi)  is a `{branch}` placeholder that gets resolved in the rust openapi converter by getting the correct branch value from the schema model. The problem is that the branch/version doesn't exist in the schema model anymore, because it was causing problems with PRs, so right now it always defaults to "current".
This PR gets the version for `externalDocs` from a CLI argument instead. This is a temporary solution, since the whole logic will get rewritten when the repo is transfered. 
So no changes for branches main, 9.1, 9.0, while …
=> [OpenApi] Add branch option to cli

specification/inference/_types/Services.ts, specification/inference/_types/TaskType.ts, specification/inference/put_amazonbedrock/PutAmazonBedrockResponse.ts, specification/inference/put_anthropic/PutAnthropicResponse.ts, specification/inference/put_azureaistudio/PutAzureAiStudioResponse.ts, specification/inference/put_azureopenai/PutAzureOpenAiResponse.ts, specification/inference/put_cohere/PutCohereResponse.ts, specification/inference/put_elasticsearch/PutElasticsearchResponse.ts, specification/inference/put_elser/PutElserResponse.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioResponse.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiResponse.ts, specification/inference/put_hugging_face/PutHuggingFaceResponse.ts, specification/inference/put_mistral/PutMistralResponse.ts, specification/inference/put_openai/PutOpenAiResponse.ts, specification/inference/put_voyageai/PutVoyageAIResponse.ts, specification/inference/put_watsonx/PutWatsonxResponse.ts
This was never backported properly, and it currently blocks other backports.
- [Adds custom InferenceEndpointInfo classes (#4444)](https://github.com/elastic/elasticsearch-specification/pull/4444)
=> [8.19] Adds custom InferenceEndpointInfo classes (#4444)

specification/_doc_ids/table.csv, specification/rollup/rollup_search/RollupSearchRequest.ts
DO NOT MERGE BEFORE https://github.com/elastic/docs-content/pull/1893
This PR adds an external link to the Rollup search API and removes unnecessary/redundant Request examples.
Related issue: https://github.com/elastic/docs-projects/issues/302
=> Adds external link to Rollup search API

specification/watcher/execute_watch/examples/request/WatcherExecuteRequestExample2.yaml, specification/watcher/execute_watch/examples/request/WatcherExecuteRequestExample3.yaml
This PR restores two YAML example files that were removed in a previous PR:
- `WatcherExecuteRequestExample2.yaml`
- `WatcherExecuteRequestExample3.yaml`
Related issue: 
https://github.com/elastic/docs-projects/issues/302
=> Restores Watcher execute watch request examples

specification/_doc_ids/table.csv, specification/_global/update/UpdateRequest.ts
This PR backports #4657 to the 9.0 branch.
=> [Backport 9.0] Adds external link to 'Update a document API' (#4657)

specification/_doc_ids/table.csv, specification/_global/update_by_query/UpdateByQueryRequest.ts
Backport https://github.com/elastic/elasticsearch-specification/commit/30931cbfa17b7c3bfafdeafbe6deb00a7bdb704e from https://github.com/elastic/elasticsearch-specification/pull/4705.
=> [Backport 9.0] Add link to `_update_by_query` API examples

.github/validate-pr/index.js, .github/workflows/validate-pr.yml
- [Output validation comments even without changes (#4781)](https://github.com/elastic/elasticsearch-specification/pull/4781)
=> [8.18] Output validation comments even without changes (#4781)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/index/IndexRequest.ts
Added in https://github.com/elastic/elasticsearch/pull/101872 for `index` and `bulk`. (`bulk` was fixed in https://github.com/elastic/elasticsearch-specification/pull/3273)
=> Add require_data_stream query parameter to index

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/index/IndexRequest.ts
- [Add require_data_stream query parameter to index (#4803)](https://github.com/elastic/elasticsearch-specification/pull/4803)
=> [8.18] Add require_data_stream query parameter to index (#4803)

output/schema/validation-errors.json, output/typescript/types.ts, specification/license/post_start_trial/StartTrialLicenseRequest.ts
- [Fix type query paramter in license.post_start_trial (#4807)](https://github.com/elastic/elasticsearch-specification/pull/4807)
=> [8.19] Fix type query paramter in license.post_start_trial (#4807)

output/schema/validation-errors.json, output/typescript/types.ts, specification/ingest/get_ip_location_database/GetIpLocationDatabaseRequest.ts
- [Remove master_timeout from ingest.get_ip_location_database (#4804)](https://github.com/elastic/elasticsearch-specification/pull/4804)
=> [8.19] Remove master_timeout from ingest.get_ip_location_database (#4804)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/cluster/put_component_template/ClusterPutComponentTemplateRequest.ts
Relates https://github.com/elastic/elasticsearch/pull/130634
=> Add missing cause to cluster.put_component_template

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/cluster/put_component_template/ClusterPutComponentTemplateRequest.ts
- [Add missing cause to cluster.put_component_template (#4795)](https://github.com/elastic/elasticsearch-specification/pull/4795)
=> [8.18] Add missing cause to cluster.put_component_template (#4795)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/get_source/SourceRequest.ts
- [Remove unsupported stored_fields from get_source API (#4786)](https://github.com/elastic/elasticsearch-specification/pull/4786)
=> [9.1] Remove unsupported stored_fields from get_source API (#4786)

compiler/src/steps/validate-model.ts, output/schema/validation-errors.json
As discussed in https://github.com/elastic/elasticsearch-specification/issues/4796 (and offline with @Anaethelion and @swallez), it can make sense to allow single variants. This usually happens because the other variants are not exposed or have not been implemented yet.
=> Allow containers with a single variant

compiler/src/steps/validate-model.ts, output/schema/validation-errors.json
- [Allow containers with a single variant (#4853)](https://github.com/elastic/elasticsearch-specification/pull/4853)
=> [8.19] Allow containers with a single variant (#4853)

compiler/src/steps/validate-model.ts, output/schema/validation-errors.json
- [Allow containers with a single variant (#4853)](https://github.com/elastic/elasticsearch-specification/pull/4853)
=> [8.18] Allow containers with a single variant (#4853)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/reindex/ReindexRequest.ts
This parameter is also exposed in the body, see https://github.com/search?q=repo%3Aelastic/elasticsearch%20setMaxDocsValidateIdentical&type=code. I reused the same comment.
=> Add max_docs query parameter to reindex API

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/reindex/ReindexRequest.ts
- [Add max_docs query parameter to reindex API (#4842)](https://github.com/elastic/elasticsearch-specification/pull/4842)
=> [8.19] Add max_docs query parameter to reindex API (#4842)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_global/search_mvt/SearchMvtRequest.ts
This will backport the following commits from `9.0` to `8.18`:
- [Add track_total_hits to search_mvt (#4850) (#4870)](https://github.com/elastic/elasticsearch-specification/pull/4870)
=> [8.18] Add track_total_hits to search_mvt (#4850) (#4870)

output/schema/validation-errors.json, output/typescript/types.ts, specification/snapshot/delete/SnapshotDeleteRequest.ts
- [Add wait_for_completion to snapshot.delete (#4875)](https://github.com/elastic/elasticsearch-specification/pull/4875)
=> [8.18] Add wait_for_completion to snapshot.delete (#4875)

output/schema/validation-errors.json, output/typescript/types.ts, specification/security/get_user_privileges/SecurityGetUserPrivilegesRequest.ts
They are not supported as this API only returns privileges from the current users and accepts no parameters. I've tested manually and confirmed with the source code and [8.x docs](https://www.elastic.co/guide/en/elasticsearch/reference/8.19/security-api-get-user-privileges.html):
https://github.com/elastic/elasticsearch/blob/2a9f894b7a5acb04a53541100b23aa8301c1813a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/user/RestGetUserPrivilegesAction.java#L58-L67
=> Remove query parameters from security.get_user_privileges

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/inference/put/PutRequest.ts, specification/inference/put_alibabacloud/PutAlibabaCloudRequest.ts, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_anthropic/PutAnthropicRequest.ts, specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts, specification/inference/put_azureopenai/PutAzureOpenAiRequest.ts, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_elasticsearch/PutElasticsearchRequest.ts, specification/inference/put_elser/PutElserRequest.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioRequest.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiRequest.ts, specification/inference/put_hugging_face/PutHuggingFaceRequest.ts, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_openai/PutOpenAiRequest.ts, specification/inference/put_voyageai/PutVoyageAIRequest.ts, specification/inference/put_watsonx/PutWatsonxRequest.ts, specification/inference/stream_completion/StreamInferenceRequest.ts
- [Add timeout params for PUT inference and POST inference/_stream (#4895)](https://github.com/elastic/elasticsearch-specification/pull/4895)
=> [8.18] Add timeout params for PUT inference and POST inference/_stream (#4895)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/inference/put/PutRequest.ts, specification/inference/put_alibabacloud/PutAlibabaCloudRequest.ts, specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts, specification/inference/put_anthropic/PutAnthropicRequest.ts, specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts, specification/inference/put_azureopenai/PutAzureOpenAiRequest.ts, specification/inference/put_cohere/PutCohereRequest.ts, specification/inference/put_elasticsearch/PutElasticsearchRequest.ts, specification/inference/put_elser/PutElserRequest.ts, specification/inference/put_googleaistudio/PutGoogleAiStudioRequest.ts, specification/inference/put_googlevertexai/PutGoogleVertexAiRequest.ts, specification/inference/put_hugging_face/PutHuggingFaceRequest.ts, specification/inference/put_jinaai/PutJinaAiRequest.ts, specification/inference/put_mistral/PutMistralRequest.ts, specification/inference/put_openai/PutOpenAiRequest.ts, specification/inference/put_voyageai/PutVoyageAIRequest.ts, specification/inference/put_watsonx/PutWatsonxRequest.ts, specification/inference/stream_completion/StreamInferenceRequest.ts
- [Add timeout params for PUT inference and POST inference/_stream (#4895)](https://github.com/elastic/elasticsearch-specification/pull/4895)
=> [9.0] Add timeout params for PUT inference and POST inference/_stream (#4895)

output/schema/validation-errors.json, output/typescript/types.ts, specification/indices/recovery/IndicesRecoveryRequest.ts
- [Add missing indices options to index recovery API (#4954)](https://github.com/elastic/elasticsearch-specification/pull/4954)
=> [9.1] Add missing indices options to index recovery API (#4954)

output/schema/validation-errors.json, output/typescript/types.ts, specification/indices/recovery/IndicesRecoveryRequest.ts
- [Add missing indices options to index recovery API (#4954)](https://github.com/elastic/elasticsearch-specification/pull/4954)
=> [8.19] Add missing indices options to index recovery API (#4954)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/indices/delete_alias/IndicesDeleteAliasResponse.ts
- [Fix indices.delete_alias response (#2951)](https://github.com/elastic/elasticsearch-specification/pull/2951)
=> [8.19] Fix indices.delete_alias response (#2951)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, specification/_global/msearch/MultiSearchRequest.ts
This works since at least 7.0: https://github.com/elastic/elasticsearch/pull/27274 and probably way earlier than that. I realized it when working on https://github.com/elastic/elasticsearch/pull/130627.
This fixes our last validation error!
=> Add missing index query parameter to msearch

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, specification/_global/msearch/MultiSearchRequest.ts
- [Add missing index query parameter to msearch (#4980)](https://github.com/elastic/elasticsearch-specification/pull/4980)
=> [8.18] Add missing index query parameter to msearch (#4980)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, specification/_global/msearch/MultiSearchRequest.ts
- [Add missing index query parameter to msearch (#4980)](https://github.com/elastic/elasticsearch-specification/pull/4980)
=> [8.19] Add missing index query parameter to msearch (#4980)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, specification/_global/msearch/MultiSearchRequest.ts
- [Add missing index query parameter to msearch (#4980)](https://github.com/elastic/elasticsearch-specification/pull/4980)
=> [9.1] Add missing index query parameter to msearch (#4980)

package-lock.json, package.json
- [Bump form-data and @redocly/cli (#4999)](https://github.com/elastic/elasticsearch-specification/pull/4999)
=> [8.19] Bump form-data and @redocly/cli (#4999)

specification/_doc_ids/table.csv, specification/_types/mapping/ChunkingSettings.ts, specification/inference/_types/Services.ts, specification/inference/put/examples/request/InferencePutExample1.yaml
This PR adds the new 'none' and 'recursive' chunking strategies to Inference APIs.
Related issue: https://github.com/elastic/developer-docs-team/issues/308
=> [9.1] Adds new 'none' and 'recursive' chunking strategies to Inference APIs

specification/_types/aggregations/Aggregate.ts
As reported in a [Java client issue](https://github.com/elastic/elasticsearch-java/issues/1040), the FiltersBucket aggregation result can have a `key` field if `keyed` was set as false in the request. 
~~No server code, `key` is a common field in aggregation and I couldn't find where it's added to the FiltersAggregation result.~~
[server code](https://github.com/elastic/elasticsearch/blob/f393dbab36e4a0cd5e47898ab7b0908694a9bffc/server/src/main/java/org/elasticsearch/search/aggregations/bucket/filter/InternalFilters.java#L87)
Here's a reproducer: 
```json
PUT /logs/_bulk?refresh
{ "index" : { "_id" : 1 } }
{ "body" : "warning: page could not be rendered" }
{ "index" : { "_id" : 2 } }
{ "body" : "authentication error" }
{ "index" : { "_id" : 3 } }
{ "body" : "warning: connection timed out" …
```
=> Added key field to filter bucket agg

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/transform/update_transform/examples/request/UpdateTransformRequestExample1.yaml
- [Update transform example update (#4998)](https://github.com/elastic/elasticsearch-specification/pull/4998)
NOTE: The changes in the `types.ts` file and the `PutCohereRequestExample3` in the OpenAPI documents do not originate in this PR.
=> [9.0] Update transform example update (#4998)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_types/analysis/tokenizers.ts
It's not handled in the Go generator, does not bring value and this change wasn't released in any client yet.
=> Remove string variant for token_chars field

output/openapi/elasticsearch-serverless-openapi.json, specification/esql/_types/EsqlResult.ts, specification/esql/async_query/AsyncQueryRequest.ts, specification/esql/query/QueryRequest.ts
Spec docs update for the ESQL `format` parameter. Text formats result in missing metadata in the response body.
Main docs change: https://github.com/elastic/docs-content/pull/2307
=> ESQL: Update text formats documentation

output/openapi/elasticsearch-serverless-openapi.json, specification/esql/_types/EsqlResult.ts, specification/esql/async_query/AsyncQueryRequest.ts, specification/esql/query/QueryRequest.ts
Manual 8.19 backport of https://github.com/elastic/elasticsearch-specification/pull/5054
=> [8.19] ESQL: Update text formats documentation (#5054)

specification/sql/query/QuerySqlRequest.ts
Originally reported in https://github.com/elastic/elasticsearch-java/issues/721, `params` in SQL query request is an array of objects, not a map, as per the [documentation](https://www.elastic.co/docs/explore-analyze/query-filter/languages/sql-rest-params) and the [server](https://github.com/elastic/elasticsearch/blob/d8e6cc2096aa7814d1502a756ace7669864f2614/x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/Payloads.java#L209).
=> SQL fix params type

specification/simulate/ingest/examples/request/SimulateIngestRequestExample1.yaml, specification/simulate/ingest/examples/request/SimulateIngestRequestExample2.yaml
These examples were being rendered with the `_id` as an integer, however, that is invalid and we only allow strings for integers.
=> Use strings instead of integer ids for simulate examples

specification/inference/put/PutRequest.ts
(cherry picked from commit b7dbb2aa90e358cdabd6544c4456f3df64f7cb44)
Backport of https://github.com/elastic/elasticsearch-specification/pull/5075
=> [Backport 9.1] Fixing a few missing task types and alphabetizing the PUT request

specification/_global/termvectors/TermVectorsRequest.ts
`TermVectorsRequest.fields` always expects an array.
Related to https://github.com/elastic/elasticsearch-net/issues/8641
=> Change `TermVectorsRequest.fields` from `Fields` to `Field[]`

specification/indices/put_mapping/IndicesPutMappingRequest.ts
Docs tests found a broken link in a docstring, which @KOTungseth fixed in https://github.com/elastic/elasticsearch-js/pull/2959. Just porting the fix to the spec so it stays fixed after the next codegen.
=> Fix broken docs link

specification/_types/aggregations/Aggregate.ts
As titled.
Related to https://github.com/elastic/elasticsearch-net/issues/8570
=> Change type of `ArrayPercentilesItem.key` from `string` to `double`

output/schema/validation-errors.json, output/typescript/types.ts, specification/_json_spec/simulate.ingest.json, specification/simulate/ingest/SimulateIngestRequest.ts
This adds the new `merge_type` query parameter to the specification for the simulate ingest API. The parameter was added in https://github.com/elastic/elasticsearch/pull/132210.
=> Adding the merge_type param to the ingest simulate API

docs/overlays/elasticsearch-openapi-overlays.yaml
This PR fixes the [detail in the Elasticsearch API docs](https://www.elastic.co/docs/api/doc/elasticsearch/v8/) that indicates which branch it's derived from. It incorrectly indicates that the branch used for the v8 API docs is `8.x` but it is in fact `8.19`.
=> [8.19][DOCS] Update repo branch in API docs intro

docs/add-new-api.md
Relates to https://github.com/elastic/elasticsearch-specification/pull/5148
This PR adds a sentence to `add-new-api.md` to clarify recommended behaviour for the `@availability since` property when an API is added to multiple major versions.
=> Add tip about availability since across majors

docs/examples/languageExamples.json, specification/inference/put_ai21/examples/request/PutAi21RequestExample2.yaml, specification/inference/put_amazonsagemaker/examples/request/PutAmazonSageMakerRequestExample1.yaml, specification/inference/put_amazonsagemaker/examples/request/PutAmazonSageMakerRequestExample3.yaml, specification/inference/put_amazonsagemaker/examples/request/PutAmazonSageMakerRequestExample4.yaml, specification/inference/put_custom/examples/request/PutCustomRequestExample5.yaml, specification/snapshot/create/SnapshotCreateRequest.ts, specification/snapshot/create_repository/SnapshotCreateRepositoryRequest.ts, specification/snapshot/delete_repository/SnapshotDeleteRepositoryRequest.ts, specification/snapshot/get/SnapshotGetRequest.ts, specification/snapshot/get_repository/SnapshotGetRepositoryRequest.ts, specification/snapshot/restore/SnapshotRestoreRequest.ts, specification/snapshot/verify_repository/SnapshotVerifyRepositoryRequest.ts
Closes https://github.com/elastic/docs-content/issues/2582
- removes `since=0.0.0` from `Snapshot*` endpoints (all other instances in the repo are in test files)
- some random other changes tagged along
=> [DOCS] Remove instances of `added in 0.0.0` (+ unrelated randomness)

specification/_global/delete_by_query/DeleteByQueryRequest.ts
The delete by query API's `sort` property supports the `Sort` object:
```
"sort": {
"timestamp": {
"order": "desc",
"unmapped_type": "date"
}
}
```
~~But the property's type does not reflect this fact.~~
~~This PR changes the type of `sort` from `string[]` to the more general `Sort` object (as used by the search API):~~
But the body is missing the sort parameter, this PR adds it as `Sort` object.
=> Use `Sort` object in "delete by query"

output/typescript/types.ts, specification/simulate/ingest/SimulateIngestResponse.ts, specification/simulate/ingest/examples/response/SimulateIngestResponseExample3.yaml
The `effective_mapping` field was added to the simulate ingest response in https://github.com/elastic/elasticsearch/pull/132833. This adds it to the specification.
=> Adding effective-mapping to the ingest simulate response

README.md, docs/add-new-api.md, docs/doc-comments-guide.md, docs/schema-structure.md
Backports https://github.com/elastic/elasticsearch-specification/pull/5131 to 9.0.
=> [Backport 9.0] Adds links that point to the API contrib guidelines to repo docs

output/openapi/elasticsearch-serverless-openapi.json, specification/inference/put_llama/examples/request/PutLlamaRequestExample1.yaml, specification/inference/put_llama/examples/request/PutLlamaRequestExample2.yaml, specification/inference/put_llama/examples/request/PutLlamaRequestExample3.yaml
Relates to https://github.com/elastic/elasticsearch-specification/pull/5020
This PR addresses the following errors that were returned by the `make transform-to-openapi-for-docs` command and seem to have been caused by missing commas in the examples:
```
specification/inference/put_llama/examples/request/PutLlamaRequestExample3.yaml: Error: body cannot be parsed
specification/inference/put_llama/examples/request/PutLlamaRequestExample2.yaml: Error: body cannot be parsed
specification/inference/put_llama/examples/request/PutLlamaRequestExample1.yaml: Error: body cannot be parsed
```
=> Fix errors in inference API Llama Service examples

output/openapi/elasticsearch-serverless-openapi.json, specification/inference/put/examples/request/InferencePutExample1.yaml
Relates to https://github.com/elastic/elasticsearch-specification/pull/4841
This PR addresses the following error that was returned by the `make transform-to-openapi-for-docs` command and seems to have been caused by a missing comma and closing bracket in the example:
```
specification/inference/put/examples/request/InferencePutExample1.yaml: Error: body cannot be parsed
```
=> Fix error in put inference example

specification/_global/delete_by_query/DeleteByQueryRequest.ts
Reverts elastic/elasticsearch-specification#5143
=> Revert "Use `Sort` object in "delete by query""

output/typescript/types.ts, specification/_doc_ids/table.csv, specification/transform/set_upgrade_mode/TransformSetUpgradeModeRequest.ts, specification/transform/set_upgrade_mode/TransformSetUpgradeModeResponse.ts, specification/transform/set_upgrade_mode/examples/request/TransformSetUpgradeModeExample1.yaml
Copy/paste docs for ML Upgrade Mode to show how we can enable or disable Transform Upgrade Mode
Relates https://github.com/elastic/elasticsearch/issues/132510
=> [Transform] Upgrade Mode

output/typescript/types.ts, specification/_doc_ids/table.csv, specification/transform/set_upgrade_mode/TransformSetUpgradeModeRequest.ts, specification/transform/set_upgrade_mode/TransformSetUpgradeModeResponse.ts, specification/transform/set_upgrade_mode/examples/request/TransformSetUpgradeModeExample1.yaml
- [[Transform] Upgrade Mode (#5165)](https://github.com/elastic/elasticsearch-specification/pull/5165)
=> [8.19] [Transform] Upgrade Mode (#5165)

output/typescript/types.ts, specification/_doc_ids/table.csv, specification/transform/set_upgrade_mode/TransformSetUpgradeModeRequest.ts, specification/transform/set_upgrade_mode/TransformSetUpgradeModeResponse.ts, specification/transform/set_upgrade_mode/examples/request/TransformSetUpgradeModeExample1.yaml
- [[Transform] Upgrade Mode (#5165)](https://github.com/elastic/elasticsearch-specification/pull/5165)
=> [8.18] [Transform] Upgrade Mode (#5165)

specification/_global/delete_by_query/DeleteByQueryRequest.ts
DeleteByQuery doesn't support the query parameter `sort`
=> Deprecating sort in delete by query

Makefile, specification/eslint.config.js
Right now, all rules pass, but this needs to be enforced:
- by setting the severity to `error`
- and running lint as part of `make contrib`, which runs in CI.
=> Run custom eslint rules as part of CI

specification/_types/mapping/ChunkingSettings.ts, specification/inference/_types/Services.ts
This PR updates the `InferenceChunkingSettings` type by making the `separator_group` and `separators` fields optional.
These fields are only applicable to the `recursive` strategy and required when using it.
Updated the field descriptions to clarify their usage.
=> Sets 'separators' and 'separators_group' parameters to optional and updates descriptions

compiler/src/model/utils.ts, compiler/test/body-codegen-name/specification/_global/index/request.ts, compiler/test/duplicate-body-codegen-name/specification/_global/index/request.ts, compiler/test/no-body/specification/_global/info/request.ts, compiler/test/no-doc-id/specification/_global/info/request.ts, compiler/test/no-doc-id/specification/tsconfig.json, compiler/test/no-doc-id/test.ts, compiler/test/request-availability/specification/_global/index/request.ts, compiler/test/types/specification/_global/info/request.ts, compiler/test/types/test.ts, compiler/test/writes-to-output/specification/_global/index/request.ts, compiler/test/wrong-namespace/specification/_global/foobar/request.ts
- [Enforce doc_id tag on public APIs (#5198)](https://github.com/elastic/elasticsearch-specification/pull/5198)
=> [9.0] Enforce doc_id tag on public APIs (#5198)

specification/indices/rollover/IndicesRolloverRequest.ts
Linked to https://github.com/elastic/docs-content/issues/2385
Updated tip to state that Serverless does not support ILM
=> update tip to state no support for ILM in Serverless

output/openapi/elasticsearch-serverless-openapi.json, specification/inference/_types/Services.ts, specification/inference/put_elser/PutElserRequest.ts
Updates the max values for chunking settings to be in line with this PR to remove the upper bound: https://github.com/elastic/elasticsearch/pull/133718
=> Update specification to clarify max chunking settings

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/_doc_ids/table.csv, specification/inference/_types/CommonTypes.ts
This PR updates the specification to include the `thinking_config` object that was added to `task_settings` for Google Vertex AI inference endpoint creation in elastic/elasticsearch#133599.
=> [ML] Include thinking_config in GoogleVertexAITaskSettings

specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts, specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts, specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts, specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts, specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts, specification/shutdown/get_node/ShutdownGetNodeRequest.ts, specification/shutdown/put_node/ShutdownPutNodeRequest.ts
shutdown and autoscaling APIs are private in rest-api-spec, and were never meant to receive public usage. This change means they will disappear from documentation and language clients.
See https://github.com/elastic/elasticsearch/pull/77493#issuecomment-919126185 where it was done in the rest-api-spec. We missed it in the Elasticsearch specification.
I'm not sure about the 8.19 backport.
=> Mark cloud-only APIs as private

specification/ml/_types/Datafeed.ts, specification/ml/update_datafeed/MlUpdateDatafeedResponse.ts
As per [this issue](https://github.com/elastic/docs-content/issues/1463), the descriptions for the `frequency` parameter were missing from the ML anomaly detection APIs.
[This issue](https://github.com/elastic/elasticsearch-specification/issues/4473) fixed the parameter descriptions in the request bodies, but the response descriptions were still missing.
After discussing with @l-trotta, we decided to add them manually. This PR adds the missing descriptions for the following API responses:
- Create an anomaly detection job
- Preview a datafeed
- Update an anomaly detection job
- Update a datafeed
=> Adds description for the 'frequency' parameter in responses

specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts, specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts, specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts, specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts, specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts, specification/shutdown/get_node/ShutdownGetNodeRequest.ts, specification/shutdown/put_node/ShutdownPutNodeRequest.ts
- [Mark cloud-only APIs as private (#5235)](https://github.com/elastic/elasticsearch-specification/pull/5235)
=> [8.19] Mark cloud-only APIs as private (#5235)

output/openapi/elasticsearch-serverless-openapi.json, output/schema/validation-errors.json, output/typescript/types.ts, specification/_spec_utils/behaviors.ts, specification/cat/allocation/CatAllocationRequest.ts, specification/cat/fielddata/CatFielddataRequest.ts, specification/cat/health/CatHealthRequest.ts, specification/cat/indices/CatIndicesRequest.ts, specification/cat/ml_data_frame_analytics/CatDataFrameAnalyticsRequest.ts, specification/cat/ml_datafeeds/CatDatafeedsRequest.ts, specification/cat/ml_jobs/CatJobsRequest.ts, specification/cat/ml_trained_models/CatTrainedModelsRequest.ts, specification/cat/nodes/CatNodesRequest.ts, specification/cat/pending_tasks/CatPendingTasksRequest.ts, specification/cat/recovery/CatRecoveryRequest.ts, specification/cat/segments/CatSegmentsRequest.ts, specification/cat/shards/CatShardsRequest.ts, specification/cat/snapshots/CatSnapshotsRequest.ts, specification/cat/tasks/CatTasksRequest.ts, specification/cat/thread_pool/CatThreadPoolRequest.ts, specification/cat/transforms/CatTransformsRequest.ts, specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts, specification/shutdown/get_node/ShutdownGetNodeRequest.ts, specification/shutdown/put_node/ShutdownPutNodeRequest.ts
Describes the `?bytes=` and `?time=` parameters which are accepted by
all the `GET _cat/...` APIs.
Backport of #5298 to `8.19`
=> [8.19] Add common cat API parameters for unit rendering

specification/inference/put_custom/PutCustomRequest.ts
Making correction to the release version when this functionality was added.
The functionality was added in 8.19: https://github.com/elastic/elasticsearch/pull/127939
=> Correcting release version to 8.19.0 for custom service for the inference API

specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts, specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts, specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts, specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts, specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts, specification/shutdown/get_node/ShutdownGetNodeRequest.ts, specification/shutdown/put_node/ShutdownPutNodeRequest.ts
- [Mark cloud-only APIs as private (#5235)](https://github.com/elastic/elasticsearch-specification/pull/5235)
=> [9.1] Mark cloud-only APIs as private (#5235)

specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts, specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts, specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts, specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts, specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts, specification/shutdown/get_node/ShutdownGetNodeRequest.ts, specification/shutdown/put_node/ShutdownPutNodeRequest.ts
- [Mark cloud-only APIs as private (#5235)](https://github.com/elastic/elasticsearch-specification/pull/5235)
=> [9.0] Mark cloud-only APIs as private (#5235)

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/ingest/_types/Pipeline.ts, specification/ingest/put_pipeline/PutPipelineRequest.ts
Adds the new field access pattern to the specification. I didn't update any example code because this is not really expected to be a common option to set.
Relates to:
* https://github.com/elastic/elasticsearch/pull/133270
* https://github.com/elastic/docs-content/pull/2994
Closes #5310
=> Add ingest field access pattern to specification

specification/_types/aggregations/bucket.ts
As titled. Also marks `CompositeAggregationSource` as a container since the aggregations are mutually exclusive.
This fix as well greatly improves the quality of the generated code for the .NET client (see [#8704](https://github.com/elastic/elasticsearch-net/issues/8704)).
Server code:
https://github.com/elastic/elasticsearch/blob/a59c182f9f7e9d1bf3d6eecbc0e44f24ff91d053/server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeValuesSourceParserHelper.java#L78
No backport, since this is a breaking change for statically typed languages.
=> `CompositeAggregation.sources` expects an array of single-key objects

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/indices/put_alias/IndicesPutAliasRequest.ts, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample1.yaml, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample2.yaml, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample3.yaml
- [Fix alias examples (#5331)](https://github.com/elastic/elasticsearch-specification/pull/5331)
=> [9.1] Fix alias examples (#5331)

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/indices/put_alias/IndicesPutAliasRequest.ts, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample1.yaml, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample2.yaml, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample3.yaml
- [Fix alias examples (#5331)](https://github.com/elastic/elasticsearch-specification/pull/5331)
=> [9.0] Fix alias examples (#5331)

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/indices/put_alias/IndicesPutAliasRequest.ts, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample1.yaml, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample2.yaml, specification/indices/put_alias/examples/request/indicesPutAliasRequestExample3.yaml
- [Fix alias examples (#5331)](https://github.com/elastic/elasticsearch-specification/pull/5331)
=> [8.19] Fix alias examples (#5331)

.github/validate-pr/index.js, specification/_types/Base.ts
- [Validate all APIs in PRs (#5341)](https://github.com/elastic/elasticsearch-specification/pull/5341)
=> [8.19] Validate all APIs in PRs (#5341)

.github/validate-pr/index.js, specification/_types/Base.ts
- [Validate all APIs in PRs (#5341)](https://github.com/elastic/elasticsearch-specification/pull/5341)
=> [9.0] Validate all APIs in PRs (#5341)

.github/workflows/validate-pr.yml
- [Validate PRs against correct branch (#5344)](https://github.com/elastic/elasticsearch-specification/pull/5344)
=> [9.0] Validate PRs against correct branch (#5344)

.github/workflows/validate-pr.yml
- [Validate PRs against correct branch (#5344)](https://github.com/elastic/elasticsearch-specification/pull/5344)
=> [8.19] Validate PRs against correct branch (#5344)

Makefile, docs/overlays/elasticsearch-shared-overlays.yaml
This PR updates the DOCS_BRANCHi in the Makefile so that the appropriate URLs are generated.
I noticed it was still linking to "8.x" URLs in https://github.com/elastic/elasticsearch-specification/pull/5339
=> Update DOCS_BRANCH from 8.x to 8.19

compiler/run-validations.js
I had trouble running `make validate` on 8.19, and it turns out it was a weird interaction with an outdated `lib` content. Using the npm commands referenced by `make contrib` is simpler and more robust.
=> Rely on npm more in make validate

output/openapi/elasticsearch-serverless-openapi.json, output/typescript/types.ts, specification/esql/_types/types.ts, specification/esql/query/QueryRequest.ts
As agreed offline, this is the only way to support multi-valued parameters in ES|QL, scheduled for 9.2.
Relates https://github.com/elastic/elasticsearch/pull/134317
=> [BREAKING] Support mutli-valued ES|QL parameters

specification/ilm/_types/Phase.ts, specification/indices/rollover/types.ts
Add deprecation notice for the `max_size` condition used for rollovers and ILM policies
Relates to: elastic/elasticsearch#130737
=> Add deprecation notice for max_size rollover condition

.github/workflows/code-format.yml, .github/workflows/compiler-rs.yml, .github/workflows/compiler.test.yml, .github/workflows/generate.yml, .github/workflows/license.yml, .github/workflows/linter.yml, .github/workflows/metamodel-sync.yml, .github/workflows/update-rest-api-json.yml, .github/workflows/validate-apis.yml
- [ci: bump action scripts versions (#5400)](https://github.com/elastic/elasticsearch-specification/pull/5400)
=> [9.1] ci: bump action scripts versions (#5400)

output/typescript/types.ts, specification/cluster/stats/types.ts
Adds the extended search usage implemented in https://github.com/elastic/elasticsearch/pull/135306 to the specification
=> Add extended search usage to spec

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_types/Time.ts
- [Add external docs link from Duration to time unit API conventions (#5409)](https://github.com/elastic/elasticsearch-specification/pull/5409)
=> [9.0] Add external docs link from Duration to time unit API conventions (#5409)

output/openapi/elasticsearch-serverless-openapi.json, specification/_doc_ids/table.csv, specification/_types/Time.ts
- [Add external docs link from Duration to time unit API conventions (#5409)](https://github.com/elastic/elasticsearch-specification/pull/5409)
=> [8.19] Add external docs link from Duration to time unit API conventions (#5409)

compiler/src/model/build-model.ts, output/typescript/types.ts
While we still depend on visibility and stability from rest-api-spec JSON, we have to override availability.stack for APIs that are only available on serverless.
=> Serverless-only availability hack

compiler/src/compiler.ts, compiler/src/model/build-model.ts
`json-spec` files do not differentiate `stack` from `serverless` as the recent `project.tags` endpoint has shown.
This moves the propagation for the availability sync from early on to last step to avoid assigning to stack by default if the endpoint has the relevant information in the typescript files.
=> Compiler: late sync endpoints availability from json-spec

specification/_global/reindex/types.ts
Field `_source` should be the same type as in SearchRequest, so a `SearchConfig`. [server code](https://github.com/elastic/elasticsearch/blob/e702edcbab3720c0f99a78fa472af24cafaab850/server/src/main/java/org/elasticsearch/index/reindex/ReindexRequest.java#L91)
This is a breaking change, and currently it partially works (when the value of _source is a boolean) (thanks @pquentin!)
=> Fix reindex validation

specification/security/_types/ApiKey.ts, specification/security/create_cross_cluster_api_key/CreateCrossClusterApiKeyRequest.ts, specification/security/update_cross_cluster_api_key/UpdateCrossClusterApiKeyRequest.ts
Add certificate_identity field to API key specs
Updates specification for create/update cross-cluster API key endpoints and ApiKey response type to include certificate_identity field.
PR that adds this functionality: https://github.com/elastic/elasticsearch/pull/134604
=> Add certificate identity field to Cross-Cluster API Key Specs

specification/_types/mapping/DenseVectorProperty.ts
Add `on_disk_rescore` option added by https://github.com/elastic/elasticsearch/pull/135778
=> Add on_disk_rescore to bbq_disk
