elastic/elasticsearch-specification

.gitignore
java-generator/enums.ts
java-generator/imports.ts
java-generator/index.ts
java-generator/naming.ts
java-generator/package-lock.json
java-generator/package.json
java-generator/specs.ts
java-generator/tsconfig.json
java-generator/tslint.json
java-generator/types-parser-read.ts
java-generator/types-parser-write.ts
java-generator/types-union.ts
java-generator/types-value.ts
java-generator/types.ts
specification/src/api-specification.ts
specification/src/domain.ts
specification/src/specification/type-reader.ts

This adds a java-generator without the output.

Java client generator

---

specification/specs/common.ts
specification/src/api-specification.ts
specification/src/domain.ts
specification/src/specification/type-reader.ts

Added NumberAlias

---

specification/specs/common.ts
specification/specs/common_options/scripting/InlineScript.ts
specification/specs/common_options/scripting/Script.ts
specification/specs/document/single/create/CreateRequest.ts
specification/specs/document/single/create/CreateResponse.ts
specification/specs/document/single/delete/DeleteRequest.ts
specification/specs/document/single/delete/DeleteResponse.ts
specification/specs/document/single/get/GetRequest.ts
specification/specs/document/single/get/GetResponse.ts
specification/specs/document/single/index/IndexRequest.ts
specification/specs/document/single/index/IndexResponse.ts
specification/specs/document/single/update/UpdateRequest.ts
specification/specs/document/single/update/UpdateResponse.ts
specification/specs/search/search/SearchRequest.ts
specification/src/domain.ts
specification/src/specification/type-reader.ts
typescript-generator/index.ts

Iterating on the spec (part 5) 

---

specification/specs/common/Refresh.ts

Fixes `create request` failures in combination with https://github.com/elastic/clients-flight-recorder/pull/569

remodels Refresh as a union of bool | RefreshOptions

---

output/typescript/types.ts
specification/specs/aggregations/AggregationContainer.ts
specification/specs/aggregations/bucket/date_histogram/DateHistogramAggregation.ts
specification/specs/aggregations/bucket/histogram/HistogramAggregation.ts
specification/specs/aggregations/bucket/variable_width_histogram/VariableWidthHistogramAggregation.ts
specification/specs/aggregations/metric/top_hits/TopHitsAggregation.ts
specification/specs/common.ts
specification/specs/common_options/time_unit/Time.ts
specification/specs/query_dsl/abstractions/container/QueryContainer.ts
specification/specs/query_dsl/specialized/distance_feature/DistanceFeatureQuery.ts
specification/specs/query_dsl/term_level/range/RangeQuery.ts
specification/specs/search/search/SearchRequest.ts
specification/specs/search/search/inner_hits/InnerHits.ts
specification/specs/search/search/point_in_time/PointInTimeReference.ts
specification/specs/search/search/sort/NestedSort.ts

Adds missing aggregations
PIT 
Formated date field lookups 
and others

Update types so that Search Requests validates

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/common_options/hit/ShardStatistics.ts
specification/specs/document/multiple/bulk/BulkResponse.ts
specification/specs/document/multiple/bulk/bulk_response_item/BulkResponseItemBase.ts
specification/specs/document/single/WriteResponseBase.ts
specification/specs/document/single/get/GetResponse.ts
specification/specs/document/single/update/UpdateResponse.ts
specification/specs/search/explain/InlineGet.ts
typescript-generator/index.js

- update optional properties in create response
- fix bulk, index, update and delete

Update specification to include optional on responses

---

specification/specs/indices/index_management/freeze_index/FreezeIndexRequest.ts
specification/specs/indices/index_management/freeze_index/FreezeIndexResponse.ts

First attempt at fixing an API, is there a way we want to word our commits?

Update and stabilize 'indices.freeze' API

---

specification/specs/cat/cat_aliases/CatAliasesRecord.ts
specification/specs/cat/cat_aliases/CatAliasesRequest.ts
specification/specs/common/ExpandWildcards.ts

Added request & response without the CSV validation.

Cat Aliases

---

.github/workflows/output-check.yml
output/schema/schema.json
output/typescript/types.ts

Add github action to check output freshness

---

.github/auto-label.json
.github/workflows/auto-label.yml

As titled. This will automate the label handling and make it easier in the future to filter pull requests.

Add auto label action

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/analysis/token_filters/ITokenFilter.ts
specification/specs/indices/analyze/AnalyzeDetail.ts
specification/specs/indices/analyze/AnalyzeRequest.ts
specification/specs/indices/analyze/AnalyzeResponse.ts
specification/specs/indices/analyze/AnalyzeToken.ts
specification/specs/indices/analyze/AnalyzerDetail.ts
specification/specs/indices/analyze/ExplainAnalyzeToken.ts

Fix request and response for indices analyze.

Indices Analyze

---

README.md
docs/special-classes.md
output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/ping/PingResponse.ts
specification/specs/common_abstractions/response/HeadResponseBase.ts
specification/specs/document/single/exists/DocumentExistsResponse.ts
specification/specs/document/single/source_exists/SourceExistsResponse.ts
specification/specs/indices/alias_management/alias_exists/AliasExistsResponse.ts
specification/specs/indices/index_management/indices_exists/ExistsResponse.ts
specification/specs/indices/index_management/indices_exists/IndexExistsResponse.ts
specification/specs/indices/index_management/types_exists/TypeExistsResponse.ts
specification/specs/indices/index_settings/index_templates/index_template_exists/IndexTemplateExistsResponse.ts
specification/src/specification/type-reader.ts
typescript-generator/index.js

As titled.
I've added a new section in the docs as well to track the "special classes" that we are using.
Closes: #74

Introduce HeadResponseBase

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/modules/snapshot_and_restore/snapshot/SnapshotInfo.ts
specification/specs/modules/snapshot_and_restore/snapshot/snapshot/SnapshotResponse.ts

Fix response type to resolve failures. I reviewed the Java code to refine a few other fields which were missing/not marked as optional.

Snapshot Create Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/common/WaitForActiveShardOptions.ts

Cluster Health Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/search/count/CountRequest.ts

Validated Count Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/single/source/SourceRequest.ts

get_source request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_reroute/ClusterRerouteRequest.ts

Fixed One Error in Cluster.Reroute Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/search/field_capabilities/FieldCapabilities.ts
specification/specs/search/field_capabilities/FieldCapabilitiesRequest.ts
specification/specs/search/field_capabilities/FieldCapabilitiesResponse.ts

Validated field_caps Req & Res

---

output/schema/schema.json
specification/compiler/model/metamodel.ts
specification/compiler/steps/add-info.ts

As titled.
Closes https://github.com/elastic/elastic-client-generator/issues/97

Add _info field to json output

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_allocation_explain/ClusterAllocationExplainResponse.ts

Fix typo in cluster explain response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/aggregations/bucket/terms/TermsAggregation.ts
specification/specs/common_options/hit/ShardStatistics.ts
specification/specs/document/single/update/UpdateResponse.ts

Keep the target APIs green

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/search/scroll/scroll/ScrollRequest.ts
specification/specs/search/scroll/scroll/ScrollResponse.ts
specification/specs/search/search/SearchResponse.ts

Validate Scroll request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_master/CatMasterRecord.ts

Validate cat.master response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_tasks/CatTasksRecord.ts

Cat Tasks Response

---

output/typescript/types.ts
typescript-generator/index.js
typescript-generator/package.json
typescript-generator/tsconfig.json

Avoid properties collisions and validate output

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/indices/monitoring/indices_recovery/RecoveryBytes.ts
specification/specs/indices/monitoring/indices_recovery/RecoveryFiles.ts
specification/specs/indices/monitoring/indices_recovery/RecoveryIndexStatus.ts
specification/specs/indices/monitoring/indices_recovery/RecoveryOrigin.ts
specification/specs/indices/monitoring/indices_recovery/RecoveryTranslogStatus.ts
specification/specs/indices/monitoring/indices_recovery/RecoveryVerifyIndex.ts
specification/specs/indices/monitoring/indices_recovery/ShardRecovery.ts

Validate indices.recovery Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common_abstractions/response/IndicesResponseBase.ts

Validate indices.delete

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/graph/explore/request/GraphExploreControls.ts
specification/specs/x_pack/graph/explore/request/GraphVertexDefinition.ts
specification/specs/x_pack/graph/explore/request/Hop.ts

Validated graph.explore Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_node_attributes/CatNodeAttributesRecord.ts

Validate cat.nodeattrs Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_trained_models/CatTrainedModelsRecord.ts

Validated cat.ml_trained_models Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_datafeeds/CatDatafeedsRecord.ts

Validated cat.ml_datafeeds Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_snapshots/CatSnapshotsRecord.ts

Validate cat.snapshots Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_templates/CatTemplatesRecord.ts

Validate cat.templates Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/enrich/EnrichPolicy.ts

Fix enrich.put_policy request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/NodeStatistics.ts
specification/specs/x_pack/watcher/watcher_stats/WatchRecordQueuedStats.ts
specification/specs/x_pack/watcher/watcher_stats/WatchRecordStats.ts
specification/specs/x_pack/watcher/watcher_stats/WatcherNodeStats.ts
specification/specs/x_pack/watcher/watcher_stats/WatcherStatsResponse.ts

Validation watcher.stats Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/license/start_basic_license/StartBasicLicenseResponse.ts

Fix license.post_start_basic response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/job/results/AnomalyRecord.ts

Fix ml.get_records response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/x_pack/ilm/Phase.ts
specification/specs/x_pack/ilm/Phases.ts
specification/specs/x_pack/ilm/delete_lifecycle/DeleteLifecycleRequest.ts
specification/specs/x_pack/ilm/put_lifecycle/PutLifecycleRequest.ts

Validated ilm.delete_lifecycle & ilm.put_lifecycle Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/search/field_capabilities/FieldCapabilitiesRequest.ts

Fix field_caps Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/modules/scripting/get_script/GetScriptResponse.ts

Fix get_script Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/search/explain/ExplainRequest.ts
specification/specs/search/explain/ExplainResponse.ts
specification/specs/search/explain/ExplanationDetail.ts
specification/specs/search/explain/InlineGet.ts

Validate Explain API

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/indices/index_management/open_close_index/open_index/OpenIndexResponse.ts

Fix indices.open Response

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/start_datafeed/StartDatafeedResponse.ts

Dangling.csv got generated but I'm not entirely sure if it was due to my change, included it for the time being.

Fix ml.start_datafeed response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/nodes_usage/NodeUsageInformation.ts

Fix NodeUsageInformation used by nodes.usage response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_health/CatHealthRecord.ts
specification/specs/cat/cat_health/CatHealthRequest.ts

Validated cat.health Req & Res

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/indices/status_management/synced_flush/SyncedFlushResponse.ts

Fix indices.flush_synced response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/multiple/delete_by_query/DeleteByQueryResponse.ts
specification/specs/search/scroll/scroll/SlicedScroll.ts

Delete by query Req & Res

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/aggregations/Aggregate.ts
specification/specs/aggregations/AggregationContainer.ts
specification/specs/aggregations/metric/geo_line/GeoLineAggregation.ts
specification/specs/common_options/date_math/DateMathTime.ts
specification/specs/query_dsl/geo/GeoLocation.ts

Fix remaining search response failures

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cat/cat_thread_pool/CatThreadPoolRecord.ts
specification/specs/cat/cat_thread_pool/CatThreadPoolRequest.ts

Fix cat.thread_pool Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_stats/ClusterIndicesShardsStats.ts
specification/specs/cluster/cluster_stats/ClusterIndicesStats.ts
specification/specs/cluster/cluster_stats/ClusterNodeCount.ts
specification/specs/common_options/stats/PluginStats.ts

Validates cluster.stats

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/task_management/list_tasks/ListTasksResponse.ts
specification/specs/cluster/task_management/list_tasks/TaskState.ts

Validates delete_by_query_rethrottle

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/async_search/AsyncSearch.ts
specification/specs/x_pack/async_search/AsyncSearchResponseBase.ts
specification/specs/x_pack/async_search/get/AsyncSearchGetResponse.ts
specification/specs/x_pack/async_search/status/AsyncSearchStatusRequest.ts
specification/specs/x_pack/async_search/status/AsyncSearchStatusResponse.ts
specification/specs/x_pack/async_search/submit/AsyncSearchSubmitResponse.ts

Add support for various AsyncSearch api's

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts

Add unsigned int and long

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/task_management/get_task/GetTaskResponse.ts
specification/specs/cluster/task_management/get_task/TaskInfo.ts
specification/specs/cluster/task_management/list_tasks/TaskStatus.ts

Validate tasks.get Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/transform/TransformDestination.ts
specification/specs/x_pack/transform/update_transform/UpdateTransformResponse.ts

not fixed but partially improved.

Improve Response of transform.update_transform

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/document/multiple/update_by_query/UpdateByQueryResponse.ts

Fix update_by_query Response

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/_json_spec/text_structure.find_structure.json
specification/specs/cluster/cluster_settings/cluster_get_settings/ClusterGetSettingsResponse.ts
specification/specs/indices/analyze/AnalyzeRequest.ts
specification/specs/x_pack/info/x_pack_usage/DatafeedCount.ts
specification/specs/x_pack/info/x_pack_usage/Job.ts
specification/specs/x_pack/info/x_pack_usage/MachineLearningUsage.ts
specification/specs/x_pack/machine_learning/datafeed/ChunkingConfig.ts
specification/specs/x_pack/machine_learning/datafeed/Datafeed.ts
specification/specs/x_pack/machine_learning/datafeed/DatafeedConfig.ts
specification/specs/x_pack/machine_learning/get_datafeeds/GetDatafeedsRequest.ts
specification/specs/x_pack/machine_learning/get_datafeeds/GetDatafeedsResponse.ts
specification/specs/x_pack/machine_learning/get_jobs/GetJobsRequest.ts
specification/specs/x_pack/machine_learning/job/config/AnalysisConfig.ts
specification/specs/x_pack/machine_learning/job/config/AnalysisLimits.ts
specification/specs/x_pack/machine_learning/job/config/DataDescription.ts
specification/specs/x_pack/machine_learning/job/config/JobStats.ts
specification/specs/x_pack/machine_learning/job/config/ModelPlotConfig.ts
specification/specs/x_pack/machine_learning/job/detectors/DetectionRule.ts
specification/specs/x_pack/machine_learning/job/detectors/Detector.ts
specification/specs/x_pack/machine_learning/job/process/DataCounts.ts
specification/specs/x_pack/machine_learning/machine_learning_info/CategorizationAnalyzer.ts
specification/specs/x_pack/machine_learning/machine_learning_info/Limits.ts
specification/specs/x_pack/machine_learning/post_job_data/PostJobDataResponse.ts
specification/specs/x_pack/machine_learning/put_datafeed/PutDatafeedRequest.ts
specification/specs/x_pack/machine_learning/update_job/UpdateJobRequest.ts
specification/specs/x_pack/text_structure/FindStructure.ts

As titled.
All `Id` issues will be fixed in a separate pr.
Related: https://github.com/elastic/kibana/pull/83808#issuecomment-791479571
/cc @jgowdyelastic

Updated ML definitions

---

.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/missing-type.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/wrong-type.md

Added issue template

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/indices/index_management/open_close_index/close_index/CloseIndexResponse.ts
specification/specs/indices/index_management/open_close_index/close_index/CloseIndexResult.ts

Fix indices.close response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/task_management/list_tasks/TaskStatus.ts

Validate DeleteByQueryRethrottle response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/license/get_license/LicenseInformation.ts

Validate license.get response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/indices/index_management/create_index/CreateIndexRequest.ts
specification/specs/mapping/TypeMapping.ts
specification/specs/mapping/meta_fields/source/SourceField.ts

Fix indices.create request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/enrich/NamedPolicyConfig.ts
specification/specs/x_pack/enrich/execute_policy/ExecuteEnrichPolicyResponse.ts

* `enrich.execute_policy`
* `enrich.get_policy`

Validate Enrich.* Responses

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common_options/hit/ShardStatistics.ts
specification/specs/x_pack/async_search/AsyncSearchResponseBase.ts
specification/specs/x_pack/async_search/status/AsyncSearchStatusResponse.ts

Validate async_search.status Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/transform/get_transform_stats/TransformCheckpointStats.ts
specification/specs/x_pack/transform/get_transform_stats/TransformCheckpointingInfo.ts
specification/specs/x_pack/transform/get_transform_stats/TransformStats.ts

Fixed transform.get_transform_stats Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/task_management/cancel_tasks/CancelTasksRequest.ts
specification/specs/cluster/task_management/cancel_tasks/CancelTasksResponse.ts

Fix Tasks.cancel Req & Resp

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/single/term_vectors/TermVectorFilter.ts
specification/specs/document/single/term_vectors/TermVectorTerm.ts
specification/specs/document/single/term_vectors/TermVectorsResponse.ts
specification/specs/document/single/term_vectors/Token.ts

Validate Termvectors Req & Resp

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/security/api_key/create_api_key/CreateApiKeyResponse.ts
specification/specs/x_pack/security/api_key/get_api_key/ApiKeys.ts
specification/specs/x_pack/security/authenticate/AuthenticateResponse.ts
specification/specs/x_pack/security/clear_cached_realms/ClearCachedRealmsResponse.ts
specification/specs/x_pack/security/privileges/put_privileges/PutPrivilegesRequest.ts
specification/specs/x_pack/security/role/FieldSecurity.ts
specification/specs/x_pack/security/role/clear_cached_roles/ClearCachedRolesResponse.ts
specification/specs/x_pack/security/role/put_role/IndicesPrivileges.ts
specification/specs/x_pack/security/role_mapping/put_role_mapping/PutRoleMappingResponse.ts

* security.authenticate response
* security.clear_cached_realms response
* security.clear_cached_roles response
* security.create_api_key response
* security.get_api_key response
* security.get_role response
* security.put_role_mapping response
* security.put_privileges request
* security.put_role request

Validated all Security.* enpoints

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/job/config/AnalysisConfig.ts
specification/specs/x_pack/machine_learning/job/config/JobStats.ts
specification/specs/x_pack/machine_learning/job/config/ModelPlotConfig.ts

Additional ml fixes

---

output/schema/schema.json
output/typescript/types.ts
specification/compiler/model/json-spec.ts
specification/compiler/model/metamodel.ts
specification/compiler/steps/add-content-type.ts

Add accept and contentType to canonical json

---

.github/auto-label.json
output/schema/schema.json
output/typescript/types.ts
specification/compiler/steps/validate-model.ts

As titled, the fix is ugly, but it's needed.

Add error response back

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/multiple/reindex/ReindexResponse.ts
specification/specs/query_dsl/term_level/ids/IdsQuery.ts

Fix Reindex Req & Resp

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/license/get_license/License.ts
specification/specs/x_pack/license/post_license/PostLicenseRequest.ts
specification/specs/x_pack/license/post_license/PostLicenseResponse.ts
specification/specs/x_pack/license/start_trial_license/StartTrialLicenseResponse.ts

* `license.post_start_trial` response
* `license.post` response + request

Fixed License.* endpoints

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/search/scroll/clear_scroll/ClearScrollRequest.ts

fixed clear_scroll request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/ssl/get_certificates/ClusterCertificateInformation.ts
specification/specs/x_pack/ssl/get_certificates/GetCertificatesResponse.ts

Fix ssl.certificates response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/search/search/point_in_time/PointInTimeReference.ts
specification/specs/x_pack/async_search/AsyncSearch.ts
specification/specs/x_pack/async_search/AsyncSearchResponseBase.ts
specification/specs/x_pack/async_search/get/AsyncSearchGetRequest.ts
specification/specs/x_pack/async_search/submit/AsyncSearchSubmitRequest.ts

* `async_search.submit` request + response
* `async_search.get` request

Fix Async.* endpoints

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/info/x_pack_usage/SnapshotLifecycleStats.ts
specification/specs/x_pack/slm/SnapshotLifecycleConfig.ts
specification/specs/x_pack/slm/SnapshotLifecyclePolicyMetadata.ts
specification/specs/x_pack/slm/get_lifecycle/GetSnapshotLifecycleResponse.ts

Fix slm.get_lifecycle Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/slm/get_stats/GetSnapshotLifecycleStatsResponse.ts

Fix slm.get_stats Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/modules/snapshot_and_restore/repositories/SnapshotRepositorySettings.ts
specification/specs/modules/snapshot_and_restore/repositories/create_repository/CreateRepositoryRequest.ts
specification/specs/modules/snapshot_and_restore/repositories/get_repository/GetRepositoryResponse.ts
specification/specs/modules/snapshot_and_restore/snapshot/SnapshotInfoFeatureState.ts

* `snapshot.create_repository` request
* `snapshot.get_repository` response
* `snapshot.create` response

Validated Snapshot.* endpoints

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_settings/cluster_get_settings/ClusterGetSettingsResponse.ts

Fix cluster.get_settings Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/pit/ClosePointInTimeRequest.ts
specification/specs/x_pack/pit/ClosePointInTimeResponse.ts
specification/specs/x_pack/pit/OpenPointInTimeRequest.ts
specification/specs/x_pack/pit/OpenPointInTimeResponse.ts

added the request & response for:
* `open_point_in_time`
* `close_point_in_time`

Point in Time Endpoints

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/modules/snapshot_and_restore/snapshot/SnapshotInfo.ts
specification/specs/modules/snapshot_and_restore/snapshot/snapshot_status/SnapshotStatus.ts

Fix Snapshot.get Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/modules/snapshot_and_restore/snapshot/clone_snapshot/CloneSnapshotRequest.ts
specification/specs/modules/snapshot_and_restore/snapshot/clone_snapshot/CloneSnapshotResponse.ts

Add snapshot.clone Endpoint

---

Makefile
output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/ilm/Phase.ts
specification/specs/x_pack/info/x_pack_info/MinimalLicenseInformation.ts
specification/specs/x_pack/info/x_pack_info/XPackFeature.ts
specification/specs/x_pack/info/x_pack_info/XPackFeatures.ts
specification/specs/x_pack/info/x_pack_usage/AlertingInput.ts
specification/specs/x_pack/info/x_pack_usage/AlertingUsage.ts
specification/specs/x_pack/info/x_pack_usage/AnalyticsUsage.ts
specification/specs/x_pack/info/x_pack_usage/AuditUsage.ts
specification/specs/x_pack/info/x_pack_usage/DataStreamsUsage.ts
specification/specs/x_pack/info/x_pack_usage/DataTiersUsage.ts
specification/specs/x_pack/info/x_pack_usage/EqlFeaturesUsage.ts
specification/specs/x_pack/info/x_pack_usage/EqlUsage.ts
specification/specs/x_pack/info/x_pack_usage/FrozenIndicesUsage.ts
specification/specs/x_pack/info/x_pack_usage/Job.ts
specification/specs/x_pack/info/x_pack_usage/MachineLearningUsage.ts
specification/specs/x_pack/info/x_pack_usage/MlDataFrameAnalyticsJobsUsage.ts
specification/specs/x_pack/info/x_pack_usage/MlInferenceUsage.ts
specification/specs/x_pack/info/x_pack_usage/RealmUsage.ts
specification/specs/x_pack/info/x_pack_usage/RuntimeFieldsUsage.ts
specification/specs/x_pack/info/x_pack_usage/SearchableSnapshotsUsage.ts
specification/specs/x_pack/info/x_pack_usage/SecurityRolesUsage.ts
specification/specs/x_pack/info/x_pack_usage/SecurityUsage.ts
specification/specs/x_pack/info/x_pack_usage/SlmUsage.ts
specification/specs/x_pack/info/x_pack_usage/UsageCount.ts
specification/specs/x_pack/info/x_pack_usage/WatcherUsage.ts
specification/specs/x_pack/info/x_pack_usage/XPackUsageResponse.ts

responses for:
* `xpack.info`
* `xpack.usage`

Validate X-pack Endpoints

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/eql/EqlHits.ts
specification/specs/x_pack/eql/EqlHitsEvent.ts
specification/specs/x_pack/eql/EqlHitsSequence.ts
specification/specs/x_pack/eql/EqlSearchResponseBase.ts
specification/specs/x_pack/eql/delete/EqlDeleteRequest.ts
specification/specs/x_pack/eql/delete/EqlDeleteResponse.ts
specification/specs/x_pack/eql/get/EqlGetRequest.ts
specification/specs/x_pack/eql/get/EqlGetResponse.ts
specification/specs/x_pack/eql/get_status/EqlGetStatusRequest.ts
specification/specs/x_pack/eql/get_status/EqlGetStatusResponse.ts
specification/specs/x_pack/eql/search/EqlSearchRequest.ts
specification/specs/x_pack/eql/search/EqlSearchResponse.ts

Validate EQL endpoints

---

README.md

Updated FAQ

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_get_component_template/ClusterGetComponentTemplateRequest.ts

Fix cluster.get_component_template Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/cross_cluster_replication/follow/follow_info/FollowerInfo.ts

Fix ccr.follow_info Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/cross_cluster_replication/follow/follow_index_stats/FollowIndexShardStats.ts
specification/specs/x_pack/cross_cluster_replication/follow/follow_index_stats/FollowIndexStats.ts

Fix ccr.follow_stats Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/cross_cluster_replication/follow/create_follow_index/CreateFollowIndexRequest.ts

Validate ccr.follow request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/info/x_pack_usage/SearchableSnapshotsUsage.ts
specification/specs/x_pack/info/x_pack_usage/VectorUsage.ts
specification/specs/x_pack/info/x_pack_usage/XPackUsageResponse.ts

Validated xpack.usage Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/single/term_vectors/TermVectorsResponse.ts

Validated termvectors Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/security/role/get_role/XPackRole.ts

Validate security.get_role Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/graph/explore/request/GraphExploreControls.ts

Validate graph.explore Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/transform/get_transform/GetTransformRequest.ts

Validated transform.get_transform Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/ilm/explain_lifecycle/LifecycleExplain.ts

Validate ilm.explain_lifecycle Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/indices/index_management/open_close_index/close_index/CloseIndexRequest.ts

Validated indices.close Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/reload_secure_settings/NodeReloadException.ts
specification/specs/cluster/reload_secure_settings/ReloadSecureSettingsResponse.ts

Validate nodes.reload_secure_settings Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_stats/ClusterIndicesStats.ts
specification/specs/cluster/cluster_stats/ClusterOperatingSystemArchitecture.ts
specification/specs/cluster/cluster_stats/ClusterOperatingSystemStats.ts
specification/specs/cluster/cluster_stats/ClusterStatsResponse.ts

Fix cluster.stats Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/cross_cluster_replication/auto_follow/get_auto_follow_pattern/AutoFollowPattern.ts

Fix ccr.get_auto_follow_pattern response

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/document/multiple/bulk/BulkRequest.ts
specification/specs/document/multiple/delete_by_query/DeleteByQueryRequest.ts
specification/specs/document/multiple/reindex/ReindexRequest.ts
specification/specs/document/multiple/update_by_query/UpdateByQueryRequest.ts
specification/specs/document/single/create/CreateRequest.ts
specification/specs/document/single/delete/DeleteRequest.ts
specification/specs/document/single/index/IndexRequest.ts
specification/specs/document/single/update/UpdateRequest.ts
specification/specs/indices/index_management/clone_index/CloneIndexRequest.ts
specification/specs/indices/index_management/create_index/CreateIndexRequest.ts
specification/specs/indices/index_management/freeze_index/FreezeIndexRequest.ts
specification/specs/indices/index_management/open_close_index/close_index/CloseIndexRequest.ts
specification/specs/indices/index_management/open_close_index/open_index/OpenIndexRequest.ts
specification/specs/indices/index_management/rollover_index/RolloverIndexRequest.ts
specification/specs/indices/index_management/shrink_index/ShrinkIndexRequest.ts
specification/specs/indices/index_management/split_index/SplitIndexRequest.ts
specification/specs/x_pack/cross_cluster_replication/follow/create_follow_index/CreateFollowIndexRequest.ts

assign the type `WaitForActiveShards` to all `wait_for_active_shards` params.

Consolidate WaitForActiveShards type

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_stats/ClusterOperatingSystemStats.ts
specification/specs/cluster/nodes_info/ClusterOperatingSystemPrettyName.ts

Fix typo in class name

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/indices/index_management/add_block/IndexAddBlockRequest.ts
specification/specs/indices/index_management/add_block/IndexAddBlockResponse.ts
specification/specs/indices/index_management/add_block/IndexBlockOptions.ts
specification/specs/indices/index_management/add_block/IndexBlockStatus.ts

Validate and add indices.add_block API

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/search/explain/ExplainResponse.ts

removed the dangling types: `TypeName` and `TypeNames`

Remove unused types

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/document/multiple/bulk/bulk_response_item/BulkResponseItemBase.ts
specification/specs/document/multiple/multi_get/MultiGetResponse.ts
specification/specs/document/single/WriteResponseBase.ts
specification/specs/document/single/delete/DeleteRequest.ts
specification/specs/document/single/get/GetResponse.ts
specification/specs/document/single/index/IndexRequest.ts
specification/specs/document/single/update/UpdateRequest.ts
specification/specs/indices/monitoring/indices_stats/ShardLease.ts
specification/specs/indices/monitoring/indices_stats/ShardSequenceNumber.ts
specification/specs/search/explain/InlineGet.ts
specification/specs/search/search/hits/Hit.ts
specification/specs/search/search/hits/HitMetadata.ts
specification/specs/search/search/inner_hits/InnerHits.ts
specification/specs/x_pack/cross_cluster_replication/follow/follow_index_stats/FollowIndexReadException.ts
specification/specs/x_pack/cross_cluster_replication/follow/follow_index_stats/FollowIndexShardStats.ts
specification/specs/x_pack/watcher/get_watch/GetWatchResponse.ts
specification/specs/x_pack/watcher/put_watch/PutWatchResponse.ts

add type `SequenceNumber` of type `integer`, that represents all `*seq_no: [int,long]` occurrences.

Introduce SequenceNumber type

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/job/process/ModelSizeStats.ts
specification/specs/x_pack/machine_learning/job/process/ModelSnapshot.ts

Fix ml.revert_model_snapshot Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/delete_trained_model/DeleteTrainedModelRequest.ts
specification/specs/x_pack/machine_learning/delete_trained_model/DeleteTrainedModelResponse.ts
specification/specs/x_pack/machine_learning/delete_trained_model_alias/DeleteTrainedModelAliasRequest.ts
specification/specs/x_pack/machine_learning/delete_trained_model_alias/DeleteTrainedModelAliasResponse.ts

added and validated the API's:
* `ml.put_trained_model`
* `ml.put_trained_model_alias`

Add ml.delete_trained_model APIs

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/flush_job/FlushJobResponse.ts

Validated ml.flush_job Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/delete_expired_data/DeleteExpiredDataRequest.ts

Fix ml.delete_expired_data request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/multiple/multi_get/MultiGetRequest.ts

Fix mget Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/cluster/cluster_put_voting_config_exclusions/ClusterPostVotingConfigExclusionsRequest.ts

Add cluster.post_voting_config_exclusions API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/indices/resolve_index/ResolveIndexRequest.ts
specification/specs/indices/resolve_index/ResolveIndexResponse.ts

added definitions for request & response, plus validated

Add indices.resolve_index API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/x_pack/security/privileges/clear_cached_privileges/ClearCachedPrivilegesRequest.ts
specification/specs/x_pack/security/privileges/clear_cached_privileges/ClearCachedPrivilegesResponse.ts

added and validated request & response.

Add security.clear_cached_privileges API

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/data_streams/data_streams_stats/IndicesDataStreamsStatsResponse.ts

Validate indices.data_streams_stats Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/security/api_key/get_api_key/ApiKeys.ts

Fix security.get_api_key Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/ingest/simulate_pipeline/DocumentSimulation.ts

Fix ingest.simulate Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/ingest/get_pipeline/GetPipelineRequest.ts

Validate ingest.get_pipeline Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/indices/index_management/split_index/SplitIndexResponse.ts

Validate indices.split Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/delete_calendar_job/DeleteCalendarJobResponse.ts

Fix ml.delete_calendar_job Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/delete_data_frame_analytics/DeleteDataFrameAnalyticsRequest.ts
specification/specs/x_pack/machine_learning/delete_data_frame_analytics/DeleteDataFrameAnalyticsResponse.ts

Add ml.delete_data_frame_analytics API

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/get_anomaly_records/GetAnomalyRecordsRequest.ts

Fix ml.get_records request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/search/validate/ValidateQueryRequest.ts
specification/specs/search/validate/ValidateQueryResponse.ts
specification/specs/search/validate/ValidationExplanation.ts

Response is validating. Request is still failing but eliminated 7 failures.

Improve indices.validate_query

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/common.ts
specification/specs/x_pack/data_streams/create_data_stream/IndicesCreateDataStreamRequest.ts
specification/specs/x_pack/data_streams/create_data_stream/IndicesCreateDataStreamResponse.ts

Validate indices.create_data_stream endpoint

---

output/dangling-types/dangling.csv
output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/job/config/ModelPlotConfigEnabled.ts
specification/specs/x_pack/machine_learning/machine_learning_info/AnomalyDetectors.ts
specification/specs/x_pack/machine_learning/machine_learning_info/Limits.ts
specification/specs/x_pack/machine_learning/machine_learning_info/MachineLearningInfoResponse.ts
specification/specs/x_pack/machine_learning/machine_learning_info/NativeCode.ts

Fix ml.info Response

---

specification/specs/cluster/cluster_stats/ClusterNodeCount.ts
specification/specs/x_pack/info/x_pack_usage/DataTiersUsage.ts
specification/specs/x_pack/machine_learning/close_job/CloseJobRequest.ts

Annotate `data_frozen` with the according version

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/stop_datafeed/StopDatafeedRequest.ts

Validate ml.stop_datafeed Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/job/config/AnalysisConfig.ts
specification/specs/x_pack/machine_learning/job/config/DataDescription.ts
specification/specs/x_pack/machine_learning/validate_job/ValidateJobRequest.ts

Fix ml.validate Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/multiple/reindex_rethrottle/ReindexNode.ts
specification/specs/document/multiple/reindex_rethrottle/ReindexRethrottleResponse.ts
specification/specs/document/multiple/reindex_rethrottle/ReindexTask.ts

Validate reindex_rethrottle Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/datafeed/Datafeed.ts
specification/specs/x_pack/machine_learning/update_data_feed/DatafeedIndicesOptions.ts
specification/specs/x_pack/machine_learning/update_data_feed/UpdateDatafeedRequest.ts
specification/specs/x_pack/machine_learning/update_data_feed/UpdateDatafeedResponse.ts

Fix ml.update_datafeed API

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/get_buckets/GetBucketsRequest.ts
specification/specs/x_pack/machine_learning/job/results/BucketInfluencer.ts
specification/specs/x_pack/machine_learning/job/results/ResultBucket.ts

Validate ml.get_buckets API

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/datafeed/DatafeedStats.ts
specification/specs/x_pack/machine_learning/datafeed/DiscoveryNode.ts
specification/specs/x_pack/machine_learning/get_datafeed_stats/GetDatafeedStatsRequest.ts

Validated ml.get_datafeed_stats API

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/get_calendar_events/GetCalendarEventsRequest.ts
specification/specs/x_pack/machine_learning/post_calendar_events/ScheduledEvent.ts

Validate ml.get_calendar_events API

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/license/delete_license/DeleteLicenseResponse.ts

as titled. Validated based on [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/delete-license.html) will add tests to recorder separately.

Fix license.delete Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/roll_up/get_rollup_job/RollupJobStatus.ts

Fix rollup.get_jobs response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/start_datafeed/StartDatafeedRequest.ts

Fix ml.start_datafeed Request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/delete_trained_model_alias/DeleteTrainedModelAliasRequest.ts

Fix ml.delete_trained_model_alias request

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/info/x_pack_usage/Job.ts
specification/specs/x_pack/machine_learning/get_jobs/GetJobsRequest.ts

Fix ml.get_jobs Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/x_pack/machine_learning/get_filters/Filter.ts
specification/specs/x_pack/machine_learning/get_filters/GetFiltersRequest.ts

Fix ml.get_filters response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/document/multiple/update_by_query_rethrottle/UpdateByQueryRethrottleNode.ts
specification/specs/document/multiple/update_by_query_rethrottle/UpdateByQueryRethrottleResponse.ts

Fix update_by_query_rethrottle Response

---

output/schema/schema.json
output/typescript/types.ts
specification/specs/modules/snapshot_and_restore/snapshot/snapshot_status/SnapshotIndexStats.ts
specification/specs/modules/snapshot_and_restore/snapshot/snapshot_status/SnapshotShardsStatsStage.ts
specification/specs/modules/snapshot_and_restore/snapshot/snapshot_status/SnapshotShardsStatus.ts

Fix snapshot.status Response

---

typescript-generator/client.js

As titled.
Related: https://github.com/elastic/elasticsearch-js/pull/1440

Updated ts client generator

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/specs/search/search_template/SearchTemplateRequest.ts
specification/specs/search/search_template/SearchTemplateResponse.ts

Fix search_template Response

---

output/schema/schema.json
specification/compiler/model/build-model.ts

Add visibility to Endpoint definition

---

output/schema/schema.json
output/typescript/types.ts
specification/security/enable_user/SecurityEnableUserResponse.ts

Renamed Security.enable_user Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts
specification/shutdown/delete_node/ShutdownDeleteNodeResponse.ts
specification/shutdown/get_node/ShutdownGetNodeRequest.ts
specification/shutdown/get_node/ShutdownGetNodeResponse.ts
specification/shutdown/put_node/ShutdownPutNodeRequest.ts
specification/shutdown/put_node/ShutdownPutNodeResponse.ts

added the request & response stubs for:
* `shutdown.put_node`
* `shutdown.get_node`
* `shutdown.delete_node`

Add Shutdown Req & Resp stubs

---

compiler/model/metamodel.ts
compiler/model/utils.ts
compiler/steps/validate-model.ts
output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts

Fix type alias generics

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ml/info/MlInfoRequest.ts
specification/ml/info/MlInfoResponse.ts

during the namespace exercise, the response class was rename incorrectly and hence was not picked up by the validator.

Fix ml.info

---

output/typescript/types.ts
typescript-generator/index.ts

Fix ts generator: emit property aliases

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/snapshot/_types/SnapshotIndexDetails.ts
specification/snapshot/_types/SnapshotInfo.ts
specification/snapshot/get/SnapshotGetRequest.ts

Fix Snapshot.get Req & Resp

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesRequest.ts

Validate security.get_builtin_privileges request

---

output/schema/schema.json
output/typescript/types.ts
specification/security/get_user_privileges/SecurityGetUserPrivilegesRequest.ts

Fix security.get_user_privileges request

---

output/typescript/types.ts
typescript-generator/index.ts

Ts generator: Fix array and unions usage

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/stats/IndexStats.ts
specification/nodes/nodes_stats/CPUStats.ts
specification/nodes/nodes_stats/ExtendedMemoryStats.ts
specification/nodes/nodes_stats/MemoryStats.ts
specification/nodes/nodes_stats/NodeStats.ts
specification/nodes/nodes_stats/NodesStatsRequest.ts
specification/nodes/nodes_stats/NodesStatsResponse.ts

fixed the request and will address based on the high amount of shared classes the response alongside nodes.info

Fix Nodes.stats Request

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/msearch/MultiSearchRequest.ts
specification/_global/msearch_template/MultiSearchTemplateRequest.ts
specification/_global/msearch_template/MultiSearchTemplateResponse.ts
specification/_global/search/hits/Hit.ts
specification/_global/search_template/SearchTemplateRequest.ts
specification/_types/common.ts

Fix msearch_template Request

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/security/authenticate/SecurityAuthenticateRequest.ts
specification/security/authenticate/SecurityAuthenticateResponse.ts

Fix security.authenticate Response

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/put_calendar_job/MlPutCalendarJobRequest.ts
specification/ml/put_calendar_job/MlPutCalendarJobResponse.ts

Fix ml.put_calendar_job Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/aggregations/pipeline/inference_bucket/InferenceBucketAggregation.ts
specification/ml/_types/TrainedModel.ts
specification/ml/get_trained_models/MlGetTrainedModelRequest.ts
specification/ml/get_trained_models/MlGetTrainedModelResponse.ts
specification/ml/get_trained_models_stats/MlGetTrainedModelStatsRequest.ts
specification/ml/get_trained_models_stats/MlGetTrainedModelStatsResponse.ts

validated request & response for:
* `ml.get_trained_models`
* `ml.get_trained_models_stats`

Fix ml.get trained models Endpoints

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ml/_types/DataFrameAnalytics.ts
specification/ml/_types/DataFrameEvaluation.ts
specification/ml/_types/DataFrameState.ts
specification/ml/evaluate_data_frame/MlEvaluateDataFrameRequest.ts
specification/ml/evaluate_data_frame/MlEvaluateDataFrameResponse.ts
specification/ml/explain_data_frame_analytics/MlExplainDataFrameAnalyticsRequest.ts
specification/ml/explain_data_frame_analytics/MlExplainDataFrameAnalyticsResponse.ts
specification/ml/get_data_frame_analytics/MlGetDataFrameAnalyticsRequest.ts
specification/ml/get_data_frame_analytics/MlGetDataFrameAnalyticsResponse.ts
specification/ml/get_data_frame_analytics_stats/MlGetDataFrameAnalyticsStatsRequest.ts
specification/ml/get_data_frame_analytics_stats/MlGetDataFrameAnalyticsStatsResponse.ts
specification/ml/preview_data_frame_analytics/MlPreviewDataFrameAnalyticsRequest.ts
specification/ml/preview_data_frame_analytics/MlPreviewDataFrameAnalyticsResponse.ts
specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts
specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsResponse.ts
specification/ml/update_data_frame_analytics/MlUpdateDataFrameAnalyticsRequest.ts
specification/ml/update_data_frame_analytics/MlUpdateDataFrameAnalyticsResponse.ts

* `ml.evaluate_data_frame`
* `ml.put_data_frame_analytics`
* `ml.update_data_frame_analytics`
* `ml.get_data_frame_analytics`
* `ml.preview_data_frame_analytics`
* `ml.get_data_frame_analytics_stats`

Validate ml.data frame_* Endpoints

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ingest/geo_ip_stats/IngestGeoIpStatsRequest.ts
specification/ingest/geo_ip_stats/IngestGeoIpStatsResponse.ts

no tests available (yet), modelled of the docs: https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-stats-api.html

Validated GeoIP Stats API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/features/reset_features/ResetFeaturesRequest.ts
specification/features/reset_features/ResetFeaturesResponse.ts

Stub features.reset_features API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/get_script_context/GetScriptContextRequest.ts
specification/_global/get_script_context/GetScriptContextResponse.ts
specification/_global/get_script_languages/GetScriptLanguagesRequest.ts
specification/_global/get_script_languages/GetScriptLanguagesResponse.ts

added request & response for:
* `get_script_context`
* `get_script_languages`

Fix Scripting API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/indices/get_index_template/IndicesGetIndexTemplateRequest.ts
specification/indices/get_index_template/IndicesGetIndexTemplateResponse.ts

Fix indices.get_index_template API

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/_types/DataFrameAnalytics.ts

Fix ml.put_data_frame_analytics Response

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/post_calendar_events/MlPostCalendarEventsRequest.ts
specification/ml/post_calendar_events/ScheduledEvent.ts

Fix ml.post_calendar_events API

---

output/schema/schema.json
output/typescript/types.ts
specification/_types/common.ts
specification/_types/mapping/TypeMapping.ts
specification/cluster/_types/ComponentTemplate.ts
specification/cluster/cluster_put_component_template/ClusterPutComponentTemplateRequest.ts
specification/indices/get_data_stream/IndicesGetDataStreamResponse.ts
specification/indices/get_index_template/IndicesGetIndexTemplateResponse.ts
specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts

Replace IndexMetaData with Metadata

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/get_script/GetScriptRequest.ts
specification/_global/get_script/GetScriptResponse.ts
specification/_global/get_script_context/GetScriptContextResponse.ts
specification/_global/get_script_context/types.ts
specification/_global/get_script_languages/GetScriptLanguagesResponse.ts
specification/_global/get_script_languages/types.ts
specification/_types/Scripting.ts

_global/get_script
_global/get_script_context
_global/get_script_languages 
FYI: @sethmlarson - ref: #409

[409] get_script and more

---

.github/download-artifacts/action.yml
.github/download-artifacts/index.js
.github/download-artifacts/package.json
.github/workflows/update-rest-api-json.yml
.gitignore

Automate download rest-api-spec

---

Makefile
README.md

Improve make targets

---

specification/text_structure/find_structure/FindStructureResponse.ts
specification/text_structure/find_structure/types.ts

Reorg text_structure

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/mget/MultiGetRequest.ts
specification/_global/mget/MultiGetResponse.ts
specification/_global/mget/types.ts

Per title.
First attempt to check I'm on the right track!
Relates to #409

Reorg MGet

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/field_caps/FieldCapabilitiesResponse.ts
specification/_global/field_caps/types.ts

Reorg field_caps

---

output/schema/schema.json
output/typescript/types.ts
specification/searchable_snapshots/mount/types.ts

Reorg searchable_snapshots

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/msearch/MultiSearchRequest.ts
specification/_global/msearch/MultiSearchResponse.ts
specification/_global/msearch/types.ts

Reorg msearch

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/msearch_template/types.ts

Reorg msearch_template

---

compiler/model/utils.ts
output/schema/schema.json
output/typescript/types.ts
specification/cluster/_types/ClusterStateSnapshots.ts
specification/ml/explain_data_frame_analytics/MlExplainDataFrameAnalyticsResponse.ts
specification/snapshot/_types/SnapshotIndexDetails.ts
specification/snapshot/_types/SnapshotIndexStats.ts
specification/snapshot/_types/SnapshotInfo.ts
specification/snapshot/_types/SnapshotInfoFeatureState.ts
specification/snapshot/_types/SnapshotRepository.ts
specification/snapshot/_types/SnapshotShardsStats.ts
specification/snapshot/_types/SnapshotShardsStatsStage.ts
specification/snapshot/_types/SnapshotShardsStatus.ts
specification/snapshot/_types/SnapshotStatus.ts
specification/snapshot/create_repository/SnapshotCreateRepositoryRequest.ts
specification/snapshot/get/SnapshotGetResponse.ts
specification/snapshot/get_repository/SnapshotGetRepositoryResponse.ts
specification/snapshot/status/SnapshotStatusResponse.ts

Reorg snapshot

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/get_overall_buckets/MlGetOverallBucketsRequest.ts

Fix ml.get_overall_buckets Request

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/_types/OverlappingIndexTemplate.ts
specification/indices/get_upgrade/IndicesGetUpgradeResponse.ts
specification/indices/simulate_index_template/IndicesSimulateIndexTemplateResponse.ts

Fix indices.simulate_index_template response

---

output/schema/schema.json
output/typescript/types.ts
specification/rollup/rollup_search/RollupSearchResponse.ts

Validate rollup.rollup_search Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/enrich/_types/Policy.ts

Fix enrich.get_policy Response

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/stats/types.ts

Fix indices.stats Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/terms_enum/TermsEnumRequest.ts
specification/_global/terms_enum/TermsEnumResponse.ts

Add terms_enum API

---

output/schema/schema.json
output/typescript/types.ts
specification/cat/jobs/types.ts
specification/ml/_types/Analysis.ts
specification/ml/_types/Datafeed.ts
specification/ml/_types/DataframeAnalytics.ts
specification/ml/_types/Detector.ts
specification/ml/_types/Job.ts
specification/ml/_types/Model.ts
specification/ml/_types/Rule.ts
specification/ml/_types/Settings.ts
specification/ml/explain_data_frame_analytics/MlExplainDataFrameAnalyticsRequest.ts
specification/ml/info/types.ts
specification/ml/preview_data_frame_analytics/types.ts
specification/ml/preview_datafeed/MlPreviewDatafeedRequest.ts
specification/ml/put_datafeed/MlPutDatafeedRequest.ts
specification/ml/put_datafeed/MlPutDatafeedResponse.ts
specification/ml/put_job/MlPutJobRequest.ts
specification/ml/put_job/MlPutJobResponse.ts
specification/ml/stop_datafeed/MlStopDatafeedRequest.ts
specification/ml/update_data_frame_analytics/MlUpdateDataFrameAnalyticsRequest.ts
specification/ml/update_data_frame_analytics/MlUpdateDataFrameAnalyticsResponse.ts
specification/ml/update_job/MlUpdateJobRequest.ts
specification/xpack/usage/types.ts

#225 introduced some issues, as xPack endpoints have most of the properties marked as optional, while the MlJob definition does not.
This pr fixes that, I've also left a TODO to remember to fix the xPack endpoint, which is kind of a snowflake.

Fix ML definitions

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/_types/Datafeed.ts
specification/ml/_types/Model.ts
specification/ml/get_datafeeds/MlGetDatafeedsRequest.ts
specification/ml/info/types.ts
specification/ml/preview_datafeed/MlPreviewDatafeedRequest.ts
specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts
specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsResponse.ts
specification/ml/put_datafeed/MlPutDatafeedRequest.ts
specification/ml/put_datafeed/MlPutDatafeedResponse.ts
specification/ml/put_job/MlPutJobResponse.ts

More ml fixes

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/evaluate_data_frame/types.ts

`ConfusionMatrixTreshold` -> `ConfusionMatrixThreshold`

Fix typo in 'threshold'

---

output/schema/schema.json
specification/ml/start_data_frame_analytics/MlStartDataFrameAnalyticsRequest.ts

There doesn't look to be any tests for the Request portion of this API?

Validate 'ml.start_data_frame_analytics' API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ml/_types/Job.ts
specification/ml/_types/Model.ts
specification/ml/get_job_stats/MlGetJobStatsRequest.ts

Validate 'ml.get_job_stats' API

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/post_data/MlPostDataRequest.ts
specification/ml/post_data/MlPostDataResponse.ts
specification/ml/post_data/types.ts

- Receiving an error regarding `@timestamp` not working with `UserDefinedValue`? Perhaps some JavaScript weirdness happening here? cc @delvedor
- The Request/Response weren't named to exactly match the API, although I think the API would have been better named `ml.post_job_data`... not sure what we should do here?

Validate 'ml.post_data' API

---

compiler/steps/validate-model.ts

Follow-up to PR #506 and #505
This PR adds a model validation that checks that the properties of an interface/request/response are not already defined in a parent class or behavior.
There are still some occurences of this issue but they are on `@stability TODO` types and are therefore not reported in validation errors. Be prepared though to see them show up in the future 😉

Add a model validation that detects duplicate properties on ancestor classes

---

.github/download-artifacts/index.js
.github/workflows/update-rest-api-json.yml

Update rest-api-spec in all base branches

---

output/schema/schema.json
specification/security/_types/ApplicationPrivileges.ts

Adds missing parameter descriptions for the `ApplicationPrivileges` type.

[DOCS] Add ApplicationPrivileges param descs

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/exists/DocumentExistsRequest.ts
specification/_global/exists_source/SourceExistsRequest.ts
specification/_global/get/GetRequest.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts

Noticed this and wasn't sure how this happened or if there's something else going on here that I don't know about? Didn't find anything too magical in `git blame` though.

Rename 'source_enabled' to '_source', prefix '_'

---

output/schema/schema.json
specification/security/put_role/SecurityPutRoleRequest.ts

Updates parameter descriptions for the PUT roles security API.

[DOCS] Update put role API params

---

output/schema/schema.json
specification/security/_types/IndicesPrivileges.ts

Add parameter descriptions for the `indices` object and its sub-parameters.

[DOCS] Update indices parameter descriptions

---

output/schema/schema.json
output/typescript/types.ts
specification/_types/aggregations/bucket.ts
specification/_types/aggregations/pipeline.ts

As titled.
Related: https://github.com/elastic/elasticsearch-js/issues/1524

Add keyed property where it was missing in aggregations

---

compiler/model/utils.ts
output/schema/schema.json

As titled.
Related: https://github.com/elastic/elasticsearch-specification/pull/550

Avoid line breaks in descriptions and validate doc_url

---

output/schema/schema.json
output/typescript/types.ts
specification/cat/ml_trained_models/types.ts

Fix cat.ml_trained_models Response

---

output/schema/schema.json
output/typescript/types.ts
specification/cluster/allocation_explain/ClusterAllocationExplainResponse.ts

Fix cluster.allocation_explain Response

---

output/schema/schema.json
output/typescript/types.ts
specification/watcher/_types/Action.ts
specification/watcher/_types/Actions.ts
specification/watcher/_types/Input.ts
specification/watcher/stats/WatcherStatsRequest.ts

improved the following requests but not resolved them:
* `watcher.stats`
* `watcher.put_watch`

Improve Watcher Requests

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/reindex/types.ts

* `transform.put_transform`
* `transform.preview_transform`

Fix transform requests

---

output/schema/schema.json
output/typescript/types.ts
specification/ilm/_types/Phase.ts
specification/xpack/info/types.ts
specification/xpack/usage/XPackUsageResponse.ts
specification/xpack/usage/types.ts

* `xpack.usage`
* `xpack.info`

Fix xpack Responses

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/recovery/types.ts

Fix indices.recovery Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/dangling_indices/delete_dangling_index/DeleteDanglingIndexRequest.ts
specification/dangling_indices/delete_dangling_index/DeleteDanglingIndexResponse.ts
specification/dangling_indices/import_dangling_index/ImportDanglingIndexRequest.ts
specification/dangling_indices/import_dangling_index/ImportDanglingIndexResponse.ts
specification/dangling_indices/list_dangling_indices/ListDanglingIndicesRequest.ts
specification/dangling_indices/list_dangling_indices/ListDanglingIndicesResponse.ts

Adds dangling_indices Responses and Requests

---

compiler/model/build-model.ts
compiler/model/metamodel.ts
docs/modeling-guide.md
output/schema/schema.json
specification/_global/bulk/BulkRequest.ts
specification/_global/create/CreateRequest.ts
specification/_global/index/IndexRequest.ts
specification/_global/msearch/MultiSearchRequest.ts
specification/_global/msearch_template/MultiSearchTemplateRequest.ts
specification/text_structure/find_structure/FindStructureRequest.ts

As titled, see https://github.com/elastic/elasticsearch-specification/pull/203 discussion.

Add value body identifier

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/cluster/delete_voting_config_exclusions/ClusterDeleteVotingConfigExclusionsRequest.ts
specification/cluster/delete_voting_config_exclusions/ClusterDeleteVotingConfigExclusionsResponse.ts

Still wasn't able to get the validation error for "no body" on the Request. Want feedback on where I should go to fix that issue.

Fix cluster.delete_voting_config_exclusions API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/features/_types/Feature.ts
specification/features/get_features/GetFeaturesRequest.ts
specification/features/get_features/GetFeaturesResponse.ts
specification/features/reset_features/ResetFeaturesRequest.ts
specification/features/reset_features/ResetFeaturesResponse.ts

Fix features namespace

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ilm/start/StartIlmRequest.ts
specification/ilm/stop/StopIlmRequest.ts

Fix ilm stubbed classes

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts
specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyResponse.ts
specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts
specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityResponse.ts
specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts
specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyResponse.ts

Correct request & response definition for the autoscaling namespace.

Fix autoscaling APIs

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts
specification/shutdown/delete_node/ShutdownDeleteNodeResponse.ts
specification/shutdown/get_node/ShutdownGetNodeRequest.ts
specification/shutdown/get_node/ShutdownGetNodeResponse.ts
specification/shutdown/put_node/ShutdownPutNodeRequest.ts
specification/shutdown/put_node/ShutdownPutNodeResponse.ts

Add shutdown API specs

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/autoscaling/_types/AutoscalingPolicy.ts
specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyResponse.ts
specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts
specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyResponse.ts

Follow-up to #591:
- unstub `autoscaling.put_autoscaling_policy`
- use `AcknowedgedResponseBase`

Autoscaling: more unstubbing, use AcknowledgedResponse

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/logstash/_types/Pipeline.ts
specification/logstash/delete_pipeline/LogstashDeletePipelineRequest.ts
specification/logstash/delete_pipeline/LogstashDeletePipelineResponse.ts
specification/logstash/get_pipeline/LogstashGetPipelineRequest.ts
specification/logstash/put_pipeline/LogstashPutPipelineRequest.ts
specification/logstash/put_pipeline/LogstashPutPipelineResponse.ts

This PR includes the type fix for logstash APIs.

Logstash API type fix

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/monitoring/bulk/BulkMonitoringRequest.ts
specification/monitoring/bulk/BulkMonitoringResponse.ts

Fix stubbed monitoring.bulk API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/cluster/remote_info/ClusterRemoteInfoRequest.ts
specification/cluster/remote_info/ClusterRemoteInfoResponse.ts

Validate the 'cluster.remote_info' API

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/bulk/types.ts

As titled, see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html).

Bulk Operation properties should be optional

---

output/schema/schema.json
output/typescript/types.ts
specification/dangling_indices/delete_dangling_index/DeleteDanglingIndexRequest.ts
specification/dangling_indices/import_dangling_index/ImportDanglingIndexRequest.ts

Prefer using the Uuid type rather than a string for the path part

Fix dangling indices requests

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts

Fix indices.simulate_index_template

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/put_trained_model_alias/MlPutTrainedModelAliasRequest.ts

Use `Name` rather than `string` for the `model_alias` path part.

Fix ML put trained model alias request

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/dangling_indices/delete_dangling_index/DeleteDanglingIndexRequest.ts
specification/dangling_indices/import_dangling_index/ImportDanglingIndexRequest.ts

Prefer using the `Uuid` type rather than a `string` for the path part.

Fix dangling index requests

---

output/schema/schema.json
output/typescript/types.ts
specification/snapshot/get/SnapshotGetRequest.ts
specification/snapshot/get/SnapshotGetResponse.ts

https://github.com/elastic/elasticsearch-specification/pull/649 will add remaining validation for the response.

Fix Snapshot.get

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/indices/promote_data_stream/IndicesPromoteDataStreamResponse.ts
specification/ml/update_job/MlUpdateJobResponse.ts
specification/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheRequest.ts
specification/searchable_snapshots/clear_cache/SearchableSnapshotsClearCacheResponse.ts

Fix stubbed apis

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/mapping/Property.ts
specification/_types/mapping/complex.ts
specification/_types/mapping/core.ts
specification/_types/mapping/dynamic-template.ts
specification/_types/mapping/meta-fields.ts
specification/_types/mapping/specialized.ts

got the error count from 100 to 5 - can be merged. The other changes need more investigation.

Improved indices.create Request

---

output/schema/schema.json
output/typescript/types.ts
specification/cluster/reroute/types.ts

Fix cluster.reroute Response

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/count/CountRequest.ts
specification/_global/explain/ExplainRequest.ts
specification/_global/scroll/ScrollRequest.ts
specification/_global/search_template/SearchTemplateRequest.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts
specification/indices/validate_query/IndicesValidateQueryRequest.ts

Backport of https://github.com/elastic/elasticsearch-specification/pull/711

[7.x] Remove unused NEST options from APIs

---

compiler/model/utils.ts

Add support for boolean and numbers in literal values

---

output/schema/schema.json
output/typescript/types.ts
specification/ilm/explain_lifecycle/ExplainLifecycleResponse.ts
specification/ilm/explain_lifecycle/types.ts

Closes https://github.com/elastic/elasticsearch-specification/issues/531

Differentiate between managed and unmanaged indices

---

output/schema/schema.json
output/typescript/types.ts
specification/security/_types/RoleMapping.ts
specification/security/_types/RoleMappingRule.ts
specification/security/put_role_mapping/SecurityPutRoleMappingRequest.ts

As per title - Added container for rules.

Fix security get role mapping

---

output/schema/schema.json
output/typescript/types.ts
specification/nodes/info/types.ts

Fix nodes.info settings

---

compiler/model/metamodel.ts
compiler/model/utils.ts

As titled, see https://github.com/elastic/elasticsearch-specification/pull/746

Add support for doc_id in properties

---

compiler/model/build-model.ts
output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts
specification/indices/put_settings/IndicesPutSettingsRequest.ts
specification/indices/simulate_template/IndicesSimulateTemplateRequest.ts
specification/logstash/put_pipeline/LogstashPutPipelineRequest.ts
specification/ml/validate_detector/MlValidateDetectorRequest.ts
specification/rollup/rollup/RollupRequest.ts
specification/security/put_privileges/SecurityPutPrivilegesRequest.ts

A body identifier should be configured for every `value` body.

Expand body identifier use

---

compiler/model/metamodel.ts
compiler/model/utils.ts
docs/doc-comments-guide.md
docs/modeling-guide.md
output/schema/schema.json
specification/cluster/state/ClusterStateRequest.ts
specification/indices/create/IndicesCreateRequest.ts
specification/ml/close_job/MlCloseJobRequest.ts
specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsRequest.ts

Rename prerequisites to privileges

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/stats/types.ts

Started from https://github.com/elastic/elasticsearch-specification/pull/725 with applied comments.

Fix the 'indices.stats' API

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/shard_stores/IndicesShardStoresRequest.ts
specification/indices/shard_stores/types.ts

Can't fix the response right now due to https://github.com/elastic/elasticsearch-specification/issues/770

Fix indices.shard_stores request

---

output/schema/schema.json
output/typescript/types.ts
specification/shutdown/get_node/ShutdownGetNodeRequest.ts

Fix shutdown.get_node

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/msearch_template/MultiSearchTemplateResponse.ts
specification/_types/Base.ts

Fix msearch_template response

---

output/schema/schema.json
output/typescript/types.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts

These keys should not be there.

Fix async_search.submit

---

compiler/model/build-model.ts
output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/indices/get_index_template/IndicesGetIndexTemplateRequest.ts
specification/ml/get_calendar_events/MlGetCalendarEventsRequest.ts

As titled.
Closes: https://github.com/elastic/elasticsearch-specification/pull/830

Throw if the api can't have a body

---

output/schema/schema.json
output/typescript/types.ts
specification/_types/analysis/char_filters.ts
specification/_types/analysis/kuromoji-plugin.ts
specification/_types/analysis/token_filters.ts
specification/_types/mapping/TypeMapping.ts
specification/_types/mapping/meta-fields.ts
specification/_types/mapping/specialized.ts
specification/indices/_types/DataStream.ts
specification/indices/_types/IndexSettings.ts
specification/indices/create/IndicesCreateResponse.ts
specification/indices/get_index_template/IndicesGetIndexTemplateResponse.ts
specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
specification/indices/put_mapping/IndicesPutMappingRequest.ts

Fix indices definitions

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/search_mvt/_types/GridType.ts

Related: https://github.com/elastic/elasticsearch/pull/78305

Add centroid to search_mvt grid type

---

output/schema/schema.json
output/typescript/types.ts
specification/ilm/_types/Phase.ts
specification/xpack/usage/XPackUsageResponse.ts
specification/xpack/usage/types.ts

Fixed errors in xpack.usage

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/mget/types.ts
specification/_types/Base.ts
specification/_types/Errors.ts

Simplify ErrorCause definition (#868)

---

output/schema/schema.json
specification/ml/delete_datafeed/MlDeleteDatafeedRequest.ts

[7.x] Updates the spec for ML delete datafeed API

---

output/schema/schema.json
specification/ml/delete_expired_data/MlDeleteExpiredDataRequest.ts

[7.x] [ML] Update the spec for delete expired data API

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/Errors.ts
specification/_types/mapping/meta-fields.ts
specification/nodes/_types/Stats.ts

Backport of https://github.com/elastic/elasticsearch-specification/pull/908

Fine tuning and minor fixes

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/get_source/SourceRequest.ts

Declare the get_source api without extending from another get

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/_types/DataStreamStatus.ts

Fix indices.get_data_stream response

---

compiler/model/metamodel.ts
compiler/model/utils.ts
docs/modeling-guide.md
output/schema/schema.json
specification/ml/_types/ModelPlot.ts

Do we need a description as well?
Closes: https://github.com/elastic/elasticsearch-specification/issues/22

Add support for experimental properties

---

output/typescript/types.ts
typescript-generator/index.ts

This pr refactors how additional properties are serialized in ts.

Refactor additional properties handling

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

Fix duplication of alias name in IndexSettings

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/analysis/analyzers.ts
specification/_types/analysis/icu-plugin.ts
specification/_types/analysis/kuromoji-plugin.ts
specification/_types/analysis/phonetic-plugin.ts
specification/_types/analysis/token_filters.ts
specification/_types/analysis/tokenizers.ts
specification/_types/mapping/DenseVectorIndexOptions.ts
specification/_types/mapping/complex.ts
specification/_types/mapping/core.ts
specification/indices/_types/IndexSegmentSort.ts
specification/indices/_types/IndexSettings.ts
specification/indices/create/IndicesCreateRequest.ts

[Backport 7.16] Fix create index request

---

Makefile

make task for https://github.com/elastic/elasticsearch-specification/pull/990

Add task to clean npm dependencies

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/_types/Model.ts

Fix ml.update_model_snapshot response

---

output/schema/schema.json
specification/ml/set_upgrade_mode/MlSetUpgradeModeRequest.ts
specification/ml/start_data_frame_analytics/MlStartDataFrameAnalyticsRequest.ts
specification/ml/start_datafeed/MlStartDatafeedRequest.ts

This PR updates the specs for the set upgrade mode and start data frame analytics job APIs.

[ML] Updates set upgrade mode and start DFA API specs

---

output/schema/schema.json
specification/ml/stop_data_frame_analytics/MlStopDataFrameAnalyticsRequest.ts
specification/ml/update_data_frame_analytics/MlUpdateDataFrameAnalyticsRequest.ts
specification/ml/update_job/MlUpdateJobRequest.ts
specification/ml/update_model_snapshot/MlUpdateModelSnapshotRequest.ts
specification/ml/upgrade_job_snapshot/MlUpgradeJobSnapshotRequest.ts

This PR updates the following API specs:
* stop DFA job
* update DFA job
* update AD job
* update model snapshot
* upgrade model snapshot.

[ML] Updates DFA and AD related API specs

---

output/schema/schema.json
specification/_types/Time.ts

Fix codegen names so they are single words

---

docs/modeling-guide.md

Fixes minor typos in modeling guide

---

output/schema/schema.json
specification/_types/Base.ts

Revert 1001 by removing `_seq_no` codegen name

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ml/update_datafeed/MlUpdateDatafeedRequest.ts
specification/ml/update_datafeed/MlUpdateDatafeedResponse.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1026

[7.16] Adds spec for update datafeed API

---

output/schema/schema.json
output/typescript/types.ts
specification/ml/_types/TrainedModel.ts
specification/ml/put_trained_model/MlPutTrainedModelRequest.ts

Adds `model_type` enum to `TrainedModelConfig`.

Add 'model_type' to 'TrainedModelConfig'

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/health/CatHealthRequest.ts
specification/cluster/health/ClusterHealthRequest.ts
specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts
specification/ml/explain_data_frame_analytics/MlExplainDataFrameAnalyticsRequest.ts
specification/ml/put_calendar/MlPutCalendarRequest.ts
specification/nodes/hot_threads/NodesHotThreadsRequest.ts
specification/security/change_password/SecurityChangePasswordRequest.ts
specification/watcher/put_watch/WatcherPutWatchRequest.ts

When switching to code generation for the Python client I found the following issues. These issues apply to 8.x and 7.16, another PR will be raised with 8.x-specific additions.

Many small fixes from running REST API tests

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ml/close_job/MlCloseJobRequest.ts
specification/ml/get_overall_buckets/MlGetOverallBucketsRequest.ts
specification/ml/get_records/MlGetAnomalyRecordsRequest.ts
specification/ml/open_job/MlOpenJobRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1037

[7.16] Add missing request body detail for ML get APIs (#1037)

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/delete_by_query/DeleteByQueryRequest.ts
specification/_global/exists/DocumentExistsRequest.ts
specification/_global/exists_source/SourceExistsRequest.ts
specification/_global/explain/ExplainRequest.ts
specification/_global/get/GetRequest.ts
specification/_global/get/GetResponse.ts
specification/_global/get/types.ts
specification/_global/get_source/SourceRequest.ts
specification/_global/mget/MultiGetRequest.ts
specification/_global/mget/MultiGetResponse.ts
specification/_global/mget/types.ts
specification/_global/msearch/MultiSearchRequest.ts
specification/_global/msearch/MultiSearchResponse.ts
specification/_global/msearch/types.ts
specification/_global/msearch_template/MultiSearchTemplateRequest.ts
specification/_global/msearch_template/MultiSearchTemplateResponse.ts
specification/_global/msearch_template/types.ts
specification/_global/search/SearchRequest.ts
specification/_global/search/_types/SourceFilter.ts
specification/_global/update/UpdateRequest.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts

Backport 1034 to 7.16

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/count/CountRequest.ts
specification/_global/delete_by_query/DeleteByQueryRequest.ts
specification/_global/explain/ExplainRequest.ts
specification/_global/search/SearchRequest.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts
specification/_types/common.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts
specification/indices/validate_query/IndicesValidateQueryRequest.ts

`Operator` and `DefaultOperator` are really the same thing!

Unify Operator and DefaultOperator enums

---

output/schema/schema.json
output/typescript/types.ts
specification/_global/count/CountRequest.ts
specification/_global/delete_by_query/DeleteByQueryRequest.ts
specification/_global/explain/ExplainRequest.ts
specification/_global/search/SearchRequest.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts
specification/_types/common.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts
specification/indices/validate_query/IndicesValidateQueryRequest.ts

Unify Operator and DefaultOperator enums (#1047)

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/_types/IndexState.ts

Add missing field reported in https://github.com/elastic/elasticsearch-java/issues/46

Add missing "defaults" field to IndexState

---

output/schema/schema.json
output/typescript/types.ts
specification/indices/_types/IndexRouting.ts
specification/indices/_types/IndexSegmentSort.ts

Fix some index setting fields (#1056)

---

output/schema/schema.json
output/typescript/types.ts
specification/transform/delete_transform/DeleteTransformRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1070

[7.16]Adds descriptions to delete transform API (#1070)

---

output/schema/schema.json
specification/_json_spec/ml.validate.json
specification/_json_spec/ml.validate_detector.json
specification/ml/validate/MlValidateJobRequest.ts
specification/ml/validate_detector/MlValidateDetectorRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1063

[7.16] Adds visibility tag to ML validate APIs (#1063)

---

output/schema/schema.json
output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts

I presume the value should be a long here.

Long terms should have long value

---

output/typescript/types.ts
specification/transform/start_transform/StartTransformRequest.ts
specification/transform/stop_transform/StopTransformRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1072

[Backport 7.16] Adds descriptions for start and stop transform APIs (#1072)

---

output/schema/schema.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/delete_by_query/DeleteByQueryRequest.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts

[7.15] Remove source parameters from update_by_query/delete_by_query

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/delete_by_query/DeleteByQueryRequest.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts

[7.16] Remove source parameters from update_by_query/delete_by_query

---

specification/transform/get_transform/GetTransformRequest.ts
specification/transform/get_transform_stats/GetTransformStatsRequest.ts

This PR adds descriptions to the properties of the GET transforms and GET transforms stats APIs.

[Transform] Updates GET and GET stats Transform API specs

---

specification/snapshot/cleanup_repository/SnapshotCleanupRepositoryRequest.ts
specification/snapshot/cleanup_repository/SnapshotCleanupRepositoryResponse.ts

Adds descriptions to the [clean up snapshot repo API](https://www.elastic.co/guide/en/elasticsearch/reference/master/clean-up-snapshot-repo-api.html) spec.

[DOCS] Add descriptions to clean up snapshot repo API

---

specification/snapshot/cleanup_repository/SnapshotCleanupRepositoryRequest.ts
specification/snapshot/cleanup_repository/SnapshotCleanupRepositoryResponse.ts

[7.16] [DOCS] Add descriptions to clean up snapshot repo API

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/transform/upgrade_transforms/UpgradeTransformsRequest.ts
specification/transform/upgrade_transforms/UpgradeTransformsResponse.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1105

[7.16]Adds upgrade transform specification

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/transform/reset_transform/ResetTransformRequest.ts
specification/transform/reset_transform/ResetTransformResponse.ts

Relates to https://github.com/elastic/elasticsearch/pull/79828

Adds reset transform API specification

---

output/typescript/types.ts
specification/transform/preview_transform/PreviewTransformRequest.ts
specification/transform/update_transform/UpdateTransformRequest.ts
specification/transform/update_transform/UpdateTransformResponse.ts

This PR updates the specs files of the preview transform and the update transform APIs.

Updates preview and update Transform API specs.

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/Stats.ts
specification/indices/stats/types.ts
specification/nodes/_types/NodesResponseBase.ts
specification/nodes/_types/Stats.ts
specification/nodes/stats/NodesStatsResponse.ts

Fixing nodes.stats request and response, backport of #844

[Backport 8.0] Fix nodes.stats

---

docs/modeling-guide.md

As titled.
Closes: https://github.com/elastic/elasticsearch-specification/issues/1010

Add visibility to modeling guide

---

output/typescript/types.ts
specification/_global/bulk/types.ts

Remove _type which is no longer returned on bulk response items

---

specification/_global/mget/MultiGetRequest.ts
specification/_global/mget/types.ts

Improve Descriptions for mget

---

output/typescript/types.ts
specification/_global/bulk/types.ts

[8.0] Remove _type which is not longer returned

---

compiler/model/build-model.ts
output/schema/validation-errors.json
output/typescript/types.ts
specification/transform/_types/Transform.ts
specification/watcher/_types/Trigger.ts

All container properties must be optional

---

output/typescript/types.ts
specification/ml/put_trained_model/MlPutTrainedModelRequest.ts

[8.0] Add model_size_bytes parameter to ml.put_trained_model API

---

output/typescript/types.ts
specification/_types/query_dsl/abstractions.ts

As titled.
Fixes: https://github.com/elastic/elasticsearch-js/issues/1598

Fix typo in CombinedFieldsQuery

---

output/typescript/types.ts
specification/_global/rank_eval/types.ts
specification/_types/Node.ts
specification/_types/aggregations/metric.ts
specification/_types/query_dsl/term.ts
specification/cat/allocation/types.ts
specification/cat/indices/types.ts
specification/cat/shards/types.ts
specification/cat/templates/types.ts
specification/cat/thread_pool/types.ts
specification/cat/transforms/types.ts

Minor type fixes

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/ilm/delete_lifecycle/DeleteLifecycleRequest.ts
specification/ilm/explain_lifecycle/ExplainLifecycleRequest.ts
specification/ilm/explain_lifecycle/types.ts

fix response of `ilm.explain_lifecylce` and add more descriptions.

Fix ilm.explain_lifecycle

---

output/typescript/types.ts
specification/_global/field_caps/FieldCapabilitiesRequest.ts
specification/_global/field_caps/FieldCapabilitiesResponse.ts
specification/_global/field_caps/types.ts
specification/_types/query_dsl/abstractions.ts

Add TSDB fields to FieldCapsResponse

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/ilm/get_lifecycle/GetLifecycleRequest.ts

Fix ilm.get_lifecycle

---

compiler/run-validations.js
output/typescript/types.ts
typescript-generator/src/index.ts

As titled.
Bonus: improved run validations script.

Use codegen name in ts generator

---

output/typescript/types.ts
specification/watcher/_types/Action.ts
specification/watcher/_types/Actions.ts
specification/watcher/_types/Execution.ts
specification/watcher/execute_watch/WatcherExecuteWatchRequest.ts
specification/watcher/execute_watch/types.ts

fixes the response and adds more descriptions to the request class.

Fix watcher.execute_watch

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/xpack/info/XPackInfoRequest.ts

Fix xpack.info Request

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/tasks/_types/GroupBy.ts
specification/tasks/list/ListTasksRequest.ts
specification/tasks/list/ListTasksResponse.ts

Fix tasks.list response

---

output/typescript/types.ts
specification/license/_types/License.ts
specification/license/get/GetLicenseRequest.ts
specification/license/get/types.ts
specification/license/post/PostLicenseRequest.ts
specification/license/post_start_basic/StartBasicLicenseRequest.ts
specification/license/post_start_basic/StartBasicLicenseResponse.ts
specification/license/post_start_trial/StartTrialLicenseRequest.ts
specification/license/post_start_trial/StartTrialLicenseResponse.ts

* `license.get`
* `license.post`
* `license.post_start_basic`
* `license.post_start_trial`

Validate license.* endpoints

---

output/typescript/types.ts
specification/rollup/_types/Metric.ts
specification/rollup/put_job/CreateRollupJobRequest.ts

Validate rollup.put_job

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/common.ts
specification/nodes/hot_threads/NodesHotThreadsRequest.ts

Fix nodes.hot_threads request

---

output/typescript/types.ts
specification/nodes/info/types.ts

Fix nodes.info response

---

output/typescript/types.ts
specification/transform/get_transform_stats/types.ts
specification/transform/preview_transform/PreviewTransformRequest.ts
specification/transform/put_transform/PutTransformRequest.ts
specification/transform/update_transform/UpdateTransformRequest.ts
specification/transform/update_transform/UpdateTransformResponse.ts

* `transform.preview_transform`
* `transform.put_transform`
* `transform.update_transform`
* `transform.get_transform_stats`

Fix Transform.* endpoints

---

output/typescript/types.ts
specification/_global/search/_types/FieldCollapse.ts
specification/_global/search/_types/hits.ts
specification/_global/search/_types/profile.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/aggregations/bucket.ts
specification/_types/aggregations/pipeline.ts
specification/_types/query_dsl/abstractions.ts
specification/_types/query_dsl/term.ts

Request and response are not fully passing but, pushed the error count down.
Aggregations & Queries added:
* `bucket_ks`
* `bucket_correlations`
* `knn`
Investigated recordings for upstream test muting.

Improve Search

---

output/typescript/types.ts
specification/_global/search_mvt/SearchMvtRequest.ts

Fix search_mvt request

---

output/typescript/types.ts
specification/_types/aggregations/bucket.ts

more refinements of the `search` endpoint, still not fully green.

Improve search request

---

output/typescript/types.ts
specification/security/_types/Privileges.ts

[Backport 8.0] Remove kibana private roles in IndexPrivilege (#1240)

---

specification/ml/_types/Analysis.ts

Relates to https://github.com/elastic/elasticsearch/pull/82145

[ML] Augment bucket_span description

---

compiler/src/model/metamodel.ts
compiler/src/model/utils.ts
docs/modeling-guide.md
output/typescript/types.ts
specification/_global/search/_types/highlighting.ts
specification/_types/Scripting.ts
typescript-generator/src/index.ts
typescript-generator/src/metamodel.ts

As titled.
**This should not be backported to v7**.

Add support for open/close enums

---

output/typescript/types.ts
specification/_types/Stats.ts
specification/indices/data_streams_stats/IndicesDataStreamsStatsResponse.ts
specification/ml/_types/Model.ts
specification/ml/post_data/MlPostJobDataResponse.ts

Change timestamps defined as integer to long

---

output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts

[Backport] Fix regression in aggregation changes

---

output/typescript/types.ts
specification/indices/stats/IndicesStatsRequest.ts
specification/indices/stats/types.ts

closes https://github.com/elastic/elasticsearch-specification/issues/1253

Add new 8.1.0 fields for indices.stats

---

output/typescript/types.ts
specification/_types/Node.ts

Partial backport of #1264 to 7.17

Fix node shard node_id

---

output/typescript/types.ts
specification/transform/get_transform_stats/GetTransformStatsRequest.ts

Make transport_id accept an array for transforms.get_transform_stats

---

output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts

Add an optional key field to RangeBucket (#1279)

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/Transform.ts
specification/watcher/_types/Action.ts
specification/watcher/_types/Actions.ts
specification/watcher/_types/Conditions.ts
specification/watcher/_types/Schedule.ts

Fixes all tests for `watcher.put_watch` except for search input test failures which look like bad NEST recordings, will make a separate PR for those.

Fix Action definitions for watcher.put_watcher API

---

output/typescript/types.ts
specification/_types/Transform.ts

Backport https://github.com/elastic/elasticsearch-specification/pull/1285

Fix chained transform definition (#1285)

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/ilm/migrate_to_data_tiers/Request.ts
specification/ilm/migrate_to_data_tiers/Response.ts

Add ilm.migrate_to_data_tiers

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/searchable_snapshots/cache_stats/Request.ts
specification/searchable_snapshots/cache_stats/Response.ts

Add searchable_snapshots.cache_stats

---

output/typescript/types.ts
specification/_types/mapping/RuntimeFields.ts
specification/rollup/get_rollup_index_caps/GetRollupIndexCapabilitiesRequest.ts
specification/security/get_privileges/SecurityGetPrivilegesRequest.ts
specification/xpack/usage/types.ts

This pr fixes a bunch of apis that are currently failing (but it's not worth opening a separate pr for each one of them).

Small api fixes

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/security/enroll_kibana/Request.ts
specification/security/enroll_kibana/Response.ts
specification/security/enroll_node/Request.ts
specification/security/enroll_node/Response.ts
specification/security/saml_authenticate/Request.ts
specification/security/saml_authenticate/Response.ts
specification/security/saml_complete_logout/Request.ts
specification/security/saml_complete_logout/Response.ts
specification/security/saml_invalidate/Request.ts
specification/security/saml_invalidate/Response.ts
specification/security/saml_logout/Request.ts
specification/security/saml_logout/Response.ts
specification/security/saml_prepare_authentication/Request.ts
specification/security/saml_prepare_authentication/Response.ts
specification/security/saml_service_provider_metadata/Request.ts
specification/security/saml_service_provider_metadata/Response.ts

Add missing security api definitions

---

output/typescript/types.ts
specification/indices/_types/IndexSegmentSort.ts
specification/indices/_types/IndexSettings.ts
specification/indices/create/IndicesCreateRequest.ts
specification/indices/update_aliases/types.ts

[8.0 Fix indices apis

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/search/_types/suggester.ts

Fix suggest results that are a typed-key union type (#1301)

---

output/typescript/types.ts
specification/_global/bulk/BulkRequest.ts
specification/_global/bulk/types.ts
specification/monitoring/bulk/BulkMonitoringRequest.ts

Add UpdateAction for bulk requests (#1312)

---

docs/style-guide.md
output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/ml_jobs/CatJobsRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1303

[8.0] cat anomaly detectors specification (#1303)

---

docs/style-guide.md
output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/ml_jobs/CatJobsRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1303

[7.17] cat anomaly detectors specification

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/ml_datafeeds/CatDatafeedsRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1304

[8.0] Update cat datafeeds specification (#1304)

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/ml_datafeeds/CatDatafeedsRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1304

[7.17] Update cat datafeeds specification

---

output/typescript/types.ts
specification/_global/search/SearchResponse.ts
specification/_global/search_template/SearchTemplateResponse.ts

Add missing fields to SearchTemplateResponse (#1335)

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

As titled.
I've also added a missing setting.
I'll keep it a draft until I can have a green build for this API.

Unflat IndexSettings

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/ml_data_frame_analytics/CatDataFrameAnalyticsRequest.ts

This PR backports the changes of the following: https://github.com/elastic/elasticsearch-specification/pull/1355

[8.0] Updates cat DFA API spec (#1355)

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/ml_data_frame_analytics/CatDataFrameAnalyticsRequest.ts

This PR backports the following changes: https://github.com/elastic/elasticsearch-specification/pull/1355

[7.17] Updates cat DFA API spec

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/transforms/CatTransformsRequest.ts

This PR updates the cat transform API spec. 
Related to https://github.com/elastic/elasticsearch-specification/pull/1355

Updates cat transform API spec

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/transforms/CatTransformsRequest.ts

This PR backports the following changes: https://github.com/elastic/elasticsearch-specification/pull/1370

[7.17] Updates cat transform API spec

---

output/typescript/types.ts
specification/_types/analysis/char_filters.ts

Validate ml.get_jobs Response

---

output/typescript/types.ts
specification/ml/_types/TrainedModel.ts
specification/ml/get_trained_models_stats/MlGetTrainedModelStatsRequest.ts
specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentRequest.ts

Relates to https://github.com/elastic/elasticsearch/pull/82705

Add error counts to trained model stats

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/security/_types/Privileges.ts

Fix 'security.put_role' API

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/migration/get_feature_upgrade_status/GetFeatureUpgradeStatusRequest.ts
specification/migration/get_feature_upgrade_status/GetFeatureUpgradeStatusResponse.ts
specification/migration/post_feature_upgrade/PostFeatureUpgradeRequest.ts
specification/migration/post_feature_upgrade/PostFeatureUpgradeResponse.ts

added and validated the endpoints:
* `migration.get_feature_upgrade_status`
* `migration.post_feature_upgrade`

Missing migration types

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/indices/field_usage_stats/IndicesFieldUsageStatsRequest.ts
specification/indices/field_usage_stats/IndicesFieldUsageStatsResponse.ts

added the `indices.field_usage_stats` request & response types and validated them.

Validate indices.field_usage_stats

---

compiler/run-validations.js

This will allow us to test every minor release and not only the latest.

Updated branch version detection

---

docs/known-issues.md

Add DynamicMapping special snowflake case to known issue for future ref

---

.github/workflows/update-rest-api-json.yml

Update rest-api-spec data in 8.1 and 8.0 as well

---

output/typescript/types.ts
specification/_types/common.ts

Add 'index-setting' to WaitForActiveShardOptions

---

output/typescript/types.ts
specification/transform/get_transform/GetTransformRequest.ts

API allows list of Names, change from type `Name` to `Names`

Fix transform.get_transform Request

---

output/typescript/types.ts
specification/ml/_types/Model.ts

Needed to change some properties to optional to validate the response.

Fix ml.get_model_snapshots Response

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/_types/CatBase.ts
specification/cat/ml_trained_models/CatTrainedModelsRequest.ts

Backports Updates cat trained models API spec #1418

[7.17] Updates cat trained models API spec

---

compiler/src/model/metamodel.ts
compiler/src/model/utils.ts
compiler/src/steps/validate-model.ts

Adopt new specLocation format

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/scroll/ScrollResponse.ts
specification/_global/search/SearchResponse.ts

Use search ResponseBody in Scroll response

---

specification/_doc_ids/table.csv
specification/security/_types/Privileges.ts
specification/security/create_api_key/SecurityCreateApiKeyRequest.ts
specification/security/get_role/SecurityGetRoleRequest.ts
specification/security/put_role/SecurityPutRoleRequest.ts
specification/security/query_api_keys/QueryApiKeysRequest.ts
specification/snapshot/_types/SnapshotShardsStatsStage.ts
specification/sql/query/QuerySqlRequest.ts
specification/watcher/_types/Action.ts
specification/watcher/execute_watch/WatcherExecuteWatchRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1502

[8.0] Replace or remove more doc URLs (#1502)

---

output/typescript/types.ts
specification/cluster/delete_component_template/ClusterDeleteComponentTemplateRequest.ts

Fix cluster.delete_component_template API

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/xpack/info/XPackInfoRequest.ts
specification/xpack/info/types.ts
specification/xpack/usage/XPackUsageRequest.ts
specification/xpack/usage/XPackUsageResponse.ts
specification/xpack/usage/types.ts

New property introduced for `8.2` called `archive`. Do not backport this PR

Fix xpack.* endpoints

---

output/typescript/types.ts
specification/_global/field_caps/FieldCapabilitiesRequest.ts

Backport #1517 to version 7.17

Backport 1517 to 7.17

---

specification/_doc_ids/table.csv
specification/_global/search/_types/suggester.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts
specification/ccr/put_auto_follow_pattern/PutAutoFollowPatternRequest.ts
specification/cluster/put_component_template/ClusterPutComponentTemplateRequest.ts
specification/cluster/stats/ClusterStatsResponse.ts
specification/eql/_types/EqlSearchResponseBase.ts
specification/eql/search/EqlSearchRequest.ts
specification/fleet/msearch/MultiSearchRequest.ts
specification/fleet/search/SearchRequest.ts
specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts

This PR replaces more occurrences of hard-coded @doc_url values with @doc_id keys.

Replace more hard-coded doc URLs with @doc_id

---

specification/_doc_ids/table.csv
specification/_global/search/_types/suggester.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts
specification/ccr/put_auto_follow_pattern/PutAutoFollowPatternRequest.ts
specification/cluster/put_component_template/ClusterPutComponentTemplateRequest.ts
specification/cluster/stats/ClusterStatsResponse.ts
specification/eql/_types/EqlSearchResponseBase.ts
specification/eql/search/EqlSearchRequest.ts
specification/fleet/msearch/MultiSearchRequest.ts
specification/fleet/search/SearchRequest.ts
specification/indices/put_index_template/IndicesPutIndexTemplateRequest.ts
specification/indices/simulate_index_template/IndicesSimulateIndexTemplateRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/1523

[8.1] Replace more hard-coded doc URLs with @doc_id #1523

---

specification/_doc_ids/table.csv
specification/_global/rank_eval/types.ts
specification/_types/Scripting.ts
specification/_types/Time.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/analysis/normalizers.ts
specification/_types/common.ts
specification/_types/mapping/Property.ts
specification/_types/mapping/TypeMapping.ts
specification/_types/mapping/geo.ts
specification/_types/query_dsl/abstractions.ts
specification/_types/query_dsl/fulltext.ts
specification/_types/query_dsl/specialized.ts
specification/_types/sort.ts
specification/cluster/_types/ComponentTemplate.ts
specification/cluster/allocation_explain/types.ts
specification/cluster/reroute/types.ts
specification/cluster/stats/types.ts
specification/eql/_types/EqlHits.ts
specification/indices/_types/DataStream.ts
specification/indices/_types/IndexSettings.ts
specification/indices/_types/IndexTemplate.ts
specification/nodes/_types/NodesResponseBase.ts
specification/nodes/info/types.ts
specification/security/_types/Privileges.ts
specification/watcher/_types/Schedule.ts

This PR replaces more occurrences of hard-coded @doc_url values with @doc_id keys.

Replace hard-coded doc URLs with @doc_id

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

[Backport 7.17] Missing Index mapping settings

---

output/typescript/types.ts
specification/_global/knn_search/KnnSearchRequest.ts

Closes #1542
Reference: https://github.com/elastic/elasticsearch/pull/84734

Add the 'filters' property to KnnSearchRequest

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/Node.ts
specification/ml/get_memory_stats/MlGetMemoryStatsRequest.ts
specification/ml/get_memory_stats/MlGetMemoryStatsResponse.ts
specification/ml/get_memory_stats/types.ts

closes https://github.com/elastic/elasticsearch-specification/issues/1538

Add ml.get_memory_stats Endpoint

---

output/typescript/types.ts
specification/_types/aggregations/bucket.ts

Use correct type for Significant Terms Agg

---

compiler/src/model/build-model.ts
compiler/src/model/json-spec.ts
compiler/src/model/metamodel.ts

Add feature flag support

---

output/typescript/types.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/aggregations/bucket.ts

[8.1] Add the 'geohex_tile' aggregation

---

output/typescript/types.ts
specification/_types/mapping/core.ts
specification/_types/mapping/specialized.ts

(cherry picked from commit c969655f07731666292c4c8dfbad59617254e792)

Remove generic property (#1595)

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/security/_types/GrantType.ts
specification/security/_types/UserProfile.ts
specification/security/activate_user_profile/Request.ts
specification/security/activate_user_profile/Response.ts
specification/security/disable_user_profile/Request.ts
specification/security/disable_user_profile/Response.ts
specification/security/enable_user_profile/Request.ts
specification/security/enable_user_profile/Response.ts
specification/security/get_user_profile/Request.ts
specification/security/get_user_profile/Response.ts
specification/security/suggest_user_profiles/Request.ts
specification/security/suggest_user_profiles/Response.ts
specification/security/update_user_profile_data/Request.ts
specification/security/update_user_profile_data/Response.ts

Adds the following APIs related to the new feature "User Profiles":
- `activate_user_profile`
- `enable_user_profile`
- `disable_user_profile`
- `get_user_profile`
- `update_user_profile_data`
- `suggest_user_profiles`

Add the User Profiles APIs

---

output/typescript/types.ts
specification/transform/update_transform/UpdateTransformRequest.ts

fix update_transform api

---

output/typescript/types.ts
specification/_global/search/_types/suggester.ts

[Backport 7.17] Add score to CompletionSuggestOption (#1621)

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

#1500 didn't get successfully backported to 8.1

[8.1] Missing Index mapping settings

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

[8.2] Add 'ignore_malformed' to MappingLimitSettings

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

Add 'ignore_malformed' to MappingLimitSettings

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts
specification/indices/create/IndicesCreateResponse.ts

Misc fixes found validating Java client 8.2

---

output/typescript/types.ts
specification/_global/search/_types/suggester.ts

Add container_property variants to FieldSuggester

---

output/typescript/types.ts
specification/_global/search/_types/suggester.ts

[7.17] Add container_property variants to FieldSuggester

---

output/typescript/types.ts
specification/_types/aggregations/pipeline.ts
specification/ml/_types/TrainedModel.ts
specification/ml/_types/inference.ts
specification/ml/infer_trained_model_deployment/MlInferTrainedModelDeploymentRequest.ts
specification/ml/put_trained_model/MlPutTrainedModelRequest.ts

[ML] update inference configuration options for storage and inference

---

compiler/src/model/metamodel.ts
compiler/src/model/utils.ts
docs/modeling-guide.md
specification/_global/search/_types/suggester.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/analysis/analyzers.ts
specification/_types/analysis/char_filters.ts
specification/_types/analysis/token_filters.ts
specification/_types/analysis/tokenizers.ts
specification/_types/mapping/Property.ts
specification/_types/query_dsl/abstractions.ts
specification/ingest/_types/Processors.ts

[7.17] Add support for non exhaustive variants (#1662)

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts
specification/indices/create/IndicesCreateResponse.ts

[7.17] Misc fixes found validating Java client 8.2 (#1632)

---

output/typescript/types.ts
specification/_global/msearch/types.ts

Fix multi search request

---

output/typescript/types.ts
specification/security/has_privileges/SecurityHasPrivilegesRequest.ts

Fix security/has_privileges

---

output/typescript/types.ts
specification/_global/msearch/types.ts

Fix Multisearch request properties

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/component_templates/CatComponentTemplatesRequest.ts
specification/cat/component_templates/CatComponentTemplatesResponse.ts
specification/cat/component_templates/types.ts

Adds `cat.component_templates` request & response objects

Add request & response types for cat.component_templates

---

.github/workflows/metamodel-sync.yml

Verify that metamodel is always in sync between compiler and ts generator

---

compiler/src/model/utils.ts
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/delete_by_query/DeleteByQueryRequest.ts
specification/_global/msearch/MultiSearchRequest.ts
specification/_global/msearch/types.ts
specification/_global/reindex/ReindexRequest.ts
specification/_global/reindex/types.ts
specification/_global/search/SearchRequest.ts
specification/_global/search/_types/highlighting.ts
specification/_global/search/_types/suggester.ts
specification/_global/termvectors/types.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts
specification/_types/common.ts
specification/_types/mapping/Property.ts
specification/_types/mapping/core.ts
specification/ilm/_types/Policy.ts
specification/indices/analyze/types.ts
specification/security/_types/TransientMetadataConfig.ts
specification/security/get_service_accounts/types.ts
typescript-generator/src/metamodel.ts

[7.17] Fix spec issues reported in the Java client (#1723)

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/ml/_types/Model.ts
specification/ml/get_model_snapshot_upgrade_stats/MlGetModelSnapshotUpgradeStatsRequest.ts
specification/ml/get_model_snapshot_upgrade_stats/MlGetModelSnapshotUpgradeStatsResponse.ts

Adds request & response for `ml.get_model_snapshot_upgrade_stats`.

Add ml.get_model_snapshot_upgrade_stats

---

compiler/src/model/utils.ts
output/typescript/types.ts
specification/security/_types/Privileges.ts
specification/security/get_builtin_privileges/SecurityGetBuiltinPrivilegesRequest.ts
specification/security/put_role/SecurityPutRoleRequest.ts

Update cluster privileges list

---

output/typescript/types.ts
specification/security/_types/Privileges.ts
specification/security/get_user_privileges/SecurityGetUserPrivilegesResponse.ts

Backport https://github.com/elastic/elasticsearch-specification/commit/906a519c49fe09c81f3a95552208c6dbcf7dcd0b from https://github.com/elastic/elasticsearch-specification/pull/1735

Extract security.privileges.query in a typealias (#1735)

---

docs/add-new-api.md

We're tracking multiple branches now, not only 7.x.

Remove mention of only tracking 7.x

---

compiler/src/model/utils.ts
output/schema/validation-errors.json
output/typescript/types.ts
specification/security/_types/Privileges.ts
specification/security/_types/UserProfile.ts
specification/security/disable_user_profile/Request.ts
specification/security/enable_user_profile/Request.ts
specification/security/get_user_profile/Request.ts
specification/security/has_privileges_user_profile/Request.ts
specification/security/has_privileges_user_profile/Response.ts
specification/security/has_privileges_user_profile/types.ts
specification/security/suggest_user_profiles/Request.ts
specification/security/suggest_user_profiles/types.ts
specification/security/update_user_profile_data/Request.ts

Closes https://github.com/elastic/elasticsearch-specification/issues/1742

Add 'manage_user_profile' privilege, security.has_privileges_user_profile API

---

.gitignore
output/typescript/types.ts
specification/_spec_utils/Stringified.ts
specification/_types/aggregations/bucket.ts
specification/_types/analysis/token_filters.ts
specification/indices/_types/IndexSettings.ts
specification/indices/recovery/types.ts
specification/sql/translate/TranslateSqlResponse.ts

[7.17] Misc java fixes 220617 (#1773)

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/ml/_types/Authorization.ts
specification/ml/_types/Datafeed.ts
specification/ml/_types/DataframeAnalytics.ts
specification/ml/put_data_frame_analytics/MlPutDataFrameAnalyticsResponse.ts
specification/ml/put_datafeed/MlPutDatafeedResponse.ts
specification/ml/update_data_frame_analytics/MlUpdateDataFrameAnalyticsResponse.ts
specification/ml/update_datafeed/MlUpdateDatafeedResponse.ts
specification/transform/get_transform/types.ts
specification/transform/update_transform/UpdateTransformResponse.ts

Relates to https://github.com/elastic/elasticsearch/pull/87884

Add authorization object to ML datafeed, job, transform specifications

---

output/typescript/types.ts
specification/_global/search/_types/suggester.ts
specification/_types/analysis/char_filters.ts

[7.17] Fix suggestion options and mapping char filter (#1783)

---

output/typescript/types.ts
specification/_global/msearch/types.ts
specification/_global/search/SearchRequest.ts
specification/_types/Errors.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/analysis/icu-plugin.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts
specification/cluster/_types/ComponentTemplate.ts
specification/indices/_types/IndexSettings.ts
specification/security/get_token/GetUserAccessTokenResponse.ts

[7.17] Fix optional/missing fields reported via Java client issues (#1823)

---

output/typescript/types.ts
specification/_types/common.ts
specification/tasks/_types/TaskInfo.ts
specification/watcher/_types/Conditions.ts
specification/watcher/_types/Input.ts
specification/watcher/put_watch/WatcherPutWatchRequest.ts

* Add a cancelled property to `TaskInfo`.
* Add `UserDefinedValue` in `FieldValue` union.
* Fix watcher input and conditions.
Fixes #1886

[validation-errors] Fixes in watcher API

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/security/_types/ApiKey.ts
specification/security/_types/User.ts
specification/security/_types/UserProfile.ts
specification/security/get_api_key/SecurityGetApiKeyRequest.ts
specification/security/get_user/SecurityGetUserRequest.ts
specification/security/get_user_profile/Request.ts
specification/security/get_user_profile/Response.ts
specification/security/get_user_profile/types.ts
specification/security/grant_api_key/SecurityGrantApiKeyRequest.ts
specification/security/grant_api_key/SecurityGrantApiKeyResponse.ts
specification/security/grant_api_key/types.ts
specification/security/has_privileges_user_profile/Response.ts
specification/security/has_privileges_user_profile/types.ts
specification/security/query_api_keys/QueryApiKeysRequest.ts

Most of these changes can't be backported to 7.17 so I'll be creating a separate PR for 7.17.
Part of https://github.com/elastic/elasticsearch-specification/issues/1884

Fix type issues in security APIs

---

output/typescript/types.ts
specification/_types/common.ts
specification/tasks/_types/TaskInfo.ts
specification/watcher/_types/Conditions.ts
specification/watcher/_types/Input.ts

[Backport 7.17] [validation-errors] Fixes in watcher API (#1889)

---

.github/workflows/update-rest-api-json.yml

Bump branch on github workflow to 8.5

---

.github/workflows/validate-pr.yml

Change ref to 'main' for flight recorder

---

specification/_json_spec/ml.clear_trained_model_deployment_cache.json
specification/_json_spec/ml.infer_trained_model.json
specification/_json_spec/ml.put_trained_model_definition_part.json
specification/_json_spec/ml.put_trained_model_vocabulary.json
specification/_json_spec/ml.start_trained_model_deployment.json
specification/_json_spec/ml.stop_trained_model_deployment.json
specification/ml/_types/ModelPlot.ts
specification/ml/infer_trained_model/MlInferTrainedModelRequest.ts
specification/ml/put_trained_model_definition_part/MlPutTrainedModelDefinitionPartRequest.ts
specification/ml/put_trained_model_vocabulary/MlPutTrainedModelVocabularyRequest.ts
specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentRequest.ts
specification/ml/stop_trained_model_deployment/MlStopTrainedModelDeploymentRequest.ts

Closes https://github.com/elastic/elasticsearch-specification/issues/1907 In the interest of not spamming up the issues with errors, going to merge this one to unstick our automation.

Mark ML model APIs as beta

---

specification/_json_spec/security.activate_user_profile.json
specification/_json_spec/security.disable_user_profile.json
specification/_json_spec/security.enable_user_profile.json
specification/_json_spec/security.get_user_profile.json
specification/_json_spec/security.has_privileges_user_profile.json
specification/_json_spec/security.suggest_user_profiles.json
specification/_json_spec/security.update_user_profile_data.json
specification/security/activate_user_profile/Request.ts
specification/security/disable_user_profile/Request.ts
specification/security/enable_user_profile/Request.ts
specification/security/get_user_profile/Request.ts
specification/security/has_privileges_user_profile/Request.ts
specification/security/suggest_user_profiles/Request.ts
specification/security/update_user_profile_data/Request.ts

See: https://github.com/elastic/elasticsearch/pull/90439

Mark User Profile APIs as stable

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/aggregations/bucket.ts

Add support for the ip_prefix aggregation

---

output/typescript/types.ts
specification/_global/search/_types/suggester.ts

Related: https://github.com/elastic/elasticsearch-java/issues/411

Add collate_match and highlighted to SuggestionOptions

---

output/schema/validation-errors.json
specification/_types/aggregations/Aggregate.ts

Follow-up to #1795 - add `@variant` annotation to `IpPrefixAggregate`

Add missing @variant on IpPrefixAggregate

---

output/typescript/types.ts
specification/_global/search/_types/profile.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/bucket.ts
specification/_types/aggregations/pipeline.ts
specification/_types/common.ts

[8.5] Fix issues in aggregations found with java-client+recordings (#1940)

---

output/typescript/types.ts
specification/_global/search/_types/profile.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/bucket.ts
specification/_types/aggregations/pipeline.ts
specification/_types/common.ts

[7.17] Fix issues in aggregations found with java-client+recordings (#1940)

---

output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts
specification/indices/_types/IndexSettings.ts
specification/indices/rollover/types.ts

Additional fixes for the core and indices namespaces.

More fixes in the core and indices namespaces

---

output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts
specification/indices/_types/IndexSettings.ts
specification/indices/rollover/types.ts

[7.17] More fixes in the core and indices namespaces (#1958)

---

output/typescript/types.ts
specification/security/_types/Privileges.ts

IndicesPrivileges can contain multiple queries

---

output/typescript/types.ts
specification/security/_types/FieldSecurity.ts
specification/security/_types/Privileges.ts
specification/security/get_user_privileges/SecurityGetUserPrivilegesResponse.ts

[7.17] Fix user privileges (#1966)

---

output/typescript/types.ts
specification/ingest/_types/Processors.ts

[7.17] Fix optional Processor fields and add missing fields (#1970)

---

output/typescript/types.ts
specification/ilm/_types/Phase.ts

Adds the missing `frozen` phase to ILM.

Add frozen ILM phase

---

output/schema/validation-errors.json
specification/_json_spec/health.json
specification/_json_spec/ml.clear_trained_model_deployment_cache.json
specification/_json_spec/ml.infer_trained_model.json
specification/_json_spec/ml.put_trained_model_definition_part.json
specification/_json_spec/ml.put_trained_model_vocabulary.json
specification/_json_spec/ml.start_trained_model_deployment.json
specification/_json_spec/ml.stop_trained_model_deployment.json
specification/_json_spec/semantic_search.json
specification/_json_spec/transform.get_transform_stats.json
specification/ml/clear_trained_model_deployment_cache/MlClearTrainedModelDeploymentCacheRequest.ts
specification/ml/infer_trained_model/MlInferTrainedModelRequest.ts
specification/ml/put_trained_model_definition_part/MlPutTrainedModelDefinitionPartRequest.ts
specification/ml/put_trained_model_vocabulary/MlPutTrainedModelVocabularyRequest.ts
specification/ml/start_trained_model_deployment/MlStartTrainedModelDeploymentRequest.ts
specification/ml/stop_trained_model_deployment/MlStopTrainedModelDeploymentRequest.ts

Update JSON specs, fix stabilities

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/open_point_in_time/OpenPointInTimeRequest.ts

Closes https://github.com/elastic/elasticsearch-specification/issues/1980, also interested in testing CI to see if this PR can validate.

Add missing query parameters to 'open_point_in_time' API

---

output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/aggregations/bucket.ts

Closes https://github.com/elastic/elasticsearch-specification/issues/2022

Add 'frequent_item_sets' aggregation

---

.github/workflows/update-rest-api-json.yml

Update Stack versions in rest-api-spec updater

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/transform/schedule_now_transform/ScheduleNowTransformRequest.ts
specification/transform/schedule_now_transform/ScheduleNowTransformResponse.ts

Add 'transform.transform-schedule-now' API

---

output/typescript/types.ts
specification/snapshot/restore/SnapshotRestoreRequest.ts

Add feature_states parameter in snapshot.restore

---

output/typescript/types.ts
specification/security/_types/Privileges.ts

[8.8] Convert IndexPrivilege and ClusterPrivilege to non-exhaustive enums (#2084)

---

specification/security/_types/Privileges.ts

[7.17] Convert IndexPrivilege and ClusterPrivilege to non-exhaustive enums (#2084)

---

docs/modeling-guide.md

Fixes link in modeling-guide.md

---

compiler/src/model/metamodel.ts
compiler/src/model/utils.ts
specification/_global/search_mvt/_types/GridType.ts
specification/indices/stats/types.ts
specification/snapshot/_types/SnapshotInfo.ts
typescript-generator/src/metamodel.ts

Final part of https://github.com/elastic/elasticsearch-specification/issues/2107, but for enum members!

Add `@availability` tag to EnumMembers

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/cat/master/CatMasterRequest.ts
specification/cat/nodeattrs/CatNodeAttributesRequest.ts
specification/cat/nodeattrs/types.ts
specification/cat/nodes/CatNodesRequest.ts
specification/cat/nodes/types.ts
specification/cat/pending_tasks/CatPendingTasksRequest.ts
specification/cat/pending_tasks/types.ts
specification/cat/plugins/CatPluginsRequest.ts
specification/cat/plugins/types.ts
specification/cat/recovery/CatRecoveryRequest.ts
specification/cat/recovery/types.ts
specification/cat/repositories/CatRepositoriesRequest.ts
specification/cat/repositories/types.ts

This PR pulls descriptions from these docs:
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-nodeattrs.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-nodes.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-pending-tasks.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-plugins.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-recovery.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-repositories.html

Add descriptions for more cat APIs

---

output/typescript/types.ts
specification/_types/analysis/token_filters.ts
specification/indices/_types/IndexSettings.ts

Related to https://github.com/elastic/elasticsearch-net/issues/7755

Use `Stringified<boolean>` for `preserve_original` and `indexing_complete`

---

output/typescript/types.ts
specification/_doc_ids/table.csv
specification/logstash/_types/Pipeline.ts
specification/logstash/delete_pipeline/LogstashDeletePipelineRequest.ts
specification/logstash/get_pipeline/LogstashGetPipelineRequest.ts
specification/logstash/put_pipeline/LogstashPutPipelineRequest.ts

Adds descriptions to Logstash API properties. Source of info: https://www.elastic.co/guide/en/elasticsearch/reference/master/logstash-apis.html

[DOCS] Adds descriptions to Logstash APIs

---

.github/workflows/validate-pr.yml

Update STACK_VERSION to 8.10-SNAPSHOT in validate-pr.yml

---

output/schema/validation-errors.json
specification/logstash/get_pipeline/LogstashGetPipelineRequest.ts

Set id to optional in logstash.get_pipeline

---

specification/indices/_types/IndexSettings.ts

Relates to https://github.com/elastic/docs/pull/2807

Edit description in IndexSettings.ts

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/transform/delete_transform/DeleteTransformRequest.ts

Add delete_dest_index in DeleteTransformRequest

---

.gitattributes
output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_types/mapping/Property.ts

This add the SparseVectorProperty as part of the Property union.

Add sparse vector property

---

specification/esql/query/QueryRequest.ts

Remove leftover import from ES|QL Request

---

.github/workflows/validate-pr.yml
output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_types/common.ts
specification/indices/_types/DataStream.ts

[Backport 8.12] Fix definition of `ManagedBy`

---

output/typescript/types.ts
specification/_types/query_dsl/geo.ts

Fixes [issue 2387](https://github.com/elastic/elasticsearch-specification/issues/2387)

adding ignore_unmapped to GeoDistanceQuery (#2388)

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_json_spec/update_by_query.json
specification/indices/_types/IndexSettings.ts
specification/ingest/_types/Processors.ts
specification/nodes/info/types.ts

Backporting  [elastic/elasticsearch-specification#2412](https://github.com/elastic/elasticsearch-specification/pull/2412)

Backport 2412 to 8.13

---

output/openapi/elasticsearch-serverless-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_types/query_dsl/abstractions.ts
specification/nodes/info/types.ts

[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-knn-query.html) for ref.

Add knnquery to querycontainer

---

output/openapi/elasticsearch-serverless-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_types/query_dsl/abstractions.ts

[Backport 8.12] Add knnquery to querycontainer

---

specification/_json_spec/inference.delete_model.json
specification/_json_spec/inference.get_model.json
specification/_json_spec/inference.inference.json
specification/_json_spec/inference.put_model.json
specification/inference/delete_model/DeleteModelRequest.ts
specification/inference/get_model/GetModelRequest.ts
specification/inference/inference/InferenceRequest.ts
specification/inference/put_model/PutModelRequest.ts

This propagates the changes made in https://github.com/elastic/elasticsearch/commit/5f325187cb7ef997e152132943b770a8b00447ea

[Inference API] update path arguments

---

compiler/src/model/build-model.ts
output/typescript/types.ts
specification/snapshot/_types/SnapshotRepository.ts
specification/snapshot/create_repository/SnapshotCreateRepositoryRequest.ts

[7.17] Expand snapshot repository types (#2255)

---

output/typescript/types.ts
specification/_types/Stats.ts
specification/_types/Time.ts
specification/_types/aggregations/bucket.ts
specification/_types/analysis/tokenizers.ts

This PR backports some old fixes to branch 7.17:
- #2232 -> to solve [java client issue 418](https://github.com/elastic/elasticsearch-java/issues/418) 
- #2039 -> to solve [java client issue 296](https://github.com/elastic/elasticsearch-java/issues/296) and [347](https://github.com/elastic/elasticsearch-java/issues/347)
- #2151 -> to solve [java client issue 238](https://github.com/elastic/elasticsearch-java/issues/238)

Java client backport old issues 7.17

---

output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

[7.17] Rewrite similarity definition (#2454)

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/ml/put_trained_model/MlPutTrainedModelRequest.ts

The `wait_for_completion` query parameter was first added in elastic/elasticsearch#95281

Add wait_for_completion to PUT trained model API

---

output/openapi/elasticsearch-serverless-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/msearch/types.ts
specification/_types/Base.ts
specification/_types/aggregations/bucket.ts
specification/_types/analysis/char_filters.ts
specification/_types/mapping/RuntimeFields.ts
specification/_types/mapping/core.ts
specification/ilm/put_lifecycle/PutLifecycleRequest.ts

Java issues batch 3 partial 8.13 backport

---

output/openapi/elasticsearch-serverless-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/connector.sync_job_cancel.json
specification/_json_spec/connector.sync_job_delete.json
specification/_json_spec/connector.sync_job_get.json
specification/_json_spec/connector.sync_job_list.json
specification/_json_spec/connector.sync_job_post.json
specification/connector/_types/SyncJob.ts
specification/connector/sync_job_cancel/SyncJobCancelRequest.ts
specification/connector/sync_job_cancel/SyncJobCancelResponse.ts
specification/connector/sync_job_delete/SyncJobDeleteRequest.ts
specification/connector/sync_job_delete/SyncJobDeleteResponse.ts
specification/connector/sync_job_get/SyncJobGetRequest.ts
specification/connector/sync_job_get/SyncJobGetResponse.ts
specification/connector/sync_job_list/SyncJobListRequest.ts
specification/connector/sync_job_list/SyncJobListResponse.ts
specification/connector/sync_job_post/SyncJobPostRequest.ts
specification/connector/sync_job_post/SyncJobPostResponse.ts

(cherry picked from commit 9f0dc3db0a0f82ef9ebebb276bcfdcaf28c69e6a) from #2503

[Backport 8.14] Connector SyncJob API spec (#2503)

---

specification/_doc_ids/table.csv

This PR fixes an issue that I found while testing the default OAS linter from Spectral.

Fix broken link

---

.github/workflows/code-format.yml
.github/workflows/compiler.test.yml
.github/workflows/gh-pages-report.yml
.github/workflows/license.yml
.github/workflows/linter.yml
.github/workflows/metamodel-sync.yml
.github/workflows/update-rest-api-json.yml
.github/workflows/validate-pr.yml

Validation currently fails, see https://github.com/elastic/elasticsearch-specification/actions/runs/9093977704/job/25087280424

Upgrade to checkout@v4

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/search_application/search/SearchApplicationsSearchRequest.ts

Server code will probably fix this in 8.14.1, but we can get ready before that

Added typed_keys query param in search app search

---

output/openapi/elasticsearch-serverless-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/analysis/icu-plugin.ts
specification/_types/mapping/Property.ts
specification/_types/mapping/specialized.ts

Related to: https://github.com/elastic/elasticsearch-net/issues/8212
Server code:
https://github.com/elastic/elasticsearch/blob/c5892a7044b51012e5680346c3bf7e03a70ce70d/plugins/analysis-icu/src/main/java/org/elasticsearch/plugin/analysis/icu/ICUCollationKeywordFieldMapper.java#L221

Add `IcuCollationProperty`

---

.github/workflows/generate.yml

[8.0] Minor generation workflow bugfix (#2187)

---

.github/workflows/generate.yml

[7.17] Minor generation workflow bugfix (#2187)

---

.github/labeler.yml
.github/workflows/labeler.yml

This fixes a Node.js 16 deprecation warning.

Switch to actions/labeler@v5

---

.github/workflows/code-format.yml
.github/workflows/generate.yml
.github/workflows/linter.yml
.github/workflows/update-rest-api-json.yml

I checked manually that the commands still work, even if ts-standard now complains that the TypeScript version is too recent:
```
=============                                                                                                                                                 
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.                         
You may find that it works just fine, or you may not.                                                                                                         
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0                                                                                                                 
YOUR TYPESCRIPT VERSION: 4.5.5 …
```

[7.17] Update to Node 20 and setup-node@v4

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/security/_types/RoleDescriptor.ts
specification/security/query_role/QueryRolesRequest.ts
specification/security/query_role/QueryRolesResponse.ts
specification/security/query_role/types.ts

https://github.com/elastic/elasticsearch-specification/pull/2676

[Backport 8.15] Add spec for bulk put roles

---

.github/workflows/update-rest-api-json.yml

Update 8.15 JSON spec, not 8.13

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/_global/scripts_painless_execute/ExecutePainlessScriptRequest.ts
specification/_types/Scripting.ts
specification/query_rules/_types/QueryRuleset.ts
specification/search_application/_types/SearchApplication.ts
specification/security/_types/Privileges.ts

[Backport 8.15] Transform script into a container (#2708)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/connector/_types/Connector.ts
specification/connector/_types/SyncJob.ts
specification/connector/delete/ConnectorDeleteRequest.ts
specification/connector/last_sync/ConnectorUpdateLastSyncRequest.ts
specification/connector/post/ConnectorPostRequest.ts
specification/connector/post/ConnectorPostResponse.ts
specification/connector/put/ConnectorPutRequest.ts
specification/connector/put/ConnectorPutResponse.ts
specification/connector/sync_job_list/SyncJobListRequest.ts
specification/connector/update_api_key_id/ConnectorUpdateAPIKeyIDRequest.ts
specification/connector/update_name/ConnectorUpdateNameRequest.ts

[Connector APIs] Update existing endpoints for 8.15 (#2675)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/_types/Knn.ts

Reflecting the recent server side [change](https://github.com/elastic/elasticsearch/blob/4694a44bd4ac042a0d9f047d376f46361fc01f2a/server/src/main/java/org/elasticsearch/search/vectors/KnnVectorQueryBuilder.java#L64)

Adding k to knn search

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_global/update_by_query/UpdateByQueryRequest.ts

Add q parameter to Update By Query API

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/ml/_types/inference.ts

simplifying the definition of predicted_value

making predicted_value scalar

---

output/openapi/elasticsearch-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ingest/get_geoip_database/GetGeoipDatabaseRequest.ts
specification/ingest/get_geoip_database/GetGeoipDatabaseResponse.ts

Part of #2810 
Thanks to https://github.com/elastic/elasticsearch/pull/112216 we have validation for this API, which helpfully fixed a few errors I made during development.

Add Get geoip database configuration API

---

output/openapi/elasticsearch-openapi.json
output/typescript/types.ts
specification/ingest/geo_ip_stats/types.ts

Thanks to https://github.com/elastic/elasticsearch/pull/112216 we now have one YAML test for this API.

Fix GeoIP stats API response

---

output/openapi/elasticsearch-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ingest/get_geoip_database/GetGeoipDatabaseRequest.ts
specification/ingest/get_geoip_database/GetGeoipDatabaseResponse.ts

(cherry picked from commit 79760efc9be565f93ca57e51c5d25b0d24833398)

[Backport 8.15] Add Get geoip database configuration API (#2815)

---

output/openapi/elasticsearch-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/ingest/_types/Database.ts
specification/ingest/get_geoip_database/GetGeoipDatabaseResponse.ts
specification/ingest/put_geoip_database/PutGeoipDatabaseRequest.ts
specification/ingest/put_geoip_database/PutGeoipDatabaseResponse.ts

(cherry picked from commit 48a6409d5a0ea07f8b23a55e1043e2246ab05dbd)

[Backport 8.15] Add Create or update geoip database configuration API (#2823)

---

compiler-rs/clients_schema_to_openapi/package-lock.json
compiler/package-lock.json

By running `npm update micromatch` in the relevant directories.

Fix dependabot alert on micromatch

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/aggregations/Aggregate.ts

doc_count already exists in parent class

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/aggregations/bucket.ts

(cherry picked from commit be63cfca75741f17b1a8463f5d26ea31408ca060)

[Backport 8.15] Add time series aggregation (#2862)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_types/common.ts
specification/ingest/_types/Processors.ts
specification/ml/_types/Category.ts
specification/text_structure/find_structure/FindStructureRequest.ts
specification/text_structure/find_structure/FindStructureResponse.ts
specification/text_structure/test_grok_pattern/TestGrokPatternRequest.ts

* Add Redact processor
* Add GrokPattern alias
(cherry picked from commit 39ba8e8550e75ed515c0fd76803738df3b8aafcb)

[Backport 8.15] Add Redact processor (#2858)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/esql/query/QueryRequest.ts

[8.15] Use an enum for ES|QL format parameter (#2873)

---

.github/workflows/validate-pr.yml

(cherry picked from commit 5d13480346d21a788477ce31b0190c0946a45671)

[Backport 8.15] Run validation on backports too (#2895)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/_types/analysis/token_filters.ts
specification/_types/analysis/tokenizers.ts

I know there are some other things to fix (say all token filters), but this only fixes the minimum to get validation passing. Feel free to push back and ask for more.

Fix indices.analyze request

---

.github/download-artifacts/index.js
.github/workflows/update-rest-api-json.yml

(cherry picked from commit 0464df58867761123eec71e31bde5575189fceb3)

[Backport 8.x] Fetch JSON spec from Artifacts Snapshot API (#2949)

---

docs/overlays/elasticsearch-shared-overlays.yaml
output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/_doc_ids/table.csv
specification/_global/knn_search/KnnSearchRequest.ts
specification/_types/Knn.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/aggregations/bucket.ts
specification/_types/aggregations/metric.ts
specification/_types/aggregations/pipeline.ts
specification/_types/analysis/char_filters.ts
specification/_types/analysis/token_filters.ts
specification/_types/analysis/tokenizers.ts
specification/_types/query_dsl/MatchAllQuery.ts
specification/_types/query_dsl/MatchNoneQuery.ts
specification/_types/query_dsl/SemanticQuery.ts
specification/_types/query_dsl/SparseVectorQuery.ts
specification/_types/query_dsl/TextExpansionQuery.ts
specification/_types/query_dsl/WeightedTokensQuery.ts
specification/_types/query_dsl/abstractions.ts
specification/_types/query_dsl/compound.ts
specification/_types/query_dsl/fulltext.ts
specification/_types/query_dsl/geo.ts
specification/_types/query_dsl/joining.ts
specification/_types/query_dsl/span.ts
specification/_types/query_dsl/specialized.ts
specification/_types/query_dsl/term.ts
specification/ml/_types/Analysis.ts
specification/ml/_types/Datafeed.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/3023 from d2ba7e5ddbf3f5855576e576d1e8b74f82db0b8e

[8.x][OpenAPI] Add x-model to specialized queries (#3023)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/_doc_ids/table.csv
specification/security/get_user_privileges/SecurityGetUserPrivilegesRequest.ts
specification/security/get_user_profile/Request.ts
specification/security/grant_api_key/SecurityGrantApiKeyRequest.ts
specification/security/has_privileges/SecurityHasPrivilegesRequest.ts
specification/security/has_privileges_user_profile/Request.ts
specification/security/invalidate_api_key/SecurityInvalidateApiKeyRequest.ts
specification/security/invalidate_token/SecurityInvalidateTokenRequest.ts
specification/security/put_privileges/SecurityPutPrivilegesRequest.ts
specification/security/put_role/SecurityPutRoleRequest.ts
specification/security/put_role_mapping/SecurityPutRoleMappingRequest.ts
specification/security/put_user/SecurityPutUserRequest.ts
specification/security/query_api_keys/QueryApiKeysRequest.ts
specification/security/query_role/QueryRolesRequest.ts
specification/security/query_user/SecurityQueryUserRequest.ts
specification/security/saml_authenticate/Request.ts
specification/security/saml_complete_logout/Request.ts
specification/security/saml_invalidate/Request.ts
specification/security/saml_logout/Request.ts
specification/security/saml_prepare_authentication/Request.ts
specification/security/saml_service_provider_metadata/Request.ts
specification/security/suggest_user_profiles/Request.ts
specification/security/update_api_key/Request.ts
specification/security/update_user_profile_data/Request.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/3036 from d170981470e89d2e51b289807a7028938e002a9e

[8.x][OpenAPI] Edit more security API summaries (#3036)

---

docs/overlays/elasticsearch-shared-overlays.yaml
output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts
specification/_global/mget/MultiGetRequest.ts
specification/_global/mtermvectors/MultiTermVectorsRequest.ts
specification/_global/reindex_rethrottle/ReindexRethrottleRequest.ts
specification/_global/update_by_query_rethrottle/UpdateByQueryRethrottleRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/3052 with bfbe862fceb2dc6c4d3379646885f1efd650fdcd

[8.x][OpenAPI] Edit mget, multi term vectors, and terms enum APIs (#3052)

---

docs/overlays/elasticsearch-shared-overlays.yaml
output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/_global/delete_by_query_rethrottle/DeleteByQueryRethrottleRequest.ts
specification/_global/mget/MultiGetRequest.ts
specification/_global/mtermvectors/MultiTermVectorsRequest.ts
specification/_global/reindex_rethrottle/ReindexRethrottleRequest.ts
specification/_global/update_by_query_rethrottle/UpdateByQueryRethrottleRequest.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/3052 with https://github.com/elastic/elasticsearch-specification/commit/bfbe862fceb2dc6c4d3379646885f1efd650fdcd

[8.16][OpenAPI] Edit mget, multi term vectors, and terms enum APIs (#3052)

---

docs/overlays/elasticsearch-shared-overlays.yaml
output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/_doc_ids/table.csv
specification/_global/knn_search/KnnSearchRequest.ts
specification/_types/Knn.ts
specification/_types/aggregations/Aggregate.ts
specification/_types/aggregations/AggregationContainer.ts
specification/_types/aggregations/bucket.ts
specification/_types/aggregations/metric.ts
specification/_types/aggregations/pipeline.ts
specification/_types/analysis/char_filters.ts
specification/_types/analysis/token_filters.ts
specification/_types/analysis/tokenizers.ts
specification/_types/query_dsl/MatchAllQuery.ts
specification/_types/query_dsl/MatchNoneQuery.ts
specification/_types/query_dsl/SemanticQuery.ts
specification/_types/query_dsl/SparseVectorQuery.ts
specification/_types/query_dsl/TextExpansionQuery.ts
specification/_types/query_dsl/WeightedTokensQuery.ts
specification/_types/query_dsl/abstractions.ts
specification/_types/query_dsl/compound.ts
specification/_types/query_dsl/fulltext.ts
specification/_types/query_dsl/geo.ts
specification/_types/query_dsl/joining.ts
specification/_types/query_dsl/span.ts
specification/_types/query_dsl/specialized.ts
specification/_types/query_dsl/term.ts
specification/ml/_types/Analysis.ts
specification/ml/_types/Datafeed.ts

Backports https://github.com/elastic/elasticsearch-specification/pull/3023 from d2ba7e5ddbf3f5855576e576d1e8b74f82db0b8e

[8.16][OpenAPI] Add x-model to specialized queries (#3023)

---

docs/overlays/elasticsearch-openapi-overlays.yaml
output/openapi/elasticsearch-openapi.json
specification/_doc_ids/table.csv
specification/autoscaling/_types/AutoscalingPolicy.ts
specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts
specification/autoscaling/delete_autoscaling_policy/autoscalingApisDeleteAutoscalingPolicyResponseExample1.json
specification/autoscaling/delete_autoscaling_policy/autoscalingApisDeleteAutoscalingPolicyResponseExample1.yaml
specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts
specification/autoscaling/get_autoscaling_capacity/autoscalingApisGetAutoscalingCapacityResponseExample1.json
specification/autoscaling/get_autoscaling_capacity/autoscalingApisGetAutoscalingCapacityResponseExample1.yaml
specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts
specification/autoscaling/get_autoscaling_policy/autoscalingApisGetAutoscalingPolicyResponseExample1.json
specification/autoscaling/get_autoscaling_policy/autoscalingApisGetAutoscalingPolicyResponseExample1.yaml
specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts
specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample1.json
specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample1.yaml
specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample2.json
specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyRequestExample2.yaml
specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyResponseExample1.json
specification/autoscaling/put_autoscaling_policy/autoscalingApisPutAutoscalingPolicyResponseExample1.yaml

Backports https://github.com/elastic/elasticsearch-specification/pull/3081 from b0860fca5b1e7049848d622b31481ff5f02a1a47

[8.x][OpenAPI] Edits the autoscaling APIs (#3081)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/security/_types/RoleDescriptor.ts

(cherry picked from commit 496e0b85f4e9550789ad8db8d33bc6daa00a7b89)

[8.x] Add restriction to RoleDescriptor (#3142)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/security/_types/Privileges.ts

(cherry picked from commit dd55c46bfe8334f57dfd831b56197ed3574a8a8b)

[8.x] Allow index name patterns in Privileges index fields (#3127)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/security/_types/ApiKey.ts
specification/security/authenticate/SecurityAuthenticateResponse.ts

(cherry picked from commit 986d9dba35768389938eb9801846668682138734)

[Backport 8.16] Fix security.get_api_key and security.query_api_keys APIs (#3146)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_json_spec/async_search.submit.json
specification/async_search/status/AsyncSearchStatusRequest.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts

I submitted the rest-api-spec changes to https://github.com/elastic/elasticsearch/pull/117312.

Fix async_search query parameter validation

---

docs/overlays/elasticsearch-openapi-overlays.yaml

Backports https://github.com/elastic/elasticsearch-specification/pull/3198

[8.17][OpenAPI] Add securitySchemes and security in overlays (#3198)

---

docs/overlays/elasticsearch-openapi-overlays.yaml

Backports https://github.com/elastic/elasticsearch-specification/pull/3198

[8.16][OpenAPI] Add securitySchemes and security in overlays (#3198)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/cat/allocation/CatAllocationRequest.ts
specification/cat/fielddata/CatFielddataRequest.ts
specification/cat/health/CatHealthRequest.ts
specification/cat/master/CatMasterRequest.ts
specification/cat/nodeattrs/CatNodeAttributesRequest.ts
specification/cat/nodes/CatNodesRequest.ts
specification/cat/pending_tasks/CatPendingTasksRequest.ts
specification/cat/plugins/CatPluginsRequest.ts
specification/cat/recovery/CatRecoveryRequest.ts
specification/cat/repositories/CatRepositoriesRequest.ts
specification/cat/segments/CatSegmentsRequest.ts
specification/cat/shards/CatShardsRequest.ts
specification/cat/snapshots/CatSnapshotsRequest.ts
specification/cat/tasks/CatTasksRequest.ts
specification/cat/templates/CatTemplatesRequest.ts
specification/cat/thread_pool/CatThreadPoolRequest.ts
specification/cat/transforms/CatTransformsRequest.ts

Relates to 
This PR edits the cat API summaries in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-cat based on information in https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html

[DOCS] Edit CAT operation summaries

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/_doc_ids/table.csv
specification/ilm/delete_lifecycle/DeleteLifecycleRequest.ts
specification/ilm/explain_lifecycle/ExplainLifecycleRequest.ts
specification/ilm/get_lifecycle/GetLifecycleRequest.ts
specification/ilm/get_status/GetIlmStatusRequest.ts
specification/ilm/migrate_to_data_tiers/Request.ts
specification/ilm/move_to_step/MoveToStepRequest.ts
specification/ilm/put_lifecycle/PutLifecycleRequest.ts
specification/ilm/remove_policy/RemovePolicyRequest.ts
specification/ilm/retry/RetryIlmRequest.ts
specification/ilm/start/StartIlmRequest.ts
specification/ilm/stop/StopIlmRequest.ts
specification/indices/explain_data_lifecycle/IndicesExplainDataLifecycleRequest.ts

This PR edits the ILM operations (https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-ilm) based on details from https://www.elastic.co/guide/en/elasticsearch/reference/master/index-lifecycle-management-api.html

[DOCS] Edit ILM operation summaries

---

output/openapi/elasticsearch-openapi.json
specification/_doc_ids/table.csv
specification/features/get_features/GetFeaturesRequest.ts
specification/features/reset_features/ResetFeaturesRequest.ts

This PR edits the feature APIs (https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-features) based on information copied from https://www.elastic.co/guide/en/elasticsearch/reference/current/features-apis.html

[DOCS] Edit feature operation summaries

---

output/openapi/elasticsearch-openapi.json
specification/_doc_ids/table.csv
specification/ccr/delete_auto_follow_pattern/DeleteAutoFollowPatternRequest.ts
specification/ccr/follow/CreateFollowIndexRequest.ts
specification/ccr/follow_info/FollowInfoRequest.ts
specification/ccr/follow_stats/FollowIndexStatsRequest.ts
specification/ccr/forget_follower/ForgetFollowerIndexRequest.ts
specification/ccr/get_auto_follow_pattern/GetAutoFollowPatternRequest.ts
specification/ccr/pause_auto_follow_pattern/PauseAutoFollowPatternRequest.ts
specification/ccr/pause_follow/PauseFollowIndexRequest.ts
specification/ccr/put_auto_follow_pattern/PutAutoFollowPatternRequest.ts
specification/ccr/resume_auto_follow_pattern/ResumeAutoFollowPatternRequest.ts
specification/ccr/resume_follow/ResumeFollowIndexRequest.ts
specification/ccr/stats/CcrStatsRequest.ts
specification/ccr/unfollow/UnfollowIndexRequest.ts

This PR edits the summaries in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-ccr based on information from https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-apis.html

[DOCS] Edit CCR operation summaries

---

compiler/src/steps/validate-model.ts
output/schema/validation-errors.json

This reduces the number of validation errors from 205 to 179.

Stop generating errors for body inheritance

---

output/openapi/elasticsearch-openapi.json
specification/slm/delete_lifecycle/DeleteSnapshotLifecycleRequest.ts
specification/slm/execute_lifecycle/ExecuteSnapshotLifecycleRequest.ts
specification/slm/execute_retention/ExecuteRetentionRequest.ts
specification/slm/get_lifecycle/GetSnapshotLifecycleRequest.ts
specification/slm/get_stats/GetSnapshotLifecycleStatsRequest.ts
specification/slm/get_status/GetSnapshotLifecycleManagementStatusRequest.ts
specification/slm/put_lifecycle/PutSnapshotLifecycleRequest.ts
specification/slm/start/StartSnapshotLifecycleManagementRequest.ts
specification/slm/stop/StopSnapshotLifecycleManagementRequest.ts

This PR edits the SLM summaries in https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-slm based on information from https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshot-lifecycle-management-api.html

[DOCS] Edit snapshot lifecycle management summaries

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/logstash/delete_pipeline/LogstashDeletePipelineRequest.ts
specification/logstash/get_pipeline/LogstashGetPipelineRequest.ts
specification/logstash/get_pipeline/LogstashGetPipelineResponseExample1.yaml
specification/logstash/put_pipeline/LogstashPutPipelineRequest.ts
specification/logstash/put_pipeline/LogstashPutPipelineRequestExample1.yaml

This PR copies the examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/logstash-apis.html

Add Logstash API examples

---

specification/_doc_ids/table.csv
specification/snapshot/cleanup_repository/SnapshotCleanupRepositoryRequest.ts
specification/snapshot/cleanup_repository/examples/response/SnapshotCleanupRepositoryResponseExample1.yaml
specification/snapshot/clone/SnapshotCloneRequest.ts
specification/snapshot/clone/examples/request/SnapshotCloneRequestExample1.yaml
specification/snapshot/create/SnapshotCreateRequest.ts
specification/snapshot/create/examples/request/SnapshotCreateRequestExample1.yaml
specification/snapshot/create/examples/response/SnapshotCreateResponseExample1.yaml
specification/snapshot/create_repository/examples/request/SnapshotCreateRepositoryRequestExample1.yaml
specification/snapshot/create_repository/examples/request/SnapshotCreateRepositoryRequestExample2.yaml
specification/snapshot/create_repository/examples/request/SnapshotCreateRepositoryRequestExample3.yaml
specification/snapshot/create_repository/examples/request/SnapshotCreateRepositoryRequestExample4.yaml
specification/snapshot/create_repository/examples/request/SnapshotCreateRepositoryRequestExample5.yaml
specification/snapshot/create_repository/examples/request/SnapshotCreateRepositoryRequestExample6.yaml
specification/snapshot/delete/SnapshotDeleteRequest.ts
specification/snapshot/delete/examples/response/SnapshotDeleteResponseExample1.yaml
specification/snapshot/delete_repository/SnapshotDeleteRepositoryRequest.ts
specification/snapshot/get/SnapshotGetRequest.ts
specification/snapshot/get/examples/response/SnapshotGetResponseExample1.yaml
specification/snapshot/get_repository/SnapshotGetRepositoryRequest.ts
specification/snapshot/get_repository/examples/response/SnapshotGetRepositoryResponseExample1.yaml
specification/snapshot/repository_verify_integrity/SnapshotRepositoryVerifyIntegrityRequest.ts
specification/snapshot/restore/SnapshotRestoreRequest.ts
specification/snapshot/restore/examples/request/SnapshotRestoreRequestExample1.yaml
specification/snapshot/restore/examples/request/SnapshotRestoreRequestExample2.yaml
specification/snapshot/status/SnapshotStatusRequest.ts
specification/snapshot/status/examples/response/SnapshotStatusResponseExample1.yaml
specification/snapshot/verify_repository/SnapshotVerifyRepositoryRequest.ts

This PR copies examples from https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshot-restore-apis.html

Add snapshot and restore examples

---

output/openapi/elasticsearch-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/snapshot/_types/SnapshotRepository.ts
specification/snapshot/_types/SnapshotShardsStats.ts
specification/snapshot/_types/SnapshotShardsStatsStage.ts
specification/snapshot/_types/SnapshotStats.ts
specification/snapshot/_types/SnapshotStatus.ts
specification/snapshot/cleanup_repository/SnapshotCleanupRepositoryRequest.ts
specification/snapshot/cleanup_repository/SnapshotCleanupRepositoryResponse.ts
specification/snapshot/clone/SnapshotCloneRequest.ts
specification/snapshot/create/SnapshotCreateRequest.ts
specification/snapshot/create_repository/SnapshotCreateRepositoryRequest.ts
specification/snapshot/delete/SnapshotDeleteRequest.ts
specification/snapshot/delete_repository/SnapshotDeleteRepositoryRequest.ts
specification/snapshot/get/SnapshotGetRequest.ts
specification/snapshot/get/SnapshotGetResponse.ts
specification/snapshot/get_repository/SnapshotGetRepositoryRequest.ts
specification/snapshot/repository_verify_integrity/SnapshotRepositoryVerifyIntegrityRequest.ts
specification/snapshot/restore/SnapshotRestoreRequest.ts
specification/snapshot/status/SnapshotStatusRequest.ts
specification/snapshot/verify_repository/SnapshotVerifyRepositoryRequest.ts
specification/snapshot/verify_repository/SnapshotVerifyRepositoryResponse.ts

This PR adds properties and descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/master/put-snapshot-repo-api.html and the repository settings details from the pages under https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshots-register-repository.html

Add snapshot repository descriptions

---

compiler-rs/clients_schema_to_openapi/package-lock.json

[8.x] Bump jsonpath-plus and @stoplight/spectral-core (#3124)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/indices/_types/IndexSettings.ts

Added by https://github.com/elastic/elasticsearch/pull/95423.

Add index.lifecycle.prefer_ilm setting

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/_doc_ids/table.csv
specification/_global/update_by_query/UpdateByQueryRequest.ts
specification/_global/update_by_query/UpdateByQueryResponse.ts
specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample1.yaml
specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample2.yaml
specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample3.yaml
specification/_global/update_by_query/examples/request/UpdateByQueryRequestExample4.yaml
specification/_global/update_by_query_rethrottle/UpdateByQueryRethrottleRequest.ts

This PR copies examples and descriptions from https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

[DOCS] Add examples for update by query

---

docs/modeling-guide.md

Explain purpose of server_default

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
package-lock.json
package.json
specification/cluster/_types/ComponentTemplate.ts

- [Fix cluster.get_component_template API (#3617)](https://github.com/elastic/elasticsearch-specification/pull/3617)

[8.17] Fix cluster.get_component_template API (#3617)

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
output/typescript/types.ts
specification/eql/_types/EqlSearchResponseBase.ts

[8.x] Add shard_failures to EQL response spec (#3372)

---

package-lock.json
specification/_global/bulk/BulkRequest.ts
specification/_global/create/CreateRequest.ts
specification/_global/index/IndexRequest.ts
specification/_global/update/UpdateRequest.ts

Fix server default for include_source_on_error

Fix server default for include_source_on_error

---

docs/overlays/elasticsearch-shared-overlays.yaml

Add info about required privileges to call Connector API endpoints

[Connector API][Doc] Add info about required privileges

---

output/openapi/elasticsearch-openapi.json
output/typescript/types.ts
specification/ilm/explain_lifecycle/types.ts

Server code references: [main response class](https://github.com/elastic/elasticsearch/blob/5e3fed02f1e799b217605c2eecf67f82f08f5e5d/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/IndexLifecycleExplainResponse.java#L485), [`phase_execution` field](https://github.com/elastic/elasticsearch/blob/5e3fed02f1e799b217605c2eecf67f82f08f5e5d/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/PhaseExecutionInfo.java#L129)

Adding missing fields to lifecycle explain response

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_types/query_dsl/abstractions.ts
specification/_types/query_dsl/geo.ts

Server code: https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/GeoGridQueryBuilder.java

Adding geo_grid query

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_types/mapping/core.ts

Fixes/unblock: https://github.com/elastic/elasticsearch-net/issues/8467
Add property mentioned in docs https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-text.html#semantic-text-params but missing in the specification.
Closes https://github.com/elastic/elasticsearch-specification/pull/3923

Add search_inference_id property

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put.openai.json
specification/inference/_types/Services.ts
specification/inference/put_openai/PutOpenAiRequest.ts
specification/inference/put_openai/PutOpenAiResponse.ts
specification/inference/put_openai/examples/request/PutOpenAiRequestExample1.yaml
specification/inference/put_openai/examples/request/PutOpenAiRequestExample2.yaml
specification/inference/put_watsonx/PutWatsonxRequest.ts

- [Add OpenAI inference details (#3929)](https://github.com/elastic/elasticsearch-specification/pull/3929)

[8.18] Add OpenAI inference details (#3929)

---

package-lock.json
package.json

This currently trips up every new contributor.

Add changes from `make setup`

---

specification/_global/mtermvectors/examples/request/MultiTermVectorsRequestExample2.yaml
specification/ml/evaluate_data_frame/examples/request/MlEvaluateDataFrameRequestExample4.yaml

A couple of minor mistakes that I've found in example requests while working on request converter testing.

Minor fixes in example requests

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put.eis.json
specification/inference/put_eis/PutEisRequest.ts
specification/inference/put_eis/PutEisResponse.ts
specification/inference/put_eis/example/request/PutEisRequestExample.yaml

Backport of https://github.com/elastic/elasticsearch-specification/pull/3987

[8.x] Adds PUT EIS inference details 

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put.eis.json
specification/inference/put_eis/PutEisRequest.ts
specification/inference/put_eis/PutEisResponse.ts
specification/inference/put_eis/example/request/PutEisRequestExample.yaml

Backport of https://github.com/elastic/elasticsearch-specification/pull/3987

[8.18] Adds PUT EIS inference details

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put.voyageai.json
specification/inference/put_voyageai/PutVoyageAIRequest.ts
specification/inference/put_voyageai/PutVoyageAIResponse.ts
specification/inference/put_voyageai/examples/request/PutVoyageAIRequestExample1.yaml
specification/inference/put_voyageai/examples/request/PutVoyageAIRequestExample2.yaml

Backport of https://github.com/elastic/elasticsearch-specification/pull/4009

[8.x] Adds VoyageAI PUT inference details

---

compiler/src/steps/validate-model.ts
output/schema/validation-errors.json

We have other ways of identifying them.

Stop reporting missing endpoints as errors

---

output/openapi/elasticsearch-serverless-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.post_eis_chat_completion.json
specification/inference/_types/CommonTypes.ts
specification/inference/chat_completion_unified/UnifiedRequest.ts
specification/inference/post_eis_chat_completion/PostEisChatCompletionRequest.ts
specification/inference/post_eis_chat_completion/PostEisChatCompletionResponse.ts
specification/inference/post_eis_chat_completion/examples/PostEisChatCompletionRequestExample.yaml

Backport of https://github.com/elastic/elasticsearch-specification/pull/3940

[9.0] Adds EIS POST inference details

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_hugging_face.json
specification/inference/put_hugging_face/PutHuggingFaceRequest.ts
specification/inference/put_hugging_face/PutHuggingFaceResponse.ts
specification/inference/put_hugging_face/examples/request/PutHuggingFaceRequestExample1.yaml

Relates to https://github.com/elastic/elasticsearch-specification/issues/3821
This PR adds Hugging Face inference API details and an example, derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-hugging-face.html

Add Hugging Face inference API details

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_elser.json
specification/inference/put_elser/PutElserRequest.ts
specification/inference/put_elser/PutElserResponse.ts
specification/inference/put_elser/examples/request/PutElserRequestExample1.yaml
specification/inference/put_elser/examples/request/PutElserRequestExample2.yaml
specification/inference/put_elser/examples/response/PutElserResponseExample1.yaml

This PR adds details and examples to the ELSER inference API, derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-elser.html

Add ELSER inference API details

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_elasticsearch.json
specification/inference/put_elasticsearch/PutElasticsearchRequest.ts
specification/inference/put_elasticsearch/PutElasticsearchResponse.ts
specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample1.yaml
specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample2.yaml
specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample3.yaml
specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample4.yaml
specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample5.yaml
specification/inference/put_elasticsearch/examples/request/PutElasticsearchRequestExample6.yaml
specification/inference/put_elasticsearch/examples/response/PutElasticsearchResponseExample1.yaml

This PR adds details derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-elasticsearch.html

Add Elasticsearch inference API details

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
package-lock.json
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_amazonbedrock.json
specification/inference/put_amazonbedrock/PutAmazonBedrockRequest.ts
specification/inference/put_amazonbedrock/PutAmazonBedrockResponse.ts
specification/inference/put_amazonbedrock/examples/request/PutAmazonBedrockRequestExample1.yaml
specification/inference/put_amazonbedrock/examples/request/PutAmazonBedrockRequestExample2.yaml
specification/inference/put_openai/examples/request/PutOpenAiRequestExample2.yaml

This PR adds details and examples derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-amazon-bedrock.html#infer-service-amazon-bedrock-api-request

Add Amazon Bedrock inference API

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_azureaistudio.json
specification/inference/put_azureaistudio/PutAzureAiStudioRequest.ts
specification/inference/put_azureaistudio/PutAzureAiStudioResponse.ts
specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample1.yaml
specification/inference/put_azureaistudio/examples/request/PutAzureAiStudioRequestExample2.yaml

This PR adds details that are derived from https://www.elastic.co/guide/en/elasticsearch/reference/8.18/infer-service-azure-ai-studio.html

Add Azure AI Studio inference API

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_alibabacloud.json
specification/inference/put_alibabacloud/PutAlibabaCloudRequest.ts
specification/inference/put_alibabacloud/PutAlibabaCloudResponse.ts
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample1.yaml
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample2.yaml
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample3.yaml
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample4.yaml

- [Add Alibaba Cloud inference API (#4021)](https://github.com/elastic/elasticsearch-specification/pull/4021)

[8.18] Add Alibaba Cloud inference API (#4021)

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_alibabacloud.json
specification/inference/put_alibabacloud/PutAlibabaCloudRequest.ts
specification/inference/put_alibabacloud/PutAlibabaCloudResponse.ts
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample1.yaml
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample2.yaml
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample3.yaml
specification/inference/put_alibabacloud/examples/request/PutAlibabaCloudRequestExample4.yaml

- [Add Alibaba Cloud inference API (#4021)](https://github.com/elastic/elasticsearch-specification/pull/4021)

[9.0] Add Alibaba Cloud inference API (#4021)

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_azureopenai.json
specification/inference/put_azureopenai/PutAzureOpenAiRequest.ts
specification/inference/put_azureopenai/PutAzureOpenAiResponse.ts
specification/inference/put_azureopenai/examples/request/PutAzureOpenAiRequestExample1.yaml
specification/inference/put_azureopenai/examples/request/PutAzureOpenAiRequestExample2.yaml
specification/inference/put_openai/PutOpenAiRequest.ts

- [Add Azure OpenAI inference details (#4019)](https://github.com/elastic/elasticsearch-specification/pull/4019)

[8.18] Add Azure OpenAI inference details (#4019)

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_doc_ids/table.csv
specification/_json_spec/inference.put_azureopenai.json
specification/inference/put_azureopenai/PutAzureOpenAiRequest.ts
specification/inference/put_azureopenai/PutAzureOpenAiResponse.ts
specification/inference/put_azureopenai/examples/request/PutAzureOpenAiRequestExample1.yaml
specification/inference/put_azureopenai/examples/request/PutAzureOpenAiRequestExample2.yaml
specification/inference/put_openai/PutOpenAiRequest.ts

- [Add Azure OpenAI inference details (#4019)](https://github.com/elastic/elasticsearch-specification/pull/4019)

[9.0] Add Azure OpenAI inference details (#4019)

---

specification/inference/_types/CommonTypes.ts
specification/inference/put_elasticsearch/PutElasticsearchRequest.ts
specification/inference/put_elser/PutElserRequest.ts

Move AdaptiveAllocations to common types to avoid duplicates

---

specification/_types/mapping/core.ts

[docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/boolean.html) + [server code](https://github.com/elastic/elasticsearch/blob/1d6c6a59c86de232c65a29579a12e0fdb0eb97ad/server/src/main/java/org/elasticsearch/index/mapper/BooleanFieldMapper.java#L83)

Missing fields in BooleanProperty

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
package-lock.json
package.json
specification/_types/mapping/DenseVectorProperty.ts

bbq_hnsw|flat are GA'd in 8.18+

Adding bbq index types to specification

---

output/openapi/elasticsearch-serverless-openapi.json
specification/_global/search/SearchRequest.ts
specification/_global/search/_types/SearchRequestBody.ts
specification/async_search/submit/AsyncSearchSubmitRequest.ts
specification/fleet/search/SearchRequest.ts

Relates to https://github.com/elastic/elasticsearch/pull/125882
Closes https://github.com/elastic/elasticsearch-specification/pull/4190

Clarify that min_score applies to aggs

---

specification/esql/_types/EsqlResult.ts

Followup to https://github.com/elastic/elasticsearch-specification/pull/4189

ESQL: prefix duplicates of existing types

---

docs/overlays/elasticsearch-shared-overlays.yaml

This PR updates some overlays that are used on the OpenAPI documents since they're affected by the change to the path separator in https://github.com/elastic/elasticsearch-specification/pull/4199

OpenAPI: Update overlays with new path separator

---

specification/_doc_ids/table.csv
specification/indices/cancel_migrate_reindex/MigrateCancelReindexRequest.ts
specification/indices/create_from/MigrateCreateFromRequest.ts
specification/indices/migrate_reindex/MigrateReindexRequest.ts

This PR edits more entries in the `table.csv` where there are more appropriate target URLs

[DOCS] Fix connector, migration, and k-precision URLs

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
output/schema/schema-serverless.json
specification/ml/get_data_frame_analytics_stats/MlGetDataFrameAnalyticsStatsRequest.ts
specification/ml/get_datafeed_stats/MlGetDatafeedStatsRequest.ts
specification/ml/get_job_stats/MlGetJobStatsRequest.ts

Backport of https://github.com/elastic/elasticsearch-specification/pull/4299

[8.16][DOCS] Renames ML get usage info APIs back to get stats

---

output/openapi/elasticsearch-openapi.json
output/openapi/elasticsearch-serverless-openapi.json
specification/ml/get_data_frame_analytics_stats/MlGetDataFrameAnalyticsStatsRequest.ts
specification/ml/get_datafeed_stats/MlGetDatafeedStatsRequest.ts
specification/ml/get_job_stats/MlGetJobStatsRequest.ts

Backport of https://github.com/elastic/elasticsearch-specification/pull/4299

[8.17][DOCS] Renames ML get usage info APIs back to get stats.

---

specification/_global/search/_types/profile.ts
specification/snapshot/_types/SnapshotShardFailure.ts

Fix type of `shard_id`

---

specification/inference/_types/Services.ts
specification/inference/_types/TaskType.ts
specification/inference/put_jinaai/PutJinaAiResponse.ts

Backport of https://github.com/elastic/elasticsearch-specification/pull/4391

[Backport 8.19]Adds custom InferenceEndpointInfo class for JinaAI

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/inference/_types/Services.ts
specification/inference/_types/TaskType.ts
specification/inference/put_alibabacloud/PutAlibabaCloudResponse.ts

Backporting https://github.com/elastic/elasticsearch-specification/pull/4424

Backport 4424 to 8.19

---

specification/inference/put/PutRequest.ts

This PR updates the general PUT inference API docs page with the newly added Hugging Face task types.

Updates general PUT inference page with new HuggingFace task types

---

output/schema/validation-errors.json
output/typescript/types.ts
specification/esql/async_query/AsyncQueryRequest.ts

(cherry picked from commit 0ac4f3b154e93370517d5e6e3551e0a1be11470a)

[Backport 8.19] Fix AsyncQueryResuest - those parameters should be in the body (#4517)

---

specification/ilm/explain_lifecycle/types.ts

Follow-up of https://github.com/elastic/elasticsearch/pull/128736

Add `skip` to `ilm.explain_lifecycle` response

---

compiler/package-lock.json
compiler/package.json
compiler/tsconfig.json
typescript-generator/package-lock.json
typescript-generator/tsconfig.json

- [Bump ts-morph version (#4524)](https://github.com/elastic/elasticsearch-specification/pull/4524)

[8.18] Bump ts-morph version (#4524)

---

output/openapi/elasticsearch-serverless-openapi.json
output/schema/validation-errors.json
output/typescript/types.ts
specification/_types/Binary.ts
specification/esql/_types/EsqlResult.ts
specification/esql/async_query/AsyncQueryResponse.ts
specification/esql/async_query_get/AsyncQueryGetResponse.ts
specification/esql/async_query_stop/AsyncQueryStopResponse.ts
specification/esql/query/QueryResponse.ts

[Backport 8.19] Add ESQL result type definitions

---

CONTRIBUTING.md
README.md

I keep seeing this and realized we don't mention it in instructions.

Add more instructions against PRs from forks

---

output/openapi/elasticsearch-serverless-openapi.json
specification/_doc_ids/table.csv
specification/synonyms/put_synonym/SynonymsPutRequest.ts

This PR backports #4756 to the 9.0 branch.

[Backport 9.0] Adds external link to the Synonyms API (#4756)

---

.github/validate-pr/index.js
.github/workflows/validate-pr.yml

Otherwise, a PR that breaks validation but then restores it will keep a comment saying that validation is broken.

Output validation comments even without changes

---

docs/schema-structure.md

[Docs] Fix relative link in schema-structure.md

---

specification/cat/_types/CatBase.ts

Addition to https://github.com/elastic/elasticsearch-specification/pull/4736

Fixed typo in catsnapshots 

---

output/openapi/elasticsearch-serverless-openapi.json
specification/esql/_types/EsqlResult.ts
specification/esql/async_query/AsyncQueryRequest.ts
specification/esql/query/QueryRequest.ts

Manual 9.0 backport of https://github.com/elastic/elasticsearch-specification/pull/5054

[9.0] ESQL: Update text formats documentation (#5054)

---

specification/_global/bulk/BulkRequest.ts

[DOCS] Adds Ruby bulk helper to BulkRequest documentation

---

specification/_global/delete_by_query/DeleteByQueryRequest.ts

Add `sort` to DeleteByQueryRequest's body (#5143)

---

specification/autoscaling/delete_autoscaling_policy/DeleteAutoscalingPolicyRequest.ts
specification/autoscaling/get_autoscaling_capacity/GetAutoscalingCapacityRequest.ts
specification/autoscaling/get_autoscaling_policy/GetAutoscalingPolicyRequest.ts
specification/autoscaling/put_autoscaling_policy/PutAutoscalingPolicyRequest.ts
specification/shutdown/delete_node/ShutdownDeleteNodeRequest.ts
specification/shutdown/get_node/ShutdownGetNodeRequest.ts
specification/shutdown/put_node/ShutdownPutNodeRequest.ts

Reverts elastic/elasticsearch-specification#5316

Revert "[9.0] Mark cloud-only APIs as private (#5235)"

---

output/openapi/elasticsearch-serverless-openapi.json
specification/logstash/put_pipeline/LogstashPutPipelineRequest.ts

Updates the Logstash pipeline ID description to add more details about restrictions.

Update pipeline ID description of Logstash pipeline create REST API.

---

output/typescript/types.ts
specification/ilm/explain_lifecycle/types.ts

As done in https://github.com/elastic/elasticsearch/pull/128866

Add age_in_millis to ILM Explain Response

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_types/mapping/core.ts

Added in https://github.com/elastic/elasticsearch/pull/120128

Allow multi-fields in semantic_text property

---

.github/workflows/validate-apis.yml
.github/workflows/validate-pr.yml

- [Cache API validation results (#5376)](https://github.com/elastic/elasticsearch-specification/pull/5376)

[9.0] Cache API validation results (#5376)

---

.github/workflows/code-format.yml
.github/workflows/compiler-rs.yml
.github/workflows/compiler.test.yml
.github/workflows/generate.yml
.github/workflows/license.yml
.github/workflows/linter.yml
.github/workflows/metamodel-sync.yml
.github/workflows/update-rest-api-json.yml
.github/workflows/validate-apis.yml

ci: bump action scripts versions

---

output/openapi/elasticsearch-serverless-openapi.json
specification/inference/put_amazonbedrock/examples/request/PutAmazonBedrockRequestExample2.yaml
specification/inference/put_openai/examples/request/PutOpenAiRequestExample2.yaml

Fixing a mix-up between OpenAI and Amazon Bedrock examples for completion task

Move examples for completion task of OpenAI and Amazon Bedrock to the dedicated sections

---

output/openapi/elasticsearch-serverless-openapi.json
output/typescript/types.ts
specification/_types/mapping/DenseVectorProperty.ts

bbq_disk will be available in 9.2.0

Adding new bbq_disk index type
